"""Auto-generated high-fidelity type stubs for edge_webgl from ml-framework-snapshots."""
# ruff: noqa: E501

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    def __init__(self, *args: object, **kwargs: object) -> None: ...

def clamp(x: Tensor, minVal: Tensor, maxVal: Tensor) -> Tensor: ...
def fma(a: Tensor, b: Tensor, c: Tensor) -> Tensor: ...
def inverse(m: Tensor) -> Tensor: ...
def inversesqrt(x: Tensor) -> Tensor: ...
def matrixCompMult(x: Tensor, y: Tensor) -> Tensor: ...
def mix(x: Tensor, y: Tensor, a: Tensor) -> Tensor: ...
def packHalf2x16(v: Tensor) -> Tensor: ...
def texelFetch(sampler: Tensor, P: Tensor, lod: Tensor, *, sampler_type: str = ...) -> Tensor: ...
def texture(sampler: Tensor, P: Tensor, *, bias: float = ...) -> Tensor: ...
def textureSize(sampler: Tensor, lod: Tensor) -> Tensor: ...
def transpose(m: Tensor) -> Tensor: ...
def unpackHalf2x16(v: Tensor) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
