"""Auto-generated high-fidelity type stubs for edge_webgl from ml-framework-snapshots."""
# ruff: noqa: E501, UP007, UP045, D100, D101, D102, D103

from collections.abc import Sequence

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    device: str
    ndim: int
    size: int
    def __init__(self, data: object = ..., shape: Sequence[int] | None = ..., dtype: str | None = ...) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: object) -> Tensor: ...
    def __add__(self, other: Tensor | float | int) -> Tensor: ...
    def __sub__(self, other: Tensor | float | int) -> Tensor: ...
    def __mul__(self, other: Tensor | float | int) -> Tensor: ...
    def __truediv__(self, other: Tensor | float | int) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def numpy(self) -> object: ...
    def to(self, device: str) -> Tensor: ...
    def reshape(self, shape: Sequence[int]) -> Tensor: ...
    def transpose(self, axes: Sequence[int] | None = ...) -> Tensor: ...

def clamp(x: Tensor, minVal: Tensor, maxVal: Tensor) -> Tensor: ...
def fma(a: Tensor, b: Tensor, c: Tensor) -> Tensor: ...
def inverse(m: Tensor) -> Tensor: ...
def inversesqrt(x: Tensor) -> Tensor: ...
def matrixCompMult(x: Tensor, y: Tensor) -> Tensor: ...
def mix(x: Tensor, y: Tensor, a: Tensor) -> Tensor: ...
def packHalf2x16(v: Tensor) -> Tensor: ...
def texelFetch(sampler: Tensor, P: Tensor, lod: Tensor, *, sampler_type: str = ...) -> Tensor: ...
def texture(sampler: Tensor, P: Tensor, *, bias: float = ...) -> Tensor: ...
def textureSize(sampler: Tensor, lod: Tensor) -> Tensor: ...
def transpose(m: Tensor) -> Tensor: ...
def unpackHalf2x16(v: Tensor) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
