"""JAX-like numpy API backed by ml-switcheroo-compiler."""

from ml_switcheroo.jnp.array import ndarray
from ml_switcheroo.jnp.math_ops import (
    abs as abs,
    add as add,
    all as all,
    allclose as allclose,
    amax as amax,
    amin as amin,
    any as any,
    arccos as arccos,
    arccosh as arccosh,
    arcsin as arcsin,
    arcsinh as arcsinh,
    arctan as arctan,
    arctan2 as arctan2,
    arctanh as arctanh,
    argmax as argmax,
    argmin as argmin,
    array_equal as array_equal,
    broadcast_shapes as broadcast_shapes,
    ceil as ceil,
    clip as clip,
    cos as cos,
    cosh as cosh,
    cumsum as cumsum,
    divide as divide,
    divmod as divmod,
    exp as exp,
    exp2 as exp2,
    expm1 as expm1,
    floor as floor,
    floor_divide as floor_divide,
    isfinite as isfinite,
    isnan as isnan,
    log as log,
    log10 as log10,
    log1p as log1p,
    log2 as log2,
    max as max,
    maximum as maximum,
    mean as mean,
    min as min,
    minimum as minimum,
    mod as mod,
    multiply as multiply,
    negative as negative,
    positive as positive,
    power as power,
    prod as prod,
    remainder as remainder,
    rint as rint,
    sign as sign,
    sin as sin,
    sinh as sinh,
    sqrt as sqrt,
    square as square,
    std as std,
    subtract as subtract,
    sum as sum,
    tan as tan,
    tanh as tanh,
    true_divide as true_divide,
    trunc as trunc,
    var as var,
)
from ml_switcheroo.jnp.math_ops import _unary_op
from ml_switcheroo.jnp.manipulation import (
    array_split as array_split,
    broadcast_to as broadcast_to,
    concatenate as concatenate,
    dsplit as dsplit,
    dstack as dstack,
    expand_dims as expand_dims,
    hsplit as hsplit,
    hstack as hstack,
    moveaxis as moveaxis,
    pad as pad,
    ravel as ravel,
    repeat as repeat,
    reshape as reshape,
    shape as shape,
    split as split,
    squeeze as squeeze,
    stack as stack,
    swapaxes as swapaxes,
    take as take,
    take_along_axis as take_along_axis,
    tile as tile,
    transpose as transpose,
    vsplit as vsplit,
    vstack as vstack,
    where as where,
)
from ml_switcheroo.jnp.linalg import (
    dot as dot,
    einsum as einsum,
    inner as inner,
    matmul as matmul,
    outer as outer,
    tensordot as tensordot,
    vdot as vdot,
)
from ml_switcheroo.jnp.creation import (
    arange as arange,
    array as array,
    asarray as asarray,
    empty as empty,
    empty_like as empty_like,
    eye as eye,
    full as full,
    full_like as full_like,
    identity as identity,
    linspace as linspace,
    logspace as logspace,
    meshgrid as meshgrid,
    ones as ones,
    ones_like as ones_like,
    zeros as zeros,
    zeros_like as zeros_like,
)

# Explicit __all__ list to guarantee 1:1 API compatibility
__all__ = [
    "ndarray",
    "sin",
    "cos",
    "exp",
    "log",
    "add",
    "multiply",
    "power",
    "maximum",
    "minimum",
    "clip",
    "abs",
    "isfinite",
    "allclose",
    "array_equal",
    "broadcast_shapes",
    "subtract",
    "divide",
    "true_divide",
    "floor_divide",
    "mod",
    "remainder",
    "divmod",
    "negative",
    "positive",
    "sign",
    "floor",
    "ceil",
    "trunc",
    "rint",
    "tan",
    "arcsin",
    "arccos",
    "arctan",
    "arctan2",
    "sinh",
    "cosh",
    "tanh",
    "arcsinh",
    "arccosh",
    "arctanh",
    "exp2",
    "expm1",
    "log2",
    "log10",
    "log1p",
    "sqrt",
    "square",
    "isnan",
    "_unary_op",
    "transpose",
    "reshape",
    "broadcast_to",
    "concatenate",
    "where",
    "expand_dims",
    "ravel",
    "squeeze",
    "swapaxes",
    "moveaxis",
    "stack",
    "vstack",
    "hstack",
    "dstack",
    "split",
    "array_split",
    "vsplit",
    "hsplit",
    "dsplit",
    "tile",
    "repeat",
    "pad",
    "take",
    "take_along_axis",
    "shape",
    "einsum",
    "dot",
    "matmul",
    "vdot",
    "inner",
    "outer",
    "tensordot",
    "zeros_like",
    "zeros",
    "array",
    "ones",
    "empty",
    "full",
    "ones_like",
    "empty_like",
    "full_like",
    "asarray",
    "arange",
    "linspace",
    "logspace",
    "eye",
    "identity",
    "meshgrid",
    "max",
    "sum",
    "mean",
    "prod",
    "min",
    "amin",
    "amax",
    "argmax",
    "argmin",
    "any",
    "all",
    "var",
    "std",
    "cumsum",
]
