"""Auto-generated high-fidelity type stubs for jax from ml-ecosystem-snapshots."""
# ruff: noqa: E501, UP007, UP045, D100, D101, D102, D103

from collections.abc import Sequence

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    device: str
    ndim: int
    size: int
    def __init__(self, data: object = ..., shape: Sequence[int] | None = ..., dtype: str | None = ...) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: object) -> Tensor: ...
    def __add__(self, other: Tensor | float | int) -> Tensor: ...
    def __sub__(self, other: Tensor | float | int) -> Tensor: ...
    def __mul__(self, other: Tensor | float | int) -> Tensor: ...
    def __truediv__(self, other: Tensor | float | int) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def numpy(self) -> object: ...
    def to(self, device: str) -> Tensor: ...
    def reshape(self, shape: Sequence[int]) -> Tensor: ...
    def transpose(self, axes: Sequence[int] | None = ...) -> Tensor: ...

def dot_product_attention(
    query: Tensor, key: Tensor, value: Tensor, bias: Tensor = ..., mask: bool = ..., *, scale: Tensor = ..., is_causal: bool = ..., query_seq_lengths: Tensor = ..., key_value_seq_lengths: Tensor = ..., local_window_size: Tensor = ..., return_residual: bool = ..., implementation: str = ...
) -> Tensor: ...
def gelu(x: Tensor, approximate: bool = ...) -> Tensor: ...
def get_scaled_dot_general_config(mode: Tensor, global_scale: Tensor = ...) -> Tensor: ...
def logsumexp(a: Tensor, axis: Tensor = ..., b: Tensor = ..., keepdims: bool = ..., return_sign: bool = ..., where: Tensor = ...) -> Tensor: ...
def one_hot(x: Tensor, num_classes: int, *, dtype: float = ..., axis: Tensor = ..., out_sharding: Tensor = ...) -> Tensor: ...
def scaled_dot_general(lhs: Tensor, rhs: Tensor, dimension_numbers: Tensor, preferred_element_type: Tensor = ..., configs: Tensor = ..., implementation: Tensor = ...) -> Tensor: ...
def scaled_matmul(lhs: Tensor, rhs: Tensor, lhs_scales: Tensor, rhs_scales: Tensor, preferred_element_type: Tensor = ...) -> Tensor: ...
def softmax(x: Tensor, axis: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def ANY(*values: Tensor) -> Tensor: ...
def PRNGKey(seed: int, *, impl: str = ...) -> Tensor: ...
def abs(x: Tensor) -> Tensor: ...
def absolute(x: Tensor) -> Tensor: ...
def acos(x: Tensor) -> Tensor: ...
def acosh(x: Tensor) -> Tensor: ...
def add(*args: Tensor, out: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def after_all(*operands: Tensor) -> Tensor: ...
def align_to(a: Tensor, alignment: Tensor) -> Tensor: ...
def all(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., out: Tensor = ..., *, where: Tensor = ...) -> Tensor: ...
def all_gather(x: Tensor, axis_name: Tensor, *, axis_index_groups: Tensor = ..., axis: int = ..., tiled: bool = ..., to: str = ...) -> Tensor: ...
def all_to_all(x: Tensor, axis_name: Tensor, split_axis: Tensor, concat_axis: Tensor, *, axis_index_groups: Tensor = ..., tiled: bool = ...) -> Tensor: ...
def allclose(a: Tensor, b: Tensor, rtol: Tensor = ..., atol: Tensor = ..., equal_nan: bool = ...) -> Tensor: ...
def amax(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: bool = ..., initial: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def amin(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: bool = ..., initial: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def angle(z: Tensor, deg: bool = ...) -> Tensor: ...
def any(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., out: Tensor = ..., *, where: Tensor = ...) -> Tensor: ...
def append(arr: Tensor, values: int, axis: Tensor = ...) -> Tensor: ...
def apply_along_axis(func1d: Tensor, axis: int, arr: Tensor, *args: Tensor, **kwargs: Tensor) -> Tensor: ...
def apply_over_axes(func: Tensor, a: Tensor, axes: Sequence[int]) -> Tensor: ...
def approx_max_k(operand: int, k: int, reduction_dimension: float = ..., recall_target: float = ..., reduction_input_size_override: int = ..., aggregate_to_topk: bool = ...) -> Tensor: ...
def approx_min_k(operand: int, k: int, reduction_dimension: float = ..., recall_target: float = ..., reduction_input_size_override: int = ..., aggregate_to_topk: bool = ...) -> Tensor: ...
def arange(start: Tensor, stop: Tensor = ..., step: Tensor = ..., dtype: Tensor = ..., *, device: Tensor = ..., out_sharding: Tensor = ...) -> Tensor: ...
def arccos(x: Tensor) -> Tensor: ...
def arccosh(x: Tensor) -> Tensor: ...
def arcsin(x: Tensor) -> Tensor: ...
def arcsinh(x: Tensor) -> Tensor: ...
def arctan(x: Tensor) -> Tensor: ...
def arctan2(x1: Tensor, x2: Tensor, x: Tensor, y: Tensor) -> Tensor: ...
def arctanh(x: Tensor) -> Tensor: ...
def argmax(a: Tensor, axis: int = ..., out: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def argmin(a: Tensor, axis: int = ..., out: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def argpartition(a: Tensor, kth: int, axis: int = ...) -> Tensor: ...
def argsort(a: Tensor, axis: int = ..., *, stable: bool = ..., descending: bool = ..., kind: Tensor = ..., order: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def argwhere(a: Tensor, *, size: Tensor = ..., fill_value: Tensor = ...) -> Tensor: ...
def around(a: Tensor, decimals: int = ..., out: Tensor = ...) -> Tensor: ...
def array(object: Tensor, dtype: Tensor = ..., copy: bool = ..., order: Tensor = ..., ndmin: int = ..., *, device: Tensor = ..., out_sharding: Tensor = ...) -> Tensor: ...
def array_equal(a1: Tensor, a2: Tensor, equal_nan: bool = ...) -> Tensor: ...
def array_equiv(a1: Tensor, a2: Tensor) -> Tensor: ...
def array_repr(arr: Tensor, max_line_width: Tensor = ..., precision: Tensor = ..., suppress_small: Tensor = ...) -> Tensor: ...
def array_split(ary: Tensor, indices_or_sections: Tensor, axis: int = ...) -> Tensor: ...
def array_str(a: Tensor, max_line_width: Tensor = ..., precision: Tensor = ..., suppress_small: Tensor = ...) -> Tensor: ...
def asarray(a: Tensor, dtype: Tensor = ..., order: Tensor = ..., *, copy: bool = ..., device: Tensor = ..., out_sharding: Tensor = ...) -> Tensor: ...
def asin(x: Tensor) -> Tensor: ...
def asinh(x: Tensor) -> Tensor: ...
def associative_scan(fn: Tensor, elems: Tensor, reverse: bool = ..., axis: int = ...) -> Tensor: ...
def astype(x: Tensor, dtype: Tensor, a: Tensor, *, copy: bool = ..., device: Tensor = ...) -> Tensor: ...
def atan(x: Tensor) -> Tensor: ...
def atan2(x: Tensor, y: Tensor) -> Tensor: ...
def atanh(x: Tensor) -> Tensor: ...
def atleast_1d(*arys: Tensor) -> Tensor: ...
def atleast_2d(*arys: Tensor) -> Tensor: ...
def atleast_3d(*arys: Tensor) -> Tensor: ...
def auto_axes(f: Tensor = ..., *, axes: Tensor = ..., out_sharding: Tensor = ...) -> Tensor: ...
def average(a: Tensor, axis: Tensor = ..., weights: Tensor = ..., returned: bool = ..., keepdims: bool = ...) -> Tensor: ...
def axis_index(axis_name: Tensor) -> Tensor: ...
def axis_size(axis_name: Tensor) -> Tensor: ...
def ball(key: Tensor, d: int, p: float = ..., shape: Tensor = ..., dtype: float = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def bartlett(M: int) -> Tensor: ...
def batch_matmul(lhs: Tensor, rhs: Tensor, precision: Tensor = ...) -> Tensor: ...
def bernoulli(key: Tensor, p: float = ..., shape: Tensor = ..., mode: str = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def bessel_i0e(x: Tensor) -> Tensor: ...
def bessel_i1e(x: Tensor) -> Tensor: ...
def beta(key: Tensor, a: Tensor, b: Tensor, shape: Tensor = ..., dtype: float = ..., *, method: str = ..., out_sharding: Tensor = ...) -> Tensor: ...
def betainc(a: Tensor, b: Tensor, x: Tensor) -> Tensor: ...
def bincount(x: Tensor, weights: Tensor = ..., minlength: int = ..., *, length: Tensor = ..., out_sharding: Tensor = ...) -> Tensor: ...
def binomial(key: Tensor, n: Tensor, p: Tensor, shape: Tensor = ..., dtype: float = ...) -> Tensor: ...
def bitcast_convert_type(operand: Tensor, new_dtype: Tensor) -> Tensor: ...
def bits(key: Tensor, shape: Tensor = ..., dtype: int = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def bitwise_and(*args: Tensor, out: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def bitwise_count(x: int) -> Tensor: ...
def bitwise_invert(x: Tensor) -> Tensor: ...
def bitwise_left_shift(x: Tensor, y: Tensor) -> Tensor: ...
def bitwise_not(x: Tensor) -> Tensor: ...
def bitwise_or(*args: Tensor, out: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def bitwise_right_shift(x: Tensor, y: Tensor) -> Tensor: ...
def bitwise_xor(*args: Tensor, out: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def blackman(M: int) -> Tensor: ...
def block(arrays: Tensor) -> Tensor: ...
def broadcast(operand: Tensor, sizes: Sequence[int], *, out_sharding: Tensor = ...) -> Tensor: ...
def broadcast_arrays(*args: Tensor) -> Tensor: ...
def broadcast_in_dim(operand: Tensor, shape: Tensor, broadcast_dimensions: Sequence[int], *, out_sharding: Tensor = ...) -> Tensor: ...
def broadcast_like(arr: Tensor, like_arr: Tensor) -> Tensor: ...
def broadcast_shapes(*shapes: Tensor) -> Tensor: ...
def broadcast_to(array: Tensor, shape: Tensor, *, out_sharding: Tensor = ...) -> Tensor: ...
def broadcast_to_rank(x: Tensor, rank: int) -> Tensor: ...
def broadcasted_iota(dtype: Tensor, shape: Tensor, dimension: int, *, out_sharding: Tensor = ...) -> Tensor: ...
def can_cast(from_: Tensor, to: Tensor, casting: Tensor = ...) -> Tensor: ...
def categorical(key: Tensor, logits: Tensor, axis: int = ..., shape: Tensor = ..., replace: bool = ..., mode: Tensor = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def cauchy(key: Tensor, shape: Tensor = ..., dtype: float = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def cbrt(x: Tensor) -> Tensor: ...
def cdiv(a: Tensor, b: Tensor) -> Tensor: ...
def ceil(x: Tensor) -> Tensor: ...
def checkpoint(fun: Tensor, *, prevent_cse: Tensor = ..., static_argnums: Tensor = ..., policy: Tensor = ..., static_argnames: Tensor = ...) -> Tensor: ...
def chisquare(key: Tensor, df: Tensor, shape: Tensor = ..., dtype: float = ..., *, method: str = ..., out_sharding: Tensor = ...) -> Tensor: ...
def choice(key: Tensor, a: Tensor, shape: Tensor = ..., replace: bool = ..., p: Tensor = ..., axis: int = ..., mode: Tensor = ...) -> Tensor: ...
def choose(a: Tensor, choices: Tensor, out: Tensor = ..., mode: str = ...) -> Tensor: ...
def clamp(min: Tensor, x: Tensor, max: Tensor) -> Tensor: ...
def clip(arr: Tensor, min: Tensor, max: Tensor = ..., x: Tensor = ..., *, a: Tensor = ..., a_min: Tensor = ..., a_max: Tensor = ...) -> Tensor: ...
def clone(key: Tensor) -> Tensor: ...
def clz(x: int) -> Tensor: ...
def collapse(operand: Tensor, start_dimension: int, stop_dimension: Tensor = ...) -> Tensor: ...
def column_stack(tup: Tensor) -> Tensor: ...
def complex(x: Tensor, y: Tensor) -> Tensor: ...
def composite(decomposition: Tensor, name: str, version: int = ...) -> Tensor: ...
def compress(condition: Tensor, a: Tensor, axis: Tensor = ..., *, size: Tensor = ..., fill_value: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def concat(arrays: Tensor, *, axis: Tensor = ...) -> Tensor: ...
def concatenate(arrays: Tensor, axis: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def cond(pred: Tensor, true_fun: Tensor, false_fun: Tensor, *operands: Tensor, operand: Tensor = ...) -> Tensor: ...
def conj(x: Tensor) -> Tensor: ...
def conjugate(x: Tensor) -> Tensor: ...
def conv(lhs: Tensor, rhs: Tensor, window_strides: Sequence[int], padding: str, precision: Tensor = ..., preferred_element_type: Tensor = ...) -> Tensor: ...
def conv_dimension_numbers(lhs_shape: Tensor, rhs_shape: Tensor, dimension_numbers: Tensor) -> Tensor: ...
def conv_general_dilated(
    lhs: Tensor,
    rhs: Tensor,
    window_strides: Sequence[int],
    padding: Tensor,
    lhs_dilation: Tensor = ...,
    rhs_dilation: Tensor = ...,
    dimension_numbers: str = ...,
    feature_group_count: int = ...,
    batch_group_count: int = ...,
    precision: Tensor = ...,
    preferred_element_type: Tensor = ...,
    out_sharding: Tensor = ...,
) -> Tensor: ...
def conv_general_dilated_local(lhs: Tensor, rhs: Tensor, window_strides: Sequence[int], padding: Tensor, filter_shape: Sequence[int], lhs_dilation: Tensor = ..., rhs_dilation: Tensor = ..., dimension_numbers: str = ..., precision: Tensor = ...) -> Tensor: ...
def conv_general_dilated_patches(lhs: Tensor, filter_shape: Sequence[int], window_strides: Sequence[int], padding: Tensor, lhs_dilation: Tensor = ..., rhs_dilation: Tensor = ..., dimension_numbers: str = ..., precision: Tensor = ..., preferred_element_type: Tensor = ...) -> Tensor: ...
def conv_general_permutations(dimension_numbers: Tensor) -> Tensor: ...
def conv_general_shape_tuple(lhs_shape: Tensor, rhs_shape: Tensor, window_strides: Tensor, padding: Tensor, dimension_numbers: Tensor) -> Tensor: ...
def conv_shape_tuple(lhs_shape: Tensor, rhs_shape: Tensor, strides: Tensor, pads: Tensor, batch_group_count: int = ...) -> Tensor: ...
def conv_transpose(lhs: Tensor, rhs: Tensor, strides: Sequence[int], padding: Tensor, rhs_dilation: Tensor = ..., dimension_numbers: Tensor = ..., transpose_kernel: bool = ..., precision: Tensor = ..., preferred_element_type: Tensor = ..., use_consistent_padding: bool = ...) -> Tensor: ...
def conv_transpose_shape_tuple(lhs_shape: Tensor, rhs_shape: Tensor, window_strides: Tensor, padding: Tensor, dimension_numbers: Tensor) -> Tensor: ...
def conv_with_general_padding(lhs: Tensor, rhs: Tensor, window_strides: Sequence[int], padding: Tensor, lhs_dilation: Tensor, rhs_dilation: Tensor, precision: Tensor = ..., preferred_element_type: Tensor = ...) -> Tensor: ...
def convert_element_type(operand: Tensor, new_dtype: Tensor) -> Tensor: ...
def convolve(a: Tensor, v: Tensor, mode: str = ..., *, preferred_element_type: Tensor = ..., precision: Tensor = ...) -> Tensor: ...
def copy(a: Tensor, order: Tensor = ...) -> Tensor: ...
def copysign(x1: Tensor, x2: Tensor, x: Tensor, y: Tensor) -> Tensor: ...
def corrcoef(x: Tensor, y: Tensor = ..., rowvar: bool = ..., dtype: Tensor = ...) -> Tensor: ...
def correlate(a: Tensor, v: Tensor, mode: str = ..., *, preferred_element_type: Tensor = ..., precision: Tensor = ...) -> Tensor: ...
def cos(x: Tensor) -> Tensor: ...
def cosh(x: Tensor) -> Tensor: ...
def count_nonzero(a: Tensor, axis: Tensor = ..., keepdims: bool = ...) -> Tensor: ...
def cov(m: Tensor, y: Tensor = ..., rowvar: bool = ..., bias: bool = ..., ddof: Tensor = ..., fweights: Tensor = ..., aweights: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def create_token(_: Tensor = ...) -> Tensor: ...
def cross(a: Tensor, b: Tensor, axisa: int = ..., axisb: int = ..., axisc: int = ..., axis: Tensor = ...) -> Tensor: ...
def cumlogsumexp(operand: Tensor, axis: int = ..., reverse: bool = ...) -> Tensor: ...
def cummax(operand: Tensor, axis: int = ..., reverse: bool = ...) -> Tensor: ...
def cummin(operand: Tensor, axis: int = ..., reverse: bool = ...) -> Tensor: ...
def cumprod(a: Tensor, axis: int = ..., dtype: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def cumsum(a: Tensor, axis: int = ..., dtype: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def cumulative_prod(x: Tensor, *, axis: int = ..., dtype: Tensor = ..., include_initial: bool = ...) -> Tensor: ...
def cumulative_sum(x: Tensor, *, axis: int = ..., dtype: Tensor = ..., include_initial: bool = ...) -> Tensor: ...
def custom_linear_solve(matvec: Tensor, b: Tensor, solve: Tensor, transpose_solve: Tensor = ..., symmetric: bool = ..., has_aux: bool = ...) -> Tensor: ...
def custom_root(f: Tensor, initial_guess: Tensor, solve: bool, tangent_solve: Tensor, has_aux: bool = ...) -> Tensor: ...
def dce_sink(val: Tensor, *, prevent_mlir_dce: bool = ...) -> Tensor: ...
def debug_check(condition: Tensor, message: Tensor) -> Tensor: ...
def debug_print(fmt: str, *args: Tensor) -> Tensor: ...
def deg2rad(x: Tensor) -> Tensor: ...
def degrees(x: Tensor) -> Tensor: ...
def delay(nanos: Tensor) -> Tensor: ...
def delete(arr: Tensor, obj: Tensor, axis: Tensor = ..., *, assume_unique_indices: int = ...) -> Tensor: ...
def diag(v: Tensor, k: int = ...) -> Tensor: ...
def diag_indices(n: int, ndim: int = ...) -> Tensor: ...
def diag_indices_from(arr: Tensor) -> Tensor: ...
def diagflat(v: Tensor, k: int = ...) -> Tensor: ...
def diagonal(a: Tensor, offset: int = ..., axis1: int = ..., axis2: int = ...) -> Tensor: ...
def diff(a: Tensor, n: int = ..., axis: int = ..., prepend: Tensor = ..., append: Tensor = ...) -> Tensor: ...
def digamma(x: Tensor) -> Tensor: ...
def digitize(x: Tensor, bins: Tensor, right: bool = ..., *, method: Tensor = ...) -> Tensor: ...
def dirichlet(key: Tensor, alpha: Tensor, shape: Tensor = ..., dtype: float = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def div(x: Tensor, y: Tensor) -> Tensor: ...
def divide(x: Tensor, y: Tensor) -> Tensor: ...
def divmod(x1: Tensor, x2: Tensor, x: Tensor, y: Tensor) -> Tensor: ...
def dot(a: Tensor, b: Tensor, *, precision: Tensor = ..., preferred_element_type: Tensor = ..., out_sharding: Tensor = ...) -> Tensor: ...
def dot_general(lhs: Tensor, rhs: Tensor, dimension_numbers: Tensor, precision: Tensor = ..., preferred_element_type: Tensor = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def double_sided_maxwell(key: Tensor, loc: Tensor, scale: Tensor, shape: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def dslice(start: Tensor, size: Tensor = ..., stride: Tensor = ...) -> Tensor: ...
def dsplit(ary: Tensor, indices_or_sections: Tensor) -> Tensor: ...
def dstack(tup: Tensor, dtype: Tensor = ...) -> Tensor: ...
def dtype(x: Tensor) -> Tensor: ...
def dynamic_index_in_dim(operand: Tensor, index: Tensor, axis: int = ..., keepdims: bool = ..., *, allow_negative_indices: bool = ...) -> Tensor: ...
def dynamic_slice(operand: Tensor, start_indices: Tensor, slice_sizes: Tensor, *, allow_negative_indices: bool = ...) -> Tensor: ...
def dynamic_slice_in_dim(operand: Tensor, start_index: Tensor, slice_size: int, axis: int = ..., *, allow_negative_indices: bool = ...) -> Tensor: ...
def dynamic_update_index_in_dim(operand: Tensor, update: Tensor, index: Tensor, axis: int, *, allow_negative_indices: bool = ...) -> Tensor: ...
def dynamic_update_slice(operand: Tensor, update: Tensor, start_indices: Tensor, *, allow_negative_indices: bool = ...) -> Tensor: ...
def dynamic_update_slice_in_dim(operand: Tensor, update: Tensor, start_index: Tensor, axis: int, *, allow_negative_indices: bool = ...) -> Tensor: ...
def ediff1d(ary: Tensor, to_end: Tensor = ..., to_begin: Tensor = ...) -> Tensor: ...
def einsum(subscripts: str, *operands: Tensor, optimize: Tensor = ..., precision: Tensor = ..., preferred_element_type: Tensor = ..., out: Tensor = ..., _dot_general: Tensor = ..., out_sharding: Tensor = ...) -> Tensor: ...
def einsum_path(subscripts: str, *operands: Tensor, optimize: Tensor = ...) -> Tensor: ...
def empty(shape: Tensor, dtype: Tensor = ..., *, device: Tensor = ..., out_sharding: Tensor = ...) -> Tensor: ...
def empty_like(prototype: Tensor, dtype: Tensor = ..., shape: Tensor = ..., *, device: Tensor = ...) -> Tensor: ...
def empty_ref_like(x: Tensor) -> Tensor: ...
def eq(x: Tensor, y: Tensor) -> Tensor: ...
def equal(x: Tensor, y: Tensor) -> Tensor: ...
def erf(x: Tensor) -> Tensor: ...
def erf_inv(x: Tensor) -> Tensor: ...
def erfc(x: Tensor) -> Tensor: ...
def estimate_cost(fun: Tensor, *args: Tensor, **kwargs: Tensor) -> Tensor: ...
def exp(x: Tensor) -> Tensor: ...
def exp2(x: Tensor) -> Tensor: ...
def expand_dims(a: Tensor, axis: Tensor) -> Tensor: ...
def explicit_axes(f: Tensor = ..., *, axes: Tensor = ..., in_sharding: Tensor = ...) -> Tensor: ...
def expm1(x: Tensor) -> Tensor: ...
def exponential(key: Tensor, shape: Tensor = ..., dtype: float = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def extract(condition: Tensor, arr: Tensor, *, size: Tensor = ..., fill_value: Tensor = ...) -> Tensor: ...
def eye(N: Tensor, M: Tensor = ..., k: Tensor = ..., dtype: float = ..., *, device: Tensor = ...) -> Tensor: ...
def f(key: Tensor, dfnum: float, dfden: float, shape: Tensor = ..., dtype: float = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def fabs(x: Tensor) -> Tensor: ...
def fft(x: Tensor, fft_type: Tensor, fft_lengths: Sequence[int]) -> Tensor: ...
def fill_diagonal(a: Tensor, val: Tensor, wrap: bool = ..., *, inplace: bool = ...) -> Tensor: ...
def flatnonzero(a: Tensor, *, size: int = ..., fill_value: Tensor = ...) -> Tensor: ...
def flip(m: Tensor, axis: Tensor = ...) -> Tensor: ...
def fliplr(m: Tensor) -> Tensor: ...
def flipud(m: Tensor) -> Tensor: ...
def float_power(x: Tensor, y: Tensor) -> Tensor: ...
def floor(x: Tensor) -> Tensor: ...
def floor_divide(x1: Tensor, x2: Tensor, x: Tensor, y: Tensor) -> Tensor: ...
def fmax(x1: Tensor, x2: Tensor, x: Tensor, y: Tensor) -> Tensor: ...
def fmin(x1: Tensor, x2: Tensor, x: Tensor, y: Tensor) -> Tensor: ...
def fmod(x1: Tensor, x2: Tensor, x: Tensor, y: Tensor) -> Tensor: ...
def fold_in(key: Tensor, data: int) -> Tensor: ...
def fori_loop(lower: int, upper: int, body_fun: Tensor, init_val: Tensor, *, unroll: Tensor = ...) -> Tensor: ...
def frexp(x: Tensor) -> Tensor: ...
def from_dlpack(x: Tensor, *, device: Tensor = ..., copy: bool = ...) -> Tensor: ...
def frombuffer(buffer: Tensor, dtype: Tensor = ..., count: int = ..., offset: int = ...) -> Tensor: ...
def fromfile(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fromfunction(function: Tensor, shape: Tensor, *, dtype: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def fromiter(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def frompyfunc(func: Tensor, nin: int, nout: int, *, identity: Tensor = ...) -> Tensor: ...
def fromstring(string: str, dtype: Tensor = ..., count: int = ..., *, sep: str) -> Tensor: ...
def full(shape: Tensor, fill_value: Tensor, dtype: Tensor = ..., *, device: Tensor = ..., out_sharding: Tensor = ...) -> Tensor: ...
def full_like(a: Tensor, fill_value: Tensor, shape: Tensor = ..., dtype: Tensor = ..., *, device: Tensor = ..., out_sharding: Tensor = ...) -> Tensor: ...
def gamma(key: Tensor, a: Tensor, shape: Tensor = ..., dtype: float = ..., *, method: str = ..., out_sharding: Tensor = ...) -> Tensor: ...
def gather(operand: Tensor, start_indices: Tensor, dimension_numbers: Tensor, slice_sizes: Tensor, *, indices_are_sorted: bool = ..., unique_indices: bool = ..., mode: Tensor = ..., fill_value: str = ...) -> Tensor: ...
def gcd(x1: int, x2: int) -> Tensor: ...
def ge(x: Tensor, y: Tensor) -> Tensor: ...
def generalized_normal(key: Tensor, p: Tensor, shape: Tensor = ..., dtype: float = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def geometric(key: Tensor, p: Tensor, shape: Tensor = ..., dtype: int = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def geomspace(start: Tensor, stop: Tensor, num: int = ..., endpoint: bool = ..., dtype: Tensor = ..., axis: int = ...) -> Tensor: ...
def get_abstract_mesh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def get_global(what: Tensor) -> Tensor: ...
def get_mesh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def get_printoptions(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def grad(fun: Tensor, argnums: Tensor = ..., has_aux: Tensor = ..., holomorphic: Tensor = ..., allow_int: Tensor = ..., reduce_axes: Tensor = ...) -> Tensor: ...
def gradient(f: Tensor, *varargs: Tensor, edge_order: Tensor = ..., axis: Tensor = ...) -> Tensor: ...
def greater(x: Tensor, y: Tensor) -> Tensor: ...
def greater_equal(x: Tensor, y: Tensor) -> Tensor: ...
def gt(x: Tensor, y: Tensor) -> Tensor: ...
def gumbel(key: Tensor, shape: Tensor = ..., dtype: float = ..., mode: Tensor = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def hamming(M: int) -> Tensor: ...
def hanning(M: int) -> Tensor: ...
def heaviside(x1: Tensor, x2: Tensor, x: Tensor, y: Tensor) -> Tensor: ...
def histogram(a: Tensor, bins: int = ..., range: Tensor = ..., weights: Tensor = ..., density: Tensor = ..., out_sharding: Tensor = ...) -> Tensor: ...
def histogram2d(x: Tensor, y: Tensor, bins: int = ..., range: Tensor = ..., weights: Tensor = ..., density: Tensor = ...) -> Tensor: ...
def histogram_bin_edges(a: Tensor, bins: int = ..., range: Tensor = ..., weights: Tensor = ...) -> Tensor: ...
def histogramdd(sample: Tensor, bins: int = ..., range: Tensor = ..., weights: Tensor = ..., density: Tensor = ...) -> Tensor: ...
def hsplit(ary: Tensor, indices_or_sections: Tensor) -> Tensor: ...
def hstack(tup: Tensor, dtype: Tensor = ...) -> Tensor: ...
def hypot(x1: Tensor, x2: Tensor, x: Tensor, y: Tensor) -> Tensor: ...
def i0(x: Tensor) -> Tensor: ...
def identity(n: Tensor, dtype: float = ...) -> Tensor: ...
def igamma(a: Tensor, x: Tensor) -> Tensor: ...
def igamma_grad_a(a: Tensor, x: Tensor) -> Tensor: ...
def igammac(a: Tensor, x: Tensor) -> Tensor: ...
def imag(val: Tensor, x: Tensor) -> Tensor: ...
def index_in_dim(operand: Tensor, index: int, axis: int = ..., keepdims: bool = ...) -> Tensor: ...
def index_take(src: Tensor, idxs: Tensor, axes: Sequence[int]) -> Tensor: ...
def indices(dimensions: Sequence[int], dtype: Tensor = ..., sparse: bool = ...) -> Tensor: ...
def inner(a: Tensor, b: Tensor, *, precision: Tensor = ..., preferred_element_type: Tensor = ...) -> Tensor: ...
def insert(arr: Tensor, obj: Tensor, values: Tensor, axis: Tensor = ...) -> Tensor: ...
def integer_pow(x: Tensor, y: int) -> Tensor: ...
def interp(x: Tensor, xp: Tensor, fp: Tensor, left: str = ..., right: str = ..., period: Tensor = ...) -> Tensor: ...
def intersect1d(ar1: Tensor, ar2: Tensor, assume_unique: bool = ..., return_indices: bool = ..., *, size: Tensor = ..., fill_value: int = ...) -> Tensor: ...
def invert(x: Tensor) -> Tensor: ...
def iota(dtype: Tensor, size: int) -> Tensor: ...
def is_finite(x: Tensor) -> Tensor: ...
def isclose(a: Tensor, b: Tensor, rtol: Tensor = ..., atol: Tensor = ..., equal_nan: bool = ...) -> Tensor: ...
def iscomplex(x: Tensor) -> Tensor: ...
def iscomplexobj(x: Tensor) -> Tensor: ...
def isdtype(dtype: Tensor, kind: str) -> Tensor: ...
def isfinite(x: Tensor) -> Tensor: ...
def isin(element: Tensor, test_elements: Tensor, invert: bool = ..., assume_unique: bool = ..., *, method: str = ...) -> Tensor: ...
def isinf(x: Tensor) -> Tensor: ...
def isnan(x: Tensor) -> Tensor: ...
def isneginf(x: Tensor, out: Tensor = ...) -> Tensor: ...
def isposinf(x: Tensor, out: Tensor = ...) -> Tensor: ...
def isreal(x: Tensor) -> Tensor: ...
def isrealobj(x: Tensor) -> Tensor: ...
def isscalar(element: Tensor) -> Tensor: ...
def issubdtype(arg1: str, arg2: Tensor) -> Tensor: ...
def iterable(y: Tensor) -> Tensor: ...
def ix_(*args: Tensor) -> Tensor: ...
def jit(
    fun: Tensor,
    *,
    in_shardings: Tensor = ...,
    out_shardings: Tensor = ...,
    static_argnums: Tensor = ...,
    donate_argnames: Tensor = ...,
    keep_unused: bool = ...,
    donate_argnums: Tensor = ...,
    inline: Tensor = ...,
    static_argnames: Tensor = ...,
    backend: Tensor = ...,
    compiler_options: Tensor = ...,
    device: Tensor = ...,
) -> Tensor: ...
def kaiser(M: int, beta: Tensor) -> Tensor: ...
def kernel(body: Tensor = ..., out_type: Tensor = ..., *, mesh: Tensor, scratch_types: Tensor = ..., compiler_params: Tensor = ..., interpret: Tensor = ..., debug: bool = ..., cost_estimate: Tensor = ..., name: Tensor = ..., metadata: Tensor = ...) -> Tensor: ...
def key(seed: int, *, impl: str = ..., dtype: Tensor = ...) -> Tensor: ...
def key_data(keys: Tensor) -> Tensor: ...
def key_dtype(impl_spec: Tensor = ...) -> Tensor: ...
def key_impl(keys: Tensor) -> Tensor: ...
def kron(a: Tensor, b: Tensor) -> Tensor: ...
def laplace(key: Tensor, shape: Tensor = ..., dtype: float = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def lcm(x1: int, x2: int) -> Tensor: ...
def ldexp(x1: Tensor, x2: int, x: Tensor, y: Tensor) -> Tensor: ...
def le(x: Tensor, y: Tensor) -> Tensor: ...
def left_shift(x: Tensor, y: Tensor) -> Tensor: ...
def less(x: Tensor, y: Tensor) -> Tensor: ...
def less_equal(x: Tensor, y: Tensor) -> Tensor: ...
def lexsort(keys: Tensor, axis: float = ...) -> Tensor: ...
def lgamma(x: Tensor) -> Tensor: ...
def linspace(start: Tensor, stop: Tensor, num: int = ..., endpoint: bool = ..., retstep: Tensor = ..., dtype: Tensor = ..., axis: int = ..., *, device: Tensor = ...) -> Tensor: ...
def load(file: Tensor, *args: Tensor, **kwargs: Tensor) -> Tensor: ...
def log(x: Tensor) -> Tensor: ...
def log10(x: Tensor) -> Tensor: ...
def log1p(x: Tensor) -> Tensor: ...
def log2(x: Tensor) -> Tensor: ...
def logaddexp(*args: Tensor, out: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def logaddexp2(*args: Tensor, out: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def loggamma(key: Tensor, a: Tensor, shape: Tensor = ..., dtype: float = ..., *, method: str = ..., out_sharding: Tensor = ...) -> Tensor: ...
def logical_and(*args: Tensor, out: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def logical_not(x: Tensor) -> Tensor: ...
def logical_or(*args: Tensor, out: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def logical_xor(*args: Tensor, out: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def logistic(x: float, *, accuracy: Tensor = ...) -> Tensor: ...
def lognormal(key: Tensor, sigma: Tensor = ..., shape: Tensor = ..., dtype: float = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def logspace(start: Tensor, stop: Tensor, num: int = ..., endpoint: bool = ..., base: Tensor = ..., dtype: Tensor = ..., axis: int = ...) -> Tensor: ...
def loop(lower: Tensor, upper: Tensor, *, init_carry: Tensor = ..., step: Tensor = ..., unroll: Tensor = ...) -> Tensor: ...
def lower_as_mlir(f: Tensor, *args: Tensor, dynamic_shapes: bool = ..., device: Tensor = ..., static_argnames: Tensor = ..., platforms: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def lt(x: Tensor, y: Tensor) -> Tensor: ...
def make_single_device_sharding(device: Tensor, *, memory_kind: Tensor = ...) -> Tensor: ...
def map(f: Tensor, xs: Tensor, *, batch_size: int = ...) -> Tensor: ...
def mask_indices(n: int, mask_func: Tensor, k: int = ..., *, size: Tensor = ...) -> Tensor: ...
def matmul(a: Tensor, b: Tensor, *, precision: Tensor = ..., preferred_element_type: Tensor = ..., out_sharding: Tensor = ...) -> Tensor: ...
def matrix_transpose(x: Tensor) -> Tensor: ...
def matvec(x1: Tensor, x2: Tensor) -> Tensor: ...
def max(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., initial: Tensor = ..., where: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def maximum(*args: Tensor, out: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def maxwell(key: Tensor, shape: Tensor = ..., dtype: float = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def mean(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., keepdims: bool = ..., out: Tensor = ..., *, where: bool = ...) -> Tensor: ...
def median(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., out: Tensor = ..., overwrite_input: bool = ...) -> Tensor: ...
def meshgrid(*xi: Tensor, copy: bool = ..., sparse: bool = ..., indexing: str = ...) -> Tensor: ...
def min(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., initial: Tensor = ..., where: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def minimum(*args: Tensor, out: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def minmax(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., initial: Tensor = ..., where: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def mod(x: Tensor, y: Tensor) -> Tensor: ...
def modf(x: Tensor, out: Tensor = ...) -> Tensor: ...
def moveaxis(a: Tensor, source: Tensor, destination: Tensor) -> Tensor: ...
def mul(x: Tensor, y: Tensor, *, out_dtype: Tensor = ...) -> Tensor: ...
def mulhi(x: Tensor, y: Tensor) -> Tensor: ...
def multinomial(key: Tensor, n: Tensor, p: Tensor, *, shape: Tensor = ..., dtype: float = ..., unroll: Tensor = ...) -> Tensor: ...
def multiple_of(x: Tensor, values: Tensor) -> Tensor: ...
def multiply(*args: Tensor, out: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def multivariate_normal(key: Tensor, mean: Tensor, cov: Tensor, shape: Tensor = ..., dtype: float = ..., method: str = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def nan_to_num(x: Tensor, copy: bool = ..., nan: Tensor = ..., posinf: Tensor = ..., neginf: Tensor = ...) -> Tensor: ...
def nanargmax(a: Tensor, axis: int = ..., out: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def nanargmin(a: Tensor, axis: int = ..., out: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def nancumprod(a: Tensor, axis: int = ..., dtype: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nancumsum(a: Tensor, axis: int = ..., dtype: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nanmax(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., initial: Tensor = ..., where: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nanmean(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., keepdims: bool = ..., where: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nanmedian(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., out: Tensor = ..., overwrite_input: bool = ...) -> Tensor: ...
def nanmin(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., initial: Tensor = ..., where: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nanpercentile(a: Tensor, q: Tensor, axis: Tensor = ..., out: Tensor = ..., overwrite_input: bool = ..., method: Tensor = ..., keepdims: int = ..., weights: Tensor = ..., *, interpolation: Tensor = ...) -> Tensor: ...
def nanprod(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., keepdims: bool = ..., initial: Tensor = ..., where: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nanquantile(a: Tensor, q: Tensor, axis: Tensor = ..., out: Tensor = ..., overwrite_input: bool = ..., method: Tensor = ..., keepdims: int = ..., weights: Tensor = ..., *, interpolation: Tensor = ...) -> Tensor: ...
def nanstd(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., ddof: int = ..., keepdims: bool = ..., where: bool = ..., mean: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nansum(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., keepdims: bool = ..., initial: Tensor = ..., where: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nanvar(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., ddof: int = ..., keepdims: bool = ..., where: bool = ..., mean: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def ndim(a: Tensor) -> Tensor: ...
def ne(x: Tensor, y: Tensor) -> Tensor: ...
def neg(x: Tensor) -> Tensor: ...
def negative(x: Tensor) -> Tensor: ...
def next_power_of_2(x: int) -> Tensor: ...
def nextafter(x: Tensor, y: Tensor) -> Tensor: ...
def nonzero(a: Tensor, *, size: int = ..., fill_value: Tensor = ...) -> Tensor: ...
def normal(key: Tensor, shape: Tensor = ..., dtype: float = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def not_equal(x: Tensor, y: Tensor) -> Tensor: ...
def num_programs(axis: int) -> Tensor: ...
def one_minus_square(x: Tensor) -> Tensor: ...
def ones(shape: Tensor, dtype: Tensor = ..., *, device: Tensor = ..., out_sharding: Tensor = ...) -> Tensor: ...
def ones_like(a: Tensor, shape: Tensor = ..., dtype: Tensor = ..., *, device: Tensor = ..., out_sharding: Tensor = ...) -> Tensor: ...
def optimization_barrier(operand: Tensor) -> Tensor: ...
def orthogonal(key: Tensor, n: int, shape: Tensor = ..., dtype: float = ..., m: Tensor = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def outer(a: Tensor, b: Tensor, out: Tensor = ...) -> Tensor: ...
def packbits(a: Tensor, axis: Tensor = ..., bitorder: str = ...) -> Tensor: ...
def pad(array: Tensor, pad_width: Tensor, mode: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def padtype_to_pads(in_shape: Tensor, window_shape: Tensor, window_strides: Tensor, padding: Tensor) -> Tensor: ...
def pallas_call(
    kernel: Tensor,
    out_shape: Tensor,
    *,
    grid_spec: Tensor = ...,
    grid: Tensor = ...,
    in_specs: Tensor = ...,
    out_specs: Tensor = ...,
    scratch_shapes: Tensor = ...,
    input_output_aliases: Tensor = ...,
    debug: bool = ...,
    interpret: Tensor = ...,
    name: Tensor = ...,
    compiler_params: Tensor = ...,
    metadata: Tensor = ...,
    cost_estimate: Tensor = ...,
) -> Tensor: ...
def pallas_enable_debug_checks(new_val: Tensor = ...) -> Tensor: ...
def pallas_export_experimental(dynamic_shapes: bool) -> Tensor: ...
def pallas_poison_buffers(new_val: Tensor = ...) -> Tensor: ...
def pareto(key: Tensor, b: Tensor, shape: Tensor = ..., dtype: float = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def partition(a: Tensor, kth: int, axis: int = ...) -> Tensor: ...
def pbroadcast(x: Tensor, axis_name: Tensor, source: Tensor) -> Tensor: ...
def pcast(x: Tensor, axis_name: Tensor, *, to: str) -> Tensor: ...
def percentile(a: Tensor, q: Tensor, axis: Tensor = ..., out: Tensor = ..., overwrite_input: bool = ..., method: Tensor = ..., keepdims: int = ..., weights: Tensor = ..., *, out_sharding: Tensor = ..., interpolation: Tensor = ...) -> Tensor: ...
def permutation(key: Tensor, x: Tensor, axis: int = ..., independent: bool = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def permute_dims(a: Tensor, axes: Tensor, x: Tensor) -> Tensor: ...
def piecewise(x: Tensor, condlist: Tensor, funclist: Tensor, *args: Tensor, **kw: Tensor) -> Tensor: ...
def place(arr: Tensor, mask: bool, vals: Tensor, *, inplace: bool = ...) -> Tensor: ...
def platform_dependent(*args: Tensor, default: Tensor = ..., **per_platform: Tensor) -> Tensor: ...
def pmap(fun: Tensor, axis_name: Tensor = ..., *, in_axes: Tensor = ..., out_axes: int = ..., static_broadcasted_argnums: Tensor = ..., donate_argnums: Tensor = ..., backend: Tensor = ..., axis_size: Tensor = ..., devices: Tensor = ...) -> Tensor: ...
def pmax(x: Tensor, axis_name: Tensor, *, axis_index_groups: Tensor = ...) -> Tensor: ...
def pmean(x: Tensor, axis_name: Tensor, *, axis_index_groups: Tensor = ...) -> Tensor: ...
def pmin(x: Tensor, axis_name: Tensor, *, axis_index_groups: Tensor = ...) -> Tensor: ...
def poisson(key: Tensor, lam: Tensor, shape: Tensor = ..., dtype: int = ..., *, method: str = ..., out_sharding: Tensor = ...) -> Tensor: ...
def poly(seq_of_zeros: Tensor) -> Tensor: ...
def polyadd(a1: Tensor, a2: Tensor) -> Tensor: ...
def polyder(p: Tensor, m: int = ...) -> Tensor: ...
def polydiv(u: Tensor, v: Tensor, *, trim_leading_zeros: bool = ...) -> Tensor: ...
def polyfit(x: Tensor, y: Tensor, deg: int, rcond: Tensor = ..., full: Tensor = ..., w: Tensor = ..., cov: Tensor = ...) -> Tensor: ...
def polygamma(m: Tensor, x: Tensor) -> Tensor: ...
def polyint(p: Tensor, m: int = ..., k: Tensor = ...) -> Tensor: ...
def polymul(a1: Tensor, a2: Tensor, *, trim_leading_zeros: bool = ...) -> Tensor: ...
def polysub(a1: Tensor, a2: Tensor) -> Tensor: ...
def polyval(p: Tensor, x: Tensor, *, unroll: int = ...) -> Tensor: ...
def population_count(x: int) -> Tensor: ...
def positive(x: Tensor) -> Tensor: ...
def pow(x: Tensor, y: Tensor) -> Tensor: ...
def power(x1: Tensor, x2: Tensor, x: Tensor, y: Tensor) -> Tensor: ...
def ppermute(x: Tensor, axis_name: Tensor, perm: Tensor) -> Tensor: ...
def precv(token: Tensor, out_shape: Tensor, axis_name: Tensor, perm: Tensor) -> Tensor: ...
def printoptions(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def prod(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., keepdims: bool = ..., initial: Tensor = ..., where: Tensor = ..., promote_integers: bool = ..., out: Tensor = ...) -> Tensor: ...
def program_id(axis: int) -> Tensor: ...
def promote_types(a: Tensor, b: Tensor) -> Tensor: ...
def psend(x: Tensor, axis_name: Tensor, perm: Tensor) -> Tensor: ...
def pshuffle(x: Tensor, axis_name: Tensor, perm: Tensor) -> Tensor: ...
def psum(x: Tensor, axis_name: Tensor, *, axis_index_groups: Tensor = ...) -> Tensor: ...
def psum_scatter(x: Tensor, axis_name: Tensor, *, scatter_dimension: int = ..., axis_index_groups: Tensor = ..., tiled: bool = ...) -> Tensor: ...
def pswapaxes(x: Tensor, axis_name: Tensor, axis: Tensor, *, axis_index_groups: Tensor = ...) -> Tensor: ...
def ptp(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., out: Tensor = ...) -> Tensor: ...
def put(a: Tensor, ind: Tensor, v: Tensor, mode: str = ..., *, inplace: bool = ...) -> Tensor: ...
def put_along_axis(arr: Tensor, indices: Tensor, values: Tensor, axis: Tensor, inplace: bool = ..., *, mode: Tensor = ...) -> Tensor: ...
def quantile(a: Tensor, q: Tensor, axis: Tensor = ..., out: Tensor = ..., overwrite_input: bool = ..., method: Tensor = ..., keepdims: int = ..., weights: Tensor = ..., *, interpolation: Tensor = ...) -> Tensor: ...
def rad2deg(x: Tensor) -> Tensor: ...
def rademacher(key: Tensor, shape: Tensor = ..., dtype: Tensor = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def radians(x: Tensor) -> Tensor: ...
def ragged_all_to_all(operand: Tensor, output: Tensor, input_offsets: Tensor, send_sizes: Tensor, output_offsets: int, recv_sizes: Tensor, *, axis_name: Tensor, axis_index_groups: Tensor = ...) -> Tensor: ...
def ragged_dot(lhs: Tensor, rhs: Tensor, group_sizes: int, precision: Tensor = ..., preferred_element_type: Tensor = ..., group_offset: Tensor = ..., out_sharding: Tensor = ...) -> Tensor: ...
def ragged_dot_general(lhs: Tensor, rhs: Tensor, group_sizes: int, ragged_dot_dimension_numbers: Tensor, precision: Tensor = ..., preferred_element_type: Tensor = ..., group_offset: Tensor = ..., out_sharding: Tensor = ...) -> Tensor: ...
def randint(key: Tensor, shape: Tensor, minval: Tensor, maxval: Tensor, dtype: int = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def ravel(a: Tensor, order: bool = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def ravel_multi_index(multi_index: int, dims: int, mode: str = ..., dtype: Tensor = ..., order: str = ...) -> Tensor: ...
def rayleigh(key: Tensor, scale: Tensor, shape: Tensor = ..., dtype: float = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def real(val: Tensor, x: Tensor) -> Tensor: ...
def reciprocal(x: Tensor) -> Tensor: ...
def reduce(operands: Tensor, init_values: Tensor, computation: Tensor, dimensions: Sequence[int], out_sharding: Tensor = ...) -> Tensor: ...
def reduce_and(operand: Tensor, axes: Sequence[int]) -> Tensor: ...
def reduce_max(operand: Tensor, axes: Sequence[int], *, out_sharding: Tensor = ...) -> Tensor: ...
def reduce_min(operand: Tensor, axes: Sequence[int], *, out_sharding: Tensor = ...) -> Tensor: ...
def reduce_or(operand: Tensor, axes: Sequence[int]) -> Tensor: ...
def reduce_precision(operand: Tensor, exponent_bits: int, mantissa_bits: int) -> Tensor: ...
def reduce_prod(operand: Tensor, axes: Sequence[int]) -> Tensor: ...
def reduce_sum(operand: Tensor, axes: Sequence[int], *, out_sharding: Tensor = ...) -> Tensor: ...
def reduce_window(operand: Tensor, init_value: Tensor, computation: Tensor, window_dimensions: Tensor, window_strides: Tensor = ..., padding: Tensor = ..., base_dilation: Tensor = ..., window_dilation: Tensor = ...) -> Tensor: ...
def reduce_window_shape_tuple(operand_shape: Tensor, window_dimensions: Tensor, window_strides: Tensor, padding: Tensor, base_dilation: Tensor = ..., window_dilation: Tensor = ...) -> Tensor: ...
def reduce_xor(operand: Tensor, axes: Sequence[int]) -> Tensor: ...
def rem(x: Tensor, y: Tensor) -> Tensor: ...
def remainder(x1: Tensor, x2: Tensor, x: Tensor, y: Tensor) -> Tensor: ...
def repeat(a: Tensor, repeats: Tensor, axis: Tensor = ..., *, total_repeat_length: Tensor = ..., out_sharding: Tensor = ...) -> Tensor: ...
def reshape(a: Tensor, shape: Tensor, order: bool = ..., *, copy: Tensor = ..., out_sharding: Tensor = ...) -> Tensor: ...
def reshard(xs: Tensor, out_shardings: Tensor) -> Tensor: ...
def resize(a: Tensor, new_shape: Tensor) -> Tensor: ...
def result_type(*args: Tensor) -> Tensor: ...
def rev(operand: Tensor, dimensions: Sequence[int]) -> Tensor: ...
def right_shift(x1: int, x2: Tensor, x: Tensor, y: Tensor) -> Tensor: ...
def rint(x: Tensor) -> Tensor: ...
def rng_bit_generator(key: Tensor, shape: Tensor, dtype: Tensor = ..., algorithm: Tensor = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def rng_uniform(a: Tensor, b: Tensor, shape: Tensor) -> Tensor: ...
def roll(a: Tensor, shift: Tensor, axis: Tensor = ...) -> Tensor: ...
def rollaxis(a: Tensor, axis: int, start: int = ...) -> Tensor: ...
def roots(p: Tensor, *, strip_zeros: bool = ...) -> Tensor: ...
def rot90(m: Tensor, k: int = ..., axes: Tensor = ...) -> Tensor: ...
def round(a: Tensor, decimals: int = ..., out: Tensor = ...) -> Tensor: ...
def rsqrt(x: Tensor, *, accuracy: Tensor = ...) -> Tensor: ...
def run_scoped(f: Tensor, *types: Tensor, collective_axes: Tensor = ..., **kw_types: Tensor) -> Tensor: ...
def run_state(f: Tensor) -> Tensor: ...
def save(file: Tensor, arr: Tensor, allow_pickle: bool = ...) -> Tensor: ...
def savez(file: Tensor, *args: Tensor, allow_pickle: bool = ..., **kwds: Tensor) -> Tensor: ...
def scaled_dot(lhs: Tensor, rhs: Tensor, *, lhs_scale: Tensor = ..., rhs_scale: Tensor = ..., dimension_numbers: Tensor = ..., preferred_element_type: Tensor = ...) -> Tensor: ...
def scan(f: Tensor, init: Tensor, xs: Tensor = ..., length: Tensor = ..., reverse: bool = ..., unroll: bool = ..., _split_transpose: bool = ...) -> Tensor: ...
def scatter(operand: Tensor, scatter_indices: Tensor, updates: Tensor, dimension_numbers: Tensor, *, indices_are_sorted: bool = ..., unique_indices: bool = ..., mode: Tensor = ...) -> Tensor: ...
def scatter_add(operand: Tensor, scatter_indices: Tensor, updates: Tensor, dimension_numbers: Tensor, *, indices_are_sorted: bool = ..., unique_indices: bool = ..., mode: Tensor = ...) -> Tensor: ...
def scatter_apply(operand: Tensor, scatter_indices: Tensor, func: Tensor, dimension_numbers: Tensor, *, update_shape: Tensor = ..., indices_are_sorted: bool = ..., unique_indices: bool = ..., mode: Tensor = ...) -> Tensor: ...
def scatter_max(operand: Tensor, scatter_indices: Tensor, updates: Tensor, dimension_numbers: Tensor, *, indices_are_sorted: bool = ..., unique_indices: bool = ..., mode: Tensor = ...) -> Tensor: ...
def scatter_min(operand: Tensor, scatter_indices: Tensor, updates: Tensor, dimension_numbers: Tensor, *, indices_are_sorted: bool = ..., unique_indices: bool = ..., mode: Tensor = ...) -> Tensor: ...
def scatter_mul(operand: Tensor, scatter_indices: Tensor, updates: Tensor, dimension_numbers: Tensor, *, indices_are_sorted: bool = ..., unique_indices: bool = ..., mode: Tensor = ...) -> Tensor: ...
def scatter_sub(operand: Tensor, scatter_indices: Tensor, updates: Tensor, dimension_numbers: Tensor, *, indices_are_sorted: bool = ..., unique_indices: bool = ..., mode: Tensor = ...) -> Tensor: ...
def searchsorted(a: Tensor, v: Tensor, side: Tensor = ..., sorter: Tensor = ..., *, method: str = ...) -> Tensor: ...
def select(condlist: Tensor, choicelist: Tensor, default: Tensor = ...) -> Tensor: ...
def select_n(which: Tensor, *cases: Tensor) -> Tensor: ...
def select_ref(idx: Tensor, *refs: Tensor) -> Tensor: ...
def semaphore_read(sem_or_view: Tensor) -> Tensor: ...
def semaphore_signal(sem_or_view: Tensor, inc: Tensor = ..., *, device_id: Tensor = ..., device_id_type: Tensor = ..., core_index: Tensor = ...) -> Tensor: ...
def semaphore_wait(sem_or_view: Tensor, value: Tensor = ..., *, decrement: bool = ...) -> Tensor: ...
def set_printoptions(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def setdiff1d(ar1: Tensor, ar2: Tensor, assume_unique: bool = ..., *, size: Tensor = ..., fill_value: int = ...) -> Tensor: ...
def setxor1d(ar1: Tensor, ar2: Tensor, assume_unique: bool = ..., *, size: Tensor = ..., fill_value: int = ...) -> Tensor: ...
def shape(a: Tensor) -> Tensor: ...
def shape_as_value(shape: Tensor) -> Tensor: ...
def shift_left(x: Tensor, y: Tensor) -> Tensor: ...
def shift_right_arithmetic(x: Tensor, y: Tensor) -> Tensor: ...
def shift_right_logical(x: Tensor, y: Tensor) -> Tensor: ...
def sign(x: Tensor) -> Tensor: ...
def signbit(x: Tensor) -> Tensor: ...
def sin(x: Tensor) -> Tensor: ...
def sinc(x: Tensor) -> Tensor: ...
def sinh(x: Tensor) -> Tensor: ...
def size(a: Tensor, axis: Tensor = ...) -> Tensor: ...
def slice(operand: Tensor, start_indices: Sequence[int], limit_indices: Sequence[int], strides: Tensor = ...) -> Tensor: ...
def slice_in_dim(operand: Tensor, start_index: Tensor = ..., limit_index: Tensor = ..., stride: int = ..., axis: int = ...) -> Tensor: ...
def sort(a: Tensor, axis: int = ..., *, stable: bool = ..., descending: bool = ..., kind: Tensor = ..., order: Tensor = ...) -> Tensor: ...
def sort_complex(a: Tensor) -> Tensor: ...
def sort_key_val(keys: Tensor, values: Tensor, dimension: int = ..., is_stable: bool = ...) -> Tensor: ...
def spacing(x: Tensor) -> Tensor: ...
def split(ary: Tensor, indices_or_sections: Tensor, axis: int = ...) -> Tensor: ...
def sqrt(x: Tensor) -> Tensor: ...
def square(x: Tensor) -> Tensor: ...
def squeeze(a: Tensor, axis: Tensor = ...) -> Tensor: ...
def stack(arrays: Tensor, axis: int = ..., out: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def stage(x: Tensor) -> Tensor: ...
def std(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., ddof: int = ..., keepdims: bool = ..., mean: Tensor = ..., out: Tensor = ..., *, where: bool = ..., correction: Tensor = ...) -> Tensor: ...
def stop_gradient(x: Tensor) -> Tensor: ...
def strides_from_shape(shape: Tensor) -> Tensor: ...
def sub(x: Tensor, y: Tensor) -> Tensor: ...
def subtract(*args: Tensor, out: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def sum(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: bool = ..., initial: Tensor = ..., where: Tensor = ..., promote_integers: bool = ...) -> Tensor: ...
def swapaxes(a: Tensor, axis1: int, axis2: int) -> Tensor: ...
def switch(index: Tensor, branches: Tensor, *operands: Tensor, operand: Tensor = ...) -> Tensor: ...
def t(key: Tensor, df: Tensor, shape: Tensor = ..., dtype: float = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def take(a: Tensor, indices: int, axis: Tensor = ..., out: Tensor = ..., mode: Tensor = ..., fill_value: Tensor = ..., unique_indices: bool = ..., indices_are_sorted: bool = ...) -> Tensor: ...
def take_along_axis(arr: Tensor, indices: Tensor, axis: Tensor = ..., mode: Tensor = ..., fill_value: Tensor = ..., *, wrap_negative_indices: bool = ...) -> Tensor: ...
def tan(x: Tensor) -> Tensor: ...
def tanh(x: Tensor) -> Tensor: ...
def tensordot(a: Tensor, b: Tensor, axes: Tensor = ..., *, precision: Tensor = ..., preferred_element_type: Tensor = ..., out_sharding: Tensor = ...) -> Tensor: ...
def tile(A: Tensor, reps: Tensor) -> Tensor: ...
def top_k(a: Tensor, k: int, *, axis: int = ..., mode: str = ..., sorted: bool = ...) -> Tensor: ...
def trace(a: Tensor, offset: Tensor = ..., axis1: int = ..., axis2: int = ..., dtype: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def transpose(a: Tensor, axes: Tensor = ...) -> Tensor: ...
def trapezoid(y: Tensor, x: Tensor = ..., dx: Tensor = ..., axis: float = ...) -> Tensor: ...
def tri(N: int, M: Tensor = ..., k: int = ..., dtype: Tensor = ...) -> Tensor: ...
def triangular(key: Tensor, left: Tensor, mode: Tensor, right: Tensor, shape: Tensor = ..., dtype: float = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def tril(m: Tensor, k: int = ...) -> Tensor: ...
def tril_indices(n: int, k: Tensor = ..., m: Tensor = ...) -> Tensor: ...
def tril_indices_from(arr: Tensor, k: int = ...) -> Tensor: ...
def trim_zeros(filt: Tensor, trim: str = ..., axis: Tensor = ...) -> Tensor: ...
def triu(m: Tensor, k: int = ...) -> Tensor: ...
def triu_indices(n: int, k: Tensor = ..., m: Tensor = ...) -> Tensor: ...
def triu_indices_from(arr: Tensor, k: int = ...) -> Tensor: ...
def true_divide(x1: Tensor, x2: Tensor, x: Tensor, y: Tensor) -> Tensor: ...
def trunc(x: Tensor) -> Tensor: ...
def truncated_normal(key: Tensor, lower: float, upper: float, shape: Tensor = ..., dtype: float = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def tuple(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def uniform(key: Tensor, shape: Tensor = ..., dtype: float = ..., minval: Tensor = ..., maxval: Tensor = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def union1d(ar1: Tensor, ar2: Tensor, *, size: Tensor = ..., fill_value: int = ...) -> Tensor: ...
def unique(ar: Tensor, return_index: bool = ..., return_inverse: bool = ..., return_counts: int = ..., axis: Tensor = ..., *, equal_nan: bool = ..., size: Tensor = ..., fill_value: int = ..., sorted: bool = ...) -> Tensor: ...
def unique_all(x: Tensor, *, size: Tensor = ..., fill_value: int = ...) -> Tensor: ...
def unique_counts(x: Tensor, *, size: Tensor = ..., fill_value: int = ...) -> Tensor: ...
def unique_inverse(x: Tensor, *, size: Tensor = ..., fill_value: int = ...) -> Tensor: ...
def unique_values(x: Tensor, *, size: Tensor = ..., fill_value: int = ...) -> Tensor: ...
def unpackbits(a: Tensor, axis: Tensor = ..., count: int = ..., bitorder: str = ...) -> Tensor: ...
def unravel_index(indices: Tensor, shape: Tensor) -> Tensor: ...
def unstack(x: Tensor, *, axis: int = ...) -> Tensor: ...
def unwrap(p: Tensor, discont: Tensor = ..., axis: float = ..., period: Tensor = ...) -> Tensor: ...
def up_and_broadcast(a: Tensor, x: Tensor, *, dtype: Tensor) -> Tensor: ...
def vander(x: Tensor, N: Tensor = ..., increasing: bool = ...) -> Tensor: ...
def var(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., ddof: int = ..., keepdims: bool = ..., mean: Tensor = ..., out: Tensor = ..., *, where: bool = ..., correction: Tensor = ...) -> Tensor: ...
def vdot(a: Tensor, b: Tensor, *, precision: Tensor = ..., preferred_element_type: Tensor = ...) -> Tensor: ...
def vecdot(x1: Tensor, x2: Tensor, *, axis: float = ..., precision: Tensor = ..., preferred_element_type: Tensor = ...) -> Tensor: ...
def vecmat(x1: Tensor, x2: Tensor) -> Tensor: ...
def vectorize(pyfunc: Tensor, *, excluded: Tensor = ..., signature: Tensor = ...) -> Tensor: ...
def vmap(fun: Tensor, in_axes: Tensor = ..., axis_name: Tensor = ..., sum_match: bool = ..., spmd_axis_name: Tensor = ..., out_axes: Tensor = ..., axis_size: Tensor = ...) -> Tensor: ...
def vsplit(ary: Tensor, indices_or_sections: Tensor) -> Tensor: ...
def vstack(tup: Tensor, dtype: Tensor = ...) -> Tensor: ...
def wald(key: Tensor, mean: Tensor, shape: Tensor = ..., dtype: float = ..., *, out_sharding: Tensor = ...) -> Tensor: ...
def weibull_min(key: Tensor, scale: Tensor, concentration: Tensor, shape: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def when(condition: bool) -> Tensor: ...
def where(condition: bool, x: Tensor, y: Tensor, *, size: int = ..., fill_value: Tensor = ...) -> Tensor: ...
def while_loop(cond_fun: Tensor, body_fun: Tensor, init_val: Tensor) -> Tensor: ...
def with_scoped(*types: Tensor, collective_axes: Tensor = ..., **kw_types: Tensor) -> Tensor: ...
def with_sharding_constraint(x: Tensor, shardings: Tensor) -> Tensor: ...
def wrap_key_data(key_bits_array: Tensor, *, impl: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def zeros(shape: Tensor, dtype: Tensor = ..., *, device: Tensor = ..., out_sharding: Tensor = ...) -> Tensor: ...
def zeros_like(a: Tensor, shape: Tensor = ..., dtype: Tensor = ..., *, device: Tensor = ..., out_sharding: Tensor = ...) -> Tensor: ...
def zeta(x: Tensor, q: Tensor) -> Tensor: ...
def constant(value: Tensor, dtype: Tensor = ...) -> Tensor: ...
def delta_orthogonal(scale: Tensor = ..., column_axis: int = ..., dtype: Tensor = ...) -> Tensor: ...
def glorot_normal(in_axis: Tensor = ..., out_axis: Tensor = ..., batch_axis: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def glorot_uniform(in_axis: Tensor = ..., out_axis: Tensor = ..., batch_axis: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def he_normal(in_axis: Tensor = ..., out_axis: Tensor = ..., batch_axis: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def he_uniform(in_axis: Tensor = ..., out_axis: Tensor = ..., batch_axis: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def lecun_normal(in_axis: Tensor = ..., out_axis: Tensor = ..., batch_axis: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def lecun_uniform(in_axis: Tensor = ..., out_axis: Tensor = ..., batch_axis: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def variance_scaling(scale: float, mode: Tensor, distribution: Tensor, in_axis: Tensor = ..., out_axis: Tensor = ..., batch_axis: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
