"""Auto-generated high-fidelity type stubs for jax from live module introspection."""
# ruff: noqa: E501

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    def __init__(self, *args: object, **kwargs: object) -> None: ...

def ComplexWarning(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def abs(x: Tensor) -> Tensor: ...
def absolute(x: Tensor) -> Tensor: ...
def acos(x: Tensor) -> Tensor: ...
def acosh(x: Tensor) -> Tensor: ...
def add(x1: Tensor, x2: Tensor) -> Tensor: ...
def all(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., *, where: Tensor = ...) -> Tensor: ...
def allclose(a: Tensor, b: Tensor, rtol: Tensor = ..., atol: Tensor = ..., equal_nan: Tensor = ...) -> Tensor: ...
def amax(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., initial: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def amin(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., initial: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def angle(z: Tensor, deg: Tensor = ...) -> Tensor: ...
def any(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., *, where: Tensor = ...) -> Tensor: ...
def append(arr: Tensor, values: Tensor, axis: Tensor = ...) -> Tensor: ...
def apply_along_axis(func1d: Tensor, axis: Tensor, arr: Tensor, *args: Tensor, **kwargs: Tensor) -> Tensor: ...
def apply_over_axes(func: Tensor, a: Tensor, axes: Tensor) -> Tensor: ...
def arange(start: Tensor, stop: Tensor = ..., step: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def arccos(x: Tensor) -> Tensor: ...
def arccosh(x: Tensor) -> Tensor: ...
def arcsin(x: Tensor) -> Tensor: ...
def arcsinh(x: Tensor) -> Tensor: ...
def arctan(x: Tensor) -> Tensor: ...
def arctan2(x1: Tensor, x2: Tensor) -> Tensor: ...
def arctanh(x: Tensor) -> Tensor: ...
def argmax(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def argmin(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def argpartition(a: Tensor, kth: Tensor, axis: Tensor = ...) -> Tensor: ...
def argsort(a: Tensor, axis: Tensor = ..., *, kind: Tensor = ..., order: Tensor = ..., stable: Tensor = ..., descending: Tensor = ...) -> Tensor: ...
def argwhere(a: Tensor, *, size: Tensor = ..., fill_value: Tensor = ...) -> Tensor: ...
def around(a: Tensor, decimals: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def array(object: Tensor, dtype: Tensor = ..., copy: Tensor = ..., order: Tensor = ..., ndmin: Tensor = ...) -> Tensor: ...
def array_equal(a1: Tensor, a2: Tensor, equal_nan: Tensor = ...) -> Tensor: ...
def array_equiv(a1: Tensor, a2: Tensor) -> Tensor: ...
def array_repr(arr: Tensor, max_line_width: Tensor = ..., precision: Tensor = ..., suppress_small: Tensor = ...) -> Tensor: ...
def array_split(ary: Tensor, indices_or_sections: Tensor, axis: Tensor = ...) -> Tensor: ...
def array_str(a: Tensor, max_line_width: Tensor = ..., precision: Tensor = ..., suppress_small: Tensor = ...) -> Tensor: ...
def asarray(a: Tensor, dtype: Tensor = ..., order: Tensor = ..., *, copy: Tensor = ...) -> Tensor: ...
def asin(x: Tensor) -> Tensor: ...
def asinh(x: Tensor) -> Tensor: ...
def astype(x: Tensor, dtype: Tensor, *, copy: Tensor = ..., device: Tensor = ...) -> Tensor: ...
def atan(x: Tensor) -> Tensor: ...
def atan2(x1: Tensor, x2: Tensor) -> Tensor: ...
def atanh(x: Tensor) -> Tensor: ...
def atleast_1d(*arys: Tensor) -> Tensor: ...
def atleast_2d(*arys: Tensor) -> Tensor: ...
def atleast_3d(*arys: Tensor) -> Tensor: ...
def average(a: Tensor, axis: Tensor = ..., weights: Tensor = ..., returned: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def bartlett(M: Tensor) -> Tensor: ...
def bfloat16(x: Tensor) -> Tensor: ...
def bincount(x: Tensor, weights: Tensor = ..., minlength: Tensor = ..., *, length: Tensor = ...) -> Tensor: ...
def bitwise_and(x1: Tensor, x2: Tensor) -> Tensor: ...
def bitwise_count(x: Tensor) -> Tensor: ...
def bitwise_invert(x: Tensor) -> Tensor: ...
def bitwise_left_shift(x1: Tensor, x2: Tensor) -> Tensor: ...
def bitwise_not(x: Tensor) -> Tensor: ...
def bitwise_or(x1: Tensor, x2: Tensor) -> Tensor: ...
def bitwise_right_shift(x1: Tensor, x2: Tensor) -> Tensor: ...
def bitwise_xor(x1: Tensor, x2: Tensor) -> Tensor: ...
def blackman(M: Tensor) -> Tensor: ...
def block(arrays: Tensor) -> Tensor: ...
def bool(x: Tensor) -> Tensor: ...
def bool_(x: Tensor) -> Tensor: ...
def broadcast_arrays(*args: Tensor) -> Tensor: ...
def broadcast_shapes(*shapes: Tensor) -> Tensor: ...
def broadcast_to(array: Tensor, shape: Tensor) -> Tensor: ...
def can_cast(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cbrt(x: Tensor) -> Tensor: ...
def cdouble(x: Tensor) -> Tensor: ...
def ceil(x: Tensor) -> Tensor: ...
def character() -> Tensor: ...
def choose(a: Tensor, choices: Tensor, out: Tensor = ..., mode: Tensor = ...) -> Tensor: ...
def clip(x: Tensor = ..., min: Tensor = ..., max: Tensor = ..., *, a: Tensor = ..., a_min: Tensor = ..., a_max: Tensor = ...) -> Tensor: ...
def column_stack(tup: Tensor) -> Tensor: ...
def complex128(x: Tensor) -> Tensor: ...
def complex64(x: Tensor) -> Tensor: ...
def complex_(x: Tensor) -> Tensor: ...
def complexfloating() -> Tensor: ...
def compress(condition: Tensor, a: Tensor, axis: Tensor = ..., *, size: Tensor = ..., fill_value: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def concat(arrays: Tensor, *, axis: Tensor = ...) -> Tensor: ...
def concatenate(arrays: Tensor, axis: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def conj(x: Tensor) -> Tensor: ...
def conjugate(x: Tensor) -> Tensor: ...
def convolve(a: Tensor, v: Tensor, mode: Tensor = ..., *, precision: Tensor = ..., preferred_element_type: Tensor = ...) -> Tensor: ...
def copy(a: Tensor, order: Tensor = ...) -> Tensor: ...
def copysign(x1: Tensor, x2: Tensor) -> Tensor: ...
def corrcoef(x: Tensor, y: Tensor = ..., rowvar: Tensor = ...) -> Tensor: ...
def correlate(a: Tensor, v: Tensor, mode: Tensor = ..., *, precision: Tensor = ..., preferred_element_type: Tensor = ...) -> Tensor: ...
def cos(x: Tensor) -> Tensor: ...
def cosh(x: Tensor) -> Tensor: ...
def count_nonzero(a: Tensor, axis: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def cov(m: Tensor, y: Tensor = ..., rowvar: Tensor = ..., bias: Tensor = ..., ddof: Tensor = ..., fweights: Tensor = ..., aweights: Tensor = ...) -> Tensor: ...
def cross(a: Tensor, b: Tensor, axisa: Tensor = ..., axisb: Tensor = ..., axisc: Tensor = ..., axis: Tensor = ...) -> Tensor: ...
def csingle(x: Tensor) -> Tensor: ...
def cumprod(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def cumsum(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def cumulative_sum(x: Tensor, *, axis: Tensor = ..., dtype: Tensor = ..., include_initial: Tensor = ...) -> Tensor: ...
def deg2rad(x: Tensor) -> Tensor: ...
def degrees(x: Tensor) -> Tensor: ...
def delete(arr: Tensor, obj: Tensor, axis: Tensor = ..., *, assume_unique_indices: Tensor = ...) -> Tensor: ...
def diag(v: Tensor, k: Tensor = ...) -> Tensor: ...
def diag_indices(n: Tensor, ndim: Tensor = ...) -> Tensor: ...
def diag_indices_from(arr: Tensor) -> Tensor: ...
def diagflat(v: Tensor, k: Tensor = ...) -> Tensor: ...
def diagonal(a: Tensor, offset: Tensor = ..., axis1: Tensor = ..., axis2: Tensor = ...) -> Tensor: ...
def diff(a: Tensor, n: Tensor = ..., axis: Tensor = ..., prepend: Tensor = ..., append: Tensor = ...) -> Tensor: ...
def digitize(x: Tensor, bins: Tensor, right: Tensor = ...) -> Tensor: ...
def divide(x1: Tensor, x2: Tensor) -> Tensor: ...
def divmod(x1: Tensor, x2: Tensor) -> Tensor: ...
def dot(a: Tensor, b: Tensor, *, precision: Tensor = ..., preferred_element_type: Tensor = ...) -> Tensor: ...
def double(x: Tensor) -> Tensor: ...
def dsplit(ary: Tensor, indices_or_sections: Tensor) -> Tensor: ...
def dstack(tup: Tensor, dtype: Tensor = ...) -> Tensor: ...
def dtype(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ediff1d(ary: Tensor, to_end: Tensor = ..., to_begin: Tensor = ...) -> Tensor: ...
def einsum(subscripts: Tensor, *operands: Tensor, out: Tensor = ..., optimize: Tensor = ..., precision: Tensor = ..., preferred_element_type: Tensor = ..., _dot_general: Tensor = ...) -> Tensor: ...
def einsum_path(subscripts: Tensor, *operands: Tensor, optimize: Tensor = ...) -> Tensor: ...
def empty(shape: Tensor, dtype: Tensor = ..., *, device: Tensor = ...) -> Tensor: ...
def empty_like(prototype: Tensor, dtype: Tensor = ..., shape: Tensor = ..., *, device: Tensor = ...) -> Tensor: ...
def equal(x1: Tensor, x2: Tensor) -> Tensor: ...
def exp(x: Tensor) -> Tensor: ...
def exp2(x: Tensor) -> Tensor: ...
def expand_dims(a: Tensor, axis: Tensor) -> Tensor: ...
def expm1(x: Tensor) -> Tensor: ...
def extract(condition: Tensor, arr: Tensor, *, size: Tensor = ..., fill_value: Tensor = ...) -> Tensor: ...
def eye(N: Tensor, M: Tensor = ..., k: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def fabs(x: Tensor) -> Tensor: ...
def fill_diagonal(a: Tensor, val: Tensor, wrap: Tensor = ..., *, inplace: Tensor = ...) -> Tensor: ...
def finfo(dtype: Tensor) -> Tensor: ...
def fix(x: Tensor, out: Tensor = ...) -> Tensor: ...
def flatnonzero(a: Tensor, *, size: Tensor = ..., fill_value: Tensor = ...) -> Tensor: ...
def flexible() -> Tensor: ...
def flip(m: Tensor, axis: Tensor = ...) -> Tensor: ...
def fliplr(m: Tensor) -> Tensor: ...
def flipud(m: Tensor) -> Tensor: ...
def float16(x: Tensor) -> Tensor: ...
def float32(x: Tensor) -> Tensor: ...
def float64(x: Tensor) -> Tensor: ...
def float8_e4m3b11fnuz(x: Tensor) -> Tensor: ...
def float8_e4m3fn(x: Tensor) -> Tensor: ...
def float8_e4m3fnuz(x: Tensor) -> Tensor: ...
def float8_e5m2(x: Tensor) -> Tensor: ...
def float8_e5m2fnuz(x: Tensor) -> Tensor: ...
def float_(x: Tensor) -> Tensor: ...
def float_power(x1: Tensor, x2: Tensor) -> Tensor: ...
def floating() -> Tensor: ...
def floor(x: Tensor) -> Tensor: ...
def floor_divide(x1: Tensor, x2: Tensor) -> Tensor: ...
def fmax(x1: Tensor, x2: Tensor) -> Tensor: ...
def fmin(x1: Tensor, x2: Tensor) -> Tensor: ...
def fmod(x1: Tensor, x2: Tensor) -> Tensor: ...
def frexp(x: Tensor) -> Tensor: ...
def from_dlpack(x: Tensor, *, device: Tensor = ..., copy: Tensor = ...) -> Tensor: ...
def frombuffer(buffer: Tensor, dtype: Tensor = ..., count: Tensor = ..., offset: Tensor = ...) -> Tensor: ...
def fromfile(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fromfunction(function: Tensor, shape: Tensor, *, dtype: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def fromiter(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def frompyfunc(func: Tensor, nin: Tensor, nout: Tensor, *, identity: Tensor = ...) -> Tensor: ...
def fromstring(string: Tensor, dtype: Tensor = ..., count: Tensor = ..., *, sep: Tensor) -> Tensor: ...
def full(shape: Tensor, fill_value: Tensor, dtype: Tensor = ..., *, device: Tensor = ...) -> Tensor: ...
def full_like(a: Tensor, fill_value: Tensor, dtype: Tensor = ..., shape: Tensor = ..., *, device: Tensor = ...) -> Tensor: ...
def gcd(x1: Tensor, x2: Tensor) -> Tensor: ...
def generic() -> Tensor: ...
def geomspace(start: Tensor, stop: Tensor, num: Tensor = ..., endpoint: Tensor = ..., dtype: Tensor = ..., axis: Tensor = ...) -> Tensor: ...
def get_printoptions() -> Tensor: ...
def gradient(f: Tensor, *varargs: Tensor, axis: Tensor = ..., edge_order: Tensor = ...) -> Tensor: ...
def greater(x1: Tensor, x2: Tensor) -> Tensor: ...
def greater_equal(x1: Tensor, x2: Tensor) -> Tensor: ...
def hamming(M: Tensor) -> Tensor: ...
def hanning(M: Tensor) -> Tensor: ...
def heaviside(x1: Tensor, x2: Tensor) -> Tensor: ...
def histogram(a: Tensor, bins: Tensor = ..., range: Tensor = ..., weights: Tensor = ..., density: Tensor = ...) -> Tensor: ...
def histogram2d(x: Tensor, y: Tensor, bins: Tensor = ..., range: Tensor = ..., weights: Tensor = ..., density: Tensor = ...) -> Tensor: ...
def histogram_bin_edges(a: Tensor, bins: Tensor = ..., range: Tensor = ..., weights: Tensor = ...) -> Tensor: ...
def histogramdd(sample: Tensor, bins: Tensor = ..., range: Tensor = ..., weights: Tensor = ..., density: Tensor = ...) -> Tensor: ...
def hsplit(ary: Tensor, indices_or_sections: Tensor) -> Tensor: ...
def hstack(tup: Tensor, dtype: Tensor = ...) -> Tensor: ...
def hypot(x1: Tensor, x2: Tensor) -> Tensor: ...
def i0(x: Tensor) -> Tensor: ...
def identity(n: Tensor, dtype: Tensor = ...) -> Tensor: ...
def iinfo(int_type: Tensor) -> Tensor: ...
def imag(val: Tensor) -> Tensor: ...
def indices(dimensions: Tensor, dtype: Tensor = ..., sparse: Tensor = ...) -> Tensor: ...
def inexact() -> Tensor: ...
def inner(a: Tensor, b: Tensor, *, precision: Tensor = ..., preferred_element_type: Tensor = ...) -> Tensor: ...
def insert(arr: Tensor, obj: Tensor, values: Tensor, axis: Tensor = ...) -> Tensor: ...
def int16(x: Tensor) -> Tensor: ...
def int32(x: Tensor) -> Tensor: ...
def int4(x: Tensor) -> Tensor: ...
def int64(x: Tensor) -> Tensor: ...
def int8(x: Tensor) -> Tensor: ...
def int_(x: Tensor) -> Tensor: ...
def integer() -> Tensor: ...
def interp(x: Tensor, xp: Tensor, fp: Tensor, left: Tensor = ..., right: Tensor = ..., period: Tensor = ...) -> Tensor: ...
def intersect1d(ar1: Tensor, ar2: Tensor, assume_unique: Tensor = ..., return_indices: Tensor = ...) -> Tensor: ...
def invert(x: Tensor) -> Tensor: ...
def isclose(a: Tensor, b: Tensor, rtol: Tensor = ..., atol: Tensor = ..., equal_nan: Tensor = ...) -> Tensor: ...
def iscomplex(x: Tensor) -> Tensor: ...
def iscomplexobj(x: Tensor) -> Tensor: ...
def isdtype(dtype: Tensor, kind: Tensor) -> Tensor: ...
def isfinite(x: Tensor) -> Tensor: ...
def isin(element: Tensor, test_elements: Tensor, assume_unique: Tensor = ..., invert: Tensor = ...) -> Tensor: ...
def isinf(x: Tensor) -> Tensor: ...
def isnan(x: Tensor) -> Tensor: ...
def isneginf(x: Tensor, out: Tensor = ...) -> Tensor: ...
def isposinf(x: Tensor, out: Tensor = ...) -> Tensor: ...
def isreal(x: Tensor) -> Tensor: ...
def isrealobj(x: Tensor) -> Tensor: ...
def isscalar(element: Tensor) -> Tensor: ...
def issubdtype(arg1: Tensor, arg2: Tensor) -> Tensor: ...
def iterable(y: Tensor) -> Tensor: ...
def ix_(*args: Tensor) -> Tensor: ...
def kaiser(M: Tensor, beta: Tensor) -> Tensor: ...
def kron(a: Tensor, b: Tensor) -> Tensor: ...
def lcm(x1: Tensor, x2: Tensor) -> Tensor: ...
def ldexp(x1: Tensor, x2: Tensor) -> Tensor: ...
def left_shift(x1: Tensor, x2: Tensor) -> Tensor: ...
def less(x1: Tensor, x2: Tensor) -> Tensor: ...
def less_equal(x1: Tensor, x2: Tensor) -> Tensor: ...
def lexsort(keys: Tensor, axis: Tensor = ...) -> Tensor: ...
def linspace(start: Tensor, stop: Tensor, num: Tensor = ..., endpoint: Tensor = ..., retstep: Tensor = ..., dtype: Tensor = ..., axis: Tensor = ...) -> Tensor: ...
def load(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def log(x: Tensor) -> Tensor: ...
def log10(x: Tensor) -> Tensor: ...
def log1p(x: Tensor) -> Tensor: ...
def log2(x: Tensor) -> Tensor: ...
def logaddexp(x1: Tensor, x2: Tensor) -> Tensor: ...
def logaddexp2(x1: Tensor, x2: Tensor) -> Tensor: ...
def logical_and(*args: Tensor) -> Tensor: ...
def logical_not(*args: Tensor) -> Tensor: ...
def logical_or(*args: Tensor) -> Tensor: ...
def logical_xor(*args: Tensor) -> Tensor: ...
def logspace(start: Tensor, stop: Tensor, num: Tensor = ..., endpoint: Tensor = ..., base: Tensor = ..., dtype: Tensor = ..., axis: Tensor = ...) -> Tensor: ...
def mask_indices(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def matmul(a: Tensor, b: Tensor, *, precision: Tensor = ..., preferred_element_type: Tensor = ...) -> Tensor: ...
def matrix_transpose(x: Tensor) -> Tensor: ...
def max(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., initial: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def maximum(x1: Tensor, x2: Tensor) -> Tensor: ...
def mean(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., *, where: Tensor = ...) -> Tensor: ...
def median(a: Tensor, axis: Tensor = ..., out: Tensor = ..., overwrite_input: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def meshgrid(*xi: Tensor, copy: Tensor = ..., sparse: Tensor = ..., indexing: Tensor = ...) -> Tensor: ...
def min(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., initial: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def minimum(x1: Tensor, x2: Tensor) -> Tensor: ...
def mod(x1: Tensor, x2: Tensor) -> Tensor: ...
def modf(x: Tensor, out: Tensor = ...) -> Tensor: ...
def moveaxis(a: Tensor, source: Tensor, destination: Tensor) -> Tensor: ...
def multiply(x1: Tensor, x2: Tensor) -> Tensor: ...
def nan_to_num(x: Tensor, copy: Tensor = ..., nan: Tensor = ..., posinf: Tensor = ..., neginf: Tensor = ...) -> Tensor: ...
def nanargmax(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def nanargmin(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def nancumprod(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nancumsum(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nanmax(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., initial: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def nanmean(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def nanmedian(a: Tensor, axis: Tensor = ..., out: Tensor = ..., overwrite_input: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def nanmin(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., initial: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def nanpercentile(a: Tensor, q: Tensor, axis: Tensor = ..., out: Tensor = ..., overwrite_input: Tensor = ..., method: Tensor = ..., keepdims: Tensor = ..., *, interpolation: Tensor = ...) -> Tensor: ...
def nanprod(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., initial: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def nanquantile(a: Tensor, q: Tensor, axis: Tensor = ..., out: Tensor = ..., overwrite_input: Tensor = ..., method: Tensor = ..., keepdims: Tensor = ..., *, interpolation: Tensor = ...) -> Tensor: ...
def nanstd(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., ddof: Tensor = ..., keepdims: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def nansum(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., initial: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def nanvar(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., ddof: Tensor = ..., keepdims: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def ndarray() -> Tensor: ...
def ndim(a: Tensor) -> Tensor: ...
def negative(x: Tensor) -> Tensor: ...
def nextafter(x1: Tensor, x2: Tensor) -> Tensor: ...
def nonzero(a: Tensor, *, size: Tensor = ..., fill_value: Tensor = ...) -> Tensor: ...
def not_equal(x1: Tensor, x2: Tensor) -> Tensor: ...
def number() -> Tensor: ...
def object_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ones(shape: Tensor, dtype: Tensor = ..., *, device: Tensor = ...) -> Tensor: ...
def ones_like(a: Tensor, dtype: Tensor = ..., shape: Tensor = ..., *, device: Tensor = ...) -> Tensor: ...
def outer(a: Tensor, b: Tensor, out: Tensor = ...) -> Tensor: ...
def packbits(a: Tensor, axis: Tensor = ..., bitorder: Tensor = ...) -> Tensor: ...
def pad(array: Tensor, pad_width: Tensor, mode: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def partition(a: Tensor, kth: Tensor, axis: Tensor = ...) -> Tensor: ...
def percentile(a: Tensor, q: Tensor, axis: Tensor = ..., out: Tensor = ..., overwrite_input: Tensor = ..., method: Tensor = ..., keepdims: Tensor = ..., *, interpolation: Tensor = ...) -> Tensor: ...
def permute_dims(a: Tensor, axes: Tensor) -> Tensor: ...
def piecewise(x: Tensor, condlist: Tensor, funclist: Tensor, *args: Tensor, **kw: Tensor) -> Tensor: ...
def place(arr: Tensor, mask: Tensor, vals: Tensor, *, inplace: Tensor = ...) -> Tensor: ...
def poly(seq_of_zeros: Tensor) -> Tensor: ...
def polyadd(a1: Tensor, a2: Tensor) -> Tensor: ...
def polyder(p: Tensor, m: Tensor = ...) -> Tensor: ...
def polydiv(u: Tensor, v: Tensor, *, trim_leading_zeros: Tensor = ...) -> Tensor: ...
def polyfit(x: Tensor, y: Tensor, deg: Tensor, rcond: Tensor = ..., full: Tensor = ..., w: Tensor = ..., cov: Tensor = ...) -> Tensor: ...
def polyint(p: Tensor, m: Tensor = ..., k: Tensor = ...) -> Tensor: ...
def polymul(a1: Tensor, a2: Tensor, *, trim_leading_zeros: Tensor = ...) -> Tensor: ...
def polysub(a1: Tensor, a2: Tensor) -> Tensor: ...
def polyval(p: Tensor, x: Tensor, *, unroll: Tensor = ...) -> Tensor: ...
def positive(x: Tensor) -> Tensor: ...
def pow(x1: Tensor, x2: Tensor) -> Tensor: ...
def power(x1: Tensor, x2: Tensor) -> Tensor: ...
def printoptions(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def prod(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., initial: Tensor = ..., where: Tensor = ..., promote_integers: Tensor = ...) -> Tensor: ...
def promote_types(a: Tensor, b: Tensor) -> Tensor: ...
def ptp(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def put(a: Tensor, ind: Tensor, v: Tensor, mode: Tensor = ..., *, inplace: Tensor = ...) -> Tensor: ...
def quantile(a: Tensor, q: Tensor, axis: Tensor = ..., out: Tensor = ..., overwrite_input: Tensor = ..., method: Tensor = ..., keepdims: Tensor = ..., *, interpolation: Tensor = ...) -> Tensor: ...
def rad2deg(x: Tensor) -> Tensor: ...
def radians(x: Tensor) -> Tensor: ...
def ravel(a: Tensor, order: Tensor = ...) -> Tensor: ...
def ravel_multi_index(multi_index: Tensor, dims: Tensor, mode: Tensor = ..., order: Tensor = ...) -> Tensor: ...
def real(val: Tensor) -> Tensor: ...
def reciprocal(x: Tensor) -> Tensor: ...
def remainder(x1: Tensor, x2: Tensor) -> Tensor: ...
def repeat(a: Tensor, repeats: Tensor, axis: Tensor = ..., *, total_repeat_length: Tensor = ...) -> Tensor: ...
def reshape(a: Tensor, shape: Tensor = ..., order: Tensor = ..., *, newshape: Tensor = ...) -> Tensor: ...
def resize(a: Tensor, new_shape: Tensor) -> Tensor: ...
def result_type(*args: Tensor) -> Tensor: ...
def right_shift(x1: Tensor, x2: Tensor) -> Tensor: ...
def rint(x: Tensor) -> Tensor: ...
def roll(a: Tensor, shift: Tensor, axis: Tensor = ...) -> Tensor: ...
def rollaxis(a: Tensor, axis: Tensor, start: Tensor = ...) -> Tensor: ...
def roots(p: Tensor, *, strip_zeros: Tensor = ...) -> Tensor: ...
def rot90(m: Tensor, k: Tensor = ..., axes: Tensor = ...) -> Tensor: ...
def round(a: Tensor, decimals: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def round_(a: Tensor, decimals: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def save(file: Tensor, arr: Tensor, allow_pickle: Tensor = ..., fix_imports: Tensor = ...) -> Tensor: ...
def savez(file: Tensor, *args: Tensor, **kwds: Tensor) -> Tensor: ...
def searchsorted(a: Tensor, v: Tensor, side: Tensor = ..., sorter: Tensor = ..., *, method: Tensor = ...) -> Tensor: ...
def select(condlist: Tensor, choicelist: Tensor, default: Tensor = ...) -> Tensor: ...
def set_printoptions(precision: Tensor = ..., threshold: Tensor = ..., edgeitems: Tensor = ..., linewidth: Tensor = ..., suppress: Tensor = ..., nanstr: Tensor = ..., infstr: Tensor = ..., formatter: Tensor = ..., sign: Tensor = ..., floatmode: Tensor = ..., *, legacy: Tensor = ...) -> Tensor: ...
def setdiff1d(ar1: Tensor, ar2: Tensor, assume_unique: Tensor = ..., *, size: Tensor = ..., fill_value: Tensor = ...) -> Tensor: ...
def setxor1d(ar1: Tensor, ar2: Tensor, assume_unique: Tensor = ...) -> Tensor: ...
def shape(a: Tensor) -> Tensor: ...
def sign(x: Tensor) -> Tensor: ...
def signbit(x: Tensor) -> Tensor: ...
def signedinteger() -> Tensor: ...
def sin(x: Tensor) -> Tensor: ...
def sinc(x: Tensor) -> Tensor: ...
def single(x: Tensor) -> Tensor: ...
def sinh(x: Tensor) -> Tensor: ...
def size(a: Tensor, axis: Tensor = ...) -> Tensor: ...
def sort(a: Tensor, axis: Tensor = ..., *, kind: Tensor = ..., order: Tensor = ..., stable: Tensor = ..., descending: Tensor = ...) -> Tensor: ...
def sort_complex(a: Tensor) -> Tensor: ...
def split(ary: Tensor, indices_or_sections: Tensor, axis: Tensor = ...) -> Tensor: ...
def sqrt(x: Tensor) -> Tensor: ...
def square(x: Tensor) -> Tensor: ...
def squeeze(a: Tensor, axis: Tensor = ...) -> Tensor: ...
def stack(arrays: Tensor, axis: Tensor = ..., out: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def std(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., ddof: Tensor = ..., keepdims: Tensor = ..., *, where: Tensor = ..., correction: Tensor = ...) -> Tensor: ...
def subtract(x1: Tensor, x2: Tensor) -> Tensor: ...
def sum(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., initial: Tensor = ..., where: Tensor = ..., promote_integers: Tensor = ...) -> Tensor: ...
def swapaxes(a: Tensor, axis1: Tensor, axis2: Tensor) -> Tensor: ...
def take(a: Tensor, indices: Tensor, axis: Tensor = ..., out: Tensor = ..., mode: Tensor = ..., unique_indices: Tensor = ..., indices_are_sorted: Tensor = ..., fill_value: Tensor = ...) -> Tensor: ...
def take_along_axis(arr: Tensor, indices: Tensor, axis: Tensor, mode: Tensor = ..., fill_value: Tensor = ...) -> Tensor: ...
def tan(x: Tensor) -> Tensor: ...
def tanh(x: Tensor) -> Tensor: ...
def tensordot(a: Tensor, b: Tensor, axes: Tensor = ..., *, precision: Tensor = ..., preferred_element_type: Tensor = ...) -> Tensor: ...
def tile(A: Tensor, reps: Tensor) -> Tensor: ...
def trace(a: Tensor, offset: Tensor = ..., axis1: Tensor = ..., axis2: Tensor = ..., dtype: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def transpose(a: Tensor, axes: Tensor = ...) -> Tensor: ...
def trapezoid(y: Tensor, x: Tensor = ..., dx: Tensor = ..., axis: Tensor = ...) -> Tensor: ...
def tri(N: Tensor, M: Tensor = ..., k: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def tril(m: Tensor, k: Tensor = ...) -> Tensor: ...
def tril_indices(n: Tensor, k: Tensor = ..., m: Tensor = ...) -> Tensor: ...
def tril_indices_from(arr: Tensor, k: Tensor = ...) -> Tensor: ...
def trim_zeros(filt: Tensor, trim: Tensor = ...) -> Tensor: ...
def triu(m: Tensor, k: Tensor = ...) -> Tensor: ...
def triu_indices(n: Tensor, k: Tensor = ..., m: Tensor = ...) -> Tensor: ...
def triu_indices_from(arr: Tensor, k: Tensor = ...) -> Tensor: ...
def true_divide(x1: Tensor, x2: Tensor) -> Tensor: ...
def trunc(x: Tensor) -> Tensor: ...
def ufunc(func: Tensor, nin: Tensor, nout: Tensor, *, name: Tensor = ..., nargs: Tensor = ..., identity: Tensor = ..., update_doc: Tensor = ...) -> Tensor: ...
def uint(x: Tensor) -> Tensor: ...
def uint16(x: Tensor) -> Tensor: ...
def uint32(x: Tensor) -> Tensor: ...
def uint4(x: Tensor) -> Tensor: ...
def uint64(x: Tensor) -> Tensor: ...
def uint8(x: Tensor) -> Tensor: ...
def union1d(ar1: Tensor, ar2: Tensor, *, size: Tensor = ..., fill_value: Tensor = ...) -> Tensor: ...
def unique(ar: Tensor, return_index: Tensor = ..., return_inverse: Tensor = ..., return_counts: Tensor = ..., axis: Tensor = ..., *, equal_nan: Tensor = ..., size: Tensor = ..., fill_value: Tensor = ...) -> Tensor: ...
def unique_all(x: Tensor, *, size: Tensor = ..., fill_value: Tensor = ...) -> Tensor: ...
def unique_counts(x: Tensor, *, size: Tensor = ..., fill_value: Tensor = ...) -> Tensor: ...
def unique_inverse(x: Tensor, *, size: Tensor = ..., fill_value: Tensor = ...) -> Tensor: ...
def unique_values(x: Tensor, *, size: Tensor = ..., fill_value: Tensor = ...) -> Tensor: ...
def unpackbits(a: Tensor, axis: Tensor = ..., count: Tensor = ..., bitorder: Tensor = ...) -> Tensor: ...
def unravel_index(indices: Tensor, shape: Tensor) -> Tensor: ...
def unsignedinteger() -> Tensor: ...
def unstack(x: Tensor, *, axis: Tensor = ...) -> Tensor: ...
def unwrap(p: Tensor, discont: Tensor = ..., axis: Tensor = ..., period: Tensor = ...) -> Tensor: ...
def vander(x: Tensor, N: Tensor = ..., increasing: Tensor = ...) -> Tensor: ...
def var(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., ddof: Tensor = ..., keepdims: Tensor = ..., *, where: Tensor = ..., correction: Tensor = ...) -> Tensor: ...
def vdot(a: Tensor, b: Tensor, *, precision: Tensor = ..., preferred_element_type: Tensor = ...) -> Tensor: ...
def vecdot(x1: Tensor, x2: Tensor, *, axis: Tensor = ..., precision: Tensor = ..., preferred_element_type: Tensor = ...) -> Tensor: ...
def vectorize(pyfunc: Tensor, *, excluded: Tensor = ..., signature: Tensor = ...) -> Tensor: ...
def vsplit(ary: Tensor, indices_or_sections: Tensor) -> Tensor: ...
def vstack(tup: Tensor, dtype: Tensor = ...) -> Tensor: ...
def where(condition: Tensor, x: Tensor = ..., y: Tensor = ..., *, size: Tensor = ..., fill_value: Tensor = ...) -> Tensor: ...
def zeros(shape: Tensor, dtype: Tensor = ..., *, device: Tensor = ...) -> Tensor: ...
def zeros_like(a: Tensor, dtype: Tensor = ..., shape: Tensor = ..., *, device: Tensor = ...) -> Tensor: ...
def cholesky(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def qr(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def svd(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def eigh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def schur(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def polar(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def expm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bessel_i0(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bessel_i0e(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bessel_i1(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bessel_i1e(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def i0e(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def i1(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def i1e(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def beta(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def binom(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cdf(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def pdf(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def pmf(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def convolve2d(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fftconvolve(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def welch(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def gamma(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def digamma(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def polygamma(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def zeta(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def erf(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def norm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def poisson(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def segment_max(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def segment_min(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def segment_prod(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def segment_sum(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
