"""Auto-generated high-fidelity type stubs for sparse from ml-framework-snapshots."""
# ruff: noqa: E501

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    def __init__(self, *args: object, **kwargs: object) -> None: ...

def as_coo(x: Tensor, shape: Tensor = ..., fill_value: Tensor = ..., idx_dtype: Tensor = ...) -> Tensor: ...
def asnumpy(a: Tensor, order: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def concatenate(arrays: Tensor, axis: int = ..., compressed_axes: Tensor = ...) -> Tensor: ...
def diagonal(a: Tensor, offset: int = ..., axis1: int = ..., axis2: int = ...) -> Tensor: ...
def dot(a: Tensor, b: Tensor) -> Tensor: ...
def einsum(*operands: Tensor, subscripts: list, dtype: Tensor, **kwargs: Tensor) -> Tensor: ...
def elemwise(func: Tensor, *args: Tensor, **kwargs: Tensor) -> Tensor: ...
def eye(N: int, M: Tensor = ..., k: int = ..., dtype: Tensor = ..., format: str = ..., **kwargs: Tensor) -> Tensor: ...
def full(shape: Tensor, fill_value: Tensor, dtype: Tensor = ..., format: str = ..., order: str = ..., *, compressed_axes: Tensor, **kwargs: Tensor) -> Tensor: ...
def matmul(a: Tensor, b: Tensor) -> Tensor: ...
def ones(shape: Tensor, dtype: Tensor = ..., format: str = ..., *, compressed_axes: Tensor, **kwargs: Tensor) -> Tensor: ...
def stack(arrays: Tensor, axis: int = ..., compressed_axes: Tensor = ...) -> Tensor: ...
def tensordot(a: Tensor, b: Tensor, axes: int = ..., *, return_type: Tensor = ...) -> Tensor: ...
def zeros(shape: Tensor, dtype: Tensor = ..., format: str = ..., *, compressed_axes: Tensor, **kwargs: Tensor) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
