"""Auto-generated high-fidelity type stubs for sparse from live module introspection."""
# ruff: noqa: E501, UP007, UP045, D100, D101, D102, D103

from collections.abc import Sequence

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    device: str
    ndim: int
    size: int
    def __init__(self, data: object = ..., shape: Sequence[int] | None = ..., dtype: str | None = ...) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: object) -> Tensor: ...
    def __add__(self, other: Tensor | float | int) -> Tensor: ...
    def __sub__(self, other: Tensor | float | int) -> Tensor: ...
    def __mul__(self, other: Tensor | float | int) -> Tensor: ...
    def __truediv__(self, other: Tensor | float | int) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def numpy(self) -> object: ...
    def to(self, device: str) -> Tensor: ...
    def reshape(self, shape: Sequence[int]) -> Tensor: ...
    def transpose(self, axes: Sequence[int] | None = ...) -> Tensor: ...

def COO(coords: Tensor, data: Tensor = ..., shape: Tensor = ..., has_duplicates: Tensor = ..., sorted: Tensor = ..., prune: Tensor = ..., cache: Tensor = ..., fill_value: Tensor = ..., idx_dtype: Tensor = ...) -> Tensor: ...
def DOK(shape: Tensor, data: Tensor = ..., dtype: Tensor = ..., fill_value: Tensor = ...) -> Tensor: ...
def GCXS(arg: Tensor, shape: Tensor = ..., compressed_axes: Tensor = ..., prune: Tensor = ..., fill_value: Tensor = ..., idx_dtype: Tensor = ...) -> Tensor: ...
def SparseArray(shape: Tensor, fill_value: Tensor = ...) -> Tensor: ...
def abs(x: Tensor) -> Tensor: ...
def acos(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def acosh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def add(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def all(x: Tensor, *, axis: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def any(x: Tensor, *, axis: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def argmax(x: Tensor, *, axis: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def argmin(x: Tensor, *, axis: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def argwhere(a: Tensor) -> Tensor: ...
def asCOO(x: Tensor, name: Tensor = ..., check: Tensor = ...) -> Tensor: ...
def as_coo(x: Tensor, shape: Tensor = ..., fill_value: Tensor = ..., idx_dtype: Tensor = ...) -> Tensor: ...
def asarray(obj: Tensor, *, dtype: Tensor = ..., format: Tensor = ..., backend: Tensor = ..., device: Tensor = ..., copy: Tensor = ...) -> Tensor: ...
def asin(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def asinh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def asnumpy(a: Tensor, dtype: Tensor = ..., order: Tensor = ...) -> Tensor: ...
def astype(x: Tensor, dtype: Tensor, *, copy: Tensor = ...) -> Tensor: ...
def atan(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def atan2(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def atanh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bitwise_and(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bitwise_invert(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bitwise_left_shift(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bitwise_not(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bitwise_or(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bitwise_right_shift(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bitwise_xor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bool(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def broadcast_arrays(*arrays: Tensor) -> Tensor: ...
def broadcast_to(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def can_cast(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ceil(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def clip(a: Tensor, a_min: Tensor = ..., a_max: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def complex128(real: Tensor = ..., imag: Tensor = ...) -> Tensor: ...
def complex64(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def concat(arrays: Tensor, axis: Tensor = ..., compressed_axes: Tensor = ...) -> Tensor: ...
def concatenate(arrays: Tensor, axis: Tensor = ..., compressed_axes: Tensor = ...) -> Tensor: ...
def cos(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cosh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def diagonal(a: Tensor, offset: Tensor = ..., axis1: Tensor = ..., axis2: Tensor = ...) -> Tensor: ...
def diagonalize(a: Tensor, axis: Tensor = ...) -> Tensor: ...
def divide(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def dot(a: Tensor, b: Tensor) -> Tensor: ...
def einsum(*operands: Tensor, **kwargs: Tensor) -> Tensor: ...
def elemwise(func: Tensor, *args: Tensor, **kwargs: Tensor) -> Tensor: ...
def empty(shape: Tensor, dtype: Tensor = ..., format: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def empty_like(a: Tensor, dtype: Tensor = ..., shape: Tensor = ..., format: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def equal(x1: Tensor, x2: Tensor) -> Tensor: ...
def exp(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def expm1(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def eye(N: Tensor, M: Tensor = ..., k: Tensor = ..., dtype: Tensor = ..., format: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def finfo(dtype: Tensor) -> Tensor: ...
def float16(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def float32(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def float64(x: Tensor = ...) -> Tensor: ...
def floor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def floor_divide(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def full(shape: Tensor, fill_value: Tensor, dtype: Tensor = ..., format: Tensor = ..., order: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def full_like(a: Tensor, fill_value: Tensor, dtype: Tensor = ..., shape: Tensor = ..., format: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def greater(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def greater_equal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def iinfo(int_type: Tensor) -> Tensor: ...
def int16(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def int32(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def int64(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def int8(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def isfinite(x: Tensor) -> Tensor: ...
def isinf(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def isnan(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def isneginf(x: Tensor, out: Tensor = ...) -> Tensor: ...
def isposinf(x: Tensor, out: Tensor = ...) -> Tensor: ...
def kron(a: Tensor, b: Tensor) -> Tensor: ...
def less(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def less_equal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def load_npz(filename: Tensor) -> Tensor: ...
def log(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def log10(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def log1p(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def log2(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logaddexp(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logical_and(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logical_not(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logical_or(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logical_xor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def matmul(a: Tensor, b: Tensor) -> Tensor: ...
def max(x: Tensor, *, axis: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def mean(x: Tensor, *, axis: Tensor = ..., keepdims: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def min(x: Tensor, *, axis: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def moveaxis(a: Tensor, source: Tensor, destination: Tensor) -> Tensor: ...
def multiply(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def nanmax(x: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., dtype: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nanmean(x: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., dtype: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nanmin(x: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., dtype: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nanprod(x: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., dtype: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nanreduce(x: Tensor, method: Tensor, identity: Tensor = ..., axis: Tensor = ..., keepdims: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def nansum(x: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., dtype: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def negative(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def nonzero(x: Tensor) -> Tensor: ...
def not_equal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ones(shape: Tensor, dtype: Tensor = ..., format: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def ones_like(a: Tensor, dtype: Tensor = ..., shape: Tensor = ..., format: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def outer(a: Tensor, b: Tensor, out: Tensor = ...) -> Tensor: ...
def pad(array: Tensor, pad_width: Tensor, mode: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def permute_dims(x: Tensor, axes: Tensor = ...) -> Tensor: ...
def positive(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def pow(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def prod(x: Tensor, *, axis: Tensor = ..., dtype: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def random(shape: Tensor, density: Tensor = ..., nnz: Tensor = ..., random_state: Tensor = ..., data_rvs: Tensor = ..., format: Tensor = ..., fill_value: Tensor = ..., idx_dtype: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def remainder(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def reshape(x: Tensor, shape: Tensor, *, copy: Tensor = ...) -> Tensor: ...
def result_type(*arrays_and_dtypes: Tensor) -> Tensor: ...
def roll(a: Tensor, shift: Tensor, axis: Tensor = ...) -> Tensor: ...
def round(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def save_npz(filename: Tensor, matrix: Tensor, compressed: Tensor = ...) -> Tensor: ...
def sign(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sin(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sinh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sqrt(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def square(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def squeeze(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def stack(arrays: Tensor, axis: Tensor = ..., compressed_axes: Tensor = ...) -> Tensor: ...
def std(x: Tensor, *, axis: Tensor = ..., correction: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def subtract(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sum(x: Tensor, *, axis: Tensor = ..., dtype: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def tan(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def tanh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def tensordot(a: Tensor, b: Tensor, axes: Tensor = ..., *, return_type: Tensor = ...) -> Tensor: ...
def tril(x: Tensor, k: Tensor = ...) -> Tensor: ...
def triu(x: Tensor, k: Tensor = ...) -> Tensor: ...
def trunc(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def uint16(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def uint32(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def uint64(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def uint8(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def unique_counts(x: Tensor) -> Tensor: ...
def unique_values(x: Tensor) -> Tensor: ...
def where(condition: Tensor, x: Tensor = ..., y: Tensor = ...) -> Tensor: ...
def zeros(shape: Tensor, dtype: Tensor = ..., format: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def zeros_like(a: Tensor, dtype: Tensor = ..., shape: Tensor = ..., format: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
