"""Auto-generated high-fidelity type stubs for sparse from ml-framework-snapshots."""
# ruff: noqa: E501, UP007, UP045, D100, D101, D102, D103

from collections.abc import Sequence

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    device: str
    ndim: int
    size: int
    def __init__(self, data: object = ..., shape: Sequence[int] | None = ..., dtype: str | None = ...) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: object) -> Tensor: ...
    def __add__(self, other: Tensor | float | int) -> Tensor: ...
    def __sub__(self, other: Tensor | float | int) -> Tensor: ...
    def __mul__(self, other: Tensor | float | int) -> Tensor: ...
    def __truediv__(self, other: Tensor | float | int) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def numpy(self) -> object: ...
    def to(self, device: str) -> Tensor: ...
    def reshape(self, shape: Sequence[int]) -> Tensor: ...
    def transpose(self, axes: Sequence[int] | None = ...) -> Tensor: ...

def as_coo(x: Tensor, shape: Tensor = ..., fill_value: Tensor = ..., idx_dtype: Tensor = ...) -> Tensor: ...
def asnumpy(a: Tensor, order: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def concatenate(arrays: Tensor, axis: int = ..., compressed_axes: Tensor = ...) -> Tensor: ...
def diagonal(a: Tensor, offset: int = ..., axis1: int = ..., axis2: int = ...) -> Tensor: ...
def dot(a: Tensor, b: Tensor) -> Tensor: ...
def einsum(*operands: Tensor, subscripts: Tensor, dtype: Tensor, **kwargs: Tensor) -> Tensor: ...
def elemwise(func: Tensor, *args: Tensor, **kwargs: Tensor) -> Tensor: ...
def eye(N: int, M: Tensor = ..., k: int = ..., dtype: Tensor = ..., format: str = ..., **kwargs: Tensor) -> Tensor: ...
def full(shape: Tensor, fill_value: Tensor, dtype: Tensor = ..., format: str = ..., order: str = ..., *, compressed_axes: Tensor, **kwargs: Tensor) -> Tensor: ...
def matmul(a: Tensor, b: Tensor) -> Tensor: ...
def ones(shape: Tensor, dtype: Tensor = ..., format: str = ..., *, compressed_axes: Tensor, **kwargs: Tensor) -> Tensor: ...
def stack(arrays: Tensor, axis: int = ..., compressed_axes: Tensor = ...) -> Tensor: ...
def tensordot(a: Tensor, b: Tensor, axes: int = ..., *, return_type: Tensor = ...) -> Tensor: ...
def zeros(shape: Tensor, dtype: Tensor = ..., format: str = ..., *, compressed_axes: Tensor, **kwargs: Tensor) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
