"""Unary operations package."""

from ml_switcheroo.ops.unary.math import (
    UnaryMathOp,
    Sin,
    Cos,
    Exp,
    Log,
    Sqrt,
    Square,
    Abs,
    Negative,
    Positive,
    Sign,
    Floor,
    Ceil,
    Round,
)

__all__ = [
    "UnaryMathOp",
    "Sin",
    "Cos",
    "Exp",
    "Log",
    "Sqrt",
    "Square",
    "Abs",
    "Negative",
    "Positive",
    "Sign",
    "Floor",
    "Ceil",
    "Round",
]
from .frontend import (
    abs as abs,
    acos as acos,
    acosh as acosh,
    asin as asin,
    asinh as asinh,
    atan as atan,
    atan2 as atan2,
    atanh as atanh,
    bitcast as bitcast,
    bitwise_not as bitwise_not,
    cast as cast,
    cbrt as cbrt,
    ceil as ceil,
    conj as conj,
    cos as cos,
    cosh as cosh,
    deg2rad as deg2rad,
    digamma as digamma,
    erf as erf,
    erfc as erfc,
    erfinv as erfinv,
    exp as exp,
    exp2 as exp2,
    expm1 as expm1,
    fix as fix,
    floor as floor,
    frexp as frexp,
    imag as imag,
    isfinite as isfinite,
    isinf as isinf,
    isnan as isnan,
    lgamma as lgamma,
    log as log,
    log10 as log10,
    log1p as log1p,
    log2 as log2,
    logical_not as logical_not,
    negative as negative,
    positive as positive,
    rad2deg as rad2deg,
    real as real,
    reciprocal as reciprocal,
    round as round,
    rsqrt as rsqrt,
    sign as sign,
    sin as sin,
    sinc as sinc,
    sinh as sinh,
    sqrt as sqrt,
    square as square,
    tan as tan,
    tanh as tanh,
    trunc as trunc,
)
