"""ROCm backend generator."""

import os

import yaml

from ml_switcheroo_compiler.backends.base_generator import BaseGenerator
from ml_switcheroo_compiler.backends.hardware_config_models import HardwareTemplatesConfig
from ml_switcheroo_compiler.backends.registry import register_backend
from ml_switcheroo_compiler.ir.core import IRGraph


@register_backend("rocm")
class RocmCodeGenerator(BaseGenerator):
    """ROCm HIP Code Generator."""

    def __init__(self, graph: IRGraph, delegates=None) -> None:
        """Initialize RocmCodeGenerator.

        Args:
            graph (IRGraph): The IR graph to process.
            delegates (list, optional): Visitor delegates.
        """
        super().__init__(graph, delegates)

        yaml_path = os.path.join(os.path.dirname(__file__), "rocm_templates.yaml")
        if os.path.exists(yaml_path):
            with open(yaml_path) as f:
                self.config = HardwareTemplatesConfig(**yaml.safe_load(f))
        else:
            self.config = HardwareTemplatesConfig(templates={})

    def generate(self) -> str:
        """Generate ROCm HIP code.

        Returns:
            str: Generated ROCm strings.
        """
        hip = ["// ROCm HIP Generated by ml-switcheroo-compiler"]
        hip.append("#include <hip/hip_runtime.h>")
        hip.append("#include <iostream>")
        hip.append("#include <vector>")
        hip.append("")
        hip.append("#define HIP_CHECK(call) \\")
        hip.append("    do { \\")
        hip.append("        hipError_t err = call; \\")
        hip.append("        if (err != hipSuccess) { \\")
        hip.append('            std::cerr << "HIP Error: " << hipGetErrorString(err) << " at " << __FILE__ << ":" << __LINE__ << std::endl; \\')
        hip.append("            exit(err); \\")
        hip.append("        } \\")
        hip.append("    } while (0)")
        hip.append("")

        for node in getattr(self.graph, "nodes", {}).values():
            op_type = getattr(node, "op_type", "")
            tpl = self.config.templates.get(op_type.lower())
            if tpl:
                hip.append(tpl.body)

        hip.append("void evaluate_rocm(const std::vector<float*>& inputs, std::vector<float*>& outputs) {")
        hip.append("    // 1. Memory Allocation (Host to Device)")

        node_idx = 0
        for _node_id, node in getattr(self.graph, "nodes", {}).items():
            op_type = getattr(node, "op_type", "")
            tpl = self.config.templates.get(op_type.lower())
            if tpl:
                out_name = f"d_out_{node_idx}"
                hip.append(f"    float* {out_name};")
                hip.append(f"    HIP_CHECK(hipMalloc(&{out_name}, 1024 * sizeof(float))); // Mock size")
                wg = tpl.workgroup_size
                hip.append(f"    dim3 block_{node_idx}({wg[0]}, {wg[1]}, {wg[2]});")
                hip.append(f"    dim3 grid_{node_idx}((1024 + block_{node_idx}.x - 1) / block_{node_idx}.x, 1, 1);")
                hip.append(f"    hipLaunchKernelGGL({op_type.lower()}, grid_{node_idx}, block_{node_idx}, 0, 0, inputs[0], inputs[1], {out_name}, 1024);")
                hip.append("    HIP_CHECK(hipGetLastError());")
                node_idx += 1

        hip.append("    HIP_CHECK(hipDeviceSynchronize());")
        hip.append("}")

        return "\n".join(hip)
