"""Auto-generated high-fidelity type stubs for rocm from ml-ecosystem-snapshots."""
# ruff: noqa: E501, UP007, UP045, D100, D101, D102, D103

from collections.abc import Sequence

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    device: str
    ndim: int
    size: int
    def __init__(self, data: object = ..., shape: Sequence[int] | None = ..., dtype: str | None = ...) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: object) -> Tensor: ...
    def __add__(self, other: Tensor | float | int) -> Tensor: ...
    def __sub__(self, other: Tensor | float | int) -> Tensor: ...
    def __mul__(self, other: Tensor | float | int) -> Tensor: ...
    def __truediv__(self, other: Tensor | float | int) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def numpy(self) -> object: ...
    def to(self, device: str) -> Tensor: ...
    def reshape(self, shape: Sequence[int]) -> Tensor: ...
    def transpose(self, axes: Sequence[int] | None = ...) -> Tensor: ...

def global_load_dword(op0: Tensor, op1: Tensor) -> Tensor: ...
def global_store_dword(op0: Tensor, op1: Tensor) -> Tensor: ...
def s_add_u32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def s_mov_b32(op0: Tensor, op1: Tensor) -> Tensor: ...
def s_waitcnt(op0: Tensor) -> Tensor: ...
def v_add_f32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def v_dot4c_i32_i8(op0: Tensor, op1: Tensor, op2: Tensor, op3: Tensor) -> Tensor: ...
def v_dual_add_f32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def v_dual_fmac_f32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def v_fma_f32(op0: Tensor, op1: Tensor, op2: Tensor, op3: Tensor) -> Tensor: ...
def v_fmac_f32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def v_mov_b32(op0: Tensor, op1: Tensor) -> Tensor: ...
def v_mul_f32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def v_sub_f32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
