"""Auto-generated high-fidelity type stubs for keras from live module introspection."""
# ruff: noqa: E501

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    def __init__(self, *args: object, **kwargs: object) -> None: ...

def abs(x: Tensor) -> Tensor: ...
def absolute(x: Tensor) -> Tensor: ...
def add(x1: Tensor, x2: Tensor) -> Tensor: ...
def all(x: Tensor, axis: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def amax(x: Tensor, axis: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def amin(x: Tensor, axis: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def angle(x: Tensor) -> Tensor: ...
def any(x: Tensor, axis: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def append(x1: Tensor, x2: Tensor, axis: Tensor = ...) -> Tensor: ...
def arange(start: Tensor, stop: Tensor = ..., step: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def arccos(x: Tensor) -> Tensor: ...
def arccosh(x: Tensor) -> Tensor: ...
def arcsin(x: Tensor) -> Tensor: ...
def arcsinh(x: Tensor) -> Tensor: ...
def arctan(x: Tensor) -> Tensor: ...
def arctan2(x1: Tensor, x2: Tensor) -> Tensor: ...
def arctanh(x: Tensor) -> Tensor: ...
def argmax(x: Tensor, axis: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def argmin(x: Tensor, axis: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def argpartition(x: Tensor, kth: Tensor, axis: Tensor = ...) -> Tensor: ...
def argsort(x: Tensor, axis: Tensor = ...) -> Tensor: ...
def array(x: Tensor, dtype: Tensor = ...) -> Tensor: ...
def associative_scan(f: Tensor, elems: Tensor, reverse: Tensor = ..., axis: Tensor = ...) -> Tensor: ...
def average(x: Tensor, axis: Tensor = ..., weights: Tensor = ...) -> Tensor: ...
def average_pool(inputs: Tensor, pool_size: Tensor, strides: Tensor = ..., padding: Tensor = ..., data_format: Tensor = ...) -> Tensor: ...
def bartlett(x: Tensor) -> Tensor: ...
def batch_normalization(x: Tensor, mean: Tensor, variance: Tensor, axis: Tensor, offset: Tensor = ..., scale: Tensor = ..., epsilon: Tensor = ...) -> Tensor: ...
def binary_crossentropy(target: Tensor, output: Tensor, from_logits: Tensor = ...) -> Tensor: ...
def bincount(x: Tensor, weights: Tensor = ..., minlength: Tensor = ..., sparse: Tensor = ...) -> Tensor: ...
def bitwise_and(x: Tensor, y: Tensor) -> Tensor: ...
def bitwise_invert(x: Tensor) -> Tensor: ...
def bitwise_left_shift(x: Tensor, y: Tensor) -> Tensor: ...
def bitwise_not(x: Tensor) -> Tensor: ...
def bitwise_or(x: Tensor, y: Tensor) -> Tensor: ...
def bitwise_right_shift(x: Tensor, y: Tensor) -> Tensor: ...
def bitwise_xor(x: Tensor, y: Tensor) -> Tensor: ...
def blackman(x: Tensor) -> Tensor: ...
def broadcast_to(x: Tensor, shape: Tensor) -> Tensor: ...
def cast(x: Tensor, dtype: Tensor) -> Tensor: ...
def categorical_crossentropy(target: Tensor, output: Tensor, from_logits: Tensor = ..., axis: Tensor = ...) -> Tensor: ...
def ceil(x: Tensor) -> Tensor: ...
def celu(x: Tensor, alpha: Tensor = ...) -> Tensor: ...
def cholesky(x: Tensor) -> Tensor: ...
def clip(x: Tensor, x_min: Tensor, x_max: Tensor) -> Tensor: ...
def concatenate(xs: Tensor, axis: Tensor = ...) -> Tensor: ...
def cond(pred: Tensor, true_fn: Tensor, false_fn: Tensor) -> Tensor: ...
def conj(x: Tensor) -> Tensor: ...
def conjugate(x: Tensor) -> Tensor: ...
def conv(inputs: Tensor, kernel: Tensor, strides: Tensor = ..., padding: Tensor = ..., data_format: Tensor = ..., dilation_rate: Tensor = ...) -> Tensor: ...
def conv_transpose(inputs: Tensor, kernel: Tensor, strides: Tensor, padding: Tensor = ..., output_padding: Tensor = ..., data_format: Tensor = ..., dilation_rate: Tensor = ...) -> Tensor: ...
def convert_to_numpy(x: Tensor) -> Tensor: ...
def convert_to_tensor(x: Tensor, dtype: Tensor = ..., sparse: Tensor = ..., ragged: Tensor = ...) -> Tensor: ...
def copy(x: Tensor) -> Tensor: ...
def correlate(x1: Tensor, x2: Tensor, mode: Tensor = ...) -> Tensor: ...
def cos(x: Tensor) -> Tensor: ...
def cosh(x: Tensor) -> Tensor: ...
def count_nonzero(x: Tensor, axis: Tensor = ...) -> Tensor: ...
def cross(x1: Tensor, x2: Tensor, axisa: Tensor = ..., axisb: Tensor = ..., axisc: Tensor = ..., axis: Tensor = ...) -> Tensor: ...
def ctc_decode(inputs: Tensor, sequence_lengths: Tensor, strategy: Tensor = ..., beam_width: Tensor = ..., top_paths: Tensor = ..., merge_repeated: Tensor = ..., mask_index: Tensor = ...) -> Tensor: ...
def ctc_loss(target: Tensor, output: Tensor, target_length: Tensor, output_length: Tensor, mask_index: Tensor = ...) -> Tensor: ...
def cumprod(x: Tensor, axis: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def cumsum(x: Tensor, axis: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def custom_gradient(f: Tensor) -> Tensor: ...
def depthwise_conv(inputs: Tensor, kernel: Tensor, strides: Tensor = ..., padding: Tensor = ..., data_format: Tensor = ..., dilation_rate: Tensor = ...) -> Tensor: ...
def det(x: Tensor) -> Tensor: ...
def diag(x: Tensor, k: Tensor = ...) -> Tensor: ...
def diagflat(x: Tensor, k: Tensor = ...) -> Tensor: ...
def diagonal(x: Tensor, offset: Tensor = ..., axis1: Tensor = ..., axis2: Tensor = ...) -> Tensor: ...
def diff(a: Tensor, n: Tensor = ..., axis: Tensor = ...) -> Tensor: ...
def digitize(x: Tensor, bins: Tensor) -> Tensor: ...
def divide(x1: Tensor, x2: Tensor) -> Tensor: ...
def divide_no_nan(x1: Tensor, x2: Tensor) -> Tensor: ...
def dot(x1: Tensor, x2: Tensor) -> Tensor: ...
def dot_product_attention(query: Tensor, key: Tensor, value: Tensor, bias: Tensor = ..., mask: Tensor = ..., scale: Tensor = ..., is_causal: Tensor = ..., flash_attention: Tensor = ..., attn_logits_soft_cap: Tensor = ...) -> Tensor: ...
def dtype(x: Tensor) -> Tensor: ...
def eig(x: Tensor) -> Tensor: ...
def eigh(x: Tensor) -> Tensor: ...
def einsum(subscripts: Tensor, *operands: Tensor) -> Tensor: ...
def elu(x: Tensor, alpha: Tensor = ...) -> Tensor: ...
def empty(shape: Tensor, dtype: Tensor = ...) -> Tensor: ...
def equal(x1: Tensor, x2: Tensor) -> Tensor: ...
def erf(x: Tensor) -> Tensor: ...
def erfinv(x: Tensor) -> Tensor: ...
def exp(x: Tensor) -> Tensor: ...
def exp2(x: Tensor) -> Tensor: ...
def expand_dims(x: Tensor, axis: Tensor) -> Tensor: ...
def expm1(x: Tensor) -> Tensor: ...
def extract_sequences(x: Tensor, sequence_length: Tensor, sequence_stride: Tensor) -> Tensor: ...
def eye(N: Tensor, M: Tensor = ..., k: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def fft(x: Tensor) -> Tensor: ...
def fft2(x: Tensor) -> Tensor: ...
def flip(x: Tensor, axis: Tensor = ...) -> Tensor: ...
def floor(x: Tensor) -> Tensor: ...
def floor_divide(x1: Tensor, x2: Tensor) -> Tensor: ...
def fori_loop(lower: Tensor, upper: Tensor, body_fun: Tensor, init_val: Tensor) -> Tensor: ...
def full(shape: Tensor, fill_value: Tensor, dtype: Tensor = ...) -> Tensor: ...
def full_like(x: Tensor, fill_value: Tensor, dtype: Tensor = ...) -> Tensor: ...
def gelu(x: Tensor, approximate: Tensor = ...) -> Tensor: ...
def get_item(x: Tensor, key: Tensor) -> Tensor: ...
def glu(x: Tensor, axis: Tensor = ...) -> Tensor: ...
def greater(x1: Tensor, x2: Tensor) -> Tensor: ...
def greater_equal(x1: Tensor, x2: Tensor) -> Tensor: ...
def hamming(x: Tensor) -> Tensor: ...
def hard_shrink(x: Tensor, threshold: Tensor = ...) -> Tensor: ...
def hard_sigmoid(x: Tensor) -> Tensor: ...
def hard_silu(x: Tensor) -> Tensor: ...
def hard_swish(x: Tensor) -> Tensor: ...
def hard_tanh(x: Tensor) -> Tensor: ...
def histogram(x: Tensor, bins: Tensor = ..., range: Tensor = ...) -> Tensor: ...
def hstack(xs: Tensor) -> Tensor: ...
def identity(n: Tensor, dtype: Tensor = ...) -> Tensor: ...
def ifft2(x: Tensor) -> Tensor: ...
def imag(x: Tensor) -> Tensor: ...
def in_top_k(targets: Tensor, predictions: Tensor, k: Tensor) -> Tensor: ...
def inner(x1: Tensor, x2: Tensor) -> Tensor: ...
def inv(x: Tensor) -> Tensor: ...
def irfft(x: Tensor, fft_length: Tensor = ...) -> Tensor: ...
def is_tensor(x: Tensor) -> Tensor: ...
def isclose(x1: Tensor, x2: Tensor, rtol: Tensor = ..., atol: Tensor = ..., equal_nan: Tensor = ...) -> Tensor: ...
def isfinite(x: Tensor) -> Tensor: ...
def isinf(x: Tensor) -> Tensor: ...
def isnan(x: Tensor) -> Tensor: ...
def istft(x: Tensor, sequence_length: Tensor, sequence_stride: Tensor, fft_length: Tensor, length: Tensor = ..., window: Tensor = ..., center: Tensor = ...) -> Tensor: ...
def leaky_relu(x: Tensor, negative_slope: Tensor = ...) -> Tensor: ...
def left_shift(x: Tensor, y: Tensor) -> Tensor: ...
def less(x1: Tensor, x2: Tensor) -> Tensor: ...
def less_equal(x1: Tensor, x2: Tensor) -> Tensor: ...
def linspace(start: Tensor, stop: Tensor, num: Tensor = ..., endpoint: Tensor = ..., retstep: Tensor = ..., dtype: Tensor = ..., axis: Tensor = ...) -> Tensor: ...
def log(x: Tensor) -> Tensor: ...
def log10(x: Tensor) -> Tensor: ...
def log1p(x: Tensor) -> Tensor: ...
def log2(x: Tensor) -> Tensor: ...
def log_sigmoid(x: Tensor) -> Tensor: ...
def log_softmax(x: Tensor, axis: Tensor = ...) -> Tensor: ...
def logaddexp(x1: Tensor, x2: Tensor) -> Tensor: ...
def logdet(x: Tensor) -> Tensor: ...
def logical_and(x1: Tensor, x2: Tensor) -> Tensor: ...
def logical_not(x: Tensor) -> Tensor: ...
def logical_or(x1: Tensor, x2: Tensor) -> Tensor: ...
def logical_xor(x1: Tensor, x2: Tensor) -> Tensor: ...
def logspace(start: Tensor, stop: Tensor, num: Tensor = ..., endpoint: Tensor = ..., base: Tensor = ..., dtype: Tensor = ..., axis: Tensor = ...) -> Tensor: ...
def logsumexp(x: Tensor, axis: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def lstsq(a: Tensor, b: Tensor, rcond: Tensor = ...) -> Tensor: ...
def lu_factor(x: Tensor) -> Tensor: ...
def map(f: Tensor, xs: Tensor) -> Tensor: ...
def matmul(x1: Tensor, x2: Tensor) -> Tensor: ...
def max(x: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., initial: Tensor = ...) -> Tensor: ...
def max_pool(inputs: Tensor, pool_size: Tensor, strides: Tensor = ..., padding: Tensor = ..., data_format: Tensor = ...) -> Tensor: ...
def maximum(x1: Tensor, x2: Tensor) -> Tensor: ...
def mean(x: Tensor, axis: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def median(x: Tensor, axis: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def meshgrid(*x: Tensor, indexing: Tensor = ...) -> Tensor: ...
def min(x: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., initial: Tensor = ...) -> Tensor: ...
def minimum(x1: Tensor, x2: Tensor) -> Tensor: ...
def mod(x1: Tensor, x2: Tensor) -> Tensor: ...
def moments(x: Tensor, axes: Tensor, keepdims: Tensor = ..., synchronized: Tensor = ...) -> Tensor: ...
def moveaxis(x: Tensor, source: Tensor, destination: Tensor) -> Tensor: ...
def multi_hot(inputs: Tensor, num_classes: Tensor = ..., axis: Tensor = ..., dtype: Tensor = ..., sparse: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def multiply(x1: Tensor, x2: Tensor) -> Tensor: ...
def nan_to_num(x: Tensor, nan: Tensor = ..., posinf: Tensor = ..., neginf: Tensor = ...) -> Tensor: ...
def ndim(x: Tensor) -> Tensor: ...
def negative(x: Tensor) -> Tensor: ...
def nonzero(x: Tensor) -> Tensor: ...
def norm(x: Tensor, ord: Tensor = ..., axis: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def normalize(x: Tensor, axis: Tensor = ..., order: Tensor = ..., epsilon: Tensor = ...) -> Tensor: ...
def not_equal(x1: Tensor, x2: Tensor) -> Tensor: ...
def one_hot(x: Tensor, num_classes: Tensor, axis: Tensor = ..., dtype: Tensor = ..., sparse: Tensor = ...) -> Tensor: ...
def ones(shape: Tensor, dtype: Tensor = ...) -> Tensor: ...
def ones_like(x: Tensor, dtype: Tensor = ...) -> Tensor: ...
def outer(x1: Tensor, x2: Tensor) -> Tensor: ...
def pad(x: Tensor, pad_width: Tensor, mode: Tensor = ..., constant_values: Tensor = ...) -> Tensor: ...
def polar(abs_: Tensor, angle: Tensor) -> Tensor: ...
def power(x1: Tensor, x2: Tensor) -> Tensor: ...
def prod(x: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def psnr(x1: Tensor, x2: Tensor, max_val: Tensor) -> Tensor: ...
def qr(x: Tensor, mode: Tensor = ...) -> Tensor: ...
def quantile(x: Tensor, q: Tensor, axis: Tensor = ..., method: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def ravel(x: Tensor) -> Tensor: ...
def real(x: Tensor) -> Tensor: ...
def rearrange(tensor: Tensor, pattern: Tensor, **axes_lengths: Tensor) -> Tensor: ...
def reciprocal(x: Tensor) -> Tensor: ...
def relu(x: Tensor) -> Tensor: ...
def relu6(x: Tensor) -> Tensor: ...
def repeat(x: Tensor, repeats: Tensor, axis: Tensor = ...) -> Tensor: ...
def reshape(x: Tensor, newshape: Tensor) -> Tensor: ...
def rfft(x: Tensor, fft_length: Tensor = ...) -> Tensor: ...
def right_shift(x: Tensor, y: Tensor) -> Tensor: ...
def rms_normalization(x: Tensor, scale: Tensor = ..., axis: Tensor = ..., epsilon: Tensor = ...) -> Tensor: ...
def roll(x: Tensor, shift: Tensor, axis: Tensor = ...) -> Tensor: ...
def rot90(array: Tensor, k: Tensor = ..., axes: Tensor = ...) -> Tensor: ...
def round(x: Tensor, decimals: Tensor = ...) -> Tensor: ...
def rsqrt(x: Tensor) -> Tensor: ...
def saturate_cast(x: Tensor, dtype: Tensor) -> Tensor: ...
def scan(f: Tensor, init: Tensor, xs: Tensor = ..., length: Tensor = ..., reverse: Tensor = ..., unroll: Tensor = ...) -> Tensor: ...
def scatter(indices: Tensor, values: Tensor, shape: Tensor) -> Tensor: ...
def scatter_update(inputs: Tensor, indices: Tensor, updates: Tensor) -> Tensor: ...
def searchsorted(sorted_sequence: Tensor, values: Tensor, side: Tensor = ...) -> Tensor: ...
def segment_max(data: Tensor, segment_ids: Tensor, num_segments: Tensor = ..., sorted: Tensor = ...) -> Tensor: ...
def segment_sum(data: Tensor, segment_ids: Tensor, num_segments: Tensor = ..., sorted: Tensor = ...) -> Tensor: ...
def select(condlist: Tensor, choicelist: Tensor, default: Tensor = ...) -> Tensor: ...
def selu(x: Tensor) -> Tensor: ...
def separable_conv(inputs: Tensor, depthwise_kernel: Tensor, pointwise_kernel: Tensor, strides: Tensor = ..., padding: Tensor = ..., data_format: Tensor = ..., dilation_rate: Tensor = ...) -> Tensor: ...
def shape(x: Tensor) -> Tensor: ...
def sigmoid(x: Tensor) -> Tensor: ...
def sign(x: Tensor) -> Tensor: ...
def signbit(x: Tensor) -> Tensor: ...
def silu(x: Tensor) -> Tensor: ...
def sin(x: Tensor) -> Tensor: ...
def sinh(x: Tensor) -> Tensor: ...
def size(x: Tensor) -> Tensor: ...
def slice(inputs: Tensor, start_indices: Tensor, shape: Tensor) -> Tensor: ...
def slice_update(inputs: Tensor, start_indices: Tensor, updates: Tensor) -> Tensor: ...
def slogdet(x: Tensor) -> Tensor: ...
def soft_shrink(x: Tensor, threshold: Tensor = ...) -> Tensor: ...
def softmax(x: Tensor, axis: Tensor = ...) -> Tensor: ...
def softplus(x: Tensor) -> Tensor: ...
def softsign(x: Tensor) -> Tensor: ...
def solve(a: Tensor, b: Tensor) -> Tensor: ...
def solve_triangular(a: Tensor, b: Tensor, lower: Tensor = ...) -> Tensor: ...
def sort(x: Tensor, axis: Tensor = ...) -> Tensor: ...
def sparse_categorical_crossentropy(target: Tensor, output: Tensor, from_logits: Tensor = ..., axis: Tensor = ...) -> Tensor: ...
def sparse_plus(x: Tensor) -> Tensor: ...
def sparse_sigmoid(x: Tensor) -> Tensor: ...
def sparsemax(x: Tensor, axis: Tensor = ...) -> Tensor: ...
def split(x: Tensor, indices_or_sections: Tensor, axis: Tensor = ...) -> Tensor: ...
def sqrt(x: Tensor) -> Tensor: ...
def square(x: Tensor) -> Tensor: ...
def squareplus(x: Tensor, b: Tensor = ...) -> Tensor: ...
def squeeze(x: Tensor, axis: Tensor = ...) -> Tensor: ...
def stack(x: Tensor, axis: Tensor = ...) -> Tensor: ...
def std(x: Tensor, axis: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def stft(x: Tensor, sequence_length: Tensor, sequence_stride: Tensor, fft_length: Tensor, window: Tensor = ..., center: Tensor = ...) -> Tensor: ...
def stop_gradient(variable: Tensor) -> Tensor: ...
def subtract(x1: Tensor, x2: Tensor) -> Tensor: ...
def sum(x: Tensor, axis: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def svd(x: Tensor, full_matrices: Tensor = ..., compute_uv: Tensor = ...) -> Tensor: ...
def swapaxes(x: Tensor, axis1: Tensor, axis2: Tensor) -> Tensor: ...
def swish(x: Tensor) -> Tensor: ...
def switch(index: Tensor, branches: Tensor, *operands: Tensor) -> Tensor: ...
def take(x: Tensor, indices: Tensor, axis: Tensor = ...) -> Tensor: ...
def take_along_axis(x: Tensor, indices: Tensor, axis: Tensor = ...) -> Tensor: ...
def tan(x: Tensor) -> Tensor: ...
def tanh(x: Tensor) -> Tensor: ...
def tanh_shrink(x: Tensor) -> Tensor: ...
def tensordot(x1: Tensor, x2: Tensor, axes: Tensor = ...) -> Tensor: ...
def threshold(x: Tensor, threshold: Tensor, default_value: Tensor) -> Tensor: ...
def tile(x: Tensor, repeats: Tensor) -> Tensor: ...
def top_k(x: Tensor, k: Tensor, sorted: Tensor = ...) -> Tensor: ...
def trace(x: Tensor, offset: Tensor = ..., axis1: Tensor = ..., axis2: Tensor = ...) -> Tensor: ...
def transpose(x: Tensor, axes: Tensor = ...) -> Tensor: ...
def tri(N: Tensor, M: Tensor = ..., k: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def tril(x: Tensor, k: Tensor = ...) -> Tensor: ...
def triu(x: Tensor, k: Tensor = ...) -> Tensor: ...
def true_divide(x1: Tensor, x2: Tensor) -> Tensor: ...
def trunc(x: Tensor) -> Tensor: ...
def unravel_index(indices: Tensor, shape: Tensor) -> Tensor: ...
def unstack(x: Tensor, num: Tensor = ..., axis: Tensor = ...) -> Tensor: ...
def var(x: Tensor, axis: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def vdot(x1: Tensor, x2: Tensor) -> Tensor: ...
def vectorize(pyfunc: Tensor, *, excluded: Tensor = ..., signature: Tensor = ...) -> Tensor: ...
def vectorized_map(function: Tensor, elements: Tensor) -> Tensor: ...
def view_as_complex(x: Tensor) -> Tensor: ...
def view_as_real(x: Tensor) -> Tensor: ...
def vstack(xs: Tensor) -> Tensor: ...
def where(condition: Tensor, x1: Tensor = ..., x2: Tensor = ...) -> Tensor: ...
def while_loop(cond: Tensor, body: Tensor, loop_vars: Tensor, maximum_iterations: Tensor = ...) -> Tensor: ...
def zeros(shape: Tensor, dtype: Tensor = ...) -> Tensor: ...
def zeros_like(x: Tensor, dtype: Tensor = ...) -> Tensor: ...
def resize(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
