"""Auto-generated type stubs from snapshot."""

class Tensor: ...

def celu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def deserialize(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def elu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def exponential(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def gelu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def get(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def glu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def hard_shrink(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def hard_sigmoid(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def hard_silu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def hard_tanh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def leaky_relu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def linear(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def log_sigmoid(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def log_softmax(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def mish(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def relu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def relu6(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def selu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def serialize(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sigmoid(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def silu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def soft_shrink(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def softmax(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def softplus(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def softsign(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sparse_plus(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sparse_sigmoid(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sparsemax(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def squareplus(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def tanh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def tanh_shrink(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def threshold(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
