"""CUDA backend generator."""

import os
from typing import Any

import yaml

from ml_switcheroo_compiler.backends.base_generator import BaseGenerator
from ml_switcheroo_compiler.backends.hardware_config_models import HardwareTemplatesConfig
from ml_switcheroo_compiler.backends.registry import register_backend
from ml_switcheroo_compiler.ir.core import IRGraph


@register_backend("cuda")
class CudaCodeGenerator(BaseGenerator):
    """CUDA C++ Code Generator."""

    def __init__(self, graph: IRGraph, delegates: Any = None) -> None:
        """Initialize CudaCodeGenerator.

        Args:
            graph (IRGraph): The IR graph to process.
            delegates (Any, optional): Visitor delegates.
        """
        super().__init__(graph, delegates)

        yaml_path: str = os.path.join(os.path.dirname(__file__), "cuda_templates.yaml")
        if os.path.exists(yaml_path):
            with open(yaml_path) as f:
                self.config = HardwareTemplatesConfig(**yaml.safe_load(f))
        else:
            self.config = HardwareTemplatesConfig(templates={})

    def generate(self) -> str:
        """Generate CUDA C++ code.

        Returns:
            str: Generated CUDA strings.
        """
        cuda: list[str] = ["// CUDA Generated by ml-switcheroo-compiler"]
        cuda.append("#include <cuda_runtime.h>")
        cuda.append("#include <iostream>")
        cuda.append("#include <vector>")
        cuda.append("")
        cuda.append("#define CUDA_CHECK(call) \\")
        cuda.append("    do { \\")
        cuda.append("        cudaError_t err = call; \\")
        cuda.append("        if (err != cudaSuccess) { \\")
        cuda.append('            std::cerr << "CUDA Error: " << cudaGetErrorString(err) << " at " << __FILE__ << ":" << __LINE__ << std::endl; \\')
        cuda.append("            exit(err); \\")
        cuda.append("        } \\")
        cuda.append("    } while (0)")
        cuda.append("")

        for node in getattr(self.graph, "nodes", {}).values():
            op_type: str = getattr(node, "op_type", "")
            tpl = self.config.templates.get(op_type.lower())
            if tpl:
                cuda.append(tpl.body)

        cuda.append("void evaluate_cuda(const std::vector<float*>& inputs, std::vector<float*>& outputs) {")
        cuda.append("    // 1. Memory Allocation (Host to Device)")

        node_idx: int = 0
        for _node_id, node in getattr(self.graph, "nodes", {}).items():
            op_type = getattr(node, "op_type", "")
            tpl = self.config.templates.get(op_type.lower())
            if tpl:
                out_name: str = f"d_out_{node_idx}"
                cuda.append(f"    float* {out_name};")
                cuda.append(f"    CUDA_CHECK(cudaMalloc(&{out_name}, 1024 * sizeof(float))); // Mock size")
                wg: list[int] = tpl.workgroup_size
                cuda.append(f"    dim3 block_{node_idx}({wg[0]}, {wg[1]}, {wg[2]});")
                cuda.append(f"    dim3 grid_{node_idx}((1024 + block_{node_idx}.x - 1) / block_{node_idx}.x, 1, 1);")
                cuda.append(f"    {op_type.lower()}<<<grid_{node_idx}, block_{node_idx}>>>(inputs[0], inputs[1], {out_name}, 1024);")
                cuda.append("    CUDA_CHECK(cudaGetLastError());")
                node_idx += 1

        cuda.append("    CUDA_CHECK(cudaDeviceSynchronize());")
        cuda.append("}")
        return "\n".join(cuda)
