"""CUDA backend generator."""

import ctypes
import ctypes.util

try:
    import cupy
except ImportError:
    cupy = None
import os
from typing import Optional

import yaml

from ml_switcheroo_compiler.backends.base_generator import BaseGenerator
from ml_switcheroo_compiler.backends.hardware_config_models import HardwareTemplatesConfig
from ml_switcheroo_compiler.backends.registry import register_backend
from ml_switcheroo_compiler.backends.visitor import CodeGeneratorVisitor
from ml_switcheroo_compiler.ir.core import IRGraph


@register_backend("cuda")
class CudaCodeGenerator(BaseGenerator):
    """CUDA C++ Code Generator."""

    def __init__(self, graph: IRGraph, delegates: Optional[list[CodeGeneratorVisitor]] = None) -> None:
        """Initialize CudaCodeGenerator.

        Args:
            graph (IRGraph): The IR graph to process.
            delegates (Optional[list[CodeGeneratorVisitor]], optional): Visitor delegates.
        """
        super().__init__(graph, delegates)

        yaml_dir: str = os.path.join(os.path.dirname(__file__), "cuda_orchestration")
        yaml_path: str = os.path.join(os.path.dirname(__file__), "cuda_templates.yaml")
        self.config = HardwareTemplatesConfig(templates={})
        if os.path.isdir(yaml_dir):
            for filename in os.listdir(yaml_dir):
                if filename.endswith(".yaml"):
                    with open(os.path.join(yaml_dir, filename)) as f:
                        op_data = yaml.safe_load(f)
                        if isinstance(op_data, dict):
                            source = op_data.get("templates", op_data)
                            for k, v in source.items():
                                if isinstance(v, dict) and "body" in v:
                                    self.config.templates[k] = v
                                elif isinstance(v, str):
                                    self.config.templates[k] = {"body": v}
                                else:
                                    self.config.templates[k] = v
        elif os.path.exists(yaml_path):
            with open(yaml_path) as f:
                data = yaml.safe_load(f)
                if data and "templates" in data:
                    self.config.templates.update(data["templates"])

    def generate(self) -> str:
        """Generate CUDA C++ code.

        Returns:
            str: Generated CUDA strings.
        """
        cuda: list[str] = ["// CUDA Generated by ml-switcheroo-compiler"]
        cuda.append("#include <cuda_runtime.h>")
        cuda.append("#include <iostream>")
        cuda.append("#include <vector>")
        cuda.append("")
        cuda.append("#define CUDA_CHECK(call) \\")
        cuda.append("    do { \\")
        cuda.append("        cudaError_t err = call; \\")
        cuda.append("        if (err != cudaSuccess) { \\")
        cuda.append('            std::cerr << "CUDA Error: " << cudaGetErrorString(err) << " at " << __FILE__ << ":" << __LINE__ << std::endl; \\')
        cuda.append("            exit(err); \\")
        cuda.append("        } \\")
        cuda.append("    } while (0)")
        cuda.append("")

        for node in getattr(self.graph, "nodes", {}).values():
            op_type: str = getattr(node, "op_type", "")
            tpl = self.config.templates.get(op_type.lower())
            if tpl:
                cuda.append(tpl.get("body", ""))

        cuda.append("void evaluate_cuda(const std::vector<float*>& inputs, std::vector<float*>& outputs) {")
        cuda.append("    // 1. Memory Allocation (Host to Device)")

        node_idx: int = 0
        for _node_id, node in getattr(self.graph, "nodes", {}).items():
            op_type = getattr(node, "op_type", "")
            tpl = self.config.templates.get(op_type.lower())
            if tpl:
                out_name: str = f"d_out_{node_idx}"
                cuda.append(f"    float* {out_name};")
                cuda.append(f"    CUDA_CHECK(cudaMalloc(&{out_name}, 1024 * sizeof(float))); // Mock size")
                wg: list[int] = tpl.get("workgroup_size", [1, 1, 1])
                cuda.append(f"    dim3 block_{node_idx}({wg[0]}, {wg[1]}, {wg[2]});")
                cuda.append(f"    dim3 grid_{node_idx}((1024 + block_{node_idx}.x - 1) / block_{node_idx}.x, 1, 1);")
                cuda.append(f"    {op_type.lower()}<<<grid_{node_idx}, block_{node_idx}>>>(inputs[0], inputs[1], {out_name}, 1024);")
                cuda.append("    CUDA_CHECK(cudaGetLastError());")
                node_idx += 1

        cuda.append("    CUDA_CHECK(cudaDeviceSynchronize());")
        cuda.append("}")
        return "\n".join(cuda)


class CUDARunner:
    """CUDA Runner utilizing cupy if available, fallback to ctypes driver API."""

    def __init__(self) -> None:
        """Initialize CUDARunner and load hardware limits."""
        self.limits: dict[str, object] = {}
        limits_path: str = os.path.join(os.path.dirname(__file__), "hardware_limits.yaml")
        if os.path.exists(limits_path):
            with open(limits_path) as f:
                self.limits = yaml.safe_load(f)

        self.cuda_lib = None
        self._ctx = None

        if cupy is not None:
            self.mode = "cupy"
        else:
            self.mode = "ctypes"
            try:
                # Basic initialization for testing purposes without cupy
                cuda_lib_path = ctypes.util.find_library("cuda")
                if cuda_lib_path:
                    self.cuda_lib = ctypes.cdll.LoadLibrary(cuda_lib_path)
                    self.cuda_lib.cuInit(0)
                    device = ctypes.c_int()
                    self.cuda_lib.cuDeviceGet(ctypes.byref(device), 0)
                    self._ctx = ctypes.c_void_p()
                    self.cuda_lib.cuCtxCreate_v2(ctypes.byref(self._ctx), 0, device)
            except Exception:
                pass

    def allocate_buffer(self, size: int) -> Optional[ctypes.c_void_p]:
        """Allocate device memory.

        Args:
            size (int): Size in bytes.

        Returns:
            Optional[ctypes.c_void_p]: Pointer to device memory.
        """
        if self.mode == "cupy" and cupy is not None:
            mem = cupy.cuda.alloc(size)
            return ctypes.c_void_p(mem.ptr)

        if not self.cuda_lib:
            return ctypes.c_void_p(0)

        dptr = ctypes.c_void_p()
        res = self.cuda_lib.cuMemAlloc_v2(ctypes.byref(dptr), size)
        if res != 0:
            raise RuntimeError(f"cuMemAlloc failed with error code {res}")
        return dptr

    def write_buffer(self, device_ptr: ctypes.c_void_p, host_data: bytes) -> None:
        """Write to device buffer.

        Args:
            device_ptr (ctypes.c_void_p): Device pointer.
            host_data (bytes): Data to write.
        """
        if not device_ptr:
            return

        if self.mode == "cupy" and cupy is not None:
            # We can use numpy to write the bytes memory
            # NO_NUMPY_ALLOWED (relying on builtins or cupy native arrays directly, though numpy is the exception here it failed the hook)

            arr = cupy.asarray(memoryview(host_data).cast("B"))
            dst = cupy.ndarray(arr.shape, dtype=arr.dtype, memptr=cupy.cuda.MemoryPointer(cupy.cuda.UnownedMemory(device_ptr.value, arr.nbytes, device_ptr), 0))
            dst.set(arr)
            return

        if self.cuda_lib:
            res = self.cuda_lib.cuMemcpyHtoD_v2(device_ptr, host_data, len(host_data))
            if res != 0:
                raise RuntimeError(f"cuMemcpyHtoD failed with error code {res}")

    def read_buffer(self, device_ptr: ctypes.c_void_p, size: int) -> bytes:
        """Read from device buffer.

        Args:
            device_ptr (ctypes.c_void_p): Device pointer.
            size (int): Size to read.

        Returns:
            bytes: Read data.
        """
        if not device_ptr:
            return b"\x00" * size

        if self.mode == "cupy" and cupy is not None:
            src = cupy.ndarray((size,), dtype=cupy.uint8, memptr=cupy.cuda.MemoryPointer(cupy.cuda.UnownedMemory(device_ptr.value, size, device_ptr), 0))
            arr = src.get()
            return arr.tobytes()

        if self.cuda_lib:
            host_data = ctypes.create_string_buffer(size)
            res = self.cuda_lib.cuMemcpyDtoH_v2(host_data, device_ptr, size)
            if res != 0:
                raise RuntimeError(f"cuMemcpyDtoH failed with error code {res}")
            return host_data.raw
        return b"\x00" * size

    def free_buffer(self, device_ptr: ctypes.c_void_p) -> None:
        """Free device memory.

        Args:
            device_ptr (ctypes.c_void_p): Device pointer.
        """
        if not device_ptr:
            return

        if self.mode == "cupy":
            # CuPy memory pool handles this usually, but if Unowned, we don't free it this way
            # We'll just pass for CuPy as we'd normally let the allocator manage it.
            pass
        elif self.cuda_lib:
            self.cuda_lib.cuMemFree_v2(device_ptr)

    def compile_and_dispatch(self, ptx_source: str, entry_point: str, grid_size: list[int], block_size: list[int]) -> None:
        """Compile PTX modules and launch kernels.

        Args:
            ptx_source (str): PTX source code.
            entry_point (str): Kernel entry point.
            grid_size (list[int]): Grid sizing.
            block_size (list[int]): Block sizing.
        """
        if self.mode == "cupy" and cupy is not None:
            module = cupy.RawModule(code=ptx_source)
            kernel = module.get_function(entry_point)
            kernel(tuple(grid_size), tuple(block_size), ())
            return

        if self.cuda_lib:
            module = ctypes.c_void_p()
            ptx_bytes = ptx_source.encode("utf-8")
            res = self.cuda_lib.cuModuleLoadData(ctypes.byref(module), ptx_bytes)
            if res != 0:
                raise RuntimeError(f"cuModuleLoadData failed with error code {res}")

            kernel = ctypes.c_void_p()
            res = self.cuda_lib.cuModuleGetFunction(ctypes.byref(kernel), module, entry_point.encode("utf-8"))
            if res != 0:
                raise RuntimeError(f"cuModuleGetFunction failed with error code {res}")

            # Basic cuLaunchKernel with no arguments for stubbing
            res = self.cuda_lib.cuLaunchKernel(kernel, grid_size[0], grid_size[1], grid_size[2], block_size[0], block_size[1], block_size[2], 0, None, None, None)
            if res != 0:
                raise RuntimeError(f"cuLaunchKernel failed with error code {res}")
