"""CUDA backend generator."""

import os
from typing import Any, Optional

import yaml

from ml_switcheroo_compiler.backends.base_generator import BaseGenerator
from ml_switcheroo_compiler.backends.hardware_config_models import HardwareTemplatesConfig
from ml_switcheroo_compiler.backends.registry import register_backend
from ml_switcheroo_compiler.ir.core import IRGraph


@register_backend("cuda")
class CudaCodeGenerator(BaseGenerator):
    """CUDA C++ Code Generator."""

    def __init__(self, graph: IRGraph, delegates: Optional[list[Any]] = None) -> None:
        """Initialize CudaCodeGenerator.

        Args:
            graph (IRGraph): The IR graph to process.
            delegates (list, optional): Visitor delegates.
        """
        super().__init__(graph, delegates)

        yaml_path = os.path.join(os.path.dirname(__file__), "cuda_templates.yaml")
        if os.path.exists(yaml_path):
            with open(yaml_path) as f:
                self.config = HardwareTemplatesConfig(**yaml.safe_load(f))
        else:
            self.config = HardwareTemplatesConfig(templates={})

    def generate(self) -> str:
        """Generate CUDA C++ code.

        Returns:
            str: Generated CUDA strings.
        """
        cuda = ["// CUDA Generated by ml-switcheroo-compiler"]
        for node in getattr(self.graph, "nodes", {}).values():
            op_type = getattr(node, "op_type", "")
            tpl = self.config.templates.get(op_type.lower())
            if tpl:
                cuda.append(tpl.body)
        return "\n".join(cuda)
