"""Auto-generated high-fidelity type stubs for cuda from ml-ecosystem-snapshots."""
# ruff: noqa: E501, UP007, UP045, D100, D101, D102, D103

from collections.abc import Sequence

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    device: str
    ndim: int
    size: int
    def __init__(self, data: object = ..., shape: Sequence[int] | None = ..., dtype: str | None = ...) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: object) -> Tensor: ...
    def __add__(self, other: Tensor | float | int) -> Tensor: ...
    def __sub__(self, other: Tensor | float | int) -> Tensor: ...
    def __mul__(self, other: Tensor | float | int) -> Tensor: ...
    def __truediv__(self, other: Tensor | float | int) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def numpy(self) -> object: ...
    def to(self, device: str) -> Tensor: ...
    def reshape(self, shape: Sequence[int]) -> Tensor: ...
    def transpose(self, axes: Sequence[int] | None = ...) -> Tensor: ...

def ATOMG_ADD_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_ADD_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_ADD_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_ADD_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_ADD_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_ADD_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_AND_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_AND_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_AND_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_AND_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_AND_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_AND_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_CAS_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_CAS_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_CAS_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_CAS_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_CAS_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_CAS_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_DEC_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_DEC_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_DEC_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_DEC_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_DEC_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_DEC_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_EXCH_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_EXCH_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_EXCH_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_EXCH_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_EXCH_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_EXCH_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_INC_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_INC_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_INC_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_INC_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_INC_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_INC_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_MAX_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_MAX_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_MAX_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_MAX_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_MAX_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_MAX_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_MIN_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_MIN_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_MIN_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_MIN_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_MIN_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_MIN_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_OR_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_OR_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_OR_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_OR_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_OR_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_OR_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_XOR_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_XOR_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_XOR_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_XOR_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_XOR_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMG_XOR_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_ADD_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_ADD_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_ADD_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_ADD_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_ADD_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_ADD_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_AND_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_AND_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_AND_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_AND_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_AND_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_AND_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_CAS_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_CAS_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_CAS_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_CAS_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_CAS_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_CAS_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_DEC_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_DEC_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_DEC_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_DEC_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_DEC_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_DEC_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_EXCH_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_EXCH_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_EXCH_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_EXCH_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_EXCH_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_EXCH_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_INC_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_INC_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_INC_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_INC_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_INC_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_INC_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_MAX_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_MAX_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_MAX_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_MAX_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_MAX_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_MAX_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_MIN_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_MIN_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_MIN_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_MIN_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_MIN_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_MIN_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_OR_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_OR_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_OR_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_OR_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_OR_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_OR_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_XOR_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_XOR_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_XOR_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_XOR_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_XOR_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ATOMS_XOR_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def BAR_ARRIVE(op0: Tensor) -> Tensor: ...
def BAR_RED(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def BAR_SYNC(op0: Tensor) -> Tensor: ...
def BAR_WARP(op0: Tensor) -> Tensor: ...
def BMMA(op0: Tensor, op1: Tensor, op2: Tensor, op3: Tensor) -> Tensor: ...
def BMMA16816(op0: Tensor, op1: Tensor, op2: Tensor, op3: Tensor) -> Tensor: ...
def BMOV(op0: Tensor, op1: Tensor) -> Tensor: ...
def BRA(op0: Tensor) -> Tensor: ...
def CVT_BF16_TO_F16(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_BF16_TO_F32(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_BF16_TO_F64(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_BF16_TO_S32(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_BF16_TO_S64(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_BF16_TO_U32(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_BF16_TO_U64(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_F16_TO_BF16(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_F16_TO_F32(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_F16_TO_F64(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_F16_TO_S32(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_F16_TO_S64(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_F16_TO_U32(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_F16_TO_U64(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_F32_TO_BF16(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_F32_TO_F16(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_F32_TO_F64(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_F32_TO_S32(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_F32_TO_S64(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_F32_TO_U32(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_F32_TO_U64(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_F64_TO_BF16(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_F64_TO_F16(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_F64_TO_F32(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_F64_TO_S32(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_F64_TO_S64(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_F64_TO_U32(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_F64_TO_U64(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_S32_TO_BF16(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_S32_TO_F16(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_S32_TO_F32(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_S32_TO_F64(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_S32_TO_S64(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_S32_TO_U32(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_S32_TO_U64(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_S64_TO_BF16(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_S64_TO_F16(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_S64_TO_F32(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_S64_TO_F64(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_S64_TO_S32(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_S64_TO_U32(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_S64_TO_U64(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_U32_TO_BF16(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_U32_TO_F16(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_U32_TO_F32(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_U32_TO_F64(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_U32_TO_S32(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_U32_TO_S64(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_U32_TO_U64(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_U64_TO_BF16(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_U64_TO_F16(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_U64_TO_F32(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_U64_TO_F64(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_U64_TO_S32(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_U64_TO_S64(op0: Tensor, op1: Tensor) -> Tensor: ...
def CVT_U64_TO_U32(op0: Tensor, op1: Tensor) -> Tensor: ...
def DEPBAR(op0: Tensor) -> Tensor: ...
def DEPBAR_EQ(op0: Tensor) -> Tensor: ...
def DEPBAR_LE(op0: Tensor) -> Tensor: ...
def DMMA884(op0: Tensor, op1: Tensor, op2: Tensor, op3: Tensor) -> Tensor: ...
def EXIT(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def FADD(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FADD_BF16_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FADD_BF16_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FADD_BF16_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FADD_BF16_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FADD_BF16x2_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FADD_BF16x2_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FADD_BF16x2_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FADD_BF16x2_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FADD_F16_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FADD_F16_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FADD_F16_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FADD_F16_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FADD_F16x2_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FADD_F16x2_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FADD_F16x2_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FADD_F16x2_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FADD_F32_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FADD_F32_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FADD_F32_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FADD_F32_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FADD_F64_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FADD_F64_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FADD_F64_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FADD_F64_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FCMP_BF16_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FCMP_BF16_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FCMP_BF16_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FCMP_BF16_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FCMP_BF16x2_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FCMP_BF16x2_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FCMP_BF16x2_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FCMP_BF16x2_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FCMP_F16_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FCMP_F16_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FCMP_F16_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FCMP_F16_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FCMP_F16x2_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FCMP_F16x2_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FCMP_F16x2_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FCMP_F16x2_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FCMP_F32_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FCMP_F32_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FCMP_F32_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FCMP_F32_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FCMP_F64_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FCMP_F64_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FCMP_F64_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FCMP_F64_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FFMA(op0: Tensor, op1: Tensor, op2: Tensor, op3: Tensor) -> Tensor: ...
def FFMA_BF16_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FFMA_BF16_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FFMA_BF16_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FFMA_BF16_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FFMA_BF16x2_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FFMA_BF16x2_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FFMA_BF16x2_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FFMA_BF16x2_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FFMA_F16_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FFMA_F16_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FFMA_F16_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FFMA_F16_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FFMA_F16x2_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FFMA_F16x2_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FFMA_F16x2_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FFMA_F16x2_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FFMA_F32_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FFMA_F32_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FFMA_F32_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FFMA_F32_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FFMA_F64_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FFMA_F64_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FFMA_F64_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FFMA_F64_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMNMX_BF16_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMNMX_BF16_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMNMX_BF16_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMNMX_BF16_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMNMX_BF16x2_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMNMX_BF16x2_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMNMX_BF16x2_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMNMX_BF16x2_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMNMX_F16_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMNMX_F16_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMNMX_F16_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMNMX_F16_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMNMX_F16x2_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMNMX_F16x2_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMNMX_F16x2_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMNMX_F16x2_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMNMX_F32_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMNMX_F32_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMNMX_F32_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMNMX_F32_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMNMX_F64_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMNMX_F64_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMNMX_F64_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMNMX_F64_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMUL(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMUL_BF16_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMUL_BF16_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMUL_BF16_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMUL_BF16_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMUL_BF16x2_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMUL_BF16x2_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMUL_BF16x2_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMUL_BF16x2_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMUL_F16_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMUL_F16_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMUL_F16_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMUL_F16_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMUL_F16x2_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMUL_F16x2_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMUL_F16x2_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMUL_F16x2_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMUL_F32_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMUL_F32_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMUL_F32_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMUL_F32_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMUL_F64_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMUL_F64_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMUL_F64_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FMUL_F64_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSEL_BF16_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSEL_BF16_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSEL_BF16_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSEL_BF16_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSEL_BF16x2_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSEL_BF16x2_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSEL_BF16x2_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSEL_BF16x2_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSEL_F16_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSEL_F16_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSEL_F16_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSEL_F16_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSEL_F16x2_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSEL_F16x2_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSEL_F16x2_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSEL_F16x2_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSEL_F32_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSEL_F32_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSEL_F32_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSEL_F32_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSEL_F64_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSEL_F64_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSEL_F64_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSEL_F64_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSETP_BF16_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSETP_BF16_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSETP_BF16_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSETP_BF16_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSETP_BF16x2_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSETP_BF16x2_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSETP_BF16x2_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSETP_BF16x2_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSETP_F16_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSETP_F16_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSETP_F16_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSETP_F16_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSETP_F16x2_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSETP_F16x2_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSETP_F16x2_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSETP_F16x2_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSETP_F32_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSETP_F32_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSETP_F32_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSETP_F32_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSETP_F64_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSETP_F64_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSETP_F64_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSETP_F64_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSET_BF16_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSET_BF16_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSET_BF16_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSET_BF16_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSET_BF16x2_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSET_BF16x2_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSET_BF16x2_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSET_BF16x2_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSET_F16_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSET_F16_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSET_F16_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSET_F16_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSET_F16x2_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSET_F16x2_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSET_F16x2_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSET_F16x2_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSET_F32_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSET_F32_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSET_F32_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSET_F32_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSET_F64_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSET_F64_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSET_F64_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSET_F64_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSUB(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSUB_BF16_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSUB_BF16_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSUB_BF16_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSUB_BF16_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSUB_BF16x2_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSUB_BF16x2_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSUB_BF16x2_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSUB_BF16x2_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSUB_F16_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSUB_F16_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSUB_F16_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSUB_F16_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSUB_F16x2_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSUB_F16x2_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSUB_F16x2_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSUB_F16x2_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSUB_F32_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSUB_F32_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSUB_F32_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSUB_F32_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSUB_F64_RM(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSUB_F64_RN(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSUB_F64_RP(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def FSUB_F64_RZ(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def HMMA(op0: Tensor, op1: Tensor, op2: Tensor, op3: Tensor) -> Tensor: ...
def HMMA16816(op0: Tensor, op1: Tensor, op2: Tensor, op3: Tensor) -> Tensor: ...
def HMMA1688(op0: Tensor, op1: Tensor, op2: Tensor, op3: Tensor) -> Tensor: ...
def HMMA884(op0: Tensor, op1: Tensor, op2: Tensor, op3: Tensor) -> Tensor: ...
def IADD(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def IADD3(op0: Tensor, op1: Tensor, op2: Tensor, op3: Tensor) -> Tensor: ...
def IMAD(op0: Tensor, op1: Tensor, op2: Tensor, op3: Tensor) -> Tensor: ...
def IMMA(op0: Tensor, op1: Tensor, op2: Tensor, op3: Tensor) -> Tensor: ...
def IMMA16816(op0: Tensor, op1: Tensor, op2: Tensor, op3: Tensor) -> Tensor: ...
def IMMA16832(op0: Tensor, op1: Tensor, op2: Tensor, op3: Tensor) -> Tensor: ...
def IMMA8816(op0: Tensor, op1: Tensor, op2: Tensor, op3: Tensor) -> Tensor: ...
def LDC_CG_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_CG_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_CG_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_CG_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_CG_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_CG_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_CG_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_CS_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_CS_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_CS_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_CS_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_CS_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_CS_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_CS_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_CV_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_CV_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_CV_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_CV_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_CV_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_CV_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_CV_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_E_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_E_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_E_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_E_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_E_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_E_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_E_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_LU_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_LU_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_LU_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_LU_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_LU_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_LU_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_LU_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_STRONG_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_STRONG_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_STRONG_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_STRONG_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_STRONG_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_STRONG_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDC_STRONG_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDGSTS(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDGSTS_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDGSTS_BYPASS(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDGSTS_E(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_CG_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_CG_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_CG_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_CG_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_CG_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_CG_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_CG_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_CS_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_CS_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_CS_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_CS_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_CS_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_CS_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_CS_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_CV_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_CV_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_CV_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_CV_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_CV_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_CV_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_CV_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_E_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_E_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_E_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_E_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_E_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_E_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_E_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_LU_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_LU_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_LU_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_LU_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_LU_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_LU_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_LU_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_STRONG_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_STRONG_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_STRONG_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_STRONG_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_STRONG_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_STRONG_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDG_STRONG_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_CG_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_CG_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_CG_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_CG_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_CG_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_CG_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_CG_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_CS_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_CS_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_CS_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_CS_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_CS_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_CS_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_CS_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_CV_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_CV_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_CV_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_CV_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_CV_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_CV_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_CV_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_E_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_E_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_E_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_E_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_E_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_E_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_E_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_LU_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_LU_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_LU_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_LU_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_LU_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_LU_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_LU_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_STRONG_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_STRONG_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_STRONG_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_STRONG_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_STRONG_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_STRONG_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDL_STRONG_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDSM(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDSM_16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDSM_T(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDSM_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDSM_X2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def LDSM_X4(op0: Tensor, op1: Tensor, op2: Tensor, op3: Tensor, op4: Tensor) -> Tensor: ...
def LDS_CG_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_CG_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_CG_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_CG_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_CG_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_CG_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_CG_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_CS_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_CS_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_CS_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_CS_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_CS_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_CS_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_CS_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_CV_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_CV_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_CV_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_CV_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_CV_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_CV_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_CV_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_E_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_E_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_E_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_E_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_E_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_E_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_E_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_LU_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_LU_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_LU_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_LU_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_LU_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_LU_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_LU_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_STRONG_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_STRONG_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_STRONG_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_STRONG_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_STRONG_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_STRONG_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def LDS_STRONG_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def MMA_SCALE_FP4(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def MMA_SCALE_FP6(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def MOV(op0: Tensor, op1: Tensor) -> Tensor: ...
def MXFP8_MMA(op0: Tensor, op1: Tensor, op2: Tensor, op3: Tensor) -> Tensor: ...
def NANOSLEEP(op0: Tensor) -> Tensor: ...
def RED_ADD_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_ADD_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_ADD_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_ADD_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_ADD_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_ADD_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_AND_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_AND_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_AND_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_AND_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_AND_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_AND_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_CAS_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_CAS_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_CAS_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_CAS_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_CAS_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_CAS_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_DEC_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_DEC_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_DEC_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_DEC_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_DEC_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_DEC_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_EXCH_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_EXCH_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_EXCH_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_EXCH_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_EXCH_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_EXCH_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_INC_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_INC_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_INC_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_INC_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_INC_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_INC_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_MAX_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_MAX_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_MAX_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_MAX_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_MAX_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_MAX_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_MIN_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_MIN_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_MIN_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_MIN_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_MIN_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_MIN_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_OR_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_OR_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_OR_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_OR_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_OR_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_OR_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_XOR_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_XOR_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_XOR_BF16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_XOR_F16x2(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_XOR_F32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def RED_XOR_F64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def S2R(op0: Tensor, op1: Tensor) -> Tensor: ...
def S2UR_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def S2UR_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def S2UR_CC(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def S2UR_PRED(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def S2UR_X(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def STG(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_CG_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_CG_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_CG_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_CG_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_CG_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_CG_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_CG_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_CS_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_CS_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_CS_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_CS_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_CS_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_CS_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_CS_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_CV_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_CV_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_CV_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_CV_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_CV_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_CV_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_CV_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_E_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_E_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_E_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_E_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_E_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_E_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_E_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_LU_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_LU_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_LU_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_LU_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_LU_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_LU_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_LU_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_STRONG_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_STRONG_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_STRONG_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_STRONG_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_STRONG_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_STRONG_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STG_STRONG_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_CG_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_CG_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_CG_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_CG_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_CG_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_CG_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_CG_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_CS_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_CS_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_CS_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_CS_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_CS_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_CS_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_CS_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_CV_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_CV_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_CV_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_CV_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_CV_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_CV_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_CV_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_E_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_E_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_E_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_E_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_E_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_E_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_E_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_LU_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_LU_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_LU_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_LU_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_LU_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_LU_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_LU_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_STRONG_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_STRONG_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_STRONG_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_STRONG_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_STRONG_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_STRONG_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STL_STRONG_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_CG_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_CG_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_CG_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_CG_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_CG_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_CG_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_CG_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_CS_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_CS_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_CS_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_CS_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_CS_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_CS_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_CS_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_CV_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_CV_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_CV_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_CV_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_CV_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_CV_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_CV_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_E_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_E_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_E_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_E_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_E_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_E_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_E_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_LU_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_LU_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_LU_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_LU_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_LU_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_LU_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_LU_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_STRONG_128(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_STRONG_32(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_STRONG_64(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_STRONG_S16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_STRONG_S8(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_STRONG_U16(op0: Tensor, op1: Tensor) -> Tensor: ...
def STS_STRONG_U8(op0: Tensor, op1: Tensor) -> Tensor: ...
def TMA(op0: Tensor, op1: Tensor) -> Tensor: ...
def TMA_DESCRIPTOR(op0: Tensor, op1: Tensor) -> Tensor: ...
def TMA_LOAD(op0: Tensor, op1: Tensor) -> Tensor: ...
def TMA_LOAD_ASYNC(op0: Tensor, op1: Tensor) -> Tensor: ...
def TMA_STORE(op0: Tensor, op1: Tensor) -> Tensor: ...
def TMA_STORE_ASYNC(op0: Tensor, op1: Tensor) -> Tensor: ...
def UBFE_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def UBFE_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def UBFE_CC(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def UBFE_PRED(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def UBFE_X(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def UBFI_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def UBFI_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def UBFI_CC(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def UBFI_PRED(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def UBFI_X(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def UIADD3_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def UIADD3_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def UIADD3_CC(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def UIADD3_PRED(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def UIADD3_X(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def UIMAD_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def UIMAD_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def UIMAD_CC(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def UIMAD_PRED(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def UIMAD_X(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ULEA_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ULEA_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ULEA_CC(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ULEA_PRED(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ULEA_X(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ULOP3_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ULOP3_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ULOP3_CC(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ULOP3_PRED(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def ULOP3_X(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def UR2S_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def UR2S_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def UR2S_CC(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def UR2S_PRED(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def UR2S_X(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def USEL_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def USEL_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def USEL_CC(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def USEL_PRED(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def USEL_X(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def USHFL_32(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def USHFL_64(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def USHFL_CC(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def USHFL_PRED(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def USHFL_X(op0: Tensor, op1: Tensor, op2: Tensor) -> Tensor: ...
def WGMMA(op0: Tensor, op1: Tensor, op2: Tensor, op3: Tensor) -> Tensor: ...
def WGMMA_MMA_ASYNC(op0: Tensor, op1: Tensor, op2: Tensor, op3: Tensor) -> Tensor: ...
def WGMMA_MMA_ASYNC_BF16(op0: Tensor, op1: Tensor, op2: Tensor, op3: Tensor) -> Tensor: ...
def WGMMA_MMA_ASYNC_E4M3(op0: Tensor, op1: Tensor, op2: Tensor, op3: Tensor) -> Tensor: ...
def WGMMA_MMA_ASYNC_E5M2(op0: Tensor, op1: Tensor, op2: Tensor, op3: Tensor) -> Tensor: ...
def WGMMA_MMA_ASYNC_F16(op0: Tensor, op1: Tensor, op2: Tensor, op3: Tensor) -> Tensor: ...
def WGMMA_MMA_ASYNC_FP4(op0: Tensor, op1: Tensor, op2: Tensor, op3: Tensor) -> Tensor: ...
def WGMMA_MMA_ASYNC_FP6(op0: Tensor, op1: Tensor, op2: Tensor, op3: Tensor) -> Tensor: ...
def WGMMA_MMA_ASYNC_TF32(op0: Tensor, op1: Tensor, op2: Tensor, op3: Tensor) -> Tensor: ...
def YIELD(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
