operation: arrays_to_spvalues
description: Convert a pytree of (sparse) arrays to an equivalent pytree of spvalues.
std_args:
- spenv
- args
type: function
variants:
  edge_wasm_simd:
    template: unary
    simd_expr: in0_val
    scalar_expr: in0_val
  llvm_cpp:
    template: unary
    scalar_expr: in0_val
