operation: BenchmarkConfig
description: Configuration for benchmarks.
std_args: []
variants:
  numpy:
    eager: numpy.benchmarkconfig
  cupy: {}
  dask: {}
  tensorflow:
    eager: tf.benchmarkconfig
  keras:
    eager: keras_ops.benchmarkconfig
  pytorch:
    eager: torch.benchmarkconfig
  jax:
    eager: jax.numpy.benchmarkconfig
  mlx:
    eager: mlx.core.benchmarkconfig
  edge_onnx:
    generator: BenchmarkConfig
  edge_stablehlo:

    opcode: stablehlo.benchmark_config
  llvm_cpp:
    template: unary
    scalar_expr: in0_val
