operation: producer_result
description: Given an operand, returns the corresponding result in its producer.
std_args:
- operand
type: function
variants:
  edge_wasm_simd:
    template: unary
    simd_expr: in0_val
    scalar_expr: in0_val
  llvm_cpp:
    template: unary
    scalar_expr: in0_val
