[build-system]
requires = ["hatchling", "hatch-requirements-txt"]
build-backend = "hatchling.build"

[project]
name = "ml-switcheroo-compiler"
version = "0.1.0"
description = "Abstract ML Machine Compiler for Reverse-Mode AD, Optimization, and Graph Functionalization."
authors = [{ name = "Samuel Marks" }]
requires-python = ">=3.9"
dynamic = ["dependencies", "optional-dependencies"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.metadata.hooks.requirements_txt]
files = ["requirements.txt"]

[tool.hatch.metadata.hooks.requirements_txt.optional-dependencies]
dev = ["requirements-dev.txt"]
jax = ["requirements-backend-jax.txt"]
torch = ["requirements-backend-torch.txt"]
mlx = ["requirements-backend-mlx.txt"]
keras = ["requirements-backend-keras.txt"]
numpy = ["requirements-backend-numpy.txt"]
cupy = ["requirements-backend-cupy.txt"]

[tool.hatch.build.targets.wheel]
packages = ["src/ml_switcheroo_compiler"]

[tool.ruff]
exclude = ["ml-switcheroo-ir"]
line-length = 300
lint.select = ["E", "F", "D", "ANN", "UP", "B", "I", "C901", "PLR09"]

[tool.ruff.lint.pylint]
max-args = 8
max-branches = 12
max-returns = 6
max-statements = 50

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"fix_*.py" = ["D", "E501", "E701"]
"merge_tests.py" = ["D", "ANN"]
"rename_all_extras.py" = ["D", "ANN", "C901", "PLR09"]
"patch_classmethods.py" = ["D"]
"generate_undercovered.py" = ["D"]
"tests/*" = ["C901", "PLR09", "ANN", "E402", "E701", "D", "E741", "F841", "E712", "B017", "F821", "B018", "E722", "E702", "B007", "E731"]
"scripts/*" = ["C901", "PLR09", "ANN"]
"tests_js/*" = ["C901", "PLR09", "ANN"]

[tool.mypy]
disallow_untyped_defs = true
ignore_missing_imports = true

[tool.coverage.run]
omit = [
    "ml-switcheroo-ir/*",
    "tests/*",
    "tests_js/*",
    "docs/*",
    "scripts/*",
]

[tool.coverage.report]
omit = [
    "ml-switcheroo-ir/*",
    "tests/*",
    "tests_js/*",
    "docs/*",
    "scripts/*",
]
