[build-system]
requires = ["hatchling", "hatch-requirements-txt"]
build-backend = "hatchling.build"

[project]
name = "ml-switcheroo-compiler"
version = "0.1.0"
description = "Abstract ML Machine Compiler for Reverse-Mode AD, Optimization, and Graph Functionalization."
authors = [{ name = "Samuel Marks" }]
requires-python = ">=3.9"
dynamic = ["dependencies", "optional-dependencies"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.metadata.hooks.requirements_txt]
files = ["requirements.txt"]

[tool.hatch.metadata.hooks.requirements_txt.optional-dependencies]
dev = ["requirements-dev.txt"]
jax = ["requirements-backend-jax.txt"]
torch = ["requirements-backend-torch.txt"]
mlx = ["requirements-backend-mlx.txt"]
keras = ["requirements-backend-keras.txt"]
tensorflow = ["requirements-backend-tensorflow.txt"]
numpy = ["requirements-backend-numpy.txt"]
cupy = ["requirements-backend-cupy.txt"]

[tool.hatch.build.targets.wheel]
packages = ["src/ml_switcheroo_compiler"]

[tool.ruff]
line-length = 100
lint.select = ["E", "F", "D", "ANN", "UP", "B"]
lint.ignore = ["E501"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
disallow_untyped_defs = true
ignore_missing_imports = true
[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D", "ANN", "E501"]
