"""Auto-generated high-fidelity type stubs for numpy from ml-framework-snapshots."""
# ruff: noqa: E501

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    def __init__(self, *args: object, **kwargs: object) -> None: ...

def exp(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def maximum(*args: Tensor, out: Tensor, where: Tensor, x1: Tensor, x2: Tensor, **kwargs: Tensor) -> Tensor: ...
def minimum(*args: Tensor, out: Tensor, where: Tensor, x1: Tensor, x2: Tensor, **kwargs: Tensor) -> Tensor: ...
def tanh(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def absolute(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def add(*args: Tensor, out: Tensor, where: Tensor, x1: Tensor, x2: Tensor, **kwargs: Tensor) -> Tensor: ...
def all(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., *, where: Tensor = ...) -> Tensor: ...
def any(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., *, where: Tensor = ...) -> Tensor: ...
def arange(*args: Tensor, start: Tensor, stop: Tensor, step: Tensor, dtype: Tensor, like: Tensor, **kwargs: Tensor) -> Tensor: ...
def argmax(a: Tensor, axis: Tensor = ..., out: Tensor = ..., *, keepdims: Tensor = ...) -> Tensor: ...
def argmin(a: Tensor, axis: Tensor = ..., out: Tensor = ..., *, keepdims: Tensor = ...) -> Tensor: ...
def cholesky(a: Tensor) -> Tensor: ...
def clip(a: Tensor, a_min: Tensor, a_max: Tensor, out: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def concatenate(arrays: Tensor, axis: Tensor = ..., out: Tensor = ..., *, dtype: Tensor = ..., casting: Tensor = ...) -> Tensor: ...
def cond(x: Tensor, p: Tensor = ...) -> Tensor: ...
def cos(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def det(a: Tensor) -> Tensor: ...
def divide(*args: Tensor, x1: Tensor, x2: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def dot(a: Tensor, b: Tensor, out: Tensor = ...) -> Tensor: ...
def eig(a: Tensor) -> Tensor: ...
def eigh(a: Tensor, UPLO: Tensor = ...) -> Tensor: ...
def eigvals(a: Tensor) -> Tensor: ...
def eigvalsh(a: Tensor, UPLO: Tensor = ...) -> Tensor: ...
def empty(shape: Tensor, dtype: Tensor = ..., order: Tensor = ..., *, like: Tensor = ...) -> Tensor: ...
def eye(N: Tensor, M: Tensor = ..., k: Tensor = ..., dtype: Tensor = ..., order: Tensor = ..., *, like: Tensor = ...) -> Tensor: ...
def fft(a: Tensor, n: Tensor = ..., axis: Tensor = ..., norm: Tensor = ...) -> Tensor: ...
def fft2(a: Tensor, s: Tensor = ..., axes: Tensor = ..., norm: Tensor = ...) -> Tensor: ...
def fftfreq(n: Tensor, d: Tensor = ...) -> Tensor: ...
def fftn(a: Tensor, s: Tensor = ..., axes: Tensor = ..., norm: Tensor = ...) -> Tensor: ...
def fftshift(x: Tensor, axes: Tensor = ...) -> Tensor: ...
def full(shape: Tensor, fill_value: Tensor, dtype: Tensor = ..., order: Tensor = ..., *, like: Tensor = ...) -> Tensor: ...
def hfft(a: Tensor, n: Tensor = ..., axis: Tensor = ..., norm: Tensor = ...) -> Tensor: ...
def ifft(a: Tensor, n: Tensor = ..., axis: Tensor = ..., norm: Tensor = ...) -> Tensor: ...
def ifft2(a: Tensor, s: Tensor = ..., axes: Tensor = ..., norm: Tensor = ...) -> Tensor: ...
def ifftn(a: Tensor, s: Tensor = ..., axes: Tensor = ..., norm: Tensor = ...) -> Tensor: ...
def ifftshift(x: Tensor, axes: Tensor = ...) -> Tensor: ...
def ihfft(a: Tensor, n: Tensor = ..., axis: Tensor = ..., norm: Tensor = ...) -> Tensor: ...
def inv(a: Tensor) -> Tensor: ...
def irfft(a: Tensor, n: Tensor = ..., axis: Tensor = ..., norm: Tensor = ...) -> Tensor: ...
def irfft2(a: Tensor, s: Tensor = ..., axes: Tensor = ..., norm: Tensor = ...) -> Tensor: ...
def irfftn(a: Tensor, s: Tensor = ..., axes: Tensor = ..., norm: Tensor = ...) -> Tensor: ...
def linspace(start: Tensor, stop: Tensor, num: Tensor = ..., endpoint: Tensor = ..., retstep: Tensor = ..., dtype: Tensor = ..., axis: Tensor = ...) -> Tensor: ...
def log(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def lstsq(a: Tensor, b: Tensor, rcond: Tensor = ...) -> Tensor: ...
def matmul(*args: Tensor, out: Tensor, x1: Tensor, x2: Tensor, **kwargs: Tensor) -> Tensor: ...
def matrix_power(a: Tensor, n: Tensor) -> Tensor: ...
def matrix_rank(A: Tensor, tol: Tensor = ..., hermitian: Tensor = ...) -> Tensor: ...
def max(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., initial: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def mean(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., *, where: Tensor = ...) -> Tensor: ...
def min(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., initial: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def multi_dot(arrays: Tensor, *, out: Tensor = ...) -> Tensor: ...
def multiply(*args: Tensor, out: Tensor, where: Tensor, x1: Tensor, x2: Tensor, **kwargs: Tensor) -> Tensor: ...
def norm(x: Tensor, ord: Tensor = ..., axis: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def ones(shape: Tensor, dtype: Tensor = ..., order: Tensor = ..., *, like: Tensor = ...) -> Tensor: ...
def pinv(a: Tensor, rcond: Tensor = ..., hermitian: Tensor = ...) -> Tensor: ...
def prod(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., initial: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def qr(a: Tensor, mode: Tensor = ...) -> Tensor: ...
def reshape(a: Tensor, newshape: Tensor, order: Tensor = ...) -> Tensor: ...
def rfft(a: Tensor, n: Tensor = ..., axis: Tensor = ..., norm: Tensor = ...) -> Tensor: ...
def rfft2(a: Tensor, s: Tensor = ..., axes: Tensor = ..., norm: Tensor = ...) -> Tensor: ...
def rfftfreq(n: Tensor, d: Tensor = ...) -> Tensor: ...
def rfftn(a: Tensor, s: Tensor = ..., axes: Tensor = ..., norm: Tensor = ...) -> Tensor: ...
def round(a: Tensor, decimals: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def sin(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def slogdet(a: Tensor) -> Tensor: ...
def solve(a: Tensor, b: Tensor) -> Tensor: ...
def split(ary: Tensor, indices_or_sections: Tensor, axis: Tensor = ...) -> Tensor: ...
def sqrt(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def squeeze(a: Tensor, axis: Tensor = ...) -> Tensor: ...
def stack(arrays: Tensor, axis: Tensor = ..., out: Tensor = ..., *, dtype: Tensor = ..., casting: Tensor = ...) -> Tensor: ...
def subtract(*args: Tensor, out: Tensor, where: Tensor, x1: Tensor, x2: Tensor, **kwargs: Tensor) -> Tensor: ...
def sum(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., initial: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def svd(a: Tensor, full_matrices: Tensor = ..., compute_uv: Tensor = ..., hermitian: Tensor = ...) -> Tensor: ...
def tan(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def tensorinv(a: Tensor, ind: Tensor = ...) -> Tensor: ...
def tensorsolve(a: Tensor, b: Tensor, axes: Tensor = ...) -> Tensor: ...
def test(label: Tensor = ..., verbose: Tensor = ..., extra_argv: Tensor = ..., doctests: Tensor = ..., coverage: Tensor = ..., durations: Tensor = ..., tests: Tensor = ...) -> Tensor: ...
def transpose(a: Tensor, axes: Tensor = ...) -> Tensor: ...
def where(condition: Tensor, x: Tensor = ..., y: Tensor = ...) -> Tensor: ...
def zeros(shape: Tensor, dtype: Tensor = ..., order: Tensor = ..., *, like: Tensor = ...) -> Tensor: ...
