"""Auto-generated high-fidelity type stubs for numpy from live module introspection."""
# ruff: noqa: E501, UP007, UP045, D100, D101, D102, D103

from collections.abc import Sequence

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    device: str
    ndim: int
    size: int
    def __init__(self, data: object = ..., shape: Sequence[int] | None = ..., dtype: str | None = ...) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: object) -> Tensor: ...
    def __add__(self, other: Tensor | float | int) -> Tensor: ...
    def __sub__(self, other: Tensor | float | int) -> Tensor: ...
    def __mul__(self, other: Tensor | float | int) -> Tensor: ...
    def __truediv__(self, other: Tensor | float | int) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def numpy(self) -> object: ...
    def to(self, device: str) -> Tensor: ...
    def reshape(self, shape: Sequence[int]) -> Tensor: ...
    def transpose(self, axes: Sequence[int] | None = ...) -> Tensor: ...

def DataSource(destpath: Tensor = ...) -> Tensor: ...
def RankWarning(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def abs(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def absolute(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def add(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def add_docstring(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def add_newdoc(place: Tensor, obj: Tensor, doc: Tensor, warn_on_python: Tensor = ...) -> Tensor: ...
def add_newdoc_ufunc(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def all(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., *, where: Tensor = ...) -> Tensor: ...
def allclose(a: Tensor, b: Tensor, rtol: Tensor = ..., atol: Tensor = ..., equal_nan: Tensor = ...) -> Tensor: ...
def alltrue(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def amax(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., initial: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def amin(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., initial: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def angle(z: Tensor, deg: Tensor = ...) -> Tensor: ...
def any(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., *, where: Tensor = ...) -> Tensor: ...
def append(arr: Tensor, values: Tensor, axis: Tensor = ...) -> Tensor: ...
def apply_along_axis(func1d: Tensor, axis: Tensor, arr: Tensor, *args: Tensor, **kwargs: Tensor) -> Tensor: ...
def apply_over_axes(func: Tensor, a: Tensor, axes: Tensor) -> Tensor: ...
def arange(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def arccos(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def arccosh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def arcsin(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def arcsinh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def arctan(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def arctan2(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def arctanh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def argmax(a: Tensor, axis: Tensor = ..., out: Tensor = ..., *, keepdims: Tensor = ...) -> Tensor: ...
def argmin(a: Tensor, axis: Tensor = ..., out: Tensor = ..., *, keepdims: Tensor = ...) -> Tensor: ...
def argpartition(a: Tensor, kth: Tensor, axis: Tensor = ..., kind: Tensor = ..., order: Tensor = ...) -> Tensor: ...
def argsort(a: Tensor, axis: Tensor = ..., kind: Tensor = ..., order: Tensor = ...) -> Tensor: ...
def argwhere(a: Tensor) -> Tensor: ...
def around(a: Tensor, decimals: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def array(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def array2string(
    a: Tensor,
    max_line_width: Tensor = ...,
    precision: Tensor = ...,
    suppress_small: Tensor = ...,
    separator: Tensor = ...,
    prefix: Tensor = ...,
    style: Tensor = ...,
    formatter: Tensor = ...,
    threshold: Tensor = ...,
    edgeitems: Tensor = ...,
    sign: Tensor = ...,
    floatmode: Tensor = ...,
    suffix: Tensor = ...,
    *,
    legacy: Tensor = ...,
) -> Tensor: ...
def array_equal(a1: Tensor, a2: Tensor, equal_nan: Tensor = ...) -> Tensor: ...
def array_equiv(a1: Tensor, a2: Tensor) -> Tensor: ...
def array_repr(arr: Tensor, max_line_width: Tensor = ..., precision: Tensor = ..., suppress_small: Tensor = ...) -> Tensor: ...
def array_split(ary: Tensor, indices_or_sections: Tensor, axis: Tensor = ...) -> Tensor: ...
def array_str(a: Tensor, max_line_width: Tensor = ..., precision: Tensor = ..., suppress_small: Tensor = ...) -> Tensor: ...
def asanyarray(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def asarray(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def asarray_chkfinite(a: Tensor, dtype: Tensor = ..., order: Tensor = ...) -> Tensor: ...
def ascontiguousarray(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def asfarray(a: Tensor, dtype: Tensor = ...) -> Tensor: ...
def asfortranarray(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def asmatrix(data: Tensor, dtype: Tensor = ...) -> Tensor: ...
def atleast_1d(*arys: Tensor) -> Tensor: ...
def atleast_2d(*arys: Tensor) -> Tensor: ...
def atleast_3d(*arys: Tensor) -> Tensor: ...
def average(a: Tensor, axis: Tensor = ..., weights: Tensor = ..., returned: Tensor = ..., *, keepdims: Tensor = ...) -> Tensor: ...
def bartlett(M: Tensor) -> Tensor: ...
def base_repr(number: Tensor, base: Tensor = ..., padding: Tensor = ...) -> Tensor: ...
def binary_repr(num: Tensor, width: Tensor = ...) -> Tensor: ...
def bincount(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bitwise_and(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bitwise_not(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bitwise_or(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bitwise_xor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def blackman(M: Tensor) -> Tensor: ...
def block(arrays: Tensor) -> Tensor: ...
def bmat(obj: Tensor, ldict: Tensor = ..., gdict: Tensor = ...) -> Tensor: ...
def bool_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def broadcast(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def broadcast_arrays(*args: Tensor, subok: Tensor = ...) -> Tensor: ...
def broadcast_shapes(*args: Tensor) -> Tensor: ...
def broadcast_to(array: Tensor, shape: Tensor, subok: Tensor = ...) -> Tensor: ...
def busday_count(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def busday_offset(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def busdaycalendar(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def byte(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def byte_bounds(a: Tensor) -> Tensor: ...
def bytes_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def can_cast(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cbrt(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cdouble(real: Tensor = ..., imag: Tensor = ...) -> Tensor: ...
def ceil(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cfloat(real: Tensor = ..., imag: Tensor = ...) -> Tensor: ...
def character() -> Tensor: ...
def chararray(shape: Tensor, itemsize: Tensor = ..., unicode: Tensor = ..., buffer: Tensor = ..., offset: Tensor = ..., strides: Tensor = ..., order: Tensor = ...) -> Tensor: ...
def choose(a: Tensor, choices: Tensor, out: Tensor = ..., mode: Tensor = ...) -> Tensor: ...
def clip(a: Tensor, a_min: Tensor, a_max: Tensor, out: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def clongdouble(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def clongfloat(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def column_stack(tup: Tensor) -> Tensor: ...
def common_type(*arrays: Tensor) -> Tensor: ...
def compare_chararrays(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def complex128(real: Tensor = ..., imag: Tensor = ...) -> Tensor: ...
def complex64(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def complex_(real: Tensor = ..., imag: Tensor = ...) -> Tensor: ...
def complexfloating() -> Tensor: ...
def compress(condition: Tensor, a: Tensor, axis: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def concatenate(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def conj(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def conjugate(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def convolve(a: Tensor, v: Tensor, mode: Tensor = ...) -> Tensor: ...
def copy(a: Tensor, order: Tensor = ..., subok: Tensor = ...) -> Tensor: ...
def copysign(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def copyto(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def corrcoef(x: Tensor, y: Tensor = ..., rowvar: Tensor = ..., bias: Tensor = ..., ddof: Tensor = ..., *, dtype: Tensor = ...) -> Tensor: ...
def correlate(a: Tensor, v: Tensor, mode: Tensor = ...) -> Tensor: ...
def cos(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cosh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def count_nonzero(a: Tensor, axis: Tensor = ..., *, keepdims: Tensor = ...) -> Tensor: ...
def cov(m: Tensor, y: Tensor = ..., rowvar: Tensor = ..., bias: Tensor = ..., ddof: Tensor = ..., fweights: Tensor = ..., aweights: Tensor = ..., *, dtype: Tensor = ...) -> Tensor: ...
def cross(a: Tensor, b: Tensor, axisa: Tensor = ..., axisb: Tensor = ..., axisc: Tensor = ..., axis: Tensor = ...) -> Tensor: ...
def csingle(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cumprod(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def cumproduct(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cumsum(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def datetime64(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def datetime_as_string(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def datetime_data(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def deg2rad(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def degrees(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def delete(arr: Tensor, obj: Tensor, axis: Tensor = ...) -> Tensor: ...
def deprecate(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def deprecate_with_doc(msg: Tensor) -> Tensor: ...
def diag(v: Tensor, k: Tensor = ...) -> Tensor: ...
def diag_indices(n: Tensor, ndim: Tensor = ...) -> Tensor: ...
def diag_indices_from(arr: Tensor) -> Tensor: ...
def diagflat(v: Tensor, k: Tensor = ...) -> Tensor: ...
def diagonal(a: Tensor, offset: Tensor = ..., axis1: Tensor = ..., axis2: Tensor = ...) -> Tensor: ...
def diff(a: Tensor, n: Tensor = ..., axis: Tensor = ..., prepend: Tensor = ..., append: Tensor = ...) -> Tensor: ...
def digitize(x: Tensor, bins: Tensor, right: Tensor = ...) -> Tensor: ...
def disp(mesg: Tensor, device: Tensor = ..., linefeed: Tensor = ...) -> Tensor: ...
def divide(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def divmod(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def dot(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def double(x: Tensor = ...) -> Tensor: ...
def dsplit(ary: Tensor, indices_or_sections: Tensor) -> Tensor: ...
def dstack(tup: Tensor) -> Tensor: ...
def dtype(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ediff1d(ary: Tensor, to_end: Tensor = ..., to_begin: Tensor = ...) -> Tensor: ...
def einsum(*operands: Tensor, out: Tensor = ..., optimize: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def einsum_path(*operands: Tensor, optimize: Tensor = ..., einsum_call: Tensor = ...) -> Tensor: ...
def empty(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def empty_like(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def equal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def errstate(*, call: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def exp(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def exp2(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def expand_dims(a: Tensor, axis: Tensor) -> Tensor: ...
def expm1(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def extract(condition: Tensor, arr: Tensor) -> Tensor: ...
def eye(N: Tensor, M: Tensor = ..., k: Tensor = ..., dtype: Tensor = ..., order: Tensor = ..., *, like: Tensor = ...) -> Tensor: ...
def fabs(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fastCopyAndTranspose(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fill_diagonal(a: Tensor, val: Tensor, wrap: Tensor = ...) -> Tensor: ...
def find_common_type(array_types: Tensor, scalar_types: Tensor) -> Tensor: ...
def finfo(dtype: Tensor) -> Tensor: ...
def fix(x: Tensor, out: Tensor = ...) -> Tensor: ...
def flatiter() -> Tensor: ...
def flatnonzero(a: Tensor) -> Tensor: ...
def flexible() -> Tensor: ...
def flip(m: Tensor, axis: Tensor = ...) -> Tensor: ...
def fliplr(m: Tensor) -> Tensor: ...
def flipud(m: Tensor) -> Tensor: ...
def float16(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def float32(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def float64(x: Tensor = ...) -> Tensor: ...
def float_(x: Tensor = ...) -> Tensor: ...
def float_power(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def floating() -> Tensor: ...
def floor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def floor_divide(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fmax(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fmin(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fmod(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def format_float_positional(x: Tensor, precision: Tensor = ..., unique: Tensor = ..., fractional: Tensor = ..., trim: Tensor = ..., sign: Tensor = ..., pad_left: Tensor = ..., pad_right: Tensor = ..., min_digits: Tensor = ...) -> Tensor: ...
def format_float_scientific(x: Tensor, precision: Tensor = ..., unique: Tensor = ..., trim: Tensor = ..., sign: Tensor = ..., pad_left: Tensor = ..., exp_digits: Tensor = ..., min_digits: Tensor = ...) -> Tensor: ...
def format_parser(formats: Tensor, names: Tensor, titles: Tensor, aligned: Tensor = ..., byteorder: Tensor = ...) -> Tensor: ...
def frexp(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def from_dlpack(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def frombuffer(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fromfile(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fromfunction(function: Tensor, shape: Tensor, *, dtype: Tensor = ..., like: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def fromiter(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def frompyfunc(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fromregex(file: Tensor, regexp: Tensor, dtype: Tensor, encoding: Tensor = ...) -> Tensor: ...
def fromstring(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def full(shape: Tensor, fill_value: Tensor, dtype: Tensor = ..., order: Tensor = ..., *, like: Tensor = ...) -> Tensor: ...
def full_like(a: Tensor, fill_value: Tensor, dtype: Tensor = ..., order: Tensor = ..., subok: Tensor = ..., shape: Tensor = ...) -> Tensor: ...
def gcd(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def generic() -> Tensor: ...
def genfromtxt(
    fname: Tensor,
    dtype: Tensor = ...,
    comments: Tensor = ...,
    delimiter: Tensor = ...,
    skip_header: Tensor = ...,
    skip_footer: Tensor = ...,
    converters: Tensor = ...,
    missing_values: Tensor = ...,
    filling_values: Tensor = ...,
    usecols: Tensor = ...,
    names: Tensor = ...,
    excludelist: Tensor = ...,
    deletechars: Tensor = ...,
    replace_space: Tensor = ...,
    autostrip: Tensor = ...,
    case_sensitive: Tensor = ...,
    defaultfmt: Tensor = ...,
    unpack: Tensor = ...,
    usemask: Tensor = ...,
    loose: Tensor = ...,
    invalid_raise: Tensor = ...,
    max_rows: Tensor = ...,
    encoding: Tensor = ...,
    *,
    ndmin: Tensor = ...,
    like: Tensor = ...,
) -> Tensor: ...
def geomspace(start: Tensor, stop: Tensor, num: Tensor = ..., endpoint: Tensor = ..., dtype: Tensor = ..., axis: Tensor = ...) -> Tensor: ...
def get_array_wrap(*args: Tensor) -> Tensor: ...
def get_include() -> Tensor: ...
def get_printoptions() -> Tensor: ...
def getbufsize() -> Tensor: ...
def geterr() -> Tensor: ...
def geterrcall() -> Tensor: ...
def geterrobj(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def gradient(f: Tensor, *varargs: Tensor, axis: Tensor = ..., edge_order: Tensor = ...) -> Tensor: ...
def greater(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def greater_equal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def half(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def hamming(M: Tensor) -> Tensor: ...
def hanning(M: Tensor) -> Tensor: ...
def heaviside(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def histogram(a: Tensor, bins: Tensor = ..., range: Tensor = ..., density: Tensor = ..., weights: Tensor = ...) -> Tensor: ...
def histogram2d(x: Tensor, y: Tensor, bins: Tensor = ..., range: Tensor = ..., density: Tensor = ..., weights: Tensor = ...) -> Tensor: ...
def histogram_bin_edges(a: Tensor, bins: Tensor = ..., range: Tensor = ..., weights: Tensor = ...) -> Tensor: ...
def histogramdd(sample: Tensor, bins: Tensor = ..., range: Tensor = ..., density: Tensor = ..., weights: Tensor = ...) -> Tensor: ...
def hsplit(ary: Tensor, indices_or_sections: Tensor) -> Tensor: ...
def hstack(tup: Tensor, *, dtype: Tensor = ..., casting: Tensor = ...) -> Tensor: ...
def hypot(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def i0(x: Tensor) -> Tensor: ...
def identity(n: Tensor, dtype: Tensor = ..., *, like: Tensor = ...) -> Tensor: ...
def iinfo(int_type: Tensor) -> Tensor: ...
def imag(val: Tensor) -> Tensor: ...
def in1d(ar1: Tensor, ar2: Tensor, assume_unique: Tensor = ..., invert: Tensor = ..., *, kind: Tensor = ...) -> Tensor: ...
def indices(dimensions: Tensor, dtype: Tensor = ..., sparse: Tensor = ...) -> Tensor: ...
def inexact() -> Tensor: ...
def info(object: Tensor = ..., maxwidth: Tensor = ..., output: Tensor = ..., toplevel: Tensor = ...) -> Tensor: ...
def inner(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def insert(arr: Tensor, obj: Tensor, values: Tensor, axis: Tensor = ...) -> Tensor: ...
def int16(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def int32(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def int64(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def int8(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def int_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def intc(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def integer() -> Tensor: ...
def interp(x: Tensor, xp: Tensor, fp: Tensor, left: Tensor = ..., right: Tensor = ..., period: Tensor = ...) -> Tensor: ...
def intersect1d(ar1: Tensor, ar2: Tensor, assume_unique: Tensor = ..., return_indices: Tensor = ...) -> Tensor: ...
def intp(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def invert(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def is_busday(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def isclose(a: Tensor, b: Tensor, rtol: Tensor = ..., atol: Tensor = ..., equal_nan: Tensor = ...) -> Tensor: ...
def iscomplex(x: Tensor) -> Tensor: ...
def iscomplexobj(x: Tensor) -> Tensor: ...
def isfinite(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def isfortran(a: Tensor) -> Tensor: ...
def isin(element: Tensor, test_elements: Tensor, assume_unique: Tensor = ..., invert: Tensor = ..., *, kind: Tensor = ...) -> Tensor: ...
def isinf(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def isnan(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def isnat(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def isneginf(x: Tensor, out: Tensor = ...) -> Tensor: ...
def isposinf(x: Tensor, out: Tensor = ...) -> Tensor: ...
def isreal(x: Tensor) -> Tensor: ...
def isrealobj(x: Tensor) -> Tensor: ...
def isscalar(element: Tensor) -> Tensor: ...
def issctype(rep: Tensor) -> Tensor: ...
def issubclass_(arg1: Tensor, arg2: Tensor) -> Tensor: ...
def issubdtype(arg1: Tensor, arg2: Tensor) -> Tensor: ...
def issubsctype(arg1: Tensor, arg2: Tensor) -> Tensor: ...
def iterable(y: Tensor) -> Tensor: ...
def ix_(*args: Tensor) -> Tensor: ...
def kaiser(M: Tensor, beta: Tensor) -> Tensor: ...
def kron(a: Tensor, b: Tensor) -> Tensor: ...
def lcm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ldexp(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def left_shift(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def less(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def less_equal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def lexsort(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def linspace(start: Tensor, stop: Tensor, num: Tensor = ..., endpoint: Tensor = ..., retstep: Tensor = ..., dtype: Tensor = ..., axis: Tensor = ...) -> Tensor: ...
def load(file: Tensor, mmap_mode: Tensor = ..., allow_pickle: Tensor = ..., fix_imports: Tensor = ..., encoding: Tensor = ..., *, max_header_size: Tensor = ...) -> Tensor: ...
def loadtxt(
    fname: Tensor, dtype: Tensor = ..., comments: Tensor = ..., delimiter: Tensor = ..., converters: Tensor = ..., skiprows: Tensor = ..., usecols: Tensor = ..., unpack: Tensor = ..., ndmin: Tensor = ..., encoding: Tensor = ..., max_rows: Tensor = ..., *, quotechar: Tensor = ..., like: Tensor = ...
) -> Tensor: ...
def log(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def log10(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def log1p(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def log2(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logaddexp(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logaddexp2(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logical_and(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logical_not(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logical_or(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logical_xor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logspace(start: Tensor, stop: Tensor, num: Tensor = ..., endpoint: Tensor = ..., base: Tensor = ..., dtype: Tensor = ..., axis: Tensor = ...) -> Tensor: ...
def longcomplex(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def longdouble(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def longfloat(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def longlong(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def lookfor(what: Tensor, module: Tensor = ..., import_modules: Tensor = ..., regenerate: Tensor = ..., output: Tensor = ...) -> Tensor: ...
def mask_indices(n: Tensor, mask_func: Tensor, k: Tensor = ...) -> Tensor: ...
def mat(data: Tensor, dtype: Tensor = ...) -> Tensor: ...
def matmul(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def matrix(data: Tensor, dtype: Tensor = ..., copy: Tensor = ...) -> Tensor: ...
def max(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., initial: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def maximum(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def maximum_sctype(t: Tensor) -> Tensor: ...
def may_share_memory(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def mean(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., *, where: Tensor = ...) -> Tensor: ...
def median(a: Tensor, axis: Tensor = ..., out: Tensor = ..., overwrite_input: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def memmap(filename: Tensor, dtype: Tensor = ..., mode: Tensor = ..., offset: Tensor = ..., shape: Tensor = ..., order: Tensor = ...) -> Tensor: ...
def meshgrid(*xi: Tensor, copy: Tensor = ..., sparse: Tensor = ..., indexing: Tensor = ...) -> Tensor: ...
def min(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., initial: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def min_scalar_type(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def minimum(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def mintypecode(typechars: Tensor, typeset: Tensor = ..., default: Tensor = ...) -> Tensor: ...
def mod(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def modf(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def moveaxis(a: Tensor, source: Tensor, destination: Tensor) -> Tensor: ...
def msort(a: Tensor) -> Tensor: ...
def multiply(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def nan_to_num(x: Tensor, copy: Tensor = ..., nan: Tensor = ..., posinf: Tensor = ..., neginf: Tensor = ...) -> Tensor: ...
def nanargmax(a: Tensor, axis: Tensor = ..., out: Tensor = ..., *, keepdims: Tensor = ...) -> Tensor: ...
def nanargmin(a: Tensor, axis: Tensor = ..., out: Tensor = ..., *, keepdims: Tensor = ...) -> Tensor: ...
def nancumprod(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nancumsum(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nanmax(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., initial: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def nanmean(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., *, where: Tensor = ...) -> Tensor: ...
def nanmedian(a: Tensor, axis: Tensor = ..., out: Tensor = ..., overwrite_input: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def nanmin(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., initial: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def nanpercentile(a: Tensor, q: Tensor, axis: Tensor = ..., out: Tensor = ..., overwrite_input: Tensor = ..., method: Tensor = ..., keepdims: Tensor = ..., *, interpolation: Tensor = ...) -> Tensor: ...
def nanprod(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., initial: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def nanquantile(a: Tensor, q: Tensor, axis: Tensor = ..., out: Tensor = ..., overwrite_input: Tensor = ..., method: Tensor = ..., keepdims: Tensor = ..., *, interpolation: Tensor = ...) -> Tensor: ...
def nanstd(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., ddof: Tensor = ..., keepdims: Tensor = ..., *, where: Tensor = ...) -> Tensor: ...
def nansum(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., initial: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def nanvar(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., ddof: Tensor = ..., keepdims: Tensor = ..., *, where: Tensor = ...) -> Tensor: ...
def ndarray(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ndenumerate(arr: Tensor) -> Tensor: ...
def ndim(a: Tensor) -> Tensor: ...
def ndindex(*shape: Tensor) -> Tensor: ...
def nditer(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def negative(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def nested_iters(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def nextafter(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def nonzero(a: Tensor) -> Tensor: ...
def not_equal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def number() -> Tensor: ...
def obj2sctype(rep: Tensor, default: Tensor = ...) -> Tensor: ...
def object_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ones(shape: Tensor, dtype: Tensor = ..., order: Tensor = ..., *, like: Tensor = ...) -> Tensor: ...
def ones_like(a: Tensor, dtype: Tensor = ..., order: Tensor = ..., subok: Tensor = ..., shape: Tensor = ...) -> Tensor: ...
def outer(a: Tensor, b: Tensor, out: Tensor = ...) -> Tensor: ...
def packbits(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def pad(array: Tensor, pad_width: Tensor, mode: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def partition(a: Tensor, kth: Tensor, axis: Tensor = ..., kind: Tensor = ..., order: Tensor = ...) -> Tensor: ...
def percentile(a: Tensor, q: Tensor, axis: Tensor = ..., out: Tensor = ..., overwrite_input: Tensor = ..., method: Tensor = ..., keepdims: Tensor = ..., *, interpolation: Tensor = ...) -> Tensor: ...
def piecewise(x: Tensor, condlist: Tensor, funclist: Tensor, *args: Tensor, **kw: Tensor) -> Tensor: ...
def place(arr: Tensor, mask: Tensor, vals: Tensor) -> Tensor: ...
def poly(seq_of_zeros: Tensor) -> Tensor: ...
def poly1d(c_or_r: Tensor, r: Tensor = ..., variable: Tensor = ...) -> Tensor: ...
def polyadd(a1: Tensor, a2: Tensor) -> Tensor: ...
def polyder(p: Tensor, m: Tensor = ...) -> Tensor: ...
def polydiv(u: Tensor, v: Tensor) -> Tensor: ...
def polyfit(x: Tensor, y: Tensor, deg: Tensor, rcond: Tensor = ..., full: Tensor = ..., w: Tensor = ..., cov: Tensor = ...) -> Tensor: ...
def polyint(p: Tensor, m: Tensor = ..., k: Tensor = ...) -> Tensor: ...
def polymul(a1: Tensor, a2: Tensor) -> Tensor: ...
def polysub(a1: Tensor, a2: Tensor) -> Tensor: ...
def polyval(p: Tensor, x: Tensor) -> Tensor: ...
def positive(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def power(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def printoptions(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def prod(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., initial: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def product(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def promote_types(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ptp(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def put(a: Tensor, ind: Tensor, v: Tensor, mode: Tensor = ...) -> Tensor: ...
def put_along_axis(arr: Tensor, indices: Tensor, values: Tensor, axis: Tensor) -> Tensor: ...
def putmask(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def quantile(a: Tensor, q: Tensor, axis: Tensor = ..., out: Tensor = ..., overwrite_input: Tensor = ..., method: Tensor = ..., keepdims: Tensor = ..., *, interpolation: Tensor = ...) -> Tensor: ...
def rad2deg(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def radians(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ravel(a: Tensor, order: Tensor = ...) -> Tensor: ...
def ravel_multi_index(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def real(val: Tensor) -> Tensor: ...
def real_if_close(a: Tensor, tol: Tensor = ...) -> Tensor: ...
def recarray(shape: Tensor, dtype: Tensor = ..., buf: Tensor = ..., offset: Tensor = ..., strides: Tensor = ..., formats: Tensor = ..., names: Tensor = ..., titles: Tensor = ..., byteorder: Tensor = ..., aligned: Tensor = ..., order: Tensor = ...) -> Tensor: ...
def recfromcsv(fname: Tensor, **kwargs: Tensor) -> Tensor: ...
def recfromtxt(fname: Tensor, **kwargs: Tensor) -> Tensor: ...
def reciprocal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def record(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def remainder(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def repeat(a: Tensor, repeats: Tensor, axis: Tensor = ...) -> Tensor: ...
def require(a: Tensor, dtype: Tensor = ..., requirements: Tensor = ..., *, like: Tensor = ...) -> Tensor: ...
def reshape(a: Tensor, newshape: Tensor, order: Tensor = ...) -> Tensor: ...
def resize(a: Tensor, new_shape: Tensor) -> Tensor: ...
def result_type(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def right_shift(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def rint(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def roll(a: Tensor, shift: Tensor, axis: Tensor = ...) -> Tensor: ...
def rollaxis(a: Tensor, axis: Tensor, start: Tensor = ...) -> Tensor: ...
def roots(p: Tensor) -> Tensor: ...
def rot90(m: Tensor, k: Tensor = ..., axes: Tensor = ...) -> Tensor: ...
def round(a: Tensor, decimals: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def round_(a: Tensor, decimals: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def row_stack(tup: Tensor, *, dtype: Tensor = ..., casting: Tensor = ...) -> Tensor: ...
def safe_eval(source: Tensor) -> Tensor: ...
def save(file: Tensor, arr: Tensor, allow_pickle: Tensor = ..., fix_imports: Tensor = ...) -> Tensor: ...
def savetxt(fname: Tensor, X: Tensor, fmt: Tensor = ..., delimiter: Tensor = ..., newline: Tensor = ..., header: Tensor = ..., footer: Tensor = ..., comments: Tensor = ..., encoding: Tensor = ...) -> Tensor: ...
def savez(file: Tensor, *args: Tensor, **kwds: Tensor) -> Tensor: ...
def savez_compressed(file: Tensor, *args: Tensor, **kwds: Tensor) -> Tensor: ...
def sctype2char(sctype: Tensor) -> Tensor: ...
def searchsorted(a: Tensor, v: Tensor, side: Tensor = ..., sorter: Tensor = ...) -> Tensor: ...
def select(condlist: Tensor, choicelist: Tensor, default: Tensor = ...) -> Tensor: ...
def set_numeric_ops(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def set_printoptions(precision: Tensor = ..., threshold: Tensor = ..., edgeitems: Tensor = ..., linewidth: Tensor = ..., suppress: Tensor = ..., nanstr: Tensor = ..., infstr: Tensor = ..., formatter: Tensor = ..., sign: Tensor = ..., floatmode: Tensor = ..., *, legacy: Tensor = ...) -> Tensor: ...
def set_string_function(f: Tensor, repr: Tensor = ...) -> Tensor: ...
def setbufsize(size: Tensor) -> Tensor: ...
def setdiff1d(ar1: Tensor, ar2: Tensor, assume_unique: Tensor = ...) -> Tensor: ...
def seterr(all: Tensor = ..., divide: Tensor = ..., over: Tensor = ..., under: Tensor = ..., invalid: Tensor = ...) -> Tensor: ...
def seterrcall(func: Tensor) -> Tensor: ...
def seterrobj(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def setxor1d(ar1: Tensor, ar2: Tensor, assume_unique: Tensor = ...) -> Tensor: ...
def shape(a: Tensor) -> Tensor: ...
def shares_memory(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def short(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def show_config(mode: Tensor = ...) -> Tensor: ...
def show_runtime() -> Tensor: ...
def sign(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def signbit(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def signedinteger() -> Tensor: ...
def sin(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sinc(x: Tensor) -> Tensor: ...
def single(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def singlecomplex(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sinh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def size(a: Tensor, axis: Tensor = ...) -> Tensor: ...
def sometrue(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sort(a: Tensor, axis: Tensor = ..., kind: Tensor = ..., order: Tensor = ...) -> Tensor: ...
def sort_complex(a: Tensor) -> Tensor: ...
def source(object: Tensor, output: Tensor = ...) -> Tensor: ...
def spacing(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def split(ary: Tensor, indices_or_sections: Tensor, axis: Tensor = ...) -> Tensor: ...
def sqrt(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def square(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def squeeze(a: Tensor, axis: Tensor = ...) -> Tensor: ...
def stack(arrays: Tensor, axis: Tensor = ..., out: Tensor = ..., *, dtype: Tensor = ..., casting: Tensor = ...) -> Tensor: ...
def std(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., ddof: Tensor = ..., keepdims: Tensor = ..., *, where: Tensor = ...) -> Tensor: ...
def str_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def string_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def subtract(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sum(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: Tensor = ..., initial: Tensor = ..., where: Tensor = ...) -> Tensor: ...
def swapaxes(a: Tensor, axis1: Tensor, axis2: Tensor) -> Tensor: ...
def take(a: Tensor, indices: Tensor, axis: Tensor = ..., out: Tensor = ..., mode: Tensor = ...) -> Tensor: ...
def take_along_axis(arr: Tensor, indices: Tensor, axis: Tensor) -> Tensor: ...
def tan(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def tanh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def tensordot(a: Tensor, b: Tensor, axes: Tensor = ...) -> Tensor: ...
def test(label: Tensor = ..., verbose: Tensor = ..., extra_argv: Tensor = ..., doctests: Tensor = ..., coverage: Tensor = ..., durations: Tensor = ..., tests: Tensor = ...) -> Tensor: ...
def tile(A: Tensor, reps: Tensor) -> Tensor: ...
def timedelta64(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def trace(a: Tensor, offset: Tensor = ..., axis1: Tensor = ..., axis2: Tensor = ..., dtype: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def transpose(a: Tensor, axes: Tensor = ...) -> Tensor: ...
def trapz(y: Tensor, x: Tensor = ..., dx: Tensor = ..., axis: Tensor = ...) -> Tensor: ...
def tri(N: Tensor, M: Tensor = ..., k: Tensor = ..., dtype: Tensor = ..., *, like: Tensor = ...) -> Tensor: ...
def tril(m: Tensor, k: Tensor = ...) -> Tensor: ...
def tril_indices(n: Tensor, k: Tensor = ..., m: Tensor = ...) -> Tensor: ...
def tril_indices_from(arr: Tensor, k: Tensor = ...) -> Tensor: ...
def trim_zeros(filt: Tensor, trim: Tensor = ...) -> Tensor: ...
def triu(m: Tensor, k: Tensor = ...) -> Tensor: ...
def triu_indices(n: Tensor, k: Tensor = ..., m: Tensor = ...) -> Tensor: ...
def triu_indices_from(arr: Tensor, k: Tensor = ...) -> Tensor: ...
def true_divide(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def trunc(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def typename(char: Tensor) -> Tensor: ...
def ubyte(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ufunc() -> Tensor: ...
def uint(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def uint16(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def uint32(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def uint64(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def uint8(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def uintc(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def uintp(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ulonglong(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def unicode_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def union1d(ar1: Tensor, ar2: Tensor) -> Tensor: ...
def unique(ar: Tensor, return_index: Tensor = ..., return_inverse: Tensor = ..., return_counts: Tensor = ..., axis: Tensor = ..., *, equal_nan: Tensor = ...) -> Tensor: ...
def unpackbits(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def unravel_index(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def unsignedinteger() -> Tensor: ...
def unwrap(p: Tensor, discont: Tensor = ..., axis: Tensor = ..., *, period: Tensor = ...) -> Tensor: ...
def ushort(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def vander(x: Tensor, N: Tensor = ..., increasing: Tensor = ...) -> Tensor: ...
def var(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., ddof: Tensor = ..., keepdims: Tensor = ..., *, where: Tensor = ...) -> Tensor: ...
def vdot(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def vectorize(pyfunc: Tensor = ..., otypes: Tensor = ..., doc: Tensor = ..., excluded: Tensor = ..., cache: Tensor = ..., signature: Tensor = ...) -> Tensor: ...
def void(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def vsplit(ary: Tensor, indices_or_sections: Tensor) -> Tensor: ...
def vstack(tup: Tensor, *, dtype: Tensor = ..., casting: Tensor = ...) -> Tensor: ...
def where(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def who(vardict: Tensor = ...) -> Tensor: ...
def zeros(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def zeros_like(a: Tensor, dtype: Tensor = ..., order: Tensor = ..., subok: Tensor = ..., shape: Tensor = ...) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
