"""Auto-generated type stubs from snapshot."""

from typing import Any

def exp(*args: Any, **kwargs: Any) -> Any: ...
def maximum(*args: Any, **kwargs: Any) -> Any: ...
def minimum(*args: Any, **kwargs: Any) -> Any: ...
def tanh(*args: Any, **kwargs: Any) -> Any: ...
