"""Auto-generated type stubs from snapshot."""

class Tensor: ...

def exp(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def maximum(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def minimum(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def tanh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
