"""Auto-generated high-fidelity type stubs for numba from ml-framework-snapshots."""
# ruff: noqa: E501, UP007, UP045, D100, D101, D102, D103

from collections.abc import Sequence

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    device: str
    ndim: int
    size: int
    def __init__(self, data: object = ..., shape: Sequence[int] | None = ..., dtype: str | None = ...) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: object) -> Tensor: ...
    def __add__(self, other: Tensor | float | int) -> Tensor: ...
    def __sub__(self, other: Tensor | float | int) -> Tensor: ...
    def __mul__(self, other: Tensor | float | int) -> Tensor: ...
    def __truediv__(self, other: Tensor | float | int) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def numpy(self) -> object: ...
    def to(self, device: str) -> Tensor: ...
    def reshape(self, shape: Sequence[int]) -> Tensor: ...
    def transpose(self, axes: Sequence[int] | None = ...) -> Tensor: ...

def cfunc(sig: Tensor, locals: Tensor = ..., cache: bool = ..., pipeline_class: Tensor = ..., **options: Tensor) -> Tensor: ...
def from_dtype(dtype: Tensor) -> Tensor: ...
def guvectorize(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def jit(signature_or_function: Tensor = ..., locals: Tensor = ..., cache: bool = ..., pipeline_class: Tensor = ..., boundscheck: Tensor = ..., **options: Tensor) -> Tensor: ...
def njit(*args: Tensor, **kws: Tensor) -> Tensor: ...
def stencil(func_or_mode: str = ..., **options: Tensor) -> Tensor: ...
def typeof(val: Tensor, purpose: Tensor = ...) -> Tensor: ...
def vectorize(ftylist_or_function: Tensor = ..., **kws: Tensor) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
