"""Auto-generated high-fidelity type stubs for numba from ml-framework-snapshots."""
# ruff: noqa: E501

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    def __init__(self, *args: object, **kwargs: object) -> None: ...

def cfunc(sig: Tensor, locals: dict = ..., cache: bool = ..., pipeline_class: Tensor = ..., **options: Tensor) -> Tensor: ...
def from_dtype(dtype: Tensor) -> Tensor: ...
def guvectorize(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def jit(signature_or_function: Tensor = ..., locals: dict = ..., cache: bool = ..., pipeline_class: Tensor = ..., boundscheck: Tensor = ..., **options: Tensor) -> Tensor: ...
def njit(*args: Tensor, **kws: Tensor) -> Tensor: ...
def stencil(func_or_mode: str = ..., **options: Tensor) -> Tensor: ...
def typeof(val: Tensor, purpose: Tensor = ...) -> Tensor: ...
def vectorize(ftylist_or_function: tuple = ..., **kws: Tensor) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
