"""Auto-generated high-fidelity type stubs for numba from live module introspection."""
# ruff: noqa: E501, UP007, UP045, D100, D101, D102, D103

from collections.abc import Sequence

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    device: str
    ndim: int
    size: int
    def __init__(self, data: object = ..., shape: Sequence[int] | None = ..., dtype: str | None = ...) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: object) -> Tensor: ...
    def __add__(self, other: Tensor | float | int) -> Tensor: ...
    def __sub__(self, other: Tensor | float | int) -> Tensor: ...
    def __mul__(self, other: Tensor | float | int) -> Tensor: ...
    def __truediv__(self, other: Tensor | float | int) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def numpy(self) -> object: ...
    def to(self, device: str) -> Tensor: ...
    def reshape(self, shape: Sequence[int]) -> Tensor: ...
    def transpose(self, axes: Sequence[int] | None = ...) -> Tensor: ...

def ByteCodeSupportError(msg: Tensor, loc: Tensor = ...) -> Tensor: ...
def CompilerError(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def ConstantInferenceError(value: Tensor, loc: Tensor = ...) -> Tensor: ...
def DeprecationError(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def ForbiddenConstruct(msg: Tensor, loc: Tensor = ...) -> Tensor: ...
def ForceLiteralArg(arg_indices: Tensor, fold_arguments: Tensor = ..., loc: Tensor = ...) -> Tensor: ...
def IRError(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def InternalError(exception: Tensor) -> Tensor: ...
def InternalTargetMismatchError(kind: Tensor, target_hw: Tensor, hw_clazz: Tensor) -> Tensor: ...
def LiteralTypingError(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def LoweringError(msg: Tensor, loc: Tensor = ...) -> Tensor: ...
def NonexistentTargetError(exception: Tensor) -> Tensor: ...
def NotDefinedError(name: Tensor, loc: Tensor = ...) -> Tensor: ...
def NumbaAssertionError(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def NumbaAttributeError(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def NumbaDebugInfoWarning(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def NumbaDeprecationWarning(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def NumbaError(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def NumbaExperimentalFeatureWarning(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def NumbaIRAssumptionWarning(msg: Tensor, **kwargs: Tensor) -> Tensor: ...
def NumbaIndexError(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def NumbaInvalidConfigWarning(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def NumbaKeyError(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def NumbaNotImplementedError(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def NumbaParallelSafetyWarning(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def NumbaPedanticWarning(msg: Tensor, **kwargs: Tensor) -> Tensor: ...
def NumbaPendingDeprecationWarning(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def NumbaPerformanceWarning(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def NumbaRuntimeError(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def NumbaSystemWarning(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def NumbaTypeError(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def NumbaTypeSafetyWarning(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def NumbaValueError(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def NumbaWarning(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def RedefinedError(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def RequireLiteralValue(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def TypingError(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def UnsupportedError(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def UnsupportedParforsError(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def UnsupportedRewriteError(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def UntypedAttributeError(value: Tensor, attr: Tensor, loc: Tensor = ...) -> Tensor: ...
def VerificationError(msg: Tensor, loc: Tensor = ..., highlighting: Tensor = ...) -> Tensor: ...
def b1(*args: Tensor) -> Tensor: ...
def bool_(*args: Tensor) -> Tensor: ...
def boolean(*args: Tensor) -> Tensor: ...
def byte(*args: Tensor) -> Tensor: ...
def c16(*args: Tensor) -> Tensor: ...
def c8(*args: Tensor) -> Tensor: ...
def carray(ptr: Tensor, shape: Tensor, dtype: Tensor = ...) -> Tensor: ...
def cfunc(sig: Tensor, locals: Tensor = ..., cache: Tensor = ..., pipeline_class: Tensor = ..., **options: Tensor) -> Tensor: ...
def char(*args: Tensor) -> Tensor: ...
def complex128(*args: Tensor) -> Tensor: ...
def complex64(*args: Tensor) -> Tensor: ...
def deferred_type(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def double(*args: Tensor) -> Tensor: ...
def f4(*args: Tensor) -> Tensor: ...
def f8(*args: Tensor) -> Tensor: ...
def farray(ptr: Tensor, shape: Tensor, dtype: Tensor = ...) -> Tensor: ...
def ffi(*args: Tensor) -> Tensor: ...
def ffi_forced_object(*args: Tensor) -> Tensor: ...
def float32(*args: Tensor) -> Tensor: ...
def float64(*args: Tensor) -> Tensor: ...
def float_(*args: Tensor) -> Tensor: ...
def from_dtype(dtype: Tensor) -> Tensor: ...
def gdb(*args: Tensor) -> Tensor: ...
def gdb_breakpoint() -> Tensor: ...
def gdb_init(*args: Tensor) -> Tensor: ...
def get_num_threads() -> Tensor: ...
def get_parallel_chunksize() -> Tensor: ...
def get_thread_id() -> Tensor: ...
def guvectorize(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def i1(*args: Tensor) -> Tensor: ...
def i2(*args: Tensor) -> Tensor: ...
def i4(*args: Tensor) -> Tensor: ...
def i8(*args: Tensor) -> Tensor: ...
def int16(*args: Tensor) -> Tensor: ...
def int32(*args: Tensor) -> Tensor: ...
def int64(*args: Tensor) -> Tensor: ...
def int8(*args: Tensor) -> Tensor: ...
def int_(*args: Tensor) -> Tensor: ...
def intc(*args: Tensor) -> Tensor: ...
def intp(*args: Tensor) -> Tensor: ...
def jit(signature_or_function: Tensor = ..., locals: Tensor = ..., cache: Tensor = ..., pipeline_class: Tensor = ..., boundscheck: Tensor = ..., **options: Tensor) -> Tensor: ...
def jit_module(**kwargs: Tensor) -> Tensor: ...
def literal_unroll(container: Tensor) -> Tensor: ...
def literally(obj: Tensor) -> Tensor: ...
def long_(*args: Tensor) -> Tensor: ...
def longlong(*args: Tensor) -> Tensor: ...
def njit(*args: Tensor, **kws: Tensor) -> Tensor: ...
def none(*args: Tensor) -> Tensor: ...
def objmode(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def optional(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def parallel_chunksize(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def pndindex(*args: Tensor) -> Tensor: ...
def prange(*args: Tensor) -> Tensor: ...
def set_num_threads(n: Tensor) -> Tensor: ...
def set_parallel_chunksize(n: Tensor) -> Tensor: ...
def short(*args: Tensor) -> Tensor: ...
def size_t(*args: Tensor) -> Tensor: ...
def ssize_t(*args: Tensor) -> Tensor: ...
def stencil(func_or_mode: Tensor = ..., **options: Tensor) -> Tensor: ...
def test(argv: Tensor, **kwds: Tensor) -> Tensor: ...
def threading_layer() -> Tensor: ...
def typeof(val: Tensor, purpose: Tensor = ...) -> Tensor: ...
def u1(*args: Tensor) -> Tensor: ...
def u2(*args: Tensor) -> Tensor: ...
def u4(*args: Tensor) -> Tensor: ...
def u8(*args: Tensor) -> Tensor: ...
def uchar(*args: Tensor) -> Tensor: ...
def uint(*args: Tensor) -> Tensor: ...
def uint16(*args: Tensor) -> Tensor: ...
def uint32(*args: Tensor) -> Tensor: ...
def uint64(*args: Tensor) -> Tensor: ...
def uint8(*args: Tensor) -> Tensor: ...
def uintc(*args: Tensor) -> Tensor: ...
def uintp(*args: Tensor) -> Tensor: ...
def ulong(*args: Tensor) -> Tensor: ...
def ulonglong(*args: Tensor) -> Tensor: ...
def ushort(*args: Tensor) -> Tensor: ...
def vectorize(ftylist_or_function: Tensor = ..., **kws: Tensor) -> Tensor: ...
def void(*args: Tensor) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
