"""Auto-generated high-fidelity type stubs for pytorch from live module introspection."""
# ruff: noqa: E501, UP007, UP045, D100, D101, D102, D103

from collections.abc import Sequence

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    device: str
    ndim: int
    size: int
    def __init__(self, data: object = ..., shape: Sequence[int] | None = ..., dtype: str | None = ...) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: object) -> Tensor: ...
    def __add__(self, other: Tensor | float | int) -> Tensor: ...
    def __sub__(self, other: Tensor | float | int) -> Tensor: ...
    def __mul__(self, other: Tensor | float | int) -> Tensor: ...
    def __truediv__(self, other: Tensor | float | int) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def numpy(self) -> object: ...
    def to(self, device: str) -> Tensor: ...
    def reshape(self, shape: Sequence[int]) -> Tensor: ...
    def transpose(self, axes: Sequence[int] | None = ...) -> Tensor: ...

def AcceleratorError(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def AggregationType(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def AliasDb(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def AnyType(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def Argument(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ArgumentSpec(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def AwaitType(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def BFloat16Storage(*args: Tensor, wrap_storage: Tensor = ..., dtype: Tensor = ..., device: Tensor = ..., _internal: Tensor = ...) -> Tensor: ...
def BFloat16Tensor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def BenchmarkConfig(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def BenchmarkExecutionStats(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def Block(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def BoolStorage(*args: Tensor, wrap_storage: Tensor = ..., dtype: Tensor = ..., device: Tensor = ..., _internal: Tensor = ...) -> Tensor: ...
def BoolTensor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def BoolType(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def BufferDict(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ByteStorage(*args: Tensor, wrap_storage: Tensor = ..., dtype: Tensor = ..., device: Tensor = ..., _internal: Tensor = ...) -> Tensor: ...
def ByteTensor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def CallStack(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def Capsule(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def CharStorage(*args: Tensor, wrap_storage: Tensor = ..., dtype: Tensor = ..., device: Tensor = ..., _internal: Tensor = ...) -> Tensor: ...
def CharTensor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ClassType(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def Code(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def CompilationUnit(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def CompleteArgumentSpec(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ComplexDoubleStorage(*args: Tensor, wrap_storage: Tensor = ..., dtype: Tensor = ..., device: Tensor = ..., _internal: Tensor = ...) -> Tensor: ...
def ComplexFloatStorage(*args: Tensor, wrap_storage: Tensor = ..., dtype: Tensor = ..., device: Tensor = ..., _internal: Tensor = ...) -> Tensor: ...
def ComplexType(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ConcreteModuleType(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ConcreteModuleTypeBuilder(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def DeepCopyMemoTable(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def DeserializationStorageContext(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def DeviceObjType(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def DictType(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def DisableTorchFunction(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def DisableTorchFunctionSubclass(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def DispatchKey(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def DispatchKeySet(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def DoubleStorage(*args: Tensor, wrap_storage: Tensor = ..., dtype: Tensor = ..., device: Tensor = ..., _internal: Tensor = ...) -> Tensor: ...
def DoubleTensor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def EnumType(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ErrorReport(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def Event(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ExcludeDispatchKeyGuard(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ExecutionPlan(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def FatalError(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def FileCheck(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def FloatStorage(*args: Tensor, wrap_storage: Tensor = ..., dtype: Tensor = ..., device: Tensor = ..., _internal: Tensor = ...) -> Tensor: ...
def FloatTensor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def FloatType(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def FunctionSchema(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def Future(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def FutureType(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def Generator(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def GradScaler(device: Tensor = ..., init_scale: Tensor = ..., growth_factor: Tensor = ..., backoff_factor: Tensor = ..., growth_interval: Tensor = ..., enabled: Tensor = ...) -> Tensor: ...
def Gradient(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def Graph(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def GraphExecutorState(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def HalfStorage(*args: Tensor, wrap_storage: Tensor = ..., dtype: Tensor = ..., device: Tensor = ..., _internal: Tensor = ...) -> Tensor: ...
def HalfTensor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def IODescriptor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def InferredType(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def IntStorage(*args: Tensor, wrap_storage: Tensor = ..., dtype: Tensor = ..., device: Tensor = ..., _internal: Tensor = ...) -> Tensor: ...
def IntTensor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def IntType(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def InterfaceType(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def JITException(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ListType(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def LiteScriptModule(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def LockingLogger(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def LoggerBase(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def LongStorage(*args: Tensor, wrap_storage: Tensor = ..., dtype: Tensor = ..., device: Tensor = ..., _internal: Tensor = ...) -> Tensor: ...
def LongTensor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ModuleDict(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def Node(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def NoneType(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def NoopLogger(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def NumberType(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def OperatorInfo(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def OptionalType(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def OutOfMemoryError(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ParameterDict(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def PyObjectType(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def PyTorchFileReader(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def PyTorchFileWriter(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def QInt32Storage(*args: Tensor, wrap_storage: Tensor = ..., dtype: Tensor = ..., device: Tensor = ..., _internal: Tensor = ...) -> Tensor: ...
def QInt8Storage(*args: Tensor, wrap_storage: Tensor = ..., dtype: Tensor = ..., device: Tensor = ..., _internal: Tensor = ...) -> Tensor: ...
def QUInt2x4Storage(*args: Tensor, wrap_storage: Tensor = ..., dtype: Tensor = ..., device: Tensor = ..., _internal: Tensor = ...) -> Tensor: ...
def QUInt4x2Storage(*args: Tensor, wrap_storage: Tensor = ..., dtype: Tensor = ..., device: Tensor = ..., _internal: Tensor = ...) -> Tensor: ...
def QUInt8Storage(*args: Tensor, wrap_storage: Tensor = ..., dtype: Tensor = ..., device: Tensor = ..., _internal: Tensor = ...) -> Tensor: ...
def RRefType(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ScriptClass(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ScriptClassFunction(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ScriptDict(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ScriptDictIterator(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ScriptDictKeyIterator(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ScriptFunction(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ScriptList(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ScriptListIterator(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ScriptMethod(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ScriptModule(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ScriptModuleSerializer(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ScriptObject(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ScriptObjectProperty(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def SerializationStorageContext(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ShortStorage(*args: Tensor, wrap_storage: Tensor = ..., dtype: Tensor = ..., device: Tensor = ..., _internal: Tensor = ...) -> Tensor: ...
def ShortTensor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def Size(iterable: Tensor = ...) -> Tensor: ...
def StaticModule(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def Storage(*args: Tensor, wrap_storage: Tensor = ..., dtype: Tensor = ..., device: Tensor = ..., _internal: Tensor = ...) -> Tensor: ...
def StorageBase(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def Stream(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def StreamObjType(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def StringType(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def SymBool(node: Tensor) -> Tensor: ...
def SymBoolType(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def SymFloat(node: Tensor) -> Tensor: ...
def SymInt(node: Tensor) -> Tensor: ...
def SymIntType(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def Tag(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def TensorType(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ThroughputBenchmark(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def TracingState(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def TupleType(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def Type(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def TypedStorage(*args: Tensor, wrap_storage: Tensor = ..., dtype: Tensor = ..., device: Tensor = ..., _internal: Tensor = ...) -> Tensor: ...
def UnionType(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def UntypedStorage(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def Use(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def Value(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def abs(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def abs_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def absolute(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def acos(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def acos_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def acosh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def acosh_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def adaptive_avg_pool1d(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def adaptive_max_pool1d(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def add(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def addbmm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def addcdiv(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def addcmul(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def addmm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def addmv(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def addmv_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def addr(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def adjoint(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def affine_grid_generator(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def alias_copy(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def align_tensors(*tensors: Tensor) -> Tensor: ...
def all(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def allclose(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def alpha_dropout(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def alpha_dropout_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def amax(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def amin(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def aminmax(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def angle(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def any(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def arange(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def arccos(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def arccos_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def arccosh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def arccosh_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def arcsin(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def arcsin_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def arcsinh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def arcsinh_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def arctan(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def arctan2(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def arctan_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def arctanh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def arctanh_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def are_deterministic_algorithms_enabled() -> Tensor: ...
def argmax(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def argmin(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def argsort(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def argwhere(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def as_strided(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def as_strided_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def as_strided_copy(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def as_strided_scatter(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def as_tensor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def asarray(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def asin(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def asin_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def asinh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def asinh_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def atan(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def atan2(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def atan_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def atanh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def atanh_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def atleast_1d(*tensors: Tensor) -> Tensor: ...
def atleast_2d(*tensors: Tensor) -> Tensor: ...
def atleast_3d(*tensors: Tensor) -> Tensor: ...
def autocast(device_type: Tensor, dtype: Tensor = ..., enabled: Tensor = ..., cache_enabled: Tensor = ...) -> Tensor: ...
def autocast_decrement_nesting(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def autocast_increment_nesting(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def avg_pool1d(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def baddbmm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bartlett_window(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def batch_norm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def batch_norm_backward_elemt(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def batch_norm_backward_reduce(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def batch_norm_elemt(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def batch_norm_gather_stats(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def batch_norm_gather_stats_with_counts(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def batch_norm_stats(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def batch_norm_update_stats(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bernoulli(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bilinear(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def binary_cross_entropy_with_logits(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bincount(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def binomial(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bitwise_and(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bitwise_left_shift(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bitwise_not(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bitwise_or(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bitwise_right_shift(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bitwise_xor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def blackman_window(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def block_diag(*tensors: Tensor) -> Tensor: ...
def bmm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def broadcast_shapes(*shapes: Tensor) -> Tensor: ...
def broadcast_tensors(*tensors: Tensor) -> Tensor: ...
def broadcast_to(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bucketize(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def can_cast(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cartesian_prod(*tensors: Tensor) -> Tensor: ...
def cat(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ccol_indices_copy(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cdist(x1: Tensor, x2: Tensor, p: Tensor = ..., compute_mode: Tensor = ...) -> Tensor: ...
def ceil(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ceil_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def celu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def celu_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def chain_matmul(*matrices: Tensor, out: Tensor = ...) -> Tensor: ...
def channel_shuffle(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cholesky(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cholesky_inverse(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cholesky_solve(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def choose_qparams_optimized(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def chunk(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def clamp(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def clamp_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def clamp_max(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def clamp_max_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def clamp_min(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def clamp_min_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def classproperty(func: Tensor) -> Tensor: ...
def clear_autocast_cache(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def clip(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def clip_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def clone(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def col_indices_copy(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def column_stack(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def combinations(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def compile(model: Tensor = ..., *, fullgraph: Tensor = ..., dynamic: Tensor = ..., backend: Tensor = ..., mode: Tensor = ..., options: Tensor = ..., disable: Tensor = ...) -> Tensor: ...
def compiled_with_cxx11_abi() -> Tensor: ...
def complex(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def concat(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def concatenate(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cond(pred: Tensor, true_fn: Tensor, false_fn: Tensor, operands: Tensor = ...) -> Tensor: ...
def conj(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def conj_physical(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def conj_physical_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def constant_pad_nd(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def conv1d(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def conv2d(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def conv3d(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def conv_tbc(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def conv_transpose1d(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def conv_transpose2d(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def conv_transpose3d(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def convolution(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def copysign(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def corrcoef(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cos(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cos_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cosh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cosh_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cosine_embedding_loss(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cosine_similarity(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def count_nonzero(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cov(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cross(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def crow_indices_copy(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ctc_loss(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cudnn_affine_grid_generator(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cudnn_batch_norm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cudnn_convolution(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cudnn_convolution_add_relu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cudnn_convolution_relu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cudnn_convolution_transpose(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cudnn_grid_sampler(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cudnn_is_acceptable(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cummax(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cummin(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cumprod(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cumsum(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cumulative_trapezoid(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def deg2rad(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def deg2rad_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def dequantize(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def det(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def detach(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def detach_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def detach_copy(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def device(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def diag(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def diag_embed(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def diagflat(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def diagonal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def diagonal_copy(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def diagonal_scatter(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def diff(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def digamma(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def dist(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def div(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def divide(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def dot(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def dropout(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def dropout_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def dsmm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def dsplit(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def dstack(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def dtype() -> Tensor: ...
def eig(self: Tensor, eigenvectors: Tensor = ..., *, e: Tensor = ..., v: Tensor = ...) -> Tensor: ...
def einsum(*args: Tensor) -> Tensor: ...
def embedding(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def embedding_bag(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def embedding_renorm_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def empty(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def empty_like(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def empty_permuted(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def empty_quantized(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def empty_strided(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def enable_grad(orig_func: Tensor = ...) -> Tensor: ...
def eq(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def equal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def erf(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def erf_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def erfc(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def erfc_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def erfinv(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def exp(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def exp2(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def exp2_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def exp_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def expand_copy(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def expm1(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def expm1_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def eye(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fake_quantize_per_channel_affine(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fake_quantize_per_tensor_affine(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fbgemm_linear_fp16_weight(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fbgemm_linear_fp16_weight_fp32_activation(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fbgemm_linear_int8_weight(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fbgemm_linear_int8_weight_fp32_activation(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fbgemm_linear_quantize_weight(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fbgemm_pack_gemm_matrix_fp16(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fbgemm_pack_quantized_matrix(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def feature_alpha_dropout(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def feature_alpha_dropout_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def feature_dropout(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def feature_dropout_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fill(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fill_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def finfo(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fix(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fix_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def flatten(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def flip(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fliplr(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def flipud(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def float_power(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def floor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def floor_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def floor_divide(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fmax(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fmin(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fmod(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fork(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def frac(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def frac_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def frexp(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def frobenius_norm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def from_dlpack(ext_tensor: Tensor) -> Tensor: ...
def from_file(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def from_numpy(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def frombuffer(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def full(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def full_like(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fused_moving_avg_obs_fake_quant(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def gather(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def gcd(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def gcd_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ge(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def geqrf(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ger(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def get_autocast_cpu_dtype(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def get_autocast_dtype(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def get_autocast_gpu_dtype(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def get_autocast_ipu_dtype(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def get_autocast_xla_dtype(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def get_default_device() -> Tensor: ...
def get_default_dtype(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def get_deterministic_debug_mode() -> Tensor: ...
def get_device(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def get_device_module(device: Tensor = ...) -> Tensor: ...
def get_file_path(*path_components: Tensor) -> Tensor: ...
def get_float32_matmul_precision() -> Tensor: ...
def get_num_interop_threads(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def get_num_threads(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def get_rng_state() -> Tensor: ...
def gradient(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def greater(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def greater_equal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def grid_sampler(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def grid_sampler_2d(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def grid_sampler_3d(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def group_norm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def gru(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def gru_cell(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def gt(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def hamming_window(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def hann_window(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def hardshrink(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def heaviside(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def hinge_embedding_loss(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def histc(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def histogram(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def histogramdd(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def hsmm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def hsplit(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def hspmm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def hstack(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def hypot(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def i0(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def i0_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def igamma(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def igammac(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def iinfo(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def imag(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def import_ir_module(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def import_ir_module_from_buffer(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def index_add(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def index_copy(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def index_fill(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def index_put(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def index_put_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def index_reduce(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def index_select(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def indices_copy(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def inference_mode(mode: Tensor = ...) -> Tensor: ...
def init_num_threads(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def initial_seed() -> Tensor: ...
def inner(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def instance_norm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def int_repr(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def inverse(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def is_anomaly_check_nan_enabled(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def is_anomaly_enabled(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def is_autocast_cache_enabled(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def is_autocast_cpu_enabled(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def is_autocast_enabled(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def is_autocast_ipu_enabled(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def is_autocast_xla_enabled(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def is_complex(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def is_conj(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def is_deterministic_algorithms_warn_only_enabled() -> Tensor: ...
def is_distributed(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def is_floating_point(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def is_grad_enabled(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def is_inference(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def is_inference_mode_enabled(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def is_neg(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def is_nonzero(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def is_same_size(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def is_signed(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def is_storage(obj: Tensor) -> Tensor: ...
def is_tensor(obj: Tensor) -> Tensor: ...
def is_vulkan_available(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def is_warn_always_enabled() -> Tensor: ...
def isclose(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def isfinite(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def isin(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def isinf(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def isnan(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def isneginf(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def isposinf(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def isreal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def istft(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def kaiser_window(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def kl_div(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def kron(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def kthvalue(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def layer_norm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def layout() -> Tensor: ...
def lcm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def lcm_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ldexp(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ldexp_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def le(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def lerp(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def less(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def less_equal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def lgamma(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def linspace(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def load(f: Tensor, map_location: Tensor = ..., pickle_module: Tensor = ..., *, weights_only: Tensor = ..., mmap: Tensor = ..., **pickle_load_args: Tensor) -> Tensor: ...
def lobpcg(
    A: Tensor, k: Tensor = ..., B: Tensor = ..., X: Tensor = ..., n: Tensor = ..., iK: Tensor = ..., niter: Tensor = ..., tol: Tensor = ..., largest: Tensor = ..., method: Tensor = ..., tracker: Tensor = ..., ortho_iparams: Tensor = ..., ortho_fparams: Tensor = ..., ortho_bparams: Tensor = ...
) -> Tensor: ...
def log(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def log10(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def log10_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def log1p(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def log1p_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def log2(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def log2_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def log_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def log_softmax(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logaddexp(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logaddexp2(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logcumsumexp(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logdet(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logical_and(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logical_not(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logical_or(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logical_xor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logit(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logit_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logspace(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logsumexp(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def lstm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def lstm_cell(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def lstsq(input: Tensor, A: Tensor, *, out: Tensor = ...) -> Tensor: ...
def lt(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def lu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def lu_solve(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def lu_unpack(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def manual_seed(seed: Tensor) -> Tensor: ...
def margin_ranking_loss(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def masked_fill(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def masked_scatter(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def masked_select(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def matmul(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def matrix_exp(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def matrix_power(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def matrix_rank(input: Tensor, tol: Tensor = ..., symmetric: Tensor = ..., *, out: Tensor = ...) -> Tensor: ...
def max(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def max_pool1d(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def max_pool1d_with_indices(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def max_pool2d(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def max_pool3d(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def maximum(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def mean(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def median(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def memory_format() -> Tensor: ...
def merge_type_from_type_comment(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def meshgrid(*tensors: Tensor, indexing: Tensor = ...) -> Tensor: ...
def min(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def minimum(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def miopen_batch_norm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def miopen_convolution(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def miopen_convolution_add_relu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def miopen_convolution_relu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def miopen_convolution_transpose(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def miopen_depthwise_convolution(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def miopen_rnn(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def mkldnn_adaptive_avg_pool2d(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def mkldnn_convolution(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def mkldnn_linear_backward_weights(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def mkldnn_max_pool2d(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def mkldnn_max_pool3d(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def mkldnn_rnn_layer(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def mm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def mode(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def moveaxis(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def movedim(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def msort(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def mul(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def multinomial(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def multiply(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def mv(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def mvlgamma(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def nan_to_num(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def nan_to_num_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def nanmean(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def nanmedian(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def nanquantile(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def nansum(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def narrow(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def narrow_copy(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def native_batch_norm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def native_channel_shuffle(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def native_dropout(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def native_group_norm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def native_layer_norm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def native_norm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ne(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def neg(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def neg_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def negative(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def negative_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def nextafter(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def no_grad() -> Tensor: ...
def nonzero(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def nonzero_static(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def norm(input: Tensor, p: Tensor = ..., dim: Tensor = ..., keepdim: Tensor = ..., out: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def norm_except_dim(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def normal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def not_equal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def nuclear_norm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def numel(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ones(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ones_like(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def orgqr(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ormqr(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def outer(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def pairwise_distance(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def parse_ir(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def parse_schema(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def parse_type_comment(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def pca_lowrank(A: Tensor, q: Tensor = ..., center: Tensor = ..., niter: Tensor = ...) -> Tensor: ...
def pdist(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def permute(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def permute_copy(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def pinverse(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def pixel_shuffle(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def pixel_unshuffle(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def poisson(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def poisson_nll_loss(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def polar(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def polygamma(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def positive(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def pow(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def prelu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def prepare_multiprocessing_environment(path: Tensor) -> Tensor: ...
def prod(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def profiler_allow_cudagraph_cupti_lazy_reinit_cuda12() -> Tensor: ...
def promote_types(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def put(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def q_per_channel_axis(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def q_per_channel_scales(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def q_per_channel_zero_points(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def q_scale(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def q_zero_point(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def qr(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def qscheme() -> Tensor: ...
def quantile(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def quantize_per_channel(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def quantize_per_tensor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def quantize_per_tensor_dynamic(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def quantized_batch_norm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def quantized_gru(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def quantized_gru_cell(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def quantized_lstm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def quantized_lstm_cell(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def quantized_max_pool1d(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def quantized_max_pool2d(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def quantized_max_pool3d(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def quantized_rnn_relu_cell(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def quantized_rnn_tanh_cell(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def rad2deg(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def rad2deg_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def rand(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def rand_like(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def randint(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def randint_like(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def randn(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def randn_like(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def randperm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def range(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ravel(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def read_vitals(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def real(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def reciprocal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def reciprocal_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def relu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def relu_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def remainder(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def renorm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def repeat_interleave(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def reshape(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def resize_as_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def resize_as_sparse_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def resolve_conj(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def resolve_neg(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def result_type(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def rms_norm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def rnn_relu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def rnn_relu_cell(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def rnn_tanh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def rnn_tanh_cell(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def roll(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def rot90(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def round(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def round_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def row_indices_copy(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def row_stack(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def rrelu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def rrelu_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def rsqrt(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def rsqrt_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def rsub(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def saddmm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def save(obj: Tensor, f: Tensor, pickle_module: Tensor = ..., pickle_protocol: Tensor = ..., _use_new_zipfile_serialization: Tensor = ..., _disable_byteorder_record: Tensor = ...) -> Tensor: ...
def scalar_tensor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def scatter(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def scatter_add(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def scatter_reduce(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def searchsorted(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def seed() -> Tensor: ...
def segment_reduce(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def select(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def select_copy(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def select_scatter(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def selu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def selu_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def set_anomaly_enabled(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def set_autocast_cache_enabled(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def set_autocast_cpu_dtype(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def set_autocast_cpu_enabled(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def set_autocast_dtype(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def set_autocast_enabled(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def set_autocast_gpu_dtype(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def set_autocast_ipu_dtype(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def set_autocast_ipu_enabled(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def set_autocast_xla_dtype(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def set_autocast_xla_enabled(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def set_default_device(device: Tensor) -> Tensor: ...
def set_default_dtype(d: Tensor) -> Tensor: ...
def set_default_tensor_type(t: Tensor) -> Tensor: ...
def set_deterministic_debug_mode(debug_mode: Tensor) -> Tensor: ...
def set_float32_matmul_precision(precision: Tensor) -> Tensor: ...
def set_flush_denormal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def set_grad_enabled(mode: Tensor) -> Tensor: ...
def set_num_interop_threads(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def set_num_threads(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def set_printoptions(precision: Tensor = ..., threshold: Tensor = ..., edgeitems: Tensor = ..., linewidth: Tensor = ..., profile: Tensor = ..., sci_mode: Tensor = ...) -> Tensor: ...
def set_rng_state(new_state: Tensor) -> Tensor: ...
def set_vital(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def set_warn_always(b: Tensor) -> Tensor: ...
def sgn(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sigmoid(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sigmoid_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sign(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def signbit(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sin(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sin_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sinc(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sinc_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sinh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sinh_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def slice_copy(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def slice_inverse(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def slice_scatter(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def slogdet(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def smm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def softmax(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def solve(input: Tensor, A: Tensor, *, out: Tensor = ...) -> Tensor: ...
def sort(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sparse_bsc_tensor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sparse_bsr_tensor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sparse_compressed_tensor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sparse_coo_tensor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sparse_csc_tensor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sparse_csr_tensor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def split(tensor: Tensor, split_size_or_sections: Tensor, dim: Tensor = ...) -> Tensor: ...
def split_copy(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def split_with_sizes(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def split_with_sizes_copy(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def spmm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sqrt(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sqrt_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def square(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def square_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def squeeze(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def squeeze_copy(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sspaddmm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def stack(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def std(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def std_mean(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def stft(input: Tensor, n_fft: Tensor, hop_length: Tensor = ..., win_length: Tensor = ..., window: Tensor = ..., center: Tensor = ..., pad_mode: Tensor = ..., normalized: Tensor = ..., onesided: Tensor = ..., return_complex: Tensor = ..., align_to_window: Tensor = ...) -> Tensor: ...
def sub(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def subtract(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sum(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def svd(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def svd_lowrank(A: Tensor, q: Tensor = ..., niter: Tensor = ..., M: Tensor = ...) -> Tensor: ...
def swapaxes(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def swapdims(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sym_constrain_range(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sym_constrain_range_for_size(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sym_float(a: Tensor) -> Tensor: ...
def sym_fresh_size(expr: Tensor) -> Tensor: ...
def sym_int(a: Tensor) -> Tensor: ...
def sym_ite(b: Tensor, t: Tensor, f: Tensor) -> Tensor: ...
def sym_max(a: Tensor, b: Tensor) -> Tensor: ...
def sym_min(a: Tensor, b: Tensor) -> Tensor: ...
def sym_not(a: Tensor) -> Tensor: ...
def sym_sqrt(a: Tensor) -> Tensor: ...
def sym_sum(args: Tensor) -> Tensor: ...
def symeig(input: Tensor, eigenvectors: Tensor = ..., upper: Tensor = ..., *, out: Tensor = ...) -> Tensor: ...
def t(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def t_copy(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def take(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def take_along_dim(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def tan(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def tan_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def tanh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def tanh_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def tensor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def tensor_split(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def tensordot(a: Tensor, b: Tensor, dims: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def threshold(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def threshold_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def tile(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def to_dlpack(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def topk(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def trace(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def transpose(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def transpose_copy(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def trapezoid(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def trapz(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def triangular_solve(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def tril(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def tril_indices(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def triplet_margin_loss(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def triu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def triu_indices(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def true_divide(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def trunc(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def trunc_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def typename(obj: Tensor) -> Tensor: ...
def unbind(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def unbind_copy(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def unflatten(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def unfold_copy(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def unify_type_list(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def unique(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def unique_consecutive(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def unravel_index(indices: Tensor, shape: Tensor) -> Tensor: ...
def unsafe_chunk(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def unsafe_split(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def unsafe_split_with_sizes(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def unsqueeze(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def unsqueeze_copy(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def use_deterministic_algorithms(mode: Tensor, *, warn_only: Tensor = ...) -> Tensor: ...
def values_copy(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def vander(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def var(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def var_mean(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def vdot(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def view_as_complex(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def view_as_complex_copy(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def view_as_real(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def view_as_real_copy(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def view_copy(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def vitals_enabled(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def vmap(func: Tensor, in_dims: Tensor = ..., out_dims: Tensor = ..., randomness: Tensor = ..., *, chunk_size: Tensor = ...) -> Tensor: ...
def vsplit(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def vstack(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def wait(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def where(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def while_loop(cond_fn: Tensor, body_fn: Tensor, carried_inputs: Tensor) -> Tensor: ...
def xlogy(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def xlogy_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def zero_(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def zeros(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def zeros_like(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
