"""Auto-generated high-fidelity type stubs for edge_mlir from ml-ecosystem-snapshots."""
# ruff: noqa: E501, UP007, UP045, D100, D101, D102, D103

from collections.abc import Sequence

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    device: str
    ndim: int
    size: int
    def __init__(self, data: object = ..., shape: Sequence[int] | None = ..., dtype: str | None = ...) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: object) -> Tensor: ...
    def __add__(self, other: Tensor | float | int) -> Tensor: ...
    def __sub__(self, other: Tensor | float | int) -> Tensor: ...
    def __mul__(self, other: Tensor | float | int) -> Tensor: ...
    def __truediv__(self, other: Tensor | float | int) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def numpy(self) -> object: ...
    def to(self, device: str) -> Tensor: ...
    def reshape(self, shape: Sequence[int]) -> Tensor: ...
    def transpose(self, axes: Sequence[int] | None = ...) -> Tensor: ...

def AddFOp(lhs: Tensor, rhs: Tensor, *, fastmath: Tensor) -> Tensor: ...
def AddIOp(lhs: Tensor, rhs: Tensor, *, overflowFlags: Tensor) -> Tensor: ...
def DivFOp(lhs: Tensor, rhs: Tensor, *, fastmath: Tensor) -> Tensor: ...
def EmptyOp(dynamicSizes: Tensor, *, staticSizes: Tensor) -> Tensor: ...
def ExpOp(operand: Tensor) -> Tensor: ...
def ForOp(lowerBound: Tensor, upperBound: Tensor, step: Tensor) -> Tensor: ...
def FuncOp(*, sym_name: Tensor, function_type: Tensor) -> Tensor: ...
def MatmulOp(inputs: Tensor, outputs: Tensor) -> Tensor: ...
def MulFOp(lhs: Tensor, rhs: Tensor, *, fastmath: Tensor) -> Tensor: ...
def MulIOp(lhs: Tensor, rhs: Tensor, *, overflowFlags: Tensor) -> Tensor: ...
def ReturnOp(operands: Tensor) -> Tensor: ...
def SubFOp(lhs: Tensor, rhs: Tensor, *, fastmath: Tensor) -> Tensor: ...
def SubIOp(lhs: Tensor, rhs: Tensor, *, overflowFlags: Tensor) -> Tensor: ...
def YieldOp(results: Tensor) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
