"""Auto-generated high-fidelity type stubs for cupy backend."""
# ruff: noqa: E501, UP007, UP045, D100, D101, D102, D103

from collections.abc import Sequence

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    device: str
    ndim: int
    size: int
    def __init__(self, data: object = ..., shape: Sequence[int] | None = ..., dtype: str | None = ...) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: object) -> Tensor: ...
    def __add__(self, other: Tensor | float | int) -> Tensor: ...
    def __sub__(self, other: Tensor | float | int) -> Tensor: ...
    def __mul__(self, other: Tensor | float | int) -> Tensor: ...
    def __truediv__(self, other: Tensor | float | int) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def numpy(self) -> object: ...
    def to(self, device: str) -> Tensor: ...
    def reshape(self, shape: Sequence[int]) -> Tensor: ...
    def transpose(self, axes: Sequence[int] | None = ...) -> Tensor: ...

def abs(x: Tensor) -> Tensor: ...
def acos(x: Tensor) -> Tensor: ...
def acosh(x: Tensor) -> Tensor: ...
def add(x1: Tensor, x2: Tensor | float | int) -> Tensor: ...
def all(x: Tensor, axis: int | Sequence[int] | None = ..., keepdims: bool = ...) -> Tensor: ...
def any(x: Tensor, axis: int | Sequence[int] | None = ..., keepdims: bool = ...) -> Tensor: ...
def argmax(x: Tensor, axis: int | None = ..., keepdims: bool = ...) -> Tensor: ...
def argmin(x: Tensor, axis: int | None = ..., keepdims: bool = ...) -> Tensor: ...
def asin(x: Tensor) -> Tensor: ...
def asinh(x: Tensor) -> Tensor: ...
def atan(x: Tensor) -> Tensor: ...
def atan2(x1: Tensor, x2: Tensor) -> Tensor: ...
def atanh(x: Tensor) -> Tensor: ...
def ceil(x: Tensor) -> Tensor: ...
def clip(x: Tensor, min_val: Tensor | float, max_val: Tensor | float) -> Tensor: ...
def concat(tensors: Sequence[Tensor], axis: int = ...) -> Tensor: ...
def conv2d(input: Tensor, weight: Tensor, bias: Tensor | None = ..., stride: int | tuple[int, int] = ..., padding: str | int | tuple[int, int] = ...) -> Tensor: ...
def cos(x: Tensor) -> Tensor: ...
def cosh(x: Tensor) -> Tensor: ...
def cumsum(x: Tensor, axis: int | None = ...) -> Tensor: ...
def divide(x1: Tensor, x2: Tensor | float | int) -> Tensor: ...
def dot(a: Tensor, b: Tensor) -> Tensor: ...
def equal(x1: Tensor, x2: Tensor) -> Tensor: ...
def exp(x: Tensor) -> Tensor: ...
def floor(x: Tensor) -> Tensor: ...
def greater(x1: Tensor, x2: Tensor) -> Tensor: ...
def greater_equal(x1: Tensor, x2: Tensor) -> Tensor: ...
def less(x1: Tensor, x2: Tensor) -> Tensor: ...
def less_equal(x1: Tensor, x2: Tensor) -> Tensor: ...
def log(x: Tensor) -> Tensor: ...
def logical_and(x1: Tensor, x2: Tensor) -> Tensor: ...
def logical_not(x: Tensor) -> Tensor: ...
def logical_or(x1: Tensor, x2: Tensor) -> Tensor: ...
def matmul(x1: Tensor, x2: Tensor) -> Tensor: ...
def max(x: Tensor, axis: int | Sequence[int] | None = ..., keepdims: bool = ...) -> Tensor: ...
def maximum(x1: Tensor, x2: Tensor) -> Tensor: ...
def mean(x: Tensor, axis: int | Sequence[int] | None = ..., keepdims: bool = ...) -> Tensor: ...
def min(x: Tensor, axis: int | Sequence[int] | None = ..., keepdims: bool = ...) -> Tensor: ...
def minimum(x1: Tensor, x2: Tensor) -> Tensor: ...
def multiply(x1: Tensor, x2: Tensor | float | int) -> Tensor: ...
def negative(x: Tensor) -> Tensor: ...
def not_equal(x1: Tensor, x2: Tensor) -> Tensor: ...
def ones(shape: Sequence[int], dtype: str | None = ...) -> Tensor: ...
def pad(x: Tensor, pad_width: Sequence[tuple[int, int]], mode: str = ...) -> Tensor: ...
def pow(x1: Tensor, x2: Tensor | float) -> Tensor: ...
def reshape(x: Tensor, shape: Sequence[int]) -> Tensor: ...
def round(x: Tensor) -> Tensor: ...
def rsqrt(x: Tensor) -> Tensor: ...
def sigmoid(x: Tensor) -> Tensor: ...
def sin(x: Tensor) -> Tensor: ...
def sinh(x: Tensor) -> Tensor: ...
def slice(x: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def softmax(x: Tensor, axis: int = ...) -> Tensor: ...
def split(x: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def sqrt(x: Tensor) -> Tensor: ...
def squeeze(x: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def subtract(x1: Tensor, x2: Tensor | float | int) -> Tensor: ...
def sum(x: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def tan(x: Tensor) -> Tensor: ...
def tanh(x: Tensor) -> Tensor: ...
def transpose(x: Tensor, axes: Sequence[int] | None = ...) -> Tensor: ...
def zeros(shape: Sequence[int], dtype: str | None = ...) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
