"""Auto-generated high-fidelity type stubs for cupy from ml-ecosystem-snapshots."""
# ruff: noqa: E501, UP007, UP045, D100, D101, D102, D103

from collections.abc import Sequence

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    device: str
    ndim: int
    size: int
    def __init__(self, data: object = ..., shape: Sequence[int] | None = ..., dtype: str | None = ...) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: object) -> Tensor: ...
    def __add__(self, other: Tensor | float | int) -> Tensor: ...
    def __sub__(self, other: Tensor | float | int) -> Tensor: ...
    def __mul__(self, other: Tensor | float | int) -> Tensor: ...
    def __truediv__(self, other: Tensor | float | int) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def numpy(self) -> object: ...
    def to(self, device: str) -> Tensor: ...
    def reshape(self, shape: Sequence[int]) -> Tensor: ...
    def transpose(self, axes: Sequence[int] | None = ...) -> Tensor: ...

def cupy_exp(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_maximum(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_minimum(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_tanh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def all(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: bool = ...) -> Tensor: ...
def allclose(a: Tensor, b: Tensor, rtol: float = ..., atol: float = ..., equal_nan: bool = ...) -> Tensor: ...
def amax(a: Tensor, axis: int = ..., out: Tensor = ..., keepdims: bool = ...) -> Tensor: ...
def amin(a: Tensor, axis: int = ..., out: Tensor = ..., keepdims: bool = ...) -> Tensor: ...
def angle(z: Tensor, deg: bool = ...) -> Tensor: ...
def any(a: Tensor, axis: Tensor = ..., out: Tensor = ..., keepdims: bool = ...) -> Tensor: ...
def append(arr: Tensor, values: Tensor, axis: Tensor = ...) -> Tensor: ...
def apply_along_axis(func1d: Tensor, axis: Tensor, arr: Tensor, *args: Tensor, **kwargs: Tensor) -> Tensor: ...
def apply_over_axes(func: Tensor, a: Tensor, axes: Tensor) -> Tensor: ...
def arange(start: Tensor, stop: Tensor = ..., step: int = ..., dtype: Tensor = ...) -> Tensor: ...
def argmax(a: Tensor, axis: int = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: bool = ...) -> Tensor: ...
def argmin(a: Tensor, axis: int = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: bool = ...) -> Tensor: ...
def argpartition(a: Tensor, kth: Tensor, axis: Tensor = ...) -> Tensor: ...
def argsort(a: Tensor, axis: Tensor = ..., kind: Tensor = ...) -> Tensor: ...
def argwhere(a: Tensor) -> Tensor: ...
def around(a: Tensor, decimals: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def array(obj: Tensor, dtype: Tensor = ..., copy: Tensor = ..., order: Tensor = ..., subok: bool = ..., ndmin: int = ..., *, blocking: bool = ...) -> Tensor: ...
def array2string(a: Tensor, *args: Tensor, **kwargs: Tensor) -> Tensor: ...
def array_equal(a1: Tensor, a2: Tensor, equal_nan: bool = ...) -> Tensor: ...
def array_equiv(a1: Tensor, a2: Tensor) -> Tensor: ...
def array_repr(arr: Tensor, max_line_width: int = ..., precision: int = ..., suppress_small: bool = ...) -> Tensor: ...
def array_split(ary: Tensor, indices_or_sections: Tensor, axis: int = ...) -> Tensor: ...
def array_str(arr: Tensor, max_line_width: int = ..., precision: int = ..., suppress_small: int = ...) -> Tensor: ...
def asanyarray(a: Tensor, dtype: Tensor = ..., order: Tensor = ..., *, copy: Tensor = ..., blocking: bool = ...) -> Tensor: ...
def asarray(a: Tensor, dtype: Tensor = ..., order: Tensor = ..., *, copy: Tensor = ..., blocking: bool = ...) -> Tensor: ...
def asarray_chkfinite(a: Tensor, dtype: Tensor = ..., order: Tensor = ...) -> Tensor: ...
def ascontiguousarray(a: Tensor, dtype: Tensor = ...) -> Tensor: ...
def asfarray(a: Tensor, dtype: Tensor = ...) -> Tensor: ...
def asfortranarray(a: Tensor, dtype: Tensor = ...) -> Tensor: ...
def asnumpy(a: Tensor, stream: Tensor = ..., order: Tensor = ..., out: Tensor = ..., *, blocking: bool = ...) -> Tensor: ...
def astype(x: Tensor, dtype: Tensor, *, copy: bool = ...) -> Tensor: ...
def atleast_1d(*arys: Tensor) -> Tensor: ...
def atleast_2d(*arys: Tensor) -> Tensor: ...
def atleast_3d(*arys: Tensor) -> Tensor: ...
def average(a: Tensor, axis: int = ..., weights: Tensor = ..., returned: bool = ..., *, keepdims: bool = ...) -> Tensor: ...
def bartlett(M: Tensor) -> Tensor: ...
def base_repr(number: Tensor, base: int = ..., padding: int = ...) -> Tensor: ...
def binary_repr(num: Tensor, width: Tensor = ...) -> Tensor: ...
def bincount(x: Tensor, weights: Tensor = ..., minlength: int = ...) -> Tensor: ...
def blackman(M: Tensor) -> Tensor: ...
def broadcast_arrays(*args: Tensor) -> Tensor: ...
def broadcast_shapes(*args: Tensor) -> Tensor: ...
def broadcast_to(array: Tensor, shape: Tensor) -> Tensor: ...
def byte_bounds(a: Tensor) -> Tensor: ...
def can_cast(from_: Tensor, to: Tensor, casting: str = ...) -> Tensor: ...
def choose(a: Tensor, choices: Tensor, out: Tensor = ..., mode: str = ...) -> Tensor: ...
def clear_memo(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def clip(a: Tensor, a_min: Tensor, a_max: Tensor, out: Tensor = ...) -> Tensor: ...
def column_stack(tup: Tensor) -> Tensor: ...
def common_type(*arrays: Tensor) -> Tensor: ...
def compress(condition: Tensor, a: Tensor, axis: int = ..., out: Tensor = ...) -> Tensor: ...
def concatenate(tup: Tensor, axis: Tensor = ..., out: Tensor = ..., *, dtype: Tensor = ..., casting: str = ...) -> Tensor: ...
def convolve(a: Tensor, v: Tensor, mode: Tensor = ...) -> Tensor: ...
def copy(a: Tensor, order: Tensor = ...) -> Tensor: ...
def copyto(dst: Tensor, src: Tensor, casting: str = ..., where: Tensor = ...) -> Tensor: ...
def corrcoef(a: Tensor, y: Tensor = ..., rowvar: bool = ..., bias: Tensor = ..., ddof: Tensor = ..., *, dtype: Tensor = ...) -> Tensor: ...
def correlate(a: Tensor, v: Tensor, mode: Tensor = ...) -> Tensor: ...
def count_nonzero(a: Tensor, axis: Tensor = ...) -> Tensor: ...
def cov(a: Tensor, y: Tensor = ..., rowvar: bool = ..., bias: int = ..., ddof: int = ..., aweights: Tensor = ..., fweights: Tensor = ..., *, dtype: Tensor = ...) -> Tensor: ...
def cross(a: Tensor, b: Tensor, axisb: int = ..., axis: Tensor = ..., axisc: int = ..., axisa: int = ...) -> Tensor: ...
def cumprod(a: Tensor, axis: int = ..., dtype: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def cumproduct(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def cumsum(a: Tensor, axis: int = ..., dtype: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def cumulative_prod(x: Tensor, *, axis: Tensor = ..., dtype: int = ..., out: Tensor = ..., include_initial: bool = ...) -> Tensor: ...
def cumulative_sum(x: Tensor, *, axis: Tensor = ..., dtype: int = ..., out: Tensor = ..., include_initial: bool = ...) -> Tensor: ...
def cupy_absolute(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_add(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_arccos(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_arccosh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_arcsin(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_arcsinh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_arctan(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_arctan2(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_arctanh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_bitwise_and(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_bitwise_count(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_bitwise_or(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_bitwise_xor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_cbrt(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_ceil(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_conjugate(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_copysign(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_cos(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_cosh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_deg2rad(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_divmod(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_equal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_exp2(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_expm1(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_fabs(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_fix(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_float_power(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_floor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_floor_divide(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_fmax(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_fmin(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_fmod(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_frexp(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_gcd(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_greater(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_greater_equal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_heaviside(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_hypot(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_i0(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_invert(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_isfinite(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_isinf(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_isnan(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_lcm(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_ldexp(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_left_shift(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_less(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_less_equal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_log(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_log10(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_log1p(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_log2(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_logaddexp(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_logaddexp2(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_logical_and(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_logical_not(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_logical_or(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_logical_xor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_modf(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_multiply(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_negative(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_nextafter(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_not_equal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_positive(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_power(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_rad2deg(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_reciprocal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_remainder(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_right_shift(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_rint(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_sign(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_signbit(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_sin(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_sinc(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_sinh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_sqrt(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_square(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_subtract(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_tan(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_true_divide(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cupy_trunc(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def delete(arr: Tensor, indices: Tensor, axis: Tensor = ...) -> Tensor: ...
def diag(v: Tensor, k: int = ...) -> Tensor: ...
def diag_indices(n: int, ndim: int = ...) -> Tensor: ...
def diag_indices_from(arr: Tensor) -> Tensor: ...
def diagflat(v: Tensor, k: int = ...) -> Tensor: ...
def diagonal(a: Tensor, offset: int = ..., axis1: int = ..., axis2: int = ...) -> Tensor: ...
def diff(a: Tensor, n: int = ..., axis: int = ..., prepend: Tensor = ..., append: Tensor = ...) -> Tensor: ...
def digitize(x: Tensor, bins: Tensor, right: bool = ...) -> Tensor: ...
def disp(*args: Tensor, **kwds: Tensor) -> Tensor: ...
def dot(a: Tensor, b: Tensor, out: Tensor = ...) -> Tensor: ...
def dsplit(ary: Tensor, indices_or_sections: Tensor) -> Tensor: ...
def dstack(tup: Tensor) -> Tensor: ...
def ediff1d(arr: Tensor, to_end: Tensor = ..., to_begin: Tensor = ...) -> Tensor: ...
def einsum(subscripts: str, dtype: Tensor, optimize: Tensor = ..., *operands: Tensor, **kwargs: Tensor) -> Tensor: ...
def empty(shape: Tensor, dtype: Tensor = ..., order: Tensor = ...) -> Tensor: ...
def empty_like(prototype: Tensor, dtype: Tensor = ..., order: Tensor = ..., subok: Tensor = ..., shape: Tensor = ...) -> Tensor: ...
def expand_dims(a: Tensor, axis: int) -> Tensor: ...
def extract(condition: Tensor, a: Tensor) -> Tensor: ...
def eye(N: int, M: Tensor = ..., k: int = ..., dtype: Tensor = ..., order: Tensor = ...) -> Tensor: ...
def fill_diagonal(a: Tensor, val: Tensor, wrap: bool = ...) -> Tensor: ...
def find_common_type(*args: Tensor, **kwds: Tensor) -> Tensor: ...
def flatnonzero(a: Tensor) -> Tensor: ...
def flip(a: Tensor, axis: Tensor = ...) -> Tensor: ...
def fliplr(a: Tensor) -> Tensor: ...
def flipud(a: Tensor) -> Tensor: ...
def format_float_positional(x: Tensor, *args: Tensor, **kwargs: Tensor) -> Tensor: ...
def format_float_scientific(x: Tensor, *args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fromDlpack(dltensor: Tensor) -> Tensor: ...
def from_dlpack(array: Tensor, *, device: Tensor = ..., copy: Tensor = ...) -> Tensor: ...
def frombuffer(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fromfile(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fromfunction(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fromiter(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fromstring(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def full(shape: Tensor, fill_value: Tensor, dtype: Tensor = ..., order: Tensor = ...) -> Tensor: ...
def full_like(a: Tensor, fill_value: Tensor, dtype: Tensor = ..., order: Tensor = ..., subok: Tensor = ..., shape: Tensor = ...) -> Tensor: ...
def fuse(*args: Tensor, kernel_name: str, **kwargs: Tensor) -> Tensor: ...
def genfromtxt(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def get_array_module(*args: Tensor) -> Tensor: ...
def get_array_wrap(*args: Tensor, **kwds: Tensor) -> Tensor: ...
def get_default_memory_pool(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def get_default_pinned_memory_pool(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def get_printoptions(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def gradient(f: Tensor, *varargs: Tensor, edge_order: int = ..., axis: Tensor = ...) -> Tensor: ...
def hamming(M: Tensor) -> Tensor: ...
def hanning(M: Tensor) -> Tensor: ...
def histogram(x: Tensor, bins: Tensor = ..., range: Tensor = ..., density: int = ..., weights: Tensor = ...) -> Tensor: ...
def histogram2d(x: Tensor, y: Tensor, bins: Tensor = ..., range: Tensor = ..., weights: Tensor = ..., density: Tensor = ...) -> Tensor: ...
def histogramdd(sample: Tensor, range: Tensor = ..., bins: int = ..., density: bool = ..., weights: Tensor = ...) -> Tensor: ...
def hsplit(ary: Tensor, indices_or_sections: Tensor) -> Tensor: ...
def hstack(tup: Tensor, *, dtype: Tensor = ..., casting: str = ...) -> Tensor: ...
def identity(n: int, dtype: Tensor = ...) -> Tensor: ...
def imag(val: Tensor) -> Tensor: ...
def in1d(ar1: Tensor, ar2: Tensor, assume_unique: bool = ..., invert: bool = ...) -> Tensor: ...
def indices(dimensions: Tensor, dtype: Tensor = ...) -> Tensor: ...
def inner(a: Tensor, b: Tensor) -> Tensor: ...
def interp(x: Tensor, xp: Tensor, fp: Tensor, left: Tensor = ..., right: Tensor = ..., period: Tensor = ...) -> Tensor: ...
def intersect1d(arr1: Tensor, arr2: Tensor, assume_unique: bool = ..., return_indices: bool = ...) -> Tensor: ...
def is_available(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def isclose(a: Tensor, b: Tensor, rtol: float = ..., atol: float = ..., equal_nan: bool = ...) -> Tensor: ...
def iscomplex(x: Tensor) -> Tensor: ...
def iscomplexobj(x: Tensor) -> Tensor: ...
def isdtype(dtype: Tensor, kind: Tensor) -> Tensor: ...
def isfortran(a: Tensor) -> Tensor: ...
def isin(element: Tensor, test_elements: Tensor, assume_unique: bool = ..., invert: bool = ...) -> Tensor: ...
def isneginf(x: Tensor, out: bool = ...) -> Tensor: ...
def isposinf(x: Tensor, out: bool = ...) -> Tensor: ...
def isreal(x: Tensor) -> Tensor: ...
def isrealobj(x: Tensor) -> Tensor: ...
def isscalar(element: Tensor) -> Tensor: ...
def issctype(rep: Tensor) -> Tensor: ...
def issubclass_(arg1: Tensor, arg2: Tensor) -> Tensor: ...
def issubdtype(arg1: Tensor, arg2: Tensor) -> Tensor: ...
def issubsctype(arg1: Tensor, arg2: Tensor) -> Tensor: ...
def iterable(y: Tensor) -> Tensor: ...
def ix_(*args: Tensor) -> Tensor: ...
def kaiser(M: Tensor, beta: Tensor) -> Tensor: ...
def kron(a: Tensor, b: Tensor) -> Tensor: ...
def lexsort(keys: Tensor) -> Tensor: ...
def linspace(start: Tensor, stop: Tensor, num: int = ..., endpoint: bool = ..., retstep: bool = ..., dtype: Tensor = ..., axis: int = ...) -> Tensor: ...
def load(file: Tensor, mmap_mode: Tensor = ..., allow_pickle: bool = ...) -> Tensor: ...
def loadtxt(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logspace(start: Tensor, stop: Tensor, num: int = ..., endpoint: bool = ..., base: float = ..., dtype: Tensor = ..., axis: int = ...) -> Tensor: ...
def make_aligned_dtype(dtype: Tensor, *, alignment: int = ..., recurse: bool = ...) -> Tensor: ...
def mask_indices(n: int, mask_func: Tensor, k: Tensor = ...) -> Tensor: ...
def matmul(*args: Tensor, axes: Tensor = ..., axis: Tensor = ..., keepdims: Tensor = ..., casting: Tensor = ..., dtype: Tensor = ..., signature: Tensor = ..., order: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def matrix_transpose(x: Tensor) -> Tensor: ...
def may_share_memory(a: Tensor, b: Tensor, max_work: Tensor = ...) -> Tensor: ...
def mean(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: bool = ...) -> Tensor: ...
def median(a: Tensor, axis: Tensor = ..., out: Tensor = ..., overwrite_input: bool = ..., keepdims: bool = ...) -> Tensor: ...
def memoize(for_each_device: bool = ...) -> Tensor: ...
def meshgrid(indexing: Tensor, sparse: Tensor, copy: Tensor, *xi: Tensor, **kwargs: Tensor) -> Tensor: ...
def min_scalar_type(a: Tensor) -> Tensor: ...
def mintypecode(typechars: Tensor, typeset: str = ..., default: str = ...) -> Tensor: ...
def moveaxis(a: Tensor, source: Tensor, destination: Tensor) -> Tensor: ...
def msort(a: Tensor) -> Tensor: ...
def nan_to_num(x: Tensor, copy: bool = ..., nan: float = ..., posinf: Tensor = ..., neginf: Tensor = ...) -> Tensor: ...
def nanargmax(a: Tensor, axis: int = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: bool = ...) -> Tensor: ...
def nanargmin(a: Tensor, axis: int = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: bool = ...) -> Tensor: ...
def nancumprod(a: Tensor, axis: int = ..., dtype: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nancumsum(a: Tensor, axis: int = ..., dtype: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nanmax(a: Tensor, axis: int = ..., out: Tensor = ..., keepdims: bool = ...) -> Tensor: ...
def nanmean(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: bool = ...) -> Tensor: ...
def nanmedian(a: Tensor, axis: Tensor = ..., out: Tensor = ..., overwrite_input: bool = ..., keepdims: bool = ...) -> Tensor: ...
def nanmin(a: Tensor, axis: int = ..., out: Tensor = ..., keepdims: bool = ...) -> Tensor: ...
def nanprod(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: bool = ...) -> Tensor: ...
def nanstd(a: Tensor, axis: int = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: bool = ..., ddof: int = ...) -> Tensor: ...
def nansum(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: bool = ...) -> Tensor: ...
def nanvar(a: Tensor, axis: int = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: bool = ..., ddof: int = ...) -> Tensor: ...
def ndim(a: Tensor) -> Tensor: ...
def nonzero(a: Tensor) -> Tensor: ...
def obj2sctype(rep: Tensor, default: Tensor = ...) -> Tensor: ...
def ones(shape: Tensor, dtype: Tensor = ..., order: Tensor = ...) -> Tensor: ...
def ones_like(a: Tensor, dtype: Tensor = ..., order: Tensor = ..., subok: Tensor = ..., shape: Tensor = ...) -> Tensor: ...
def outer(a: Tensor, b: Tensor, out: Tensor = ...) -> Tensor: ...
def packbits(a: Tensor, axis: Tensor = ..., bitorder: Tensor = ...) -> Tensor: ...
def pad(array: Tensor, pad_width: Tensor, mode: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def partition(a: Tensor, kth: Tensor, axis: Tensor = ...) -> Tensor: ...
def percentile(a: Tensor, q: Tensor, axis: Tensor = ..., out: Tensor = ..., overwrite_input: bool = ..., method: str = ..., keepdims: bool = ..., *, interpolation: str = ...) -> Tensor: ...
def piecewise(x: Tensor, condlist: Tensor, funclist: Tensor) -> Tensor: ...
def place(arr: Tensor, mask: Tensor, vals: Tensor) -> Tensor: ...
def poly(seq_of_zeros: Tensor) -> Tensor: ...
def polyadd(a1: Tensor, a2: Tensor) -> Tensor: ...
def polyfit(x: Tensor, y: Tensor, deg: int, rcond: Tensor = ..., full: Tensor = ..., w: Tensor = ..., cov: Tensor = ...) -> Tensor: ...
def polymul(a1: Tensor, a2: Tensor) -> Tensor: ...
def polysub(a1: Tensor, a2: Tensor) -> Tensor: ...
def polyval(p: Tensor, x: Tensor) -> Tensor: ...
def printoptions(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def prod(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: bool = ...) -> Tensor: ...
def product(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: bool = ...) -> Tensor: ...
def promote_types(type1: Tensor, type2: Tensor) -> Tensor: ...
def ptp(a: Tensor, axis: int = ..., out: Tensor = ..., keepdims: bool = ...) -> Tensor: ...
def put(a: Tensor, ind: Tensor, v: Tensor, mode: Tensor = ...) -> Tensor: ...
def put_along_axis(arr: Tensor, indices: Tensor, values: Tensor, axis: Tensor) -> Tensor: ...
def putmask(a: Tensor, mask: Tensor, values: Tensor) -> Tensor: ...
def quantile(a: Tensor, q: Tensor, axis: Tensor = ..., out: Tensor = ..., overwrite_input: bool = ..., method: str = ..., keepdims: bool = ..., *, interpolation: str = ...) -> Tensor: ...
def ravel(a: Tensor, order: str = ...) -> Tensor: ...
def ravel_multi_index(multi_index: Tensor, dims: Tensor, mode: Tensor = ..., order: Tensor = ...) -> Tensor: ...
def real(val: Tensor) -> Tensor: ...
def real_if_close(a: Tensor, tol: int = ...) -> Tensor: ...
def repeat(a: Tensor, repeats: Tensor, axis: Tensor = ...) -> Tensor: ...
def require(a: Tensor, dtype: Tensor = ..., requirements: Tensor = ...) -> Tensor: ...
def reshape(a: Tensor, newshape: int, order: str = ..., *, copy: Tensor = ...) -> Tensor: ...
def resize(a: Tensor, new_shape: Tensor) -> Tensor: ...
def result_type(*arrays_and_dtypes: Tensor) -> Tensor: ...
def roll(a: Tensor, shift: Tensor, axis: Tensor = ...) -> Tensor: ...
def rollaxis(a: Tensor, axis: int, start: int = ...) -> Tensor: ...
def roots(p: Tensor) -> Tensor: ...
def rot90(a: Tensor, k: int = ..., axes: Tensor = ...) -> Tensor: ...
def round(a: Tensor, decimals: int = ..., out: Tensor = ...) -> Tensor: ...
def round_(a: Tensor, decimals: int = ..., out: Tensor = ...) -> Tensor: ...
def row_stack(tup: Tensor, *, dtype: Tensor = ..., casting: str = ...) -> Tensor: ...
def safe_eval(*args: Tensor, **kwds: Tensor) -> Tensor: ...
def save(file: Tensor, arr: Tensor, allow_pickle: bool = ...) -> Tensor: ...
def savetxt(fname: Tensor, X: Tensor, *args: Tensor, **kwargs: Tensor) -> Tensor: ...
def savez(file: Tensor, *args: Tensor, **kwds: Tensor) -> Tensor: ...
def savez_compressed(file: Tensor, *args: Tensor, **kwds: Tensor) -> Tensor: ...
def sctype2char(sctype: str) -> Tensor: ...
def searchsorted(a: Tensor, v: Tensor, side: str = ..., sorter: Tensor = ...) -> Tensor: ...
def select(condlist: Tensor, choicelist: Tensor, default: Tensor = ...) -> Tensor: ...
def set_printoptions(
    precision: float = ..., threshold: int = ..., edgeitems: Tensor = ..., linewidth: int = ..., suppress: int = ..., nanstr: float = ..., infstr: float = ..., formatter: str = ..., sign: Tensor = ..., floatmode: Tensor = ..., *, legacy: str = ..., override_repr: Tensor = ...
) -> Tensor: ...
def set_string_function(*args: Tensor, **kwds: Tensor) -> Tensor: ...
def setdiff1d(ar1: Tensor, ar2: Tensor, assume_unique: bool = ...) -> Tensor: ...
def setxor1d(ar1: Tensor, ar2: Tensor, assume_unique: bool = ...) -> Tensor: ...
def shape(a: Tensor) -> Tensor: ...
def shares_memory(a: Tensor, b: Tensor, max_work: Tensor = ...) -> Tensor: ...
def show_config(*, _full: bool = ...) -> Tensor: ...
def size(a: Tensor, axis: int = ...) -> Tensor: ...
def sort(a: Tensor, axis: Tensor = ..., kind: Tensor = ...) -> Tensor: ...
def sort_complex(a: Tensor) -> Tensor: ...
def split(ary: Tensor, indices_or_sections: int, axis: int = ...) -> Tensor: ...
def squeeze(a: Tensor, axis: Tensor = ...) -> Tensor: ...
def stack(tup: Tensor, axis: int = ..., out: Tensor = ..., *, dtype: Tensor = ..., casting: str = ...) -> Tensor: ...
def std(a: Tensor, axis: int = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: bool = ..., ddof: int = ...) -> Tensor: ...
def sum(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: bool = ...) -> Tensor: ...
def swapaxes(a: Tensor, axis1: int, axis2: int) -> Tensor: ...
def take(a: Tensor, indices: Tensor, axis: int = ..., out: Tensor = ...) -> Tensor: ...
def take_along_axis(a: Tensor, indices: Tensor, axis: int) -> Tensor: ...
def tensordot(a: Tensor, b: Tensor, axes: int = ...) -> Tensor: ...
def tile(A: Tensor, reps: Tensor) -> Tensor: ...
def trace(a: Tensor, offset: int = ..., axis1: int = ..., axis2: int = ..., dtype: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def transpose(a: Tensor, axes: Tensor = ...) -> Tensor: ...
def trapezoid(y: Tensor, x: Tensor = ..., dx: float = ..., axis: int = ...) -> Tensor: ...
def tri(N: int, M: int = ..., k: int = ..., dtype: Tensor = ...) -> Tensor: ...
def tril(m: Tensor, k: int = ...) -> Tensor: ...
def tril_indices(n: int, k: int = ..., m: Tensor = ...) -> Tensor: ...
def tril_indices_from(arr: Tensor, k: int = ...) -> Tensor: ...
def trim_zeros(filt: Tensor, trim: str = ...) -> Tensor: ...
def triu(m: Tensor, k: int = ...) -> Tensor: ...
def triu_indices(n: int, k: int = ..., m: Tensor = ...) -> Tensor: ...
def triu_indices_from(arr: Tensor, k: int = ...) -> Tensor: ...
def typename(char: str) -> Tensor: ...
def union1d(arr1: Tensor, arr2: Tensor) -> Tensor: ...
def unique(ar: Tensor, return_index: Tensor = ..., return_inverse: Tensor = ..., return_counts: Tensor = ..., axis: int = ..., *, equal_nan: Tensor = ...) -> Tensor: ...
def unique_all(x: Tensor) -> Tensor: ...
def unique_counts(x: Tensor) -> Tensor: ...
def unique_inverse(x: Tensor) -> Tensor: ...
def unique_values(x: Tensor) -> Tensor: ...
def unpackbits(a: Tensor, bitorder: Tensor = ..., axis: Tensor = ...) -> Tensor: ...
def unravel_index(indices: Tensor, dims: Tensor, order: bool = ...) -> Tensor: ...
def unwrap(p: float, axis: int = ..., discont: Tensor = ..., *, period: Tensor = ...) -> Tensor: ...
def vander(x: Tensor, N: Tensor = ..., increasing: Tensor = ...) -> Tensor: ...
def var(a: Tensor, axis: int = ..., dtype: Tensor = ..., out: Tensor = ..., keepdims: bool = ..., ddof: int = ...) -> Tensor: ...
def vdot(a: Tensor, b: Tensor) -> Tensor: ...
def vsplit(ary: Tensor, indices_or_sections: Tensor) -> Tensor: ...
def vstack(tup: Tensor, *, dtype: Tensor = ..., casting: str = ...) -> Tensor: ...
def where(condition: Tensor, x: Tensor = ..., y: Tensor = ...) -> Tensor: ...
def who(vardict: Tensor = ...) -> Tensor: ...
def zeros(shape: Tensor, dtype: Tensor = ..., order: Tensor = ...) -> Tensor: ...
def zeros_like(a: Tensor, dtype: Tensor = ..., order: Tensor = ..., subok: Tensor = ..., shape: Tensor = ...) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
