"""Auto-generated high-fidelity type stubs for cupy backend."""
# ruff: noqa: E501

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    def __init__(self, *args: object, **kwargs: object) -> None: ...

def abs(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def acos(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def acosh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def add(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def all(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def any(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def argmax(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def argmin(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def asin(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def asinh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def atan(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def atan2(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def atanh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ceil(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def clip(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def concat(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def conv2d(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cos(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cosh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cumsum(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def divide(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def dot(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def equal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def exp(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def floor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def greater(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def greater_equal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def less(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def less_equal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def log(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logical_and(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logical_not(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logical_or(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def matmul(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def max(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def maximum(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def mean(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def min(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def minimum(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def multiply(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def negative(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def not_equal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ones(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def pad(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def pow(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def reshape(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def round(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def rsqrt(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sigmoid(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sin(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sinh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def slice(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def softmax(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def split(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sqrt(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def squeeze(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def subtract(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sum(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def tan(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def tanh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def transpose(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def zeros(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
