"""Auto-generated high-fidelity type stubs for dpnp from ml-framework-snapshots."""
# ruff: noqa: E501, UP007, UP045, D100, D101, D102, D103

from collections.abc import Sequence

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    device: str
    ndim: int
    size: int
    def __init__(self, data: object = ..., shape: Sequence[int] | None = ..., dtype: str | None = ...) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: object) -> Tensor: ...
    def __add__(self, other: Tensor | float | int) -> Tensor: ...
    def __sub__(self, other: Tensor | float | int) -> Tensor: ...
    def __mul__(self, other: Tensor | float | int) -> Tensor: ...
    def __truediv__(self, other: Tensor | float | int) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def numpy(self) -> object: ...
    def to(self, device: str) -> Tensor: ...
    def reshape(self, shape: Sequence[int]) -> Tensor: ...
    def transpose(self, axes: Sequence[int] | None = ...) -> Tensor: ...

def array(obj: Tensor, dtype: Tensor = ..., copy: Tensor = ..., order: Tensor = ..., *, device: Tensor = ..., usm_type: Tensor = ..., sycl_queue: Tensor = ...) -> Tensor: ...
def asnumpy(a: Tensor) -> Tensor: ...
def dot(a: Tensor, b: Tensor, out: Tensor = ...) -> Tensor: ...
def empty(shape: Tensor, dtype: Tensor = ..., order: Tensor = ..., *, device: Tensor = ..., usm_type: Tensor = ..., sycl_queue: Tensor = ...) -> Tensor: ...
def matmul(x1: Tensor, x2: Tensor, out: Tensor = ..., *, casting: Tensor = ..., order: Tensor = ...) -> Tensor: ...
def ones(shape: Tensor, dtype: Tensor = ..., order: Tensor = ..., *, device: Tensor = ..., usm_type: Tensor = ..., sycl_queue: Tensor = ...) -> Tensor: ...
def zeros(shape: Tensor, dtype: Tensor = ..., order: Tensor = ..., *, device: Tensor = ..., usm_type: Tensor = ..., sycl_queue: Tensor = ...) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
