"""Auto-generated high-fidelity type stubs for dpnp from ml-framework-snapshots."""
# ruff: noqa: E501

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    def __init__(self, *args: object, **kwargs: object) -> None: ...

def array(obj: Tensor, dtype: Tensor = ..., copy: Tensor = ..., order: Tensor = ..., *, device: Tensor = ..., usm_type: Tensor = ..., sycl_queue: Tensor = ...) -> Tensor: ...
def asnumpy(a: Tensor) -> Tensor: ...
def dot(a: Tensor, b: Tensor, out: Tensor = ...) -> Tensor: ...
def empty(shape: Tensor, dtype: Tensor = ..., order: Tensor = ..., *, device: Tensor = ..., usm_type: Tensor = ..., sycl_queue: Tensor = ...) -> Tensor: ...
def matmul(x1: Tensor, x2: Tensor, out: Tensor = ..., *, casting: Tensor = ..., order: Tensor = ...) -> Tensor: ...
def ones(shape: Tensor, dtype: Tensor = ..., order: Tensor = ..., *, device: Tensor = ..., usm_type: Tensor = ..., sycl_queue: Tensor = ...) -> Tensor: ...
def zeros(shape: Tensor, dtype: Tensor = ..., order: Tensor = ..., *, device: Tensor = ..., usm_type: Tensor = ..., sycl_queue: Tensor = ...) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
