"""Auto-generated high-fidelity type stubs for edge_stablehlo from ml-ecosystem-snapshots."""
# ruff: noqa: E501, UP007, UP045, D100, D101, D102, D103

from collections.abc import Sequence

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    device: str
    ndim: int
    size: int
    def __init__(self, data: object = ..., shape: Sequence[int] | None = ..., dtype: str | None = ...) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: object) -> Tensor: ...
    def __add__(self, other: Tensor | float | int) -> Tensor: ...
    def __sub__(self, other: Tensor | float | int) -> Tensor: ...
    def __mul__(self, other: Tensor | float | int) -> Tensor: ...
    def __truediv__(self, other: Tensor | float | int) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def numpy(self) -> object: ...
    def to(self, device: str) -> Tensor: ...
    def reshape(self, shape: Sequence[int]) -> Tensor: ...
    def transpose(self, axes: Sequence[int] | None = ...) -> Tensor: ...

def AbsOp(operand: Tensor) -> Tensor: ...
def AddOp(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def AfterAllOp(inputs: Tensor) -> Tensor: ...
def AllGatherOp(operands: Tensor, replica_groups: Tensor, *, all_gather_dim: Tensor, channel_handle: Tensor, use_global_device_ids: Tensor) -> Tensor: ...
def AllReduceOp(operands: Tensor, replica_groups: Tensor, *, channel_handle: Tensor, use_global_device_ids: Tensor, computation: Tensor) -> Tensor: ...
def AllToAllOp(operands: Tensor, replica_groups: Tensor, *, split_dimension: Tensor, concat_dimension: Tensor, split_count: Tensor, channel_handle: Tensor) -> Tensor: ...
def AndOp(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def AsyncDoneOp(operand: Tensor) -> Tensor: ...
def AsyncStartOp(operands: Tensor, *, body: Tensor) -> Tensor: ...
def Atan2Op(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def BatchNormGradOp(operand: Tensor, scale: Tensor, mean: Tensor, variance: Tensor, grad_output: Tensor, *, epsilon: Tensor, feature_index: Tensor) -> Tensor: ...
def BatchNormInferenceOp(operand: Tensor, scale: Tensor, offset: Tensor, mean: Tensor, variance: Tensor, *, epsilon: Tensor, feature_index: Tensor) -> Tensor: ...
def BatchNormTrainingOp(operand: Tensor, scale: Tensor, offset: Tensor, *, epsilon: Tensor, feature_index: Tensor) -> Tensor: ...
def BitcastConvertOp(operand: Tensor) -> Tensor: ...
def BroadcastInDimOp(operand: Tensor, *, broadcast_dimensions: Tensor) -> Tensor: ...
def BroadcastOp(operand: Tensor, *, broadcast_sizes: Tensor) -> Tensor: ...
def CaseOp(index: Tensor, *, branches: Tensor) -> Tensor: ...
def CbrtOp(operand: Tensor, result_accuracy: Tensor) -> Tensor: ...
def CeilOp(operand: Tensor) -> Tensor: ...
def CholeskyOp(a: Tensor, lower: Tensor) -> Tensor: ...
def ClampOp(min: Tensor, operand: Tensor, max: Tensor) -> Tensor: ...
def ClzOp(operand: Tensor) -> Tensor: ...
def CollectiveBroadcastOp(operands: Tensor, replica_groups: Tensor, *, channel_handle: Tensor, has_dynamic_root: Tensor) -> Tensor: ...
def CollectivePermuteOp(operand: Tensor, *, source_target_pairs: Tensor, channel_handle: Tensor) -> Tensor: ...
def CollectiveReduceOp(operands: Tensor, replica_groups: Tensor, *, channel_handle: Tensor, use_global_device_ids: Tensor, has_dynamic_root: Tensor, computation: Tensor) -> Tensor: ...
def CompareOp(lhs: Tensor, rhs: Tensor, *, comparison_direction: Tensor, compare_type: Tensor) -> Tensor: ...
def ComplexOp(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def CompositeOp(inputs: Tensor, composite_attributes: Tensor, version: Tensor, *, name: Tensor, decomposition: Tensor, composite_regions: Tensor) -> Tensor: ...
def ConcatenateOp(inputs: Tensor, *, dimension: Tensor) -> Tensor: ...
def ConstantOp(*, value: Tensor) -> Tensor: ...
def ConvertOp(operand: Tensor) -> Tensor: ...
def ConvolutionOp(lhs: Tensor, rhs: Tensor, *, window_strides: Tensor, padding: Tensor, lhs_dilation: Tensor, rhs_dilation: Tensor, window_reversal: Tensor, dimension_numbers: Tensor, feature_group_count: Tensor, batch_group_count: Tensor, precision_config: Tensor) -> Tensor: ...
def CosineOp(operand: Tensor, result_accuracy: Tensor) -> Tensor: ...
def CreateTokenOp(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def CrossReplicaSumOp(operand: Tensor, *, replica_groups: Tensor) -> Tensor: ...
def CustomCallOp(inputs: Tensor, has_side_effect: Tensor, called_computations: Tensor, output_operand_aliases: Tensor, *, call_target_name: Tensor, backend_config: Tensor, operand_layouts: Tensor, result_layouts: Tensor, result_tilings: Tensor) -> Tensor: ...
def DivOp(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def DotGeneralOp(lhs: Tensor, rhs: Tensor, *, dot_dimension_numbers: Tensor, precision_config: Tensor, algorithm: Tensor) -> Tensor: ...
def DotOp(lhs: Tensor, rhs: Tensor, *, precision_config: Tensor) -> Tensor: ...
def DynamicBroadcastInDimOp(operand: Tensor, output_dimensions: Tensor, *, broadcast_dimensions: Tensor, known_expanding_dimensions: Tensor, known_nonexpanding_dimensions: Tensor) -> Tensor: ...
def DynamicConvOp(lhs: Tensor, rhs: Tensor, padding: Tensor, *, window_strides: Tensor, lhs_dilation: Tensor, rhs_dilation: Tensor, window_reversal: Tensor, dimension_numbers: Tensor, feature_group_count: Tensor, batch_group_count: Tensor, precision_config: Tensor) -> Tensor: ...
def DynamicGatherOp(operand: Tensor, start_indices: Tensor, slice_sizes: Tensor, indices_are_sorted: Tensor, *, dimension_numbers: Tensor) -> Tensor: ...
def DynamicIotaOp(output_shape: Tensor, *, iota_dimension: Tensor) -> Tensor: ...
def DynamicPadOp(operand: Tensor, padding_value: Tensor, edge_padding_low: Tensor, edge_padding_high: Tensor, interior_padding: Tensor) -> Tensor: ...
def DynamicReshapeOp(operand: Tensor, output_shape: Tensor) -> Tensor: ...
def DynamicSliceOp(operand: Tensor, start_indices: Tensor, *, slice_sizes: Tensor) -> Tensor: ...
def DynamicUpdateSliceOp(operand: Tensor, update: Tensor, start_indices: Tensor) -> Tensor: ...
def EinsumOp(lhs: Tensor, rhs: Tensor, *, einsum_config: Tensor) -> Tensor: ...
def ExpOp(operand: Tensor, result_accuracy: Tensor) -> Tensor: ...
def Expm1Op(operand: Tensor, result_accuracy: Tensor) -> Tensor: ...
def FftOp(operand: Tensor, *, fft_type: Tensor, fft_length: Tensor) -> Tensor: ...
def FloorOp(operand: Tensor) -> Tensor: ...
def GatherOp(operand: Tensor, start_indices: Tensor, indices_are_sorted: Tensor, *, dimension_numbers: Tensor, slice_sizes: Tensor) -> Tensor: ...
def GetDimensionSizeOp(operand: Tensor, *, dimension: Tensor) -> Tensor: ...
def GetTupleElementOp(operand: Tensor, *, index: Tensor) -> Tensor: ...
def IfOp(pred: Tensor, *, true_branch: Tensor, false_branch: Tensor) -> Tensor: ...
def ImagOp(operand: Tensor) -> Tensor: ...
def InfeedOp(token: Tensor, infeed_config: Tensor, *, layout: Tensor) -> Tensor: ...
def IotaOp(*, iota_dimension: Tensor) -> Tensor: ...
def IsFiniteOp(x: Tensor) -> Tensor: ...
def Log1pOp(operand: Tensor, result_accuracy: Tensor) -> Tensor: ...
def LogOp(operand: Tensor, result_accuracy: Tensor) -> Tensor: ...
def LogisticOp(operand: Tensor, result_accuracy: Tensor) -> Tensor: ...
def MapOp(inputs: Tensor, *, dimensions: Tensor, computation: Tensor) -> Tensor: ...
def MaxOp(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def MinOp(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def MulOp(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def NegOp(operand: Tensor) -> Tensor: ...
def NotOp(operand: Tensor) -> Tensor: ...
def OptimizationBarrierOp(operand: Tensor) -> Tensor: ...
def OrOp(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def OutfeedOp(inputs: Tensor, token: Tensor, outfeed_config: Tensor) -> Tensor: ...
def PadOp(operand: Tensor, padding_value: Tensor, *, edge_padding_low: Tensor, edge_padding_high: Tensor, interior_padding: Tensor) -> Tensor: ...
def PartitionIdOp(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def PopulationCountOp(operand: Tensor) -> Tensor: ...
def PowOp(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def RealDynamicSliceOp(operand: Tensor, start_indices: Tensor, limit_indices: Tensor, strides: Tensor) -> Tensor: ...
def RealOp(operand: Tensor) -> Tensor: ...
def RecvOp(token: Tensor, channel_handle: Tensor, is_host_transfer: Tensor, *, source_target_pairs: Tensor) -> Tensor: ...
def ReduceOp(inputs: Tensor, init_values: Tensor, *, dimensions: Tensor, body: Tensor) -> Tensor: ...
def ReducePrecisionOp(operand: Tensor, *, exponent_bits: Tensor, mantissa_bits: Tensor) -> Tensor: ...
def ReduceScatterOp(operand: Tensor, replica_groups: Tensor, *, scatter_dimension: Tensor, channel_handle: Tensor, use_global_device_ids: Tensor, computation: Tensor) -> Tensor: ...
def ReduceWindowOp(inputs: Tensor, init_values: Tensor, *, window_dimensions: Tensor, window_strides: Tensor, base_dilations: Tensor, window_dilations: Tensor, padding: Tensor, body: Tensor) -> Tensor: ...
def RemOp(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def ReplicaIdOp(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ReshapeOp(operand: Tensor) -> Tensor: ...
def ReturnOp(results: Tensor) -> Tensor: ...
def ReverseOp(operand: Tensor, *, dimensions: Tensor) -> Tensor: ...
def RngBitGeneratorOp(initial_state: Tensor, *, rng_algorithm: Tensor) -> Tensor: ...
def RngOp(a: Tensor, b: Tensor, shape: Tensor, *, rng_distribution: Tensor) -> Tensor: ...
def RoundNearestEvenOp(operand: Tensor) -> Tensor: ...
def RoundOp(operand: Tensor) -> Tensor: ...
def RsqrtOp(operand: Tensor, result_accuracy: Tensor) -> Tensor: ...
def ScatterOp(inputs: Tensor, scatter_indices: Tensor, updates: Tensor, indices_are_sorted: Tensor, unique_indices: Tensor, *, scatter_dimension_numbers: Tensor, update_computation: Tensor) -> Tensor: ...
def SelectAndScatterOp(operand: Tensor, source: Tensor, init_value: Tensor, *, window_dimensions: Tensor, window_strides: Tensor, padding: Tensor, select: Tensor, scatter: Tensor) -> Tensor: ...
def SelectOp(pred: Tensor, on_true: Tensor, on_false: Tensor) -> Tensor: ...
def SendOp(inputs: Tensor, token: Tensor, channel_handle: Tensor, is_host_transfer: Tensor, *, source_target_pairs: Tensor) -> Tensor: ...
def SetDimensionSizeOp(operand: Tensor, size: Tensor, *, dimension: Tensor) -> Tensor: ...
def ShiftLeftOp(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def ShiftRightArithmeticOp(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def ShiftRightLogicalOp(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def SignOp(operand: Tensor) -> Tensor: ...
def SineOp(operand: Tensor, result_accuracy: Tensor) -> Tensor: ...
def SliceOp(operand: Tensor, *, start_indices: Tensor, limit_indices: Tensor, strides: Tensor) -> Tensor: ...
def SortOp(inputs: Tensor, dimension: Tensor, is_stable: Tensor, *, comparator: Tensor) -> Tensor: ...
def SqrtOp(operand: Tensor, result_accuracy: Tensor) -> Tensor: ...
def SubtractOp(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def TanOp(operand: Tensor, result_accuracy: Tensor) -> Tensor: ...
def TanhOp(operand: Tensor, result_accuracy: Tensor) -> Tensor: ...
def TorchIndexSelectOp(operand: Tensor, index: Tensor, *, dim: Tensor, batch_dims: Tensor) -> Tensor: ...
def TransposeOp(operand: Tensor, *, permutation: Tensor) -> Tensor: ...
def TriangularSolveOp(a: Tensor, b: Tensor, *, left_side: Tensor, lower: Tensor, unit_diagonal: Tensor, transpose_a: Tensor) -> Tensor: ...
def TupleOp(val: Tensor) -> Tensor: ...
def UnaryEinsumOp(operand: Tensor, *, einsum_config: Tensor) -> Tensor: ...
def UniformDequantizeOp(operand: Tensor) -> Tensor: ...
def UniformQuantizeOp(operand: Tensor) -> Tensor: ...
def WhileOp(operand: Tensor, *, cond: Tensor, body: Tensor) -> Tensor: ...
def XorOp(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
