"""Auto-generated high-fidelity type stubs for pyarrow_compute from ml-framework-snapshots."""
# ruff: noqa: E501, UP007, UP045, D100, D101, D102, D103

from collections.abc import Sequence

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    device: str
    ndim: int
    size: int
    def __init__(self, data: object = ..., shape: Sequence[int] | None = ..., dtype: str | None = ...) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: object) -> Tensor: ...
    def __add__(self, other: Tensor | float | int) -> Tensor: ...
    def __sub__(self, other: Tensor | float | int) -> Tensor: ...
    def __mul__(self, other: Tensor | float | int) -> Tensor: ...
    def __truediv__(self, other: Tensor | float | int) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def numpy(self) -> object: ...
    def to(self, device: str) -> Tensor: ...
    def reshape(self, shape: Sequence[int]) -> Tensor: ...
    def transpose(self, axes: Sequence[int] | None = ...) -> Tensor: ...

def abs(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def add(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def cast(arr: Tensor, target_type: Tensor = ..., safe: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def cos(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def divide(dividend: Tensor, divisor: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def equal(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def exp(exponent: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def filter(input: Tensor, selection_filter: Tensor, null_selection_behavior: Tensor = ..., *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def greater(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def greater_equal(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def less(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def less_equal(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def ln(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def log10(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def log2(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def max(array: Tensor, *, skip_nulls: Tensor = ..., min_count: int = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def mean(array: Tensor, *, skip_nulls: Tensor = ..., min_count: int = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def min(array: Tensor, *, skip_nulls: Tensor = ..., min_count: int = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def multiply(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def not_equal(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def sin(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def sort_indices(input: Tensor, sort_keys: str = ..., *, null_placement: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def sqrt(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def stddev(array: Tensor, *, ddof: Tensor = ..., skip_nulls: Tensor = ..., min_count: int = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def subtract(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def sum(array: Tensor, *, skip_nulls: Tensor = ..., min_count: int = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def take(data: Tensor, indices: Tensor, *, boundscheck: bool = ..., memory_pool: Tensor = ...) -> Tensor: ...
def variance(array: Tensor, *, ddof: Tensor = ..., skip_nulls: Tensor = ..., min_count: int = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
