"""Auto-generated high-fidelity type stubs for pyarrow_compute from live module introspection."""
# ruff: noqa: E501

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    def __init__(self, *args: object, **kwargs: object) -> None: ...

def ArraySortOptions(order: Tensor = ..., *, null_placement: Tensor = ...) -> Tensor: ...
def AssumeTimezoneOptions(timezone: Tensor, *, ambiguous: Tensor = ..., nonexistent: Tensor = ...) -> Tensor: ...
def CastOptions(target_type: Tensor = ..., *, allow_int_overflow: Tensor = ..., allow_time_truncate: Tensor = ..., allow_time_overflow: Tensor = ..., allow_decimal_truncate: Tensor = ..., allow_float_truncate: Tensor = ..., allow_invalid_utf8: Tensor = ...) -> Tensor: ...
def CountOptions(mode: Tensor = ...) -> Tensor: ...
def CumulativeOptions(start: Tensor = ..., *, skip_nulls: Tensor = ...) -> Tensor: ...
def CumulativeSumOptions(start: Tensor = ..., *, skip_nulls: Tensor = ...) -> Tensor: ...
def DayOfWeekOptions(*, count_from_zero: Tensor = ..., week_start: Tensor = ...) -> Tensor: ...
def DictionaryEncodeOptions(null_encoding: Tensor = ...) -> Tensor: ...
def ElementWiseAggregateOptions(*, skip_nulls: Tensor = ...) -> Tensor: ...
def Expression(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ExtractRegexOptions(pattern: Tensor) -> Tensor: ...
def ExtractRegexSpanOptions(pattern: Tensor) -> Tensor: ...
def FilterOptions(null_selection_behavior: Tensor = ...) -> Tensor: ...
def Function(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def FunctionOptions(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def FunctionRegistry(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def HashAggregateFunction(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def HashAggregateKernel(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def IndexOptions(value: Tensor) -> Tensor: ...
def JoinOptions(null_handling: Tensor = ..., null_replacement: Tensor = ...) -> Tensor: ...
def Kernel(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ListFlattenOptions(recursive: Tensor = ...) -> Tensor: ...
def ListSliceOptions(start: Tensor, stop: Tensor = ..., step: Tensor = ..., return_fixed_size_list: Tensor = ...) -> Tensor: ...
def MakeStructOptions(field_names: Tensor = ..., *, field_nullability: Tensor = ..., field_metadata: Tensor = ...) -> Tensor: ...
def MapLookupOptions(query_key: Tensor, occurrence: Tensor) -> Tensor: ...
def MatchSubstringOptions(pattern: Tensor, *, ignore_case: Tensor = ...) -> Tensor: ...
def ModeOptions(n: Tensor = ..., *, skip_nulls: Tensor = ..., min_count: Tensor = ...) -> Tensor: ...
def NullOptions(*, nan_is_null: Tensor = ...) -> Tensor: ...
def PadOptions(width: Tensor, padding: Tensor = ..., lean_left_on_odd_padding: Tensor = ...) -> Tensor: ...
def PairwiseOptions(period: Tensor = ...) -> Tensor: ...
def PartitionNthOptions(pivot: Tensor, *, null_placement: Tensor = ...) -> Tensor: ...
def PivotWiderOptions(key_names: Tensor, *, unexpected_key_behavior: Tensor = ...) -> Tensor: ...
def QuantileOptions(q: Tensor = ..., *, interpolation: Tensor = ..., skip_nulls: Tensor = ..., min_count: Tensor = ...) -> Tensor: ...
def RandomOptions(*, initializer: Tensor = ...) -> Tensor: ...
def RankOptions(sort_keys: Tensor = ..., *, null_placement: Tensor = ..., tiebreaker: Tensor = ...) -> Tensor: ...
def RankQuantileOptions(sort_keys: Tensor = ..., *, null_placement: Tensor = ...) -> Tensor: ...
def ReplaceSliceOptions(start: Tensor, stop: Tensor, replacement: Tensor) -> Tensor: ...
def ReplaceSubstringOptions(pattern: Tensor, replacement: Tensor, *, max_replacements: Tensor = ...) -> Tensor: ...
def RoundBinaryOptions(round_mode: Tensor = ...) -> Tensor: ...
def RoundOptions(ndigits: Tensor = ..., round_mode: Tensor = ...) -> Tensor: ...
def RoundTemporalOptions(multiple: Tensor = ..., unit: Tensor = ..., *, week_starts_monday: Tensor = ..., ceil_is_strictly_greater: Tensor = ..., calendar_based_origin: Tensor = ...) -> Tensor: ...
def RoundToMultipleOptions(multiple: Tensor = ..., round_mode: Tensor = ...) -> Tensor: ...
def RunEndEncodeOptions(run_end_type: Tensor = ...) -> Tensor: ...
def ScalarAggregateFunction(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ScalarAggregateKernel(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ScalarAggregateOptions(*, skip_nulls: Tensor = ..., min_count: Tensor = ...) -> Tensor: ...
def ScalarFunction(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ScalarKernel(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def SelectKOptions(k: Tensor, sort_keys: Tensor) -> Tensor: ...
def SetLookupOptions(value_set: Tensor, *, skip_nulls: Tensor = ...) -> Tensor: ...
def SkewOptions(*, skip_nulls: Tensor = ..., biased: Tensor = ..., min_count: Tensor = ...) -> Tensor: ...
def SliceOptions(start: Tensor, stop: Tensor = ..., step: Tensor = ...) -> Tensor: ...
def SortOptions(sort_keys: Tensor = ..., *, null_placement: Tensor = ...) -> Tensor: ...
def SplitOptions(*, max_splits: Tensor = ..., reverse: Tensor = ...) -> Tensor: ...
def SplitPatternOptions(pattern: Tensor, *, max_splits: Tensor = ..., reverse: Tensor = ...) -> Tensor: ...
def StrftimeOptions(format: Tensor = ..., locale: Tensor = ...) -> Tensor: ...
def StrptimeOptions(format: Tensor, unit: Tensor, error_is_null: Tensor = ...) -> Tensor: ...
def StructFieldOptions(indices: Tensor) -> Tensor: ...
def TDigestOptions(q: Tensor = ..., *, delta: Tensor = ..., buffer_size: Tensor = ..., skip_nulls: Tensor = ..., min_count: Tensor = ...) -> Tensor: ...
def TakeOptions(*, boundscheck: Tensor = ...) -> Tensor: ...
def TrimOptions(characters: Tensor) -> Tensor: ...
def UdfContext(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def Utf8NormalizeOptions(form: Tensor) -> Tensor: ...
def VarianceOptions(*, ddof: Tensor = ..., skip_nulls: Tensor = ..., min_count: Tensor = ...) -> Tensor: ...
def VectorFunction(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def VectorKernel(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def WeekOptions(*, week_starts_monday: Tensor = ..., count_from_zero: Tensor = ..., first_week_is_fully_in_year: Tensor = ...) -> Tensor: ...
def WinsorizeOptions(lower_limit: Tensor, upper_limit: Tensor) -> Tensor: ...
def ZeroFillOptions(width: Tensor, padding: Tensor = ...) -> Tensor: ...
def abs(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def abs_checked(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def acos(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def acos_checked(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def acosh(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def acosh_checked(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def add(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def add_checked(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def all(array: Tensor, *, skip_nulls: Tensor = ..., min_count: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def and_(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def and_kleene(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def and_not(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def and_not_kleene(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def any(array: Tensor, *, skip_nulls: Tensor = ..., min_count: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def approximate_median(array: Tensor, *, skip_nulls: Tensor = ..., min_count: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def array_filter(array: Tensor, selection_filter: Tensor, null_selection_behavior: Tensor = ..., *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def array_sort_indices(array: Tensor, order: Tensor = ..., *, null_placement: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def array_take(array: Tensor, indices: Tensor, *, boundscheck: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def ascii_capitalize(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def ascii_center(strings: Tensor, width: Tensor, padding: Tensor = ..., lean_left_on_odd_padding: Tensor = ..., *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def ascii_is_alnum(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def ascii_is_alpha(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def ascii_is_decimal(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def ascii_is_lower(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def ascii_is_printable(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def ascii_is_space(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def ascii_is_title(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def ascii_is_upper(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def ascii_lower(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def ascii_lpad(strings: Tensor, width: Tensor, padding: Tensor = ..., lean_left_on_odd_padding: Tensor = ..., *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def ascii_ltrim(strings: Tensor, characters: Tensor, *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def ascii_ltrim_whitespace(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def ascii_reverse(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def ascii_rpad(strings: Tensor, width: Tensor, padding: Tensor = ..., lean_left_on_odd_padding: Tensor = ..., *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def ascii_rtrim(strings: Tensor, characters: Tensor, *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def ascii_rtrim_whitespace(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def ascii_split_whitespace(strings: Tensor, *, max_splits: Tensor = ..., reverse: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def ascii_swapcase(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def ascii_title(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def ascii_trim(strings: Tensor, characters: Tensor, *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def ascii_trim_whitespace(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def ascii_upper(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def asin(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def asin_checked(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def asinh(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def assume_timezone(timestamps: Tensor, timezone: Tensor, *, ambiguous: Tensor = ..., nonexistent: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def atan(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def atan2(y: Tensor, x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def atanh(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def atanh_checked(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def binary_join(strings: Tensor, separator: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def binary_join_element_wise(*strings: Tensor, null_handling: Tensor = ..., null_replacement: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def binary_length(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def binary_repeat(strings: Tensor, num_repeats: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def binary_replace_slice(strings: Tensor, start: Tensor, stop: Tensor, replacement: Tensor, *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def binary_reverse(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def binary_slice(strings: Tensor, start: Tensor, stop: Tensor = ..., step: Tensor = ..., *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def bit_wise_and(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def bit_wise_not(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def bit_wise_or(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def bit_wise_xor(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def bottom_k_unstable(values: Tensor, k: Tensor, sort_keys: Tensor = ..., *, memory_pool: Tensor = ...) -> Tensor: ...
def call_function(name: Tensor, args: Tensor, options: Tensor = ..., memory_pool: Tensor = ..., length: Tensor = ...) -> Tensor: ...
def call_tabular_function(function_name: Tensor, args: Tensor = ..., func_registry: Tensor = ...) -> Tensor: ...
def case_when(cond: Tensor, *cases: Tensor, memory_pool: Tensor = ...) -> Tensor: ...
def cast(arr: Tensor, target_type: Tensor = ..., safe: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def ceil(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def ceil_temporal(timestamps: Tensor, multiple: Tensor = ..., unit: Tensor = ..., *, week_starts_monday: Tensor = ..., ceil_is_strictly_greater: Tensor = ..., calendar_based_origin: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def choose(indices: Tensor, *values: Tensor, memory_pool: Tensor = ...) -> Tensor: ...
def coalesce(*values: Tensor, memory_pool: Tensor = ...) -> Tensor: ...
def cos(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def cos_checked(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def cosh(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def count(array: Tensor, mode: Tensor = ..., *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def count_distinct(array: Tensor, mode: Tensor = ..., *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def count_substring(strings: Tensor, pattern: Tensor, *, ignore_case: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def count_substring_regex(strings: Tensor, pattern: Tensor, *, ignore_case: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def cumulative_max(values: Tensor, start: Tensor = ..., *, skip_nulls: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def cumulative_mean(values: Tensor, start: Tensor = ..., *, skip_nulls: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def cumulative_min(values: Tensor, start: Tensor = ..., *, skip_nulls: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def cumulative_prod(values: Tensor, start: Tensor = ..., *, skip_nulls: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def cumulative_prod_checked(values: Tensor, start: Tensor = ..., *, skip_nulls: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def cumulative_sum(values: Tensor, start: Tensor = ..., *, skip_nulls: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def cumulative_sum_checked(values: Tensor, start: Tensor = ..., *, skip_nulls: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def day(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def day_of_week(values: Tensor, *, count_from_zero: Tensor = ..., week_start: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def day_of_year(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def day_time_interval_between(start: Tensor, end: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def days_between(start: Tensor, end: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def dedent(text: Tensor) -> Tensor: ...
def dictionary_decode(dictionary_array: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def dictionary_encode(array: Tensor, null_encoding: Tensor = ..., *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def divide(dividend: Tensor, divisor: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def divide_checked(dividend: Tensor, divisor: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def drop_null(input: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def ends_with(strings: Tensor, pattern: Tensor, *, ignore_case: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def equal(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def exp(exponent: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def expm1(exponent: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def extract_regex(strings: Tensor, pattern: Tensor, *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def extract_regex_span(strings: Tensor, pattern: Tensor, *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def field(*name_or_index: Tensor) -> Tensor: ...
def fill_null(values: Tensor, fill_value: Tensor) -> Tensor: ...
def fill_null_backward(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def fill_null_forward(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def filter(input: Tensor, selection_filter: Tensor, null_selection_behavior: Tensor = ..., *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def find_substring(strings: Tensor, pattern: Tensor, *, ignore_case: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def find_substring_regex(strings: Tensor, pattern: Tensor, *, ignore_case: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def first(array: Tensor, *, skip_nulls: Tensor = ..., min_count: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def first_last(array: Tensor, *, skip_nulls: Tensor = ..., min_count: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def floor(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def floor_temporal(timestamps: Tensor, multiple: Tensor = ..., unit: Tensor = ..., *, week_starts_monday: Tensor = ..., ceil_is_strictly_greater: Tensor = ..., calendar_based_origin: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def function_registry() -> Tensor: ...
def get_function(name: Tensor) -> Tensor: ...
def greater(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def greater_equal(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def hour(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def hours_between(start: Tensor, end: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def if_else(cond: Tensor, left: Tensor, right: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def index(data: Tensor, value: Tensor, start: Tensor = ..., end: Tensor = ..., *, memory_pool: Tensor = ...) -> Tensor: ...
def index_in(values: Tensor, value_set: Tensor, *, skip_nulls: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def index_in_meta_binary(values: Tensor, value_set: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def indices_nonzero(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def inverse_permutation(indices: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def invert(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def is_dst(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def is_finite(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def is_in(values: Tensor, value_set: Tensor, *, skip_nulls: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def is_in_meta_binary(values: Tensor, value_set: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def is_inf(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def is_leap_year(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def is_nan(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def is_null(values: Tensor, *, nan_is_null: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def is_valid(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def iso_calendar(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def iso_week(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def iso_year(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def kurtosis(array: Tensor, *, skip_nulls: Tensor = ..., biased: Tensor = ..., min_count: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def last(array: Tensor, *, skip_nulls: Tensor = ..., min_count: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def less(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def less_equal(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def list_element(lists: Tensor, index: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def list_flatten(lists: Tensor, recursive: Tensor = ..., *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def list_functions() -> Tensor: ...
def list_parent_indices(lists: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def list_slice(lists: Tensor, start: Tensor, stop: Tensor = ..., step: Tensor = ..., return_fixed_size_list: Tensor = ..., *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def list_value_length(lists: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def ln(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def ln_checked(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def local_timestamp(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def log10(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def log10_checked(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def log1p(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def log1p_checked(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def log2(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def log2_checked(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def logb(x: Tensor, b: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def logb_checked(x: Tensor, b: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def make_struct(*args: Tensor, field_names: Tensor = ..., field_nullability: Tensor = ..., field_metadata: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def map_lookup(container: Tensor, query_key: Tensor, occurrence: Tensor, *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def match_like(strings: Tensor, pattern: Tensor, *, ignore_case: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def match_substring(strings: Tensor, pattern: Tensor, *, ignore_case: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def match_substring_regex(strings: Tensor, pattern: Tensor, *, ignore_case: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def max(array: Tensor, *, skip_nulls: Tensor = ..., min_count: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def max_element_wise(*args: Tensor, skip_nulls: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def mean(array: Tensor, *, skip_nulls: Tensor = ..., min_count: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def microsecond(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def microseconds_between(start: Tensor, end: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def millisecond(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def milliseconds_between(start: Tensor, end: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def min(array: Tensor, *, skip_nulls: Tensor = ..., min_count: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def min_element_wise(*args: Tensor, skip_nulls: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def min_max(array: Tensor, *, skip_nulls: Tensor = ..., min_count: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def minute(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def minutes_between(start: Tensor, end: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def mode(array: Tensor, n: Tensor = ..., *, skip_nulls: Tensor = ..., min_count: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def month(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def month_day_nano_interval_between(start: Tensor, end: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def month_interval_between(start: Tensor, end: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def multiply(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def multiply_checked(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def namedtuple(typename: Tensor, field_names: Tensor, *, rename: Tensor = ..., defaults: Tensor = ..., module: Tensor = ...) -> Tensor: ...
def nanosecond(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def nanoseconds_between(start: Tensor, end: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def negate(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def negate_checked(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def not_equal(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def or_(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def or_kleene(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def pairwise_diff(input: Tensor, period: Tensor = ..., *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def pairwise_diff_checked(input: Tensor, period: Tensor = ..., *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def partition_nth_indices(array: Tensor, pivot: Tensor, *, null_placement: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def pivot_wider(pivot_keys: Tensor, pivot_values: Tensor, key_names: Tensor, *, unexpected_key_behavior: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def power(base: Tensor, exponent: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def power_checked(base: Tensor, exponent: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def product(array: Tensor, *, skip_nulls: Tensor = ..., min_count: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def quantile(array: Tensor, q: Tensor = ..., *, interpolation: Tensor = ..., skip_nulls: Tensor = ..., min_count: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def quarter(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def quarters_between(start: Tensor, end: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def random(n: Tensor, *, initializer: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def rank(input: Tensor, sort_keys: Tensor = ..., *, null_placement: Tensor = ..., tiebreaker: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def rank_normal(input: Tensor, sort_keys: Tensor = ..., *, null_placement: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def rank_quantile(input: Tensor, sort_keys: Tensor = ..., *, null_placement: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def register_aggregate_function(func: Tensor, function_name: Tensor, function_doc: Tensor, in_types: Tensor, out_type: Tensor, func_registry: Tensor = ...) -> Tensor: ...
def register_scalar_function(func: Tensor, function_name: Tensor, function_doc: Tensor, in_types: Tensor, out_type: Tensor, func_registry: Tensor = ...) -> Tensor: ...
def register_tabular_function(func: Tensor, function_name: Tensor, function_doc: Tensor, in_types: Tensor, out_type: Tensor, func_registry: Tensor = ...) -> Tensor: ...
def register_vector_function(func: Tensor, function_name: Tensor, function_doc: Tensor, in_types: Tensor, out_type: Tensor, func_registry: Tensor = ...) -> Tensor: ...
def replace_substring(strings: Tensor, pattern: Tensor, replacement: Tensor, *, max_replacements: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def replace_substring_regex(strings: Tensor, pattern: Tensor, replacement: Tensor, *, max_replacements: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def replace_with_mask(values: Tensor, mask: Tensor, replacements: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def round(x: Tensor, ndigits: Tensor = ..., round_mode: Tensor = ..., *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def round_binary(x: Tensor, s: Tensor, round_mode: Tensor = ..., *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def round_temporal(timestamps: Tensor, multiple: Tensor = ..., unit: Tensor = ..., *, week_starts_monday: Tensor = ..., ceil_is_strictly_greater: Tensor = ..., calendar_based_origin: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def round_to_multiple(x: Tensor, multiple: Tensor = ..., round_mode: Tensor = ..., *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def run_end_decode(array: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def run_end_encode(array: Tensor, run_end_type: Tensor = ..., *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def scalar(value: Tensor) -> Tensor: ...
def scatter(values: Tensor, indices: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def second(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def seconds_between(start: Tensor, end: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def select_k_unstable(input: Tensor, k: Tensor, sort_keys: Tensor, *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def shift_left(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def shift_left_checked(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def shift_right(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def shift_right_checked(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def sign(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def sin(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def sin_checked(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def sinh(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def skew(array: Tensor, *, skip_nulls: Tensor = ..., biased: Tensor = ..., min_count: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def sort_indices(input: Tensor, sort_keys: Tensor = ..., *, null_placement: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def split_pattern(strings: Tensor, pattern: Tensor, *, max_splits: Tensor = ..., reverse: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def split_pattern_regex(strings: Tensor, pattern: Tensor, *, max_splits: Tensor = ..., reverse: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def sqrt(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def sqrt_checked(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def starts_with(strings: Tensor, pattern: Tensor, *, ignore_case: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def stddev(array: Tensor, *, ddof: Tensor = ..., skip_nulls: Tensor = ..., min_count: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def strftime(timestamps: Tensor, format: Tensor = ..., locale: Tensor = ..., *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def string_is_ascii(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def strptime(strings: Tensor, format: Tensor, unit: Tensor, error_is_null: Tensor = ..., *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def struct_field(values: Tensor, indices: Tensor, *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def subsecond(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def subtract(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def subtract_checked(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def sum(array: Tensor, *, skip_nulls: Tensor = ..., min_count: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def take(data: Tensor, indices: Tensor, *, boundscheck: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def tan(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def tan_checked(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def tanh(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def tdigest(array: Tensor, q: Tensor = ..., *, delta: Tensor = ..., buffer_size: Tensor = ..., skip_nulls: Tensor = ..., min_count: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def top_k_unstable(values: Tensor, k: Tensor, sort_keys: Tensor = ..., *, memory_pool: Tensor = ...) -> Tensor: ...
def true_unless_null(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def trunc(x: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def unique(array: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def us_week(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def us_year(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def utf8_capitalize(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def utf8_center(strings: Tensor, width: Tensor, padding: Tensor = ..., lean_left_on_odd_padding: Tensor = ..., *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def utf8_is_alnum(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def utf8_is_alpha(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def utf8_is_decimal(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def utf8_is_digit(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def utf8_is_lower(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def utf8_is_numeric(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def utf8_is_printable(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def utf8_is_space(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def utf8_is_title(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def utf8_is_upper(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def utf8_length(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def utf8_lower(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def utf8_lpad(strings: Tensor, width: Tensor, padding: Tensor = ..., lean_left_on_odd_padding: Tensor = ..., *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def utf8_ltrim(strings: Tensor, characters: Tensor, *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def utf8_ltrim_whitespace(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def utf8_normalize(strings: Tensor, form: Tensor, *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def utf8_replace_slice(strings: Tensor, start: Tensor, stop: Tensor, replacement: Tensor, *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def utf8_reverse(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def utf8_rpad(strings: Tensor, width: Tensor, padding: Tensor = ..., lean_left_on_odd_padding: Tensor = ..., *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def utf8_rtrim(strings: Tensor, characters: Tensor, *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def utf8_rtrim_whitespace(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def utf8_slice_codeunits(strings: Tensor, start: Tensor, stop: Tensor = ..., step: Tensor = ..., *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def utf8_split_whitespace(strings: Tensor, *, max_splits: Tensor = ..., reverse: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def utf8_swapcase(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def utf8_title(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def utf8_trim(strings: Tensor, characters: Tensor, *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def utf8_trim_whitespace(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def utf8_upper(strings: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def utf8_zero_fill(strings: Tensor, width: Tensor, padding: Tensor = ..., *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def utf8_zfill(strings: Tensor, width: Tensor, padding: Tensor = ..., *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def value_counts(array: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def variance(array: Tensor, *, ddof: Tensor = ..., skip_nulls: Tensor = ..., min_count: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def week(values: Tensor, *, week_starts_monday: Tensor = ..., count_from_zero: Tensor = ..., first_week_is_fully_in_year: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def weeks_between(start: Tensor, end: Tensor, *, count_from_zero: Tensor = ..., week_start: Tensor = ..., options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def winsorize(array: Tensor, lower_limit: Tensor, upper_limit: Tensor, *, options: Tensor = ..., memory_pool: Tensor = ...) -> Tensor: ...
def xor(x: Tensor, y: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def year(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def year_month_day(values: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def years_between(start: Tensor, end: Tensor, *, memory_pool: Tensor = ...) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
