# pylint: disable=too-many-lines
"""Auto-generated ml_switcheroo_compiler.ops.vision module exports."""

from ml_switcheroo_compiler.ops.vision.affine import (
    DType,
    Tensor,
    TensorConfig,
    affine_generator,
    affine_transform,
    annotations,
    config,
    random_crop,
    random_elastic_transform,
    random_flip,
    random_perspective,
    random_rotation,
    random_shear,
    random_translation,
    random_zoom,
)
from ml_switcheroo_compiler.ops.vision.bbox import (
    crop,
    crop_and_resize,
    extract_bounding_boxes,
    pad_to_bounding_box,
)
from ml_switcheroo_compiler.ops.vision.color import (
    adjust_brightness,
    adjust_contrast,
    adjust_hue,
    adjust_saturation,
    augmix,
    auto_contrast,
    degeneration,
    equalization,
    hsv_to_rgb,
    invert,
    posterize,
    rand_augment,
    random_color_jitter,
    random_erasing,
    rgb_to_grayscale,
    rgb_to_hsv,
    solarize,
)
from ml_switcheroo_compiler.ops.vision.filtering import (
    gaussian_blur,
    iou,
    median_filter,
    non_max_suppression,
    random_gaussian_blur,
    random_sharpness,
    sharpen,
)
from ml_switcheroo_compiler.ops.vision.interpolation import (
    resize_bicubic,
    resize_bilinear,
    resize_lanczos3,
    resize_nearest,
)
from ml_switcheroo_compiler.ops.vision.mixing import (
    cutmix,
    mixup,
)
from ml_switcheroo_compiler.ops.vision.transforms import (
    elastic_transform,
    flip_left_right,
    flip_up_down,
    perspective_transform,
)

__all__ = [
    "DType",
    "Tensor",
    "TensorConfig",
    "adjust_brightness",
    "adjust_contrast",
    "adjust_hue",
    "adjust_saturation",
    "affine_generator",
    "affine_transform",
    "annotations",
    "augmix",
    "auto_contrast",
    "config",
    "crop",
    "crop_and_resize",
    "cutmix",
    "degeneration",
    "elastic_transform",
    "equalization",
    "extract_bounding_boxes",
    "flip_left_right",
    "flip_up_down",
    "gaussian_blur",
    "hsv_to_rgb",
    "invert",
    "iou",
    "median_filter",
    "mixup",
    "non_max_suppression",
    "pad_to_bounding_box",
    "perspective_transform",
    "posterize",
    "rand_augment",
    "random_color_jitter",
    "random_crop",
    "random_elastic_transform",
    "random_erasing",
    "random_flip",
    "random_gaussian_blur",
    "random_perspective",
    "random_rotation",
    "random_sharpness",
    "random_shear",
    "random_translation",
    "random_zoom",
    "resize_bicubic",
    "resize_bilinear",
    "resize_lanczos3",
    "resize_nearest",
    "rgb_to_grayscale",
    "rgb_to_hsv",
    "sharpen",
    "solarize",
]
