"""Auto-generated high-fidelity type stubs for mlx from ml-ecosystem-snapshots."""
# ruff: noqa: E501, UP007, UP045, D100, D101, D102, D103

from collections.abc import Sequence

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    device: str
    ndim: int
    size: int
    def __init__(self, data: object = ..., shape: Sequence[int] | None = ..., dtype: str | None = ...) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: object) -> Tensor: ...
    def __add__(self, other: Tensor | float | int) -> Tensor: ...
    def __sub__(self, other: Tensor | float | int) -> Tensor: ...
    def __mul__(self, other: Tensor | float | int) -> Tensor: ...
    def __truediv__(self, other: Tensor | float | int) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def numpy(self) -> object: ...
    def to(self, device: str) -> Tensor: ...
    def reshape(self, shape: Sequence[int]) -> Tensor: ...
    def transpose(self, axes: Sequence[int] | None = ...) -> Tensor: ...

def elu(x: Tensor, alpha: float = ...) -> Tensor: ...
def gelu(x: Tensor) -> Tensor: ...
def hardswish(x: Tensor) -> Tensor: ...
def leaky_relu(x: Tensor, negative_slope: float = ...) -> Tensor: ...
def log_softmax(x: Tensor, axis: int = ...) -> Tensor: ...
def mish(x: Tensor) -> Tensor: ...
def prelu(x: Tensor, alpha: Tensor) -> Tensor: ...
def relu(x: Tensor) -> Tensor: ...
def selu(x: Tensor) -> Tensor: ...
def sigmoid(x: Tensor) -> Tensor: ...
def silu(x: Tensor) -> Tensor: ...
def softmax(x: Tensor, axis: int = ...) -> Tensor: ...
def softplus(x: Tensor) -> Tensor: ...
def step(x: Tensor, threshold: float = ...) -> Tensor: ...
def tanh(x: Tensor) -> Tensor: ...
def abs(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def add(*args: Tensor, a: Tensor, b: Tensor, **kwargs: Tensor) -> Tensor: ...
def addmm(*args: Tensor, c: Tensor, a: Tensor, b: Tensor, alpha: Tensor = ..., beta: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def all(*args: Tensor, a: Tensor, axis: Tensor, keepdims: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def allclose(*args: Tensor, a: Tensor, b: Tensor, rtol: float, atol: float, equal_nan: bool = ..., **kwargs: Tensor) -> Tensor: ...
def any(*args: Tensor, a: Tensor, axis: Tensor, keepdims: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def arange(*args: Tensor, start: Tensor = ..., stop: Tensor = ..., step: Tensor = ..., dtype: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def arccos(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def arccosh(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def arcsin(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def arcsinh(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def arctan(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def arctan2(*args: Tensor, a: Tensor, b: Tensor, **kwargs: Tensor) -> Tensor: ...
def arctanh(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def argmax(*args: Tensor, a: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def argmin(*args: Tensor, a: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def argpartition(*args: Tensor, a: Tensor, kth: int, axis: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def argsort(*args: Tensor, a: Tensor, axis: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def array_equal(*args: Tensor, a: Tensor, b: Tensor, equal_nan: bool = ..., **kwargs: Tensor) -> Tensor: ...
def as_strided(*args: Tensor, a: Tensor, shape: Tensor = ..., strides: Tensor = ..., offset: int = ..., **kwargs: Tensor) -> Tensor: ...
def asarray(*args: Tensor, a: Tensor, dtype: Tensor, copy: Tensor, **kwargs: Tensor) -> Tensor: ...
def astype(*args: Tensor, a: Tensor, dtype: Tensor, **kwargs: Tensor) -> Tensor: ...
def async_eval(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def atleast_1d(*args: Tensor, arys: Tensor = ..., stream: Tensor, **kwargs: Tensor) -> Tensor: ...
def atleast_2d(*args: Tensor, arys: Tensor = ..., stream: Tensor, **kwargs: Tensor) -> Tensor: ...
def atleast_3d(*args: Tensor, arys: Tensor = ..., stream: Tensor, **kwargs: Tensor) -> Tensor: ...
def bartlett(*args: Tensor, M: int, **kwargs: Tensor) -> Tensor: ...
def bernoulli(p: Tensor = ..., shape: Tensor = ..., key: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def bitwise_and(*args: Tensor, a: Tensor, b: Tensor, **kwargs: Tensor) -> Tensor: ...
def bitwise_invert(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def bitwise_or(*args: Tensor, a: Tensor, b: Tensor, **kwargs: Tensor) -> Tensor: ...
def bitwise_xor(*args: Tensor, a: Tensor, b: Tensor, **kwargs: Tensor) -> Tensor: ...
def blackman(*args: Tensor, M: int, **kwargs: Tensor) -> Tensor: ...
def block_masked_mm(*args: Tensor, a: Tensor, b: Tensor, block_size: int = ..., mask_out: Tensor = ..., mask_lhs: Tensor = ..., mask_rhs: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def broadcast_arrays(*args: Tensor, arrays: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def broadcast_shapes(*args: Tensor, shapes: Sequence[int] = ..., **kwargs: Tensor) -> Tensor: ...
def broadcast_to(*args: Tensor, a: Tensor, shape: Tensor, **kwargs: Tensor) -> Tensor: ...
def can_cast(*args: Tensor, from_: Tensor, to: Tensor, **kwargs: Tensor) -> Tensor: ...
def categorical(logits: Tensor, axis: int = ..., shape: Tensor = ..., num_samples: Tensor = ..., key: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def ceil(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def checkpoint(*args: Tensor, fun: Tensor, **kwargs: Tensor) -> Tensor: ...
def cholesky(a: Tensor, upper: bool = ..., *, stream: Tensor = ...) -> Tensor: ...
def cholesky_inv(a: Tensor, upper: bool = ..., *, stream: Tensor = ...) -> Tensor: ...
def clear_cache(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def clear_streams(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def clip(*args: Tensor, a: Tensor, a_min: Tensor, a_max: Tensor, **kwargs: Tensor) -> Tensor: ...
def compile(*args: Tensor, fun: int, inputs: Tensor = ..., outputs: Tensor = ..., shapeless: int = ..., **kwargs: Tensor) -> Tensor: ...
def concat(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def concatenate(*args: Tensor, arrays: Tensor, axis: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def conj(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def conjugate(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def contiguous(*args: Tensor, a: Tensor, allow_col_major: bool, **kwargs: Tensor) -> Tensor: ...
def conv1d(*args: Tensor, input: Tensor, weight: Tensor, stride: Tensor = ..., padding: Tensor = ..., dilation: Tensor = ..., groups: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def conv2d(*args: Tensor, input: Tensor, weight: Tensor, stride: Tensor = ..., padding: Tensor = ..., dilation: Tensor = ..., groups: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def conv3d(*args: Tensor, input: Tensor, weight: Tensor, stride: Tensor = ..., padding: Tensor = ..., dilation: Tensor = ..., groups: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def conv_general(*args: Tensor, input: Tensor, weight: Tensor, stride: int = ..., **kwargs: Tensor) -> Tensor: ...
def conv_transpose1d(*args: Tensor, input: Tensor, weight: Tensor, stride: Tensor = ..., padding: Tensor = ..., dilation: Tensor = ..., output_padding: Tensor = ..., groups: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def conv_transpose2d(*args: Tensor, input: Tensor, weight: Tensor, stride: Tensor = ..., padding: Tensor = ..., dilation: Tensor = ..., output_padding: Tensor = ..., groups: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def conv_transpose3d(*args: Tensor, input: Tensor, weight: Tensor, stride: Tensor = ..., padding: Tensor = ..., dilation: Tensor = ..., output_padding: Tensor = ..., groups: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def convolve(*args: Tensor, a: Tensor, v: Tensor, mode: Tensor, **kwargs: Tensor) -> Tensor: ...
def cos(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def cosh(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def count_nonzero(*args: Tensor, a: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def cross(a: Tensor, b: Tensor, axis: int = ..., *, stream: Tensor = ...) -> Tensor: ...
def cummax(*args: Tensor, a: Tensor, axis: Tensor, reverse: bool, inclusive: bool, **kwargs: Tensor) -> Tensor: ...
def cummin(*args: Tensor, a: Tensor, axis: Tensor, reverse: bool, inclusive: bool, **kwargs: Tensor) -> Tensor: ...
def cumprod(*args: Tensor, a: Tensor, axis: Tensor, reverse: bool, inclusive: bool, dtype: Tensor, **kwargs: Tensor) -> Tensor: ...
def cumsum(*args: Tensor, a: Tensor, axis: Tensor, reverse: bool, inclusive: bool, dtype: Tensor, **kwargs: Tensor) -> Tensor: ...
def default_device(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def default_stream(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def degrees(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def depends(*args: Tensor, inputs: Tensor, dependencies: Tensor, **kwargs: Tensor) -> Tensor: ...
def dequantize(*args: Tensor, w: Tensor, scales: Tensor, biases: Tensor = ..., group_size: Tensor = ..., bits: Tensor = ..., mode: Tensor = ..., global_scale: Tensor = ..., dtype: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def det(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def device_count(*args: Tensor, device_type: Tensor, **kwargs: Tensor) -> Tensor: ...
def device_info(*args: Tensor, d: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def diag(*args: Tensor, a: Tensor, k: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def diagonal(*args: Tensor, a: Tensor, offset: Tensor = ..., axis1: Tensor = ..., axis2: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def diff(*args: Tensor, a: Tensor, n: Tensor = ..., axis: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def disable_compile(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def divide(*args: Tensor, a: Tensor, b: Tensor, **kwargs: Tensor) -> Tensor: ...
def divmod(*args: Tensor, a: Tensor, b: Tensor, **kwargs: Tensor) -> Tensor: ...
def eig(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def eigh(a: Tensor, UPLO: str = ..., *, stream: Tensor = ...) -> Tensor: ...
def eigvals(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def eigvalsh(a: Tensor, UPLO: str = ..., *, stream: Tensor = ...) -> Tensor: ...
def einsum(*args: Tensor, subscripts: str, operands: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def einsum_path(*args: Tensor, subscripts: str, operands: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def enable_compile(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def equal(*args: Tensor, a: Tensor, b: Tensor, **kwargs: Tensor) -> Tensor: ...
def erf(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def erfinv(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def eval(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def exp(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def expand_dims(*args: Tensor, a: Tensor, axes: Tensor, **kwargs: Tensor) -> Tensor: ...
def expm1(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def export_function(*args: Tensor, file_or_callback: Tensor, fun: Tensor, shapeless: Tensor = ..., metadata: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def export_to_dot(*args: Tensor, file: str, **kwargs: Tensor) -> Tensor: ...
def exporter(*args: Tensor, file: str, shapeless: Tensor = ..., metadata: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def eye(*args: Tensor, n: int, m: int = ..., k: Tensor = ..., dtype: Tensor = ..., stream: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def fft(a: Tensor, n: Tensor = ..., axis: int = ..., norm: str = ..., stream: Tensor = ...) -> Tensor: ...
def fft2(a: Tensor, s: Tensor = ..., axes: Tensor = ..., norm: str = ..., stream: Tensor = ...) -> Tensor: ...
def fftfreq(n: int, d: float = ..., stream: Tensor = ...) -> Tensor: ...
def fftn(a: Tensor, s: Tensor = ..., axes: Tensor = ..., norm: str = ..., stream: Tensor = ...) -> Tensor: ...
def fftshift(a: Tensor, axes: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def flatten(*args: Tensor, a: Tensor, start_axis: Tensor = ..., end_axis: Tensor = ..., stream: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def flip(*args: Tensor, a: Tensor, axis: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def floor(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def floor_divide(*args: Tensor, a: Tensor, b: Tensor, **kwargs: Tensor) -> Tensor: ...
def from_dlpack(*args: Tensor, x: Tensor, copy: Tensor, **kwargs: Tensor) -> Tensor: ...
def from_fp8(*args: Tensor, x: Tensor, dtype: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def full(*args: Tensor, shape: Tensor, vals: Tensor, dtype: Tensor, **kwargs: Tensor) -> Tensor: ...
def full_like(*args: Tensor, a: Tensor, vals: Tensor, dtype: Tensor, **kwargs: Tensor) -> Tensor: ...
def gather_mm(*args: Tensor, a: Tensor, b: Tensor, lhs_indices: Tensor = ..., rhs_indices: Tensor = ..., sorted_indices: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def gather_qmm(*args: Tensor, x: Tensor, w: Tensor, scales: Tensor, biases: Tensor = ..., lhs_indices: Tensor = ..., rhs_indices: Tensor = ..., transpose: bool = ..., group_size: Tensor = ..., bits: Tensor = ..., mode: Tensor = ..., sorted_indices: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def gather_qqmm(
    *args: Tensor, x: Tensor, w: Tensor, scales: Tensor = ..., lhs_indices: Tensor = ..., rhs_indices: Tensor = ..., group_size: Tensor = ..., bits: Tensor = ..., mode: Tensor = ..., global_scale_x: Tensor = ..., global_scale_w: Tensor = ..., sorted_indices: Tensor = ..., **kwargs: Tensor
) -> Tensor: ...
def get_active_memory(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def get_cache_memory(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def get_peak_memory(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def get_printoptions(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def grad(*args: Tensor, fun: int, argnums: Tensor = ..., argnames: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def greater(*args: Tensor, a: Tensor, b: Tensor, **kwargs: Tensor) -> Tensor: ...
def greater_equal(*args: Tensor, a: Tensor, b: Tensor, **kwargs: Tensor) -> Tensor: ...
def gumbel(shape: Sequence[int] = ..., dtype: Tensor = ..., key: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def hadamard_transform(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def hamming(*args: Tensor, M: int, **kwargs: Tensor) -> Tensor: ...
def hanning(*args: Tensor, M: int, **kwargs: Tensor) -> Tensor: ...
def identity(*args: Tensor, n: int, dtype: Tensor = ..., stream: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def ifft(a: Tensor, n: Tensor = ..., axis: int = ..., norm: str = ..., stream: Tensor = ...) -> Tensor: ...
def ifft2(a: Tensor, s: Tensor = ..., axes: Tensor = ..., norm: str = ..., stream: Tensor = ...) -> Tensor: ...
def ifftn(a: Tensor, s: Tensor = ..., axes: Tensor = ..., norm: str = ..., stream: Tensor = ...) -> Tensor: ...
def ifftshift(a: Tensor, axes: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def imag(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def import_function(*args: Tensor, file: str, return_metadata: str = ..., **kwargs: Tensor) -> Tensor: ...
def inner(*args: Tensor, a: Tensor, b: Tensor, **kwargs: Tensor) -> Tensor: ...
def inv(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def irfft(a: Tensor, n: Tensor = ..., axis: int = ..., norm: str = ..., stream: Tensor = ...) -> Tensor: ...
def irfft2(a: Tensor, s: Tensor = ..., axes: Tensor = ..., norm: str = ..., stream: Tensor = ...) -> Tensor: ...
def irfftn(a: Tensor, s: Tensor = ..., axes: Tensor = ..., norm: str = ..., stream: Tensor = ...) -> Tensor: ...
def is_available(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def isclose(*args: Tensor, a: Tensor, b: Tensor, rtol: float, atol: float, equal_nan: bool = ..., **kwargs: Tensor) -> Tensor: ...
def isdtype(*args: Tensor, dtype: Tensor, kind: str, **kwargs: Tensor) -> Tensor: ...
def isfinite(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def isinf(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def isnan(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def isneginf(*args: Tensor, a: Tensor, stream: Tensor, **kwargs: Tensor) -> Tensor: ...
def isposinf(*args: Tensor, a: Tensor, stream: Tensor, **kwargs: Tensor) -> Tensor: ...
def issubdtype(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def jvp(*args: Tensor, fun: int, primals: Tensor, tangents: Tensor, **kwargs: Tensor) -> Tensor: ...
def key(seed: int) -> Tensor: ...
def kron(*args: Tensor, a: Tensor, b: Tensor, stream: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def laplace(shape: Sequence[int] = ..., dtype: Tensor = ..., loc: float = ..., scale: float = ..., key: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def left_shift(*args: Tensor, a: Tensor, b: Tensor, **kwargs: Tensor) -> Tensor: ...
def less(*args: Tensor, a: Tensor, b: Tensor, **kwargs: Tensor) -> Tensor: ...
def less_equal(*args: Tensor, a: Tensor, b: Tensor, **kwargs: Tensor) -> Tensor: ...
def linspace(*args: Tensor, start: Tensor, stop: Tensor, num: Tensor = ..., endpoint: Tensor = ..., dtype: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def load(*args: Tensor, file: Tensor, format: Tensor = ..., return_metadata: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def log(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def log10(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def log1p(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def log2(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def logaddexp(*args: Tensor, a: Tensor, b: Tensor, **kwargs: Tensor) -> Tensor: ...
def logcumsumexp(*args: Tensor, a: Tensor, axis: Tensor, reverse: bool, inclusive: bool, **kwargs: Tensor) -> Tensor: ...
def logical_and(*args: Tensor, a: Tensor, b: Tensor, **kwargs: Tensor) -> Tensor: ...
def logical_not(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def logical_or(*args: Tensor, a: Tensor, b: Tensor, **kwargs: Tensor) -> Tensor: ...
def logical_xor(*args: Tensor, a: Tensor, b: Tensor, **kwargs: Tensor) -> Tensor: ...
def logsumexp(*args: Tensor, a: Tensor, axis: Tensor, keepdims: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def lu(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def lu_factor(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def matmul(*args: Tensor, a: Tensor, b: Tensor, **kwargs: Tensor) -> Tensor: ...
def max(*args: Tensor, a: Tensor, axis: Tensor, keepdims: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def maximum(*args: Tensor, a: Tensor, b: Tensor, **kwargs: Tensor) -> Tensor: ...
def mean(*args: Tensor, a: Tensor, axis: Tensor, keepdims: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def median(*args: Tensor, a: Tensor, axis: Tensor, keepdims: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def meshgrid(*args: Tensor, arrays: Tensor = ..., sparse: Tensor = ..., indexing: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def min(*args: Tensor, a: Tensor, axis: Tensor, keepdims: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def minimum(*args: Tensor, a: Tensor, b: Tensor, **kwargs: Tensor) -> Tensor: ...
def moveaxis(*args: Tensor, a: Tensor, source: int, destination: int, **kwargs: Tensor) -> Tensor: ...
def multiply(*args: Tensor, a: Tensor, b: Tensor, **kwargs: Tensor) -> Tensor: ...
def multivariate_normal(mean: Tensor, cov: Tensor, shape: Sequence[int] = ..., dtype: Tensor = ..., key: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def nan_to_num(*args: Tensor, a: Tensor, nan: Tensor = ..., posinf: Tensor = ..., neginf: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def negative(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def new_stream(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def new_thread_local_stream(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def new_thread_unsafe_stream(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def norm(*args: Tensor, a: Tensor, ord: Tensor = ..., axis: Tensor = ..., keepdims: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def normal(shape: Sequence[int] = ..., dtype: Tensor = ..., loc: Tensor = ..., scale: Tensor = ..., key: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def not_equal(*args: Tensor, a: Tensor, b: Tensor, **kwargs: Tensor) -> Tensor: ...
def ones(*args: Tensor, shape: Tensor, dtype: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def ones_like(*args: Tensor, a: Tensor, dtype: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def outer(*args: Tensor, a: Tensor, b: Tensor, **kwargs: Tensor) -> Tensor: ...
def pad(*args: Tensor, a: Tensor, pad_width: int, mode: Tensor, constant_values: Tensor, **kwargs: Tensor) -> Tensor: ...
def partition(*args: Tensor, a: Tensor, kth: int, axis: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def permutation(x: Tensor, axis: int = ..., key: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def permute_dims(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def pinv(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def positive(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def power(*args: Tensor, a: Tensor, b: Tensor, **kwargs: Tensor) -> Tensor: ...
def printoptions(*args: Tensor, precision: int, **kwargs: Tensor) -> Tensor: ...
def prod(*args: Tensor, a: Tensor, axis: Tensor, keepdims: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def put_along_axis(*args: Tensor, a: Tensor, indices: Tensor, values: Tensor, **kwargs: Tensor) -> Tensor: ...
def qqmm(*args: Tensor, x: Tensor, w: Tensor, scales: Tensor = ..., group_size: Tensor = ..., bits: Tensor = ..., mode: Tensor = ..., global_scale: Tensor = ..., global_scale_w: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def qr(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def quantize(*args: Tensor, w: Tensor, group_size: Tensor = ..., bits: Tensor = ..., mode: Tensor = ..., global_scale: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def quantized_matmul(*args: Tensor, x: Tensor, w: Tensor, scales: Tensor, biases: Tensor = ..., transpose: bool = ..., group_size: Tensor = ..., bits: Tensor = ..., mode: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def radians(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def randint(low: Tensor, high: Tensor, shape: Sequence[int] = ..., dtype: Tensor = ..., key: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def real(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def reciprocal(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def remainder(*args: Tensor, a: Tensor, b: Tensor, **kwargs: Tensor) -> Tensor: ...
def repeat(*args: Tensor, array: Tensor, repeats: int, axis: Tensor, stream: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def reset_peak_memory(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def reshape(*args: Tensor, a: Tensor, shape: Tensor, stream: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def result_type(*args: Tensor, arrays_and_dtypes: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def rfft(a: Tensor, n: Tensor = ..., axis: int = ..., norm: str = ..., stream: Tensor = ...) -> Tensor: ...
def rfft2(a: Tensor, s: Tensor = ..., axes: Tensor = ..., norm: str = ..., stream: Tensor = ...) -> Tensor: ...
def rfftfreq(n: int, d: float = ..., stream: Tensor = ...) -> Tensor: ...
def rfftn(a: Tensor, s: Tensor = ..., axes: Tensor = ..., norm: str = ..., stream: Tensor = ...) -> Tensor: ...
def right_shift(*args: Tensor, a: Tensor, b: Tensor, **kwargs: Tensor) -> Tensor: ...
def roll(*args: Tensor, a: Tensor, shift: Tensor, axis: Tensor, **kwargs: Tensor) -> Tensor: ...
def round(*args: Tensor, a: Tensor, decimals: int = ..., **kwargs: Tensor) -> Tensor: ...
def rsqrt(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def save(*args: Tensor, file: Tensor, arr: Tensor, **kwargs: Tensor) -> Tensor: ...
def save_gguf(*args: Tensor, file: Tensor, arrays: Tensor, metadata: Tensor, **kwargs: Tensor) -> Tensor: ...
def save_safetensors(*args: Tensor, file: Tensor, arrays: Tensor, metadata: Tensor, **kwargs: Tensor) -> Tensor: ...
def savez(*args: Tensor, file: Tensor, **kwargs: Tensor) -> Tensor: ...
def savez_compressed(*args: Tensor, file: Tensor, **kwargs: Tensor) -> Tensor: ...
def searchsorted(*args: Tensor, sorted_sequence: Tensor, values: Tensor, side: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def seed(seed: int) -> Tensor: ...
def segmented_mm(*args: Tensor, a: Tensor, b: Tensor, segments: Tensor, **kwargs: Tensor) -> Tensor: ...
def set_cache_limit(*args: Tensor, limit: int, **kwargs: Tensor) -> Tensor: ...
def set_default_device(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def set_default_stream(*args: Tensor, stream: Tensor, **kwargs: Tensor) -> Tensor: ...
def set_memory_limit(*args: Tensor, limit: int, **kwargs: Tensor) -> Tensor: ...
def set_printoptions(*args: Tensor, precision: int, **kwargs: Tensor) -> Tensor: ...
def set_wired_limit(*args: Tensor, limit: int, **kwargs: Tensor) -> Tensor: ...
def sign(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def sin(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def sinh(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def slice(*args: Tensor, a: Tensor, start_indices: Tensor, axes: Tensor, slice_size: Tensor, **kwargs: Tensor) -> Tensor: ...
def slice_update(*args: Tensor, a: Tensor, update: Tensor, start_indices: Tensor, axes: Tensor, **kwargs: Tensor) -> Tensor: ...
def slogdet(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def solve(a: Tensor, b: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def solve_triangular(a: Tensor, b: Tensor, *, upper: bool = ..., stream: Tensor = ...) -> Tensor: ...
def sort(*args: Tensor, a: Tensor, axis: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def split(*args: Tensor, a: Tensor, indices_or_sections: Tensor, axis: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def sqrt(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def square(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def squeeze(*args: Tensor, a: Tensor, axis: Tensor, **kwargs: Tensor) -> Tensor: ...
def stack(*args: Tensor, arrays: Tensor, axis: Tensor = ..., stream: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def std(*args: Tensor, a: Tensor, axis: Tensor, keepdims: Tensor = ..., ddof: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def stop_gradient(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def stream(*args: Tensor, s: Tensor, **kwargs: Tensor) -> Tensor: ...
def subtract(*args: Tensor, a: Tensor, b: Tensor, **kwargs: Tensor) -> Tensor: ...
def sum(*args: Tensor, a: Tensor, axis: Tensor, keepdims: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def svd(a: Tensor, compute_uv: bool = ..., *, stream: Tensor = ...) -> Tensor: ...
def swapaxes(*args: Tensor, a: Tensor, axis1: int, axis2: int, **kwargs: Tensor) -> Tensor: ...
def synchronize(*args: Tensor, stream: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def take(*args: Tensor, a: Tensor, indices: Tensor, axis: Tensor, **kwargs: Tensor) -> Tensor: ...
def take_along_axis(*args: Tensor, a: Tensor, indices: Tensor, axis: Tensor, **kwargs: Tensor) -> Tensor: ...
def tan(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def tensordot(*args: Tensor, a: Tensor, b: Tensor, axes: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def tile(*args: Tensor, a: Tensor, reps: Tensor, **kwargs: Tensor) -> Tensor: ...
def to_fp8(*args: Tensor, x: Tensor, **kwargs: Tensor) -> Tensor: ...
def topk(*args: Tensor, a: Tensor, k: int, axis: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def trace(*args: Tensor, a: Tensor, offset: Tensor = ..., axis1: Tensor = ..., axis2: Tensor = ..., dtype: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def transpose(*args: Tensor, a: Tensor, axes: Tensor, **kwargs: Tensor) -> Tensor: ...
def tri(*args: Tensor, n: int, m: Tensor = ..., k: Tensor = ..., dtype: Tensor = ..., stream: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def tri_inv(a: Tensor, upper: bool = ..., *, stream: Tensor = ...) -> Tensor: ...
def tril(*args: Tensor, x: Tensor, k: Tensor = ..., stream: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def triu(*args: Tensor, x: Tensor, k: Tensor = ..., stream: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def trunc(*args: Tensor, a: Tensor, **kwargs: Tensor) -> Tensor: ...
def truncated_normal(lower: Tensor, upper: Tensor, shape: Tensor = ..., dtype: Tensor = ..., key: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def unflatten(*args: Tensor, a: Tensor, axis: int, shape: Tensor, stream: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def uniform(low: Tensor = ..., high: Tensor = ..., shape: Sequence[int] = ..., dtype: Tensor = ..., key: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def unstack(*args: Tensor, x: Tensor, axis: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def value_and_grad(*args: Tensor, fun: int, argnums: Tensor = ..., argnames: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def var(*args: Tensor, a: Tensor, axis: Tensor, keepdims: Tensor = ..., ddof: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def vecdot(*args: Tensor, a: Tensor, b: Tensor, axis: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def view(*args: Tensor, a: Tensor, dtype: Tensor, **kwargs: Tensor) -> Tensor: ...
def vjp(*args: Tensor, fun: int, primals: Tensor, cotangents: Tensor, **kwargs: Tensor) -> Tensor: ...
def vmap(*args: Tensor, fun: int, in_axes: Tensor = ..., out_axes: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def where(*args: Tensor, condition: Tensor, x: Tensor, y: Tensor, **kwargs: Tensor) -> Tensor: ...
def zeros(*args: Tensor, shape: Tensor, dtype: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def zeros_like(*args: Tensor, a: Tensor, dtype: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def cosine_similarity_loss(x1: Tensor, x2: Tensor, axis: Tensor = ..., eps: Tensor = ..., reduction: Tensor = ...) -> Tensor: ...
def gaussian_nll_loss(inputs: Tensor, targets: Tensor, vars: Tensor, full: Tensor = ..., eps: Tensor = ..., reduction: Tensor = ...) -> Tensor: ...
def hinge_loss(inputs: Tensor, targets: Tensor, reduction: Tensor = ...) -> Tensor: ...
def huber_loss(inputs: Tensor, targets: Tensor, delta: Tensor = ..., reduction: Tensor = ...) -> Tensor: ...
def kl_div_loss(inputs: Tensor, targets: Tensor, axis: Tensor = ..., reduction: Tensor = ...) -> Tensor: ...
def l1_loss(predictions: Tensor, targets: Tensor, reduction: Tensor = ...) -> Tensor: ...
def log_cosh_loss(inputs: Tensor, targets: Tensor, reduction: Tensor = ...) -> Tensor: ...
def margin_ranking_loss(inputs1: Tensor, inputs2: Tensor, targets: bool, margin: Tensor = ..., reduction: Tensor = ...) -> Tensor: ...
def mse_loss(predictions: Tensor, targets: Tensor, reduction: Tensor = ...) -> Tensor: ...
def nll_loss(inputs: Tensor, targets: Tensor, axis: Tensor = ..., reduction: Tensor = ...) -> Tensor: ...
def smooth_l1_loss(predictions: Tensor, targets: Tensor, beta: Tensor = ..., reduction: Tensor = ...) -> Tensor: ...
def triplet_loss(anchors: Tensor, positives: Tensor, negatives: Tensor, axis: Tensor = ..., p: Tensor = ..., margin: Tensor = ..., eps: Tensor = ..., reduction: Tensor = ...) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
