"""Auto-generated type stubs from snapshot."""

class Tensor: ...

def abs(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cosine_similarity_loss(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def elu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def gaussian_nll_loss(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def gelu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def hinge_loss(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def huber_loss(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def kl_div_loss(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def l1_loss(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def log_cosh_loss(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def margin_ranking_loss(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def mean(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def mse_loss(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def nll_loss(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def relu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sigmoid(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def silu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def smooth_l1_loss(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def softmax(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def tanh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def triplet_loss(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
