"""Auto-generated high-fidelity type stubs for mlx from ml-framework-snapshots."""
# ruff: noqa: E501, UP007, UP045, D100, D101, D102, D103

from collections.abc import Sequence

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    device: str
    ndim: int
    size: int
    def __init__(self, data: object = ..., shape: Sequence[int] | None = ..., dtype: str | None = ...) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: object) -> Tensor: ...
    def __add__(self, other: Tensor | float | int) -> Tensor: ...
    def __sub__(self, other: Tensor | float | int) -> Tensor: ...
    def __mul__(self, other: Tensor | float | int) -> Tensor: ...
    def __truediv__(self, other: Tensor | float | int) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def numpy(self) -> object: ...
    def to(self, device: str) -> Tensor: ...
    def reshape(self, shape: Sequence[int]) -> Tensor: ...
    def transpose(self, axes: Sequence[int] | None = ...) -> Tensor: ...

def elu(x: Tensor, alpha: float = ...) -> Tensor: ...
def gelu(x: Tensor) -> Tensor: ...
def hardswish(x: Tensor) -> Tensor: ...
def leaky_relu(x: Tensor, negative_slope: float = ...) -> Tensor: ...
def log_softmax(x: Tensor, axis: int = ...) -> Tensor: ...
def mish(x: Tensor) -> Tensor: ...
def prelu(x: Tensor, alpha: Tensor) -> Tensor: ...
def relu(x: Tensor) -> Tensor: ...
def selu(x: Tensor) -> Tensor: ...
def sigmoid(x: Tensor) -> Tensor: ...
def silu(x: Tensor) -> Tensor: ...
def softmax(x: Tensor, axis: int = ...) -> Tensor: ...
def softplus(x: Tensor) -> Tensor: ...
def step(x: Tensor, threshold: float = ...) -> Tensor: ...
def tanh(x: Tensor) -> Tensor: ...
def abs(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def add(a: Tensor, b: Tensor, stream: Tensor = ...) -> Tensor: ...
def addmm(c: Tensor, a: Tensor, b: Tensor, alpha: float = ..., beta: float = ..., *, stream: Tensor = ...) -> Tensor: ...
def all(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., *, stream: Tensor = ...) -> Tensor: ...
def allclose(a: Tensor, b: Tensor, rtol: float = ..., atol: float = ..., *, equal_nan: bool = ..., stream: Tensor = ...) -> Tensor: ...
def any(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., *, stream: Tensor = ...) -> Tensor: ...
def arange(start: Tensor, stop: Tensor, step: Tensor, dtype: Tensor = ..., *, stream: Tensor = ...) -> Tensor: ...
def arccos(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def arccosh(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def arcsin(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def arcsinh(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def arctan(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def arctan2(a: Tensor, b: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def arctanh(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def argmax(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., *, stream: Tensor = ...) -> Tensor: ...
def argmin(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., *, stream: Tensor = ...) -> Tensor: ...
def argpartition(a: Tensor, kth: int, axis: Tensor = ..., *, stream: Tensor = ...) -> Tensor: ...
def argsort(a: Tensor, axis: Tensor = ..., *, stream: Tensor = ...) -> Tensor: ...
def array_equal(a: Tensor, b: Tensor, equal_nan: bool = ..., stream: Tensor = ...) -> Tensor: ...
def as_strided(a: Tensor, shape: Tensor = ..., strides: Tensor = ..., offset: int = ..., *, stream: Tensor = ...) -> Tensor: ...
def async_eval(*args: Tensor) -> Tensor: ...
def atleast_1d(*arys: Tensor, stream: Tensor = ...) -> Tensor: ...
def atleast_2d(*arys: Tensor, stream: Tensor = ...) -> Tensor: ...
def atleast_3d(*arys: Tensor, stream: Tensor = ...) -> Tensor: ...
def bernoulli(p: Tensor = ..., shape: Tensor = ..., key: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def bitwise_and(a: Tensor, b: Tensor, stream: Tensor = ...) -> Tensor: ...
def bitwise_invert(a: Tensor, stream: Tensor = ...) -> Tensor: ...
def bitwise_or(a: Tensor, b: Tensor, stream: Tensor = ...) -> Tensor: ...
def bitwise_xor(a: Tensor, b: Tensor, stream: Tensor = ...) -> Tensor: ...
def block_masked_mm(a: Tensor, b: Tensor, block_size: int = ..., mask_out: Tensor = ..., mask_lhs: Tensor = ..., mask_rhs: Tensor = ..., *, stream: Tensor = ...) -> Tensor: ...
def broadcast_arrays(*arrays: Tensor, stream: Tensor = ...) -> Tensor: ...
def broadcast_shapes(*shapes: Sequence[int]) -> Tensor: ...
def broadcast_to(a: Tensor, shape: Sequence[int], *, stream: Tensor = ...) -> Tensor: ...
def categorical(logits: Tensor, axis: int = ..., shape: Tensor = ..., num_samples: Tensor = ..., key: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def ceil(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def checkpoint(fun: Tensor) -> Tensor: ...
def cholesky(a: Tensor, upper: bool = ..., *, stream: Tensor = ...) -> Tensor: ...
def cholesky_inv(L: Tensor, upper: bool = ..., *, stream: Tensor = ...) -> Tensor: ...
def clear_cache(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def clip(a: Tensor, a_min: Tensor, a_max: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def compile(fun: Tensor, inputs: Tensor = ..., outputs: Tensor = ..., shapeless: bool = ...) -> Tensor: ...
def concat(arrays: Tensor, axis: Tensor = ..., *, stream: Tensor = ...) -> Tensor: ...
def concatenate(arrays: Tensor, axis: Tensor = ..., *, stream: Tensor = ...) -> Tensor: ...
def conj(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def conjugate(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def contiguous(a: Tensor, allow_col_major: bool = ..., *, stream: Tensor = ...) -> Tensor: ...
def conv1d(input: Tensor, weight: Tensor, stride: int = ..., padding: int = ..., dilation: int = ..., groups: int = ..., *, stream: Tensor = ...) -> Tensor: ...
def conv2d(input: Tensor, weight: Tensor, stride: Tensor = ..., padding: Tensor = ..., dilation: Tensor = ..., groups: int = ..., *, stream: Tensor = ...) -> Tensor: ...
def conv3d(input: Tensor, weight: Tensor, stride: Tensor = ..., padding: Tensor = ..., dilation: Tensor = ..., groups: int = ..., *, stream: Tensor = ...) -> Tensor: ...
def conv_general(input: Tensor, weight: Tensor, stride: Tensor = ..., padding: Tensor = ..., kernel_dilation: Tensor = ..., input_dilation: Tensor = ..., groups: int = ..., flip: bool = ..., *, stream: Tensor = ...) -> Tensor: ...
def conv_transpose1d(input: Tensor, weight: Tensor, stride: int = ..., padding: int = ..., dilation: int = ..., output_padding: int = ..., groups: int = ..., *, stream: Tensor = ...) -> Tensor: ...
def conv_transpose2d(input: Tensor, weight: Tensor, stride: Tensor = ..., padding: Tensor = ..., dilation: Tensor = ..., output_padding: Tensor = ..., groups: int = ..., *, stream: Tensor = ...) -> Tensor: ...
def conv_transpose3d(input: Tensor, weight: Tensor, stride: Tensor = ..., padding: Tensor = ..., dilation: Tensor = ..., output_padding: Tensor = ..., groups: int = ..., *, stream: Tensor = ...) -> Tensor: ...
def convolve(a: Tensor, v: Tensor, mode: str = ..., *, stream: Tensor = ...) -> Tensor: ...
def cos(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def cosh(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def cross(a: Tensor, b: Tensor, axis: int = ..., *, stream: Tensor = ...) -> Tensor: ...
def cummax(a: Tensor, axis: Tensor = ..., *, reverse: bool = ..., inclusive: bool = ..., stream: Tensor = ...) -> Tensor: ...
def cummin(a: Tensor, axis: Tensor = ..., *, reverse: bool = ..., inclusive: bool = ..., stream: Tensor = ...) -> Tensor: ...
def cumprod(a: Tensor, axis: Tensor = ..., *, reverse: bool = ..., inclusive: bool = ..., stream: Tensor = ...) -> Tensor: ...
def cumsum(a: Tensor, axis: Tensor = ..., *, reverse: bool = ..., inclusive: bool = ..., stream: Tensor = ...) -> Tensor: ...
def default_device(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def default_stream(device: Tensor) -> Tensor: ...
def degrees(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def depends(inputs: Tensor, dependencies: Tensor) -> Tensor: ...
def dequantize(w: Tensor, scales: Tensor, biases: Tensor = ..., group_size: int = ..., bits: int = ..., mode: str = ..., *, stream: Tensor = ...) -> Tensor: ...
def diag(a: Tensor, k: int = ..., *, stream: Tensor = ...) -> Tensor: ...
def diagonal(a: Tensor, offset: int = ..., axis1: int = ..., axis2: int = ..., stream: Tensor = ...) -> Tensor: ...
def disable_compile(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def divide(a: Tensor, b: Tensor, stream: Tensor = ...) -> Tensor: ...
def divmod(a: Tensor, b: Tensor, stream: Tensor = ...) -> Tensor: ...
def eig(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def eigh(a: Tensor, UPLO: str = ..., *, stream: Tensor = ...) -> Tensor: ...
def eigvals(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def eigvalsh(a: Tensor, UPLO: str = ..., *, stream: Tensor = ...) -> Tensor: ...
def einsum(subscripts: str, *operands: Tensor, stream: Tensor = ...) -> Tensor: ...
def einsum_path(subscripts: str, *operands: Tensor) -> Tensor: ...
def enable_compile(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def equal(a: Tensor, b: Tensor, stream: Tensor = ...) -> Tensor: ...
def erf(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def erfinv(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def eval(*args: Tensor) -> Tensor: ...
def exp(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def expand_dims(a: Tensor, axis: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def expm1(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def export_function(arg0: Tensor, fun: Tensor, *args: Tensor, shapeless: bool = ..., file: Tensor, **kwargs: Tensor) -> Tensor: ...
def export_to_dot(file: Tensor, *args: Tensor, **kwargs: Tensor) -> Tensor: ...
def exporter(file: str, fun: Tensor, *, shapeless: bool = ...) -> Tensor: ...
def eye(n: int, m: Tensor = ..., k: int = ..., dtype: Tensor = ..., *, stream: Tensor = ...) -> Tensor: ...
def fft(a: Tensor, n: Tensor = ..., axis: int = ..., stream: Tensor = ...) -> Tensor: ...
def fft2(a: Tensor, s: Tensor = ..., axes: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def fftn(a: Tensor, s: Tensor = ..., axes: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def fftshift(a: Tensor, axes: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def flatten(a: Tensor, start_axis: int = ..., end_axis: int = ..., *, stream: Tensor = ...) -> Tensor: ...
def floor(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def floor_divide(a: Tensor, b: Tensor, stream: Tensor = ...) -> Tensor: ...
def full(shape: Tensor, vals: Tensor, dtype: Tensor = ..., *, stream: Tensor = ...) -> Tensor: ...
def gather_mm(a: Tensor, b: Tensor, lhs_indices: Tensor, rhs_indices: Tensor, *, sorted_indices: bool = ..., stream: Tensor = ...) -> Tensor: ...
def gather_qmm(x: Tensor, w: Tensor, scales: Tensor, biases: Tensor = ..., lhs_indices: Tensor = ..., rhs_indices: Tensor = ..., transpose: bool = ..., group_size: int = ..., bits: int = ..., mode: str = ..., *, sorted_indices: bool = ..., stream: Tensor = ...) -> Tensor: ...
def get_active_memory(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def get_cache_memory(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def get_peak_memory(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def grad(fun: Tensor, argnums: Tensor = ..., argnames: Tensor = ...) -> Tensor: ...
def greater(a: Tensor, b: Tensor, stream: Tensor = ...) -> Tensor: ...
def greater_equal(a: Tensor, b: Tensor, stream: Tensor = ...) -> Tensor: ...
def gumbel(shape: Sequence[int] = ..., dtype: Tensor = ..., key: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def hadamard_transform(a: Tensor, scale: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def identity(n: int, dtype: Tensor = ..., *, stream: Tensor = ...) -> Tensor: ...
def ifft(a: Tensor, n: Tensor = ..., axis: int = ..., stream: Tensor = ...) -> Tensor: ...
def ifft2(a: Tensor, s: Tensor = ..., axes: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def ifftn(a: Tensor, s: Tensor = ..., axes: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def ifftshift(a: Tensor, axes: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def imag(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def import_function(file: str) -> Tensor: ...
def inner(a: Tensor, b: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def inv(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def irfft(a: Tensor, n: Tensor = ..., axis: int = ..., stream: Tensor = ...) -> Tensor: ...
def irfft2(a: Tensor, s: Tensor = ..., axes: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def irfftn(a: Tensor, s: Tensor = ..., axes: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def is_available(device: Tensor) -> Tensor: ...
def isclose(a: Tensor, b: Tensor, rtol: float = ..., atol: float = ..., *, equal_nan: bool = ..., stream: Tensor = ...) -> Tensor: ...
def isfinite(a: Tensor, stream: Tensor = ...) -> Tensor: ...
def isinf(a: Tensor, stream: Tensor = ...) -> Tensor: ...
def isnan(a: Tensor, stream: Tensor = ...) -> Tensor: ...
def isneginf(a: Tensor, stream: Tensor = ...) -> Tensor: ...
def isposinf(a: Tensor, stream: Tensor = ...) -> Tensor: ...
def issubdtype(arg1: Tensor, arg2: Tensor) -> Tensor: ...
def jvp(fun: Tensor, primals: Tensor, tangents: Tensor) -> Tensor: ...
def key(seed: int) -> Tensor: ...
def kron(a: Tensor, b: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def laplace(shape: Sequence[int] = ..., dtype: Tensor = ..., loc: float = ..., scale: float = ..., key: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def left_shift(a: Tensor, b: Tensor, stream: Tensor = ...) -> Tensor: ...
def less(a: Tensor, b: Tensor, stream: Tensor = ...) -> Tensor: ...
def less_equal(a: Tensor, b: Tensor, stream: Tensor = ...) -> Tensor: ...
def linspace(start: Tensor, stop: Tensor, num: Tensor = ..., dtype: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def load(file: Tensor, format: Tensor = ..., return_metadata: bool = ..., *, stream: Tensor = ...) -> Tensor: ...
def log(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def log10(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def log1p(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def log2(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def logaddexp(a: Tensor, b: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def logcumsumexp(a: Tensor, axis: Tensor = ..., *, reverse: bool = ..., inclusive: bool = ..., stream: Tensor = ...) -> Tensor: ...
def logical_and(a: Tensor, b: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def logical_not(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def logical_or(a: Tensor, b: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def logsumexp(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., *, stream: Tensor = ...) -> Tensor: ...
def lu(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def lu_factor(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def matmul(a: Tensor, b: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def max(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., *, stream: Tensor = ...) -> Tensor: ...
def maximum(a: Tensor, b: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def mean(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., *, stream: Tensor = ...) -> Tensor: ...
def meshgrid(*arrays: Tensor, sparse: Tensor = ..., indexing: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def min(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., *, stream: Tensor = ...) -> Tensor: ...
def minimum(a: Tensor, b: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def moveaxis(a: Tensor, source: int, destination: int, *, stream: Tensor = ...) -> Tensor: ...
def multiply(a: Tensor, b: Tensor, stream: Tensor = ...) -> Tensor: ...
def multivariate_normal(mean: Tensor, cov: Tensor, shape: Sequence[int] = ..., dtype: Tensor = ..., key: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def nan_to_num(a: Tensor, nan: float = ..., posinf: Tensor = ..., neginf: Tensor = ..., *, stream: Tensor = ...) -> Tensor: ...
def negative(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def new_stream(device: Tensor) -> Tensor: ...
def norm(a: Tensor, ord: Tensor = ..., axis: Tensor = ..., keepdims: bool = ..., *, stream: Tensor = ...) -> Tensor: ...
def normal(shape: Sequence[int] = ..., dtype: Tensor = ..., loc: Tensor = ..., scale: Tensor = ..., key: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def not_equal(a: Tensor, b: Tensor, stream: Tensor = ...) -> Tensor: ...
def ones(shape: Tensor, dtype: Tensor = ..., *, stream: Tensor = ...) -> Tensor: ...
def ones_like(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def outer(a: Tensor, b: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def pad(a: Tensor, pad_width: Tensor, mode: Tensor = ..., constant_values: Tensor = ..., *, stream: Tensor = ...) -> Tensor: ...
def partition(a: Tensor, kth: int, axis: Tensor = ..., *, stream: Tensor = ...) -> Tensor: ...
def permutation(x: Tensor, axis: int = ..., key: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def permute_dims(a: Tensor, axes: Tensor = ..., *, stream: Tensor = ...) -> Tensor: ...
def pinv(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def power(a: Tensor, b: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def prod(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., *, stream: Tensor = ...) -> Tensor: ...
def put_along_axis(a: Tensor, indices: Tensor, values: Tensor, axis: Tensor = ..., *, stream: Tensor = ...) -> Tensor: ...
def qr(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def quantize(w: Tensor, group_size: int = ..., bits: int = ..., mode: str = ..., *, stream: Tensor = ...) -> Tensor: ...
def quantized_matmul(x: Tensor, w: Tensor, scales: Tensor, biases: Tensor = ..., transpose: bool = ..., group_size: int = ..., bits: int = ..., mode: str = ..., *, stream: Tensor = ...) -> Tensor: ...
def radians(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def randint(low: Tensor, high: Tensor, shape: Sequence[int] = ..., dtype: Tensor = ..., key: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def real(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def reciprocal(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def remainder(a: Tensor, b: Tensor, stream: Tensor = ...) -> Tensor: ...
def repeat(array: Tensor, repeats: int, axis: Tensor = ..., *, stream: Tensor = ...) -> Tensor: ...
def reset_peak_memory(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def reshape(a: Tensor, shape: Sequence[int], *, stream: Tensor = ...) -> Tensor: ...
def rfft(a: Tensor, n: Tensor = ..., axis: int = ..., stream: Tensor = ...) -> Tensor: ...
def rfft2(a: Tensor, s: Tensor = ..., axes: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def rfftn(a: Tensor, s: Tensor = ..., axes: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def right_shift(a: Tensor, b: Tensor, stream: Tensor = ...) -> Tensor: ...
def roll(a: Tensor, shift: Tensor, axis: Tensor = ..., *, stream: Tensor = ...) -> Tensor: ...
def round(a: Tensor, decimals: int = ..., stream: Tensor = ...) -> Tensor: ...
def rsqrt(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def save(file: Tensor, arr: Tensor) -> Tensor: ...
def save_gguf(file: Tensor, arrays: Tensor, metadata: Tensor) -> Tensor: ...
def save_safetensors(file: Tensor, arrays: Tensor, metadata: Tensor = ...) -> Tensor: ...
def savez(file: Tensor, *args: Tensor, **kwargs: Tensor) -> Tensor: ...
def savez_compressed(file: Tensor, *args: Tensor, **kwargs: Tensor) -> Tensor: ...
def seed(seed: int) -> Tensor: ...
def segmented_mm(a: Tensor, b: Tensor, segments: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def set_cache_limit(limit: int) -> Tensor: ...
def set_default_device(device: Tensor) -> Tensor: ...
def set_default_stream(stream: Tensor) -> Tensor: ...
def set_memory_limit(limit: int) -> Tensor: ...
def set_wired_limit(limit: int) -> Tensor: ...
def sign(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def sin(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def sinh(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def slice(a: Tensor, start_indices: Tensor, axes: Sequence[int], slice_size: Sequence[int], *, stream: Tensor = ...) -> Tensor: ...
def slice_update(a: Tensor, update: Tensor, start_indices: Tensor, axes: Sequence[int], *, stream: Tensor = ...) -> Tensor: ...
def solve(a: Tensor, b: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def solve_triangular(a: Tensor, b: Tensor, *, upper: bool = ..., stream: Tensor = ...) -> Tensor: ...
def sort(a: Tensor, axis: Tensor = ..., *, stream: Tensor = ...) -> Tensor: ...
def split(a: Tensor, indices_or_sections: Tensor, axis: int = ..., *, stream: Tensor = ...) -> Tensor: ...
def sqrt(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def square(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def squeeze(a: Tensor, axis: Tensor = ..., *, stream: Tensor = ...) -> Tensor: ...
def stack(arrays: Tensor, axis: Tensor = ..., *, stream: Tensor = ...) -> Tensor: ...
def std(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., ddof: int = ..., *, stream: Tensor = ...) -> Tensor: ...
def stop_gradient(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def stream(s: Tensor) -> Tensor: ...
def subtract(a: Tensor, b: Tensor, stream: Tensor = ...) -> Tensor: ...
def sum(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., *, stream: Tensor = ...) -> Tensor: ...
def svd(a: Tensor, compute_uv: bool = ..., *, stream: Tensor = ...) -> Tensor: ...
def swapaxes(a: Tensor, axis1: int, axis2: int, *, stream: Tensor = ...) -> Tensor: ...
def synchronize(stream: Tensor = ...) -> Tensor: ...
def take(a: Tensor, indices: Tensor, axis: Tensor = ..., *, stream: Tensor = ...) -> Tensor: ...
def take_along_axis(a: Tensor, indices: Tensor, axis: Tensor = ..., *, stream: Tensor = ...) -> Tensor: ...
def tan(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def tensordot(a: Tensor, b: Tensor, axes: Tensor = ..., *, stream: Tensor = ...) -> Tensor: ...
def tile(a: Tensor, reps: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def topk(a: Tensor, k: int, axis: Tensor = ..., *, stream: Tensor = ...) -> Tensor: ...
def trace(a: Tensor, offset: int = ..., axis1: int = ..., axis2: int = ..., dtype: Tensor = ..., *, stream: Tensor = ...) -> Tensor: ...
def transpose(a: Tensor, axes: Tensor = ..., *, stream: Tensor = ...) -> Tensor: ...
def tri(n: int, m: int, k: int, dtype: Tensor = ..., *, stream: Tensor = ...) -> Tensor: ...
def tri_inv(a: Tensor, upper: bool = ..., *, stream: Tensor = ...) -> Tensor: ...
def tril(x: Tensor, k: int, *, stream: Tensor = ...) -> Tensor: ...
def triu(x: Tensor, k: int, *, stream: Tensor = ...) -> Tensor: ...
def truncated_normal(lower: Tensor, upper: Tensor, shape: Tensor = ..., dtype: Tensor = ..., key: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def unflatten(a: Tensor, axis: int, shape: Sequence[int], *, stream: Tensor = ...) -> Tensor: ...
def uniform(low: Tensor = ..., high: Tensor = ..., shape: Sequence[int] = ..., dtype: Tensor = ..., key: Tensor = ..., stream: Tensor = ...) -> Tensor: ...
def value_and_grad(fun: Tensor, argnums: Tensor = ..., argnames: Tensor = ...) -> Tensor: ...
def var(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., ddof: int = ..., *, stream: Tensor = ...) -> Tensor: ...
def view(a: Tensor, dtype: Tensor, stream: Tensor = ...) -> Tensor: ...
def vjp(fun: Tensor, primals: Tensor, cotangents: Tensor) -> Tensor: ...
def vmap(fun: Tensor, in_axes: Tensor = ..., out_axes: Tensor = ...) -> Tensor: ...
def where(condition: Tensor, x: Tensor, y: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def zeros(shape: Tensor, dtype: Tensor = ..., *, stream: Tensor = ...) -> Tensor: ...
def zeros_like(a: Tensor, *, stream: Tensor = ...) -> Tensor: ...
def cosine_similarity_loss(x1: Tensor, x2: Tensor, axis: Tensor = ..., eps: Tensor = ..., reduction: Tensor = ...) -> Tensor: ...
def gaussian_nll_loss(inputs: Tensor, targets: Tensor, vars: Tensor, full: Tensor = ..., eps: Tensor = ..., reduction: Tensor = ...) -> Tensor: ...
def hinge_loss(inputs: Tensor, targets: Tensor, reduction: Tensor = ...) -> Tensor: ...
def huber_loss(inputs: Tensor, targets: Tensor, delta: Tensor = ..., reduction: Tensor = ...) -> Tensor: ...
def kl_div_loss(inputs: Tensor, targets: Tensor, axis: Tensor = ..., reduction: Tensor = ...) -> Tensor: ...
def l1_loss(predictions: Tensor, targets: Tensor, reduction: Tensor = ...) -> Tensor: ...
def log_cosh_loss(inputs: Tensor, targets: Tensor, reduction: Tensor = ...) -> Tensor: ...
def margin_ranking_loss(inputs1: Tensor, inputs2: Tensor, targets: bool, margin: Tensor = ..., reduction: Tensor = ...) -> Tensor: ...
def mse_loss(predictions: Tensor, targets: Tensor, reduction: Tensor = ...) -> Tensor: ...
def nll_loss(inputs: Tensor, targets: Tensor, axis: Tensor = ..., reduction: Tensor = ...) -> Tensor: ...
def smooth_l1_loss(predictions: Tensor, targets: Tensor, beta: Tensor = ..., reduction: Tensor = ...) -> Tensor: ...
def triplet_loss(anchors: Tensor, positives: Tensor, negatives: Tensor, axis: Tensor = ..., p: Tensor = ..., margin: Tensor = ..., eps: Tensor = ..., reduction: Tensor = ...) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
