# ruff: noqa: F822
# ruff: noqa: F403

"""Vision registry."""

import ml_switcheroo_compiler.ops.vision as _vision
import ml_switcheroo_compiler.ops.image as _image
import ml_switcheroo_compiler.ops.vision.ops as _vision_ops


# Inject attributes into globals
for _mod in [_vision, _image, _vision_ops]:
    for _name in getattr(_mod, "__all__", [n for n in dir(_mod) if not n.startswith("_")]):
        globals()[_name] = getattr(_mod, _name)

__all__ = [
    "AdjustBrightness",
    "AdjustContrast",
    "AdjustHue",
    "AdjustSaturation",
    "AffineConfig",
    "AffineGenerator",
    "AffineGrid",
    "AffineTransform",
    "AugMix",
    "AutoContrast",
    "Crop",
    "CropAndResize",
    "CropImages",
    "Cutmix",
    "DType",
    "Degeneration",
    "DrawBoundingBoxes",
    "ElasticTransform",
    "Equalization",
    "ExtractBoundingBoxes",
    "ExtractPatches",
    "FlipLeftRight",
    "FlipUpDown",
    "GaussianBlur",
    "GridSample",
    "HsvToRgb",
    "Invert",
    "IoU",
    "MAGIC_VAL_3",
    "MAGIC_VAL_4",
    "MapCoordinates",
    "MedianFilter",
    "Mixup",
    "NonMaxSuppression",
    "OpDef",
    "PadImages",
    "PadToBoundingBox",
    "PerspectiveTransform",
    "Posterize",
    "RandAugment",
    "RandomColorJitter",
    "RandomCropOp",
    "RandomElasticTransformOp",
    "RandomErasing",
    "RandomFlipOp",
    "RandomGaussianBlurOp",
    "RandomPerspectiveOp",
    "RandomRotationOp",
    "RandomSharpnessOp",
    "RandomShearOp",
    "RandomTranslationOp",
    "RandomZoomOp",
    "Resize",
    "ResizeBicubic",
    "ResizeBilinear",
    "ResizeLanczos3",
    "ResizeLanczos5",
    "ResizeNearest",
    "RgbToGrayscaleOp",
    "RgbToHsv",
    "RgbToYiq",
    "RgbToYuv",
    "Sharpen",
    "Solarize",
    "Tensor",
    "TensorConfig",
    "YiqToRgb",
    "YuvToRgb",
    "adjust_brightness",
    "adjust_contrast",
    "adjust_hue",
    "adjust_saturation",
    "affine_generator",
    "affine_grid",
    "affine_transform",
    "annotations",
    "augmix",
    "auto_contrast",
    "config",
    "crop",
    "crop_and_resize",
    "crop_images",
    "crop_to_bounding_box",
    "cutmix",
    "dataclass",
    "degeneration",
    "draw_bounding_boxes",
    "elastic_transform",
    "equalization",
    "extract_bounding_boxes",
    "extract_patches",
    "flip_left_right",
    "flip_up_down",
    "gaussian_blur",
    "global_config",
    "grid_sample",
    "hsv_to_rgb",
    "invert",
    "iou",
    "map_coordinates",
    "median_filter",
    "mixup",
    "non_max_suppression",
    "pad_images",
    "pad_to_bounding_box",
    "perspective_transform",
    "posterize",
    "rand_augment",
    "random_color_jitter",
    "random_crop",
    "random_elastic_transform",
    "random_erasing",
    "random_flip",
    "random_gaussian_blur",
    "random_perspective",
    "random_rotation",
    "random_sharpness",
    "random_shear",
    "random_translation",
    "random_zoom",
    "register_op",
    "resize",
    "resize_bicubic",
    "resize_bilinear",
    "resize_lanczos3",
    "resize_nearest",
    "rgb_to_grayscale",
    "rgb_to_hsv",
    "rgb_to_yiq",
    "rgb_to_yuv",
    "sharpen",
    "solarize",
    "yiq_to_rgb",
    "yuv_to_rgb",
]
