"""Auto-generated operation registry."""

# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated from src/ml_switcheroo_compiler/ops/definitions/*.yaml

__all__ = ["OPS_REGISTRY"]

OPS_REGISTRY = {
    "Abs": {"description": "The Abs operation.", "operation": "Abs", "variants": {"cupy": {"eager": "cp.abs"}, "dask": {"eager": "da.abs"}, "edge_onnx": {"generator": "Abs"}, "edge_stablehlo": {"generator": "stablehlo.abs"}, "keras": {"eager": "keras_ops.abs"}, "tensorflow": {"eager": "tf.abs"}}},
    "AccumulateN": {"description": "The AccumulateN operation.", "operation": "AccumulateN", "variants": {"tensorflow": {"eager": "tf.math.accumulate_n"}}},
    "Acos": {"description": "The Acos operation.", "operation": "Acos", "variants": {"cupy": {"generator": "cp.arccos"}, "dask": {"generator": "da.arccos"}, "numpy": {"generator": "np.arccos"}, "tensorflow": {"eager": "tf.acos"}}},
    "Acosh": {"description": "The Acosh operation.", "operation": "Acosh", "variants": {"cupy": {"generator": "cp.arccosh"}, "dask": {"generator": "da.arccosh"}, "numpy": {"generator": "np.arccosh"}, "tensorflow": {"eager": "tf.acosh"}}},
    "Add": {
        "description": "The Add operation.",
        "operation": "Add",
        "variants": {
            "cupy": {"eager": "cp.add", "generator": "cp.add"},
            "dask": {"eager": "da.add", "generator": "da.add"},
            "edge_onnx": {"generator": "Add"},
            "edge_stablehlo": {"generator": "stablehlo.add"},
            "keras": {"eager": "keras_ops.add"},
            "numpy": {"generator": "np.add"},
            "tensorflow": {"eager": "tf.add"},
        },
    },
    "AddN": {"description": "The AddN operation.", "operation": "AddN", "variants": {"tensorflow": {"eager": "tf.add_n"}}},
    "Adjoint": {"description": "The Adjoint operation.", "operation": "Adjoint", "variants": {"numpy": {"generator": "tf.linalg.adjoint"}, "tensorflow": {"eager": "tf.linalg.adjoint"}}},
    "AffineGrid": {"description": "The AffineGrid operation.", "operation": "AffineGrid", "variants": {"pytorch": {"generator": "torch.nn.functional.affine_grid({0}, {size}, align_corners={align_corners})"}}},
    "All": {"description": "The All operation.", "operation": "All", "variants": {"cupy": {"eager": "cp.all"}, "dask": {"eager": "da.all"}, "keras": {"eager": "keras_ops.all"}, "pytorch": {"generator": "torch.all({0}, dim={axis}, keepdim={keepdims})"}}},
    "AllToAll": {"description": "The AllToAll operation.", "operation": "AllToAll", "variants": {"numpy": {"generator": "{0}"}}},
    "Allclose": {
        "description": "The Allclose operation.",
        "operation": "Allclose",
        "variants": {"cupy": {"eager": "cp.allclose"}, "dask": {"eager": "da.allclose"}, "numpy": {"generator": "np.allclose"}, "pytorch": {"generator": "torch.allclose({0}, {1}, rtol={rtol}, atol={atol}, equal_nan={equal_nan})"}},
    },
    "Angle": {"description": "The Angle operation.", "operation": "Angle", "variants": {"cupy": {"eager": "cp.angle"}, "dask": {"eager": "da.angle"}, "keras": {"eager": "keras_ops.angle"}, "tensorflow": {"eager": "tf.math.angle"}}},
    "Any": {"description": "The Any operation.", "operation": "Any", "variants": {"cupy": {"eager": "cp.any"}, "dask": {"eager": "da.any"}, "keras": {"eager": "keras_ops.any"}}},
    "AnyOp": {"description": "The AnyOp operation.", "operation": "AnyOp", "variants": {"pytorch": {"generator": "torch.any({0}, dim={axis}, keepdim={keepdims})"}}},
    "Append": {"description": "The Append operation.", "operation": "Append", "variants": {"cupy": {"eager": "cp.append"}, "dask": {"eager": "da.append"}, "keras": {"eager": "keras_ops.append"}}},
    "ApplyOverAxes": {"description": "The ApplyOverAxes operation.", "operation": "ApplyOverAxes", "variants": {"cupy": {"eager": "cp.apply_over_axes"}, "dask": {"eager": "da.apply_over_axes"}}},
    "Arange": {"description": "The Arange operation.", "operation": "Arange", "variants": {"numpy": {"generator": "np.arange"}, "pytorch": {"generator": "torch.arange({0})"}}},
    "ArgSort": {"description": "The ArgSort operation.", "operation": "ArgSort", "variants": {"numpy": {"generator": "np.argsort"}, "pytorch": {"generator": "torch.argsort({0}, dim={dimension})"}}},
    "Argmax": {
        "description": "The Argmax operation.",
        "operation": "Argmax",
        "variants": {"cupy": {"eager": "cp.argmax"}, "dask": {"eager": "da.argmax"}, "keras": {"eager": "keras_ops.argmax"}, "pytorch": {"generator": "torch.argmax({0}, dim={axis}, keepdim={keepdims})"}, "tensorflow": {"eager": "tf.argmax"}},
    },
    "Argmin": {
        "description": "The Argmin operation.",
        "operation": "Argmin",
        "variants": {"cupy": {"eager": "cp.argmin"}, "dask": {"eager": "da.argmin"}, "keras": {"eager": "keras_ops.argmin"}, "pytorch": {"generator": "torch.argmin({0}, dim={axis}, keepdim={keepdims})"}, "tensorflow": {"eager": "tf.argmin"}},
    },
    "Argpartition": {"description": "The Argpartition operation.", "operation": "Argpartition", "variants": {"keras": {"eager": "keras_ops.argpartition"}}},
    "Argwhere": {"description": "The Argwhere operation.", "operation": "Argwhere", "variants": {"cupy": {"eager": "cp.argwhere"}, "dask": {"eager": "da.argwhere"}}},
    "AsString": {"description": "The AsString operation.", "operation": "AsString", "variants": {"tensorflow": {"eager": "tf.as_string"}}},
    "Asin": {"description": "The Asin operation.", "operation": "Asin", "variants": {"cupy": {"generator": "cp.arcsin"}, "dask": {"generator": "da.arcsin"}, "numpy": {"generator": "np.arcsin"}, "tensorflow": {"eager": "tf.asin"}}},
    "Asinh": {"description": "The Asinh operation.", "operation": "Asinh", "variants": {"cupy": {"generator": "cp.arcsinh"}, "dask": {"generator": "da.arcsinh"}, "numpy": {"generator": "np.arcsinh"}, "tensorflow": {"eager": "tf.asinh"}}},
    "AssignVariable": {"description": "The AssignVariable operation.", "operation": "AssignVariable", "variants": {"pytorch": {"generator": "{0}"}}},
    "AssociativeScan": {"description": "The AssociativeScan operation.", "operation": "AssociativeScan", "variants": {"keras": {"eager": "keras_ops.associative_scan"}}},
    "Atan": {"description": "The Atan operation.", "operation": "Atan", "variants": {"cupy": {"generator": "cp.arctan"}, "dask": {"generator": "da.arctan"}, "numpy": {"generator": "np.arctan"}, "tensorflow": {"eager": "tf.atan"}}},
    "Atan2": {"description": "The Atan2 operation.", "operation": "Atan2", "variants": {"cupy": {"generator": "cp.arctan2"}, "dask": {"generator": "da.arctan2"}, "numpy": {"generator": "np.arctan2"}, "tensorflow": {"eager": "tf.atan2"}}},
    "Atanh": {"description": "The Atanh operation.", "operation": "Atanh", "variants": {"cupy": {"generator": "cp.arctanh"}, "dask": {"generator": "da.arctanh"}, "numpy": {"generator": "np.arctanh"}, "tensorflow": {"eager": "tf.atanh"}}},
    "Average": {"description": "The Average operation.", "operation": "Average", "variants": {"cupy": {"eager": "cp.average"}, "dask": {"eager": "da.average"}, "keras": {"eager": "keras_ops.average"}}},
    "AvgPool": {"description": "The AvgPool operation.", "operation": "AvgPool", "variants": {"edge_onnx": {"generator": "AveragePool"}}},
    "AvgPool2D": {"description": "The AvgPool2D operation.", "operation": "AvgPool2D", "variants": {"edge_onnx": {"generator": "AveragePool"}}},
    "AxisIndex": {"description": "The AxisIndex operation.", "operation": "AxisIndex", "variants": {"numpy": {"generator": "0"}}},
    "BandPart": {"description": "The BandPart operation.", "operation": "BandPart", "variants": {"numpy": {"generator": "tf.linalg.band_part"}, "tensorflow": {"eager": "tf.linalg.band_part"}}},
    "BandedTriangularSolve": {"description": "The BandedTriangularSolve operation.", "operation": "BandedTriangularSolve", "variants": {"tensorflow": {"eager": "tf.linalg.banded_triangular_solve"}}},
    "BatchNorm": {"description": "The BatchNorm operation.", "operation": "BatchNorm", "variants": {"edge_onnx": {"generator": "BatchNormalization"}}},
    "BesselI0": {"description": "The BesselI0 operation.", "operation": "BesselI0", "variants": {"tensorflow": {"eager": "tf.math.bessel_i0"}}},
    "BesselI0e": {"description": "The BesselI0e operation.", "operation": "BesselI0e", "variants": {"numpy": {"generator": "scipy.special.i0e"}, "tensorflow": {"eager": "tf.math.bessel_i0e"}}},
    "BesselI1": {"description": "The BesselI1 operation.", "operation": "BesselI1", "variants": {"tensorflow": {"eager": "tf.math.bessel_i1"}}},
    "BesselI1e": {"description": "The BesselI1e operation.", "operation": "BesselI1e", "variants": {"numpy": {"generator": "scipy.special.i1e"}, "tensorflow": {"eager": "tf.math.bessel_i1e"}}},
    "Beta": {"description": "The Beta operation.", "operation": "Beta", "variants": {"numpy": {"generator": "np.random.beta({1}, {2}, size={shape})"}}},
    "Betainc": {"description": "The Betainc operation.", "operation": "Betainc", "variants": {"numpy": {"generator": "scipy.special.betainc"}, "tensorflow": {"eager": "tf.math.betainc"}}},
    "Bincount": {"description": "The Bincount operation.", "operation": "Bincount", "variants": {"cupy": {"eager": "cp.bincount"}, "dask": {"eager": "da.bincount"}, "keras": {"eager": "keras_ops.bincount"}, "numpy": {"generator": "np.bincount"}, "tensorflow": {"eager": "tf.math.bincount"}}},
    "Bitcast": {"description": "The Bitcast operation.", "operation": "Bitcast", "variants": {"pytorch": {"generator": "{0}.view(getattr(torch, str('{dtype}')))"}, "tensorflow": {"eager": "tf.bitcast"}}},
    "BitwiseAnd": {"description": "The BitwiseAnd operation.", "operation": "BitwiseAnd", "variants": {"cupy": {"eager": "cp.bitwise_and"}, "dask": {"eager": "da.bitwise_and"}, "keras": {"eager": "keras_ops.bitwise_and"}}},
    "BitwiseNot": {"description": "The BitwiseNot operation.", "operation": "BitwiseNot", "variants": {"cupy": {"eager": "cp.bitwise_not"}, "dask": {"eager": "da.bitwise_not"}, "keras": {"eager": "keras_ops.bitwise_not"}}},
    "BitwiseOr": {"description": "The BitwiseOr operation.", "operation": "BitwiseOr", "variants": {"cupy": {"eager": "cp.bitwise_or"}, "dask": {"eager": "da.bitwise_or"}, "keras": {"eager": "keras_ops.bitwise_or"}}},
    "BitwiseXor": {"description": "The BitwiseXor operation.", "operation": "BitwiseXor", "variants": {"cupy": {"eager": "cp.bitwise_xor"}, "dask": {"eager": "da.bitwise_xor"}, "keras": {"eager": "keras_ops.bitwise_xor"}}},
    "Block": {"description": "The Block operation.", "operation": "Block", "variants": {"cupy": {"eager": "cp.block"}, "dask": {"eager": "da.block"}}},
    "BooleanMask": {"description": "The BooleanMask operation.", "operation": "BooleanMask", "variants": {"tensorflow": {"eager": "tf.boolean_mask"}}},
    "Broadcast": {"description": "The Broadcast operation.", "operation": "Broadcast", "variants": {"edge_stablehlo": {"generator": "stablehlo.broadcast_in_dim"}}},
    "BroadcastTo": {
        "description": "The BroadcastTo operation.",
        "operation": "BroadcastTo",
        "variants": {
            "cupy": {"eager": "cp.broadcast_to", "generator": "cp.broadcast_to"},
            "dask": {"eager": "da.broadcast_to", "generator": "da.broadcast_to"},
            "keras": {"eager": "keras_ops.broadcast_to"},
            "numpy": {"generator": "np.broadcast_to"},
            "pytorch": {"generator": "{0}.expand({shape})"},
            "tensorflow": {"eager": "tf.broadcast_to"},
        },
    },
    "BroadcastToRank": {"description": "The BroadcastToRank operation.", "operation": "BroadcastToRank", "variants": {"numpy": {"generator": "np.expand_dims({0}, axis=tuple(range({0}.ndim, {1}))) if hasattr({0}, 'ndim') else {0}"}}},
    "BroadcastedIota": {"description": "The BroadcastedIota operation.", "operation": "BroadcastedIota", "variants": {"numpy": {"generator": "np.broadcasted_iota"}}},
    "C_": {"description": "The C_ operation.", "operation": "C_", "variants": {"numpy": {"generator": "np.c_"}}},
    "Cast": {
        "description": "The Cast operation.",
        "operation": "Cast",
        "variants": {"edge_onnx": {"generator": "Cast"}, "edge_stablehlo": {"generator": "stablehlo.convert"}, "keras": {"eager": "keras_ops.cast"}, "pytorch": {"generator": "getattr({0}, str('{dtype}'))()"}, "tensorflow": {"eager": "tf.cast"}},
    },
    "Cbrt": {"description": "The Cbrt operation.", "operation": "Cbrt", "variants": {"cupy": {"eager": "cp.cbrt"}, "dask": {"eager": "da.cbrt"}, "edge_stablehlo": {"generator": "stablehlo.cbrt"}}},
    "Ceil": {
        "description": "The Ceil operation.",
        "operation": "Ceil",
        "variants": {"cupy": {"eager": "cp.ceil"}, "dask": {"eager": "da.ceil"}, "edge_onnx": {"generator": "Ceil"}, "edge_stablehlo": {"generator": "stablehlo.ceil"}, "keras": {"eager": "keras_ops.ceil"}, "tensorflow": {"eager": "tf.math.ceil"}},
    },
    "Cholesky": {
        "description": "The Cholesky operation.",
        "operation": "Cholesky",
        "variants": {"cupy": {"eager": "cp.linalg.cholesky"}, "dask": {"eager": "da.linalg.cholesky"}, "keras": {"eager": "keras_ops.cholesky"}, "numpy": {"generator": "np.linalg.cholesky"}, "tensorflow": {"eager": "tf.linalg.cholesky"}},
    },
    "CholeskySolve": {"description": "The CholeskySolve operation.", "operation": "CholeskySolve", "variants": {"numpy": {"generator": "np.linalg.solve(np.matmul({0}, np.swapaxes({0}, -1, -2)), {1})"}, "tensorflow": {"eager": "tf.linalg.cholesky_solve"}}},
    "Choose": {"description": "The Choose operation.", "operation": "Choose", "variants": {"cupy": {"eager": "cp.choose"}, "dask": {"eager": "da.choose"}}},
    "Clip": {"description": "The Clip operation.", "operation": "Clip", "variants": {"cupy": {"eager": "cp.clip"}, "dask": {"eager": "da.clip"}, "keras": {"eager": "keras_ops.clip"}, "numpy": {"generator": "np.clip({0}, a_min={a_min}, a_max={a_max})"}}},
    "Collapse": {"description": "The Collapse operation.", "operation": "Collapse", "variants": {"numpy": {"generator": "np.reshape({0}, (-1,) + {0}.shape[{1}:])"}}},
    "Compress": {"description": "The Compress operation.", "operation": "Compress", "variants": {"cupy": {"eager": "cp.compress"}, "dask": {"eager": "da.compress"}}},
    "Concat": {"description": "The Concat operation.", "operation": "Concat", "variants": {"edge_onnx": {"generator": "Concat"}, "edge_stablehlo": {"generator": "stablehlo.concatenate"}}},
    "Concatenate": {"description": "The Concatenate operation.", "operation": "Concatenate", "variants": {"cupy": {"eager": "cp.concatenate"}, "dask": {"eager": "da.concatenate"}, "keras": {"eager": "keras_ops.concatenate"}}},
    "Cond": {"description": "The Cond operation.", "operation": "Cond", "variants": {"keras": {"eager": "keras_ops.cond"}, "numpy": {"generator": "np.linalg.cond"}, "tensorflow": {"eager": "tf.cond"}}},
    "ConfusionMatrix": {"description": "The ConfusionMatrix operation.", "operation": "ConfusionMatrix", "variants": {"tensorflow": {"eager": "tf.math.confusion_matrix"}}},
    "Conj": {"description": "The Conj operation.", "operation": "Conj", "variants": {"cupy": {"eager": "cp.conj"}, "dask": {"eager": "da.conj"}, "keras": {"eager": "keras_ops.conj"}, "tensorflow": {"eager": "tf.math.conj"}}},
    "Conv2D": {"description": "The Conv2D operation.", "operation": "Conv2D", "variants": {"edge_onnx": {"generator": "Conv"}, "edge_stablehlo": {"generator": "stablehlo.convolution"}}},
    "ConvTranspose": {"description": "The ConvTranspose operation.", "operation": "ConvTranspose", "variants": {"keras": {"eager": "keras_ops.conv_transpose"}, "tensorflow": {"eager": "tf.nn.conv_transpose"}}},
    "ConvTransposeShapeTuple": {"description": "The ConvTransposeShapeTuple operation.", "operation": "ConvTransposeShapeTuple", "variants": {"numpy": {"generator": "()"}}},
    "Copysign": {"description": "The Copysign operation.", "operation": "Copysign", "variants": {"cupy": {"eager": "cp.copysign"}, "dask": {"eager": "da.copysign"}}},
    "Corrcoef": {"description": "The Corrcoef operation.", "operation": "Corrcoef", "variants": {"cupy": {"eager": "cp.corrcoef"}, "dask": {"eager": "da.corrcoef"}}},
    "Correlate": {"description": "The Correlate operation.", "operation": "Correlate", "variants": {"keras": {"eager": "keras_ops.correlate"}}},
    "Cos": {
        "description": "The Cos operation.",
        "operation": "Cos",
        "variants": {
            "cupy": {"eager": "cp.cos", "generator": "cp.cos"},
            "dask": {"eager": "da.cos", "generator": "da.cos"},
            "edge_onnx": {"generator": "Cos"},
            "edge_stablehlo": {"generator": "stablehlo.cosine"},
            "keras": {"eager": "keras_ops.cos"},
            "numpy": {"generator": "np.cos"},
            "tensorflow": {"eager": "tf.cos"},
        },
    },
    "Cosh": {"description": "The Cosh operation.", "operation": "Cosh", "variants": {"cupy": {"eager": "cp.cosh"}, "dask": {"eager": "da.cosh"}, "keras": {"eager": "keras_ops.cosh"}, "tensorflow": {"eager": "tf.cosh"}}},
    "CountNonzero": {"description": "The CountNonzero operation.", "operation": "CountNonzero", "variants": {"cupy": {"eager": "cp.count_nonzero"}, "dask": {"eager": "da.count_nonzero"}, "keras": {"eager": "keras_ops.count_nonzero"}, "tensorflow": {"eager": "tf.math.count_nonzero"}}},
    "Cov": {"description": "The Cov operation.", "operation": "Cov", "variants": {"cupy": {"eager": "cp.cov"}, "dask": {"eager": "da.cov"}}},
    "CreateToken": {"description": "The CreateToken operation.", "operation": "CreateToken", "variants": {"numpy": {"generator": "0"}}},
    "Cross": {"description": "The Cross operation.", "operation": "Cross", "variants": {"keras": {"eager": "keras_ops.cross"}, "numpy": {"generator": "np.cross"}, "tensorflow": {"eager": "tf.linalg.cross"}}},
    "CtcLoss": {"description": "The CtcLoss operation.", "operation": "CtcLoss", "variants": {"keras": {"eager": "keras_ops.ctc_loss"}, "tensorflow": {"eager": "tf.nn.ctc_loss"}}},
    "Cumlogsumexp": {"description": "The Cumlogsumexp operation.", "operation": "Cumlogsumexp", "variants": {"numpy": {"generator": "np.logaddexp.accumulate"}}},
    "Cummax": {"description": "The Cummax operation.", "operation": "Cummax", "variants": {"numpy": {"generator": "np.maximum.accumulate"}}},
    "Cummin": {"description": "The Cummin operation.", "operation": "Cummin", "variants": {"numpy": {"generator": "np.minimum.accumulate"}}},
    "Cumprod": {"description": "The Cumprod operation.", "operation": "Cumprod", "variants": {"cupy": {"eager": "cp.cumprod"}, "dask": {"eager": "da.cumprod"}, "keras": {"eager": "keras_ops.cumprod"}, "numpy": {"generator": "np.cumprod"}, "tensorflow": {"eager": "tf.math.cumprod"}}},
    "Cumsum": {"description": "The Cumsum operation.", "operation": "Cumsum", "variants": {"cupy": {"eager": "cp.cumsum"}, "dask": {"eager": "da.cumsum"}, "keras": {"eager": "keras_ops.cumsum"}, "numpy": {"generator": "np.cumsum"}, "tensorflow": {"eager": "tf.cumsum"}}},
    "CumulativeLogsumexp": {"description": "The CumulativeLogsumexp operation.", "operation": "CumulativeLogsumexp", "variants": {"tensorflow": {"eager": "tf.math.cumulative_logsumexp"}}},
    "Degrees": {"description": "The Degrees operation.", "operation": "Degrees", "variants": {"cupy": {"eager": "cp.degrees"}, "dask": {"eager": "da.degrees"}}},
    "Delete": {"description": "The Delete operation.", "operation": "Delete", "variants": {"cupy": {"eager": "cp.delete"}, "dask": {"eager": "da.delete"}}},
    "Det": {"description": "The Det operation.", "operation": "Det", "variants": {"keras": {"eager": "keras_ops.det"}, "numpy": {"generator": "np.linalg.det"}, "tensorflow": {"eager": "tf.linalg.det"}}},
    "Diag": {"description": "The Diag operation.", "operation": "Diag", "variants": {"cupy": {"eager": "cp.diag"}, "dask": {"eager": "da.diag"}, "keras": {"eager": "keras_ops.diag"}, "tensorflow": {"eager": "tf.linalg.diag"}}},
    "Diagflat": {"description": "The Diagflat operation.", "operation": "Diagflat", "variants": {"keras": {"eager": "keras_ops.diagflat"}}},
    "Diagonal": {"description": "The Diagonal operation.", "operation": "Diagonal", "variants": {"cupy": {"eager": "cp.diagonal"}, "dask": {"eager": "da.diagonal"}, "keras": {"eager": "keras_ops.diagonal"}, "numpy": {"generator": "np.diagonal({0}, offset={offset}, axis1={axis1}, axis2={axis2})"}}},
    "Diff": {"description": "The Diff operation.", "operation": "Diff", "variants": {"cupy": {"eager": "cp.diff"}, "dask": {"eager": "da.diff"}, "keras": {"eager": "keras_ops.diff"}}},
    "Digamma": {"description": "The Digamma operation.", "operation": "Digamma", "variants": {"tensorflow": {"eager": "tf.math.digamma"}}},
    "Digitize": {"description": "The Digitize operation.", "operation": "Digitize", "variants": {"cupy": {"eager": "cp.digitize"}, "dask": {"eager": "da.digitize"}, "keras": {"eager": "keras_ops.digitize"}}},
    "Dirichlet": {"description": "The Dirichlet operation.", "operation": "Dirichlet", "variants": {"numpy": {"generator": "np.random.dirichlet({1}, size={shape})"}}},
    "Div": {"description": "The Div operation.", "operation": "Div", "variants": {"edge_onnx": {"generator": "Div"}, "edge_stablehlo": {"generator": "stablehlo.divide"}}},
    "Divide": {"description": "The Divide operation.", "operation": "Divide", "variants": {"cupy": {"eager": "cp.divide"}, "dask": {"eager": "da.divide"}, "keras": {"eager": "keras_ops.divide"}, "tensorflow": {"eager": "tf.divide"}}},
    "DivideNoNan": {"description": "The DivideNoNan operation.", "operation": "DivideNoNan", "variants": {"keras": {"eager": "keras_ops.divide_no_nan"}, "tensorflow": {"eager": "tf.math.divide_no_nan"}}},
    "Divmod": {"description": "The Divmod operation.", "operation": "Divmod", "variants": {"cupy": {"eager": "cp.divmod"}, "dask": {"eager": "da.divmod"}}},
    "Dot": {"description": "The Dot operation.", "operation": "Dot", "variants": {"cupy": {"eager": "cp.dot"}, "dask": {"eager": "da.dot"}, "keras": {"eager": "keras_ops.dot"}}},
    "DrawBoundingBoxes": {"description": "The DrawBoundingBoxes operation.", "operation": "DrawBoundingBoxes", "variants": {"pytorch": {"generator": "torchvision.utils.draw_bounding_boxes({0}, {1}, colors={colors}, labels={texts})"}}},
    "Dropout": {"description": "The Dropout operation.", "operation": "Dropout", "variants": {"tensorflow": {"eager": "tf.nn.dropout"}}},
    "Dstack": {"description": "The Dstack operation.", "operation": "Dstack", "variants": {"cupy": {"eager": "cp.dstack"}, "dask": {"eager": "da.dstack"}}},
    "DynamicPartition": {"description": "The DynamicPartition operation.", "operation": "DynamicPartition", "variants": {"tensorflow": {"eager": "tf.dynamic_partition"}}},
    "DynamicStitch": {"description": "The DynamicStitch operation.", "operation": "DynamicStitch", "variants": {"tensorflow": {"eager": "tf.dynamic_stitch"}}},
    "Ediff1d": {"description": "The Ediff1d operation.", "operation": "Ediff1d", "variants": {"cupy": {"eager": "cp.ediff1d"}, "dask": {"eager": "da.ediff1d"}}},
    "EditDistance": {"description": "The EditDistance operation.", "operation": "EditDistance", "variants": {"tensorflow": {"eager": "tf.edit_distance"}}},
    "Eig": {"description": "The Eig operation.", "operation": "Eig", "variants": {"keras": {"eager": "keras_ops.eig"}, "numpy": {"generator": "np.linalg.eig"}, "tensorflow": {"eager": "tf.eig"}}},
    "Eigh": {"description": "The Eigh operation.", "operation": "Eigh", "variants": {"keras": {"eager": "keras_ops.eigh"}, "numpy": {"generator": "np.linalg.eigh"}, "tensorflow": {"eager": "tf.linalg.eigh"}}},
    "EighTridiagonal": {"description": "The EighTridiagonal operation.", "operation": "EighTridiagonal", "variants": {"tensorflow": {"eager": "tf.linalg.eigh_tridiagonal"}}},
    "Eigvals": {"description": "The Eigvals operation.", "operation": "Eigvals", "variants": {"tensorflow": {"eager": "tf.eigvals"}}},
    "Eigvalsh": {"description": "The Eigvalsh operation.", "operation": "Eigvalsh", "variants": {"numpy": {"generator": "np.linalg.eigvalsh"}, "tensorflow": {"eager": "tf.linalg.eigvalsh"}}},
    "Einsum": {"description": "The Einsum operation.", "operation": "Einsum", "variants": {"cupy": {"eager": "cp.einsum"}, "dask": {"eager": "da.einsum"}, "keras": {"eager": "keras_ops.einsum"}, "tensorflow": {"eager": "tf.einsum"}}},
    "Equal": {
        "description": "The Equal operation.",
        "operation": "Equal",
        "variants": {
            "cupy": {"eager": "cp.equal", "generator": "cp.equal"},
            "dask": {"eager": "da.equal", "generator": "da.equal"},
            "edge_onnx": {"generator": "Equal"},
            "edge_stablehlo": {"generator": "stablehlo.compare"},
            "keras": {"eager": "keras_ops.equal"},
            "numpy": {"generator": "np.equal"},
            "tensorflow": {"eager": "tf.equal"},
        },
    },
    "Erf": {"description": "The Erf operation.", "operation": "Erf", "variants": {"keras": {"eager": "keras_ops.erf"}, "tensorflow": {"eager": "tf.math.erf"}}},
    "Erfc": {"description": "The Erfc operation.", "operation": "Erfc", "variants": {"tensorflow": {"eager": "tf.math.erfc"}}},
    "Erfcinv": {"description": "The Erfcinv operation.", "operation": "Erfcinv", "variants": {"tensorflow": {"eager": "tf.math.erfcinv"}}},
    "Erfinv": {"description": "The Erfinv operation.", "operation": "Erfinv", "variants": {"keras": {"eager": "keras_ops.erfinv"}, "numpy": {"generator": "scipy.special.erfinv"}, "pytorch": {"generator": "torch.erfinv({0})"}, "tensorflow": {"eager": "tf.math.erfinv"}}},
    "Exp": {
        "description": "The Exp operation.",
        "operation": "Exp",
        "variants": {
            "cupy": {"eager": "cp.exp", "generator": "cp.exp"},
            "dask": {"eager": "da.exp", "generator": "da.exp"},
            "edge_onnx": {"generator": "Exp"},
            "edge_stablehlo": {"generator": "stablehlo.exponential"},
            "keras": {"eager": "keras_ops.exp"},
            "numpy": {"generator": "np.exp"},
            "tensorflow": {"eager": "tf.exp"},
        },
    },
    "Exp2": {"description": "The Exp2 operation.", "operation": "Exp2", "variants": {"cupy": {"eager": "cp.exp2"}, "dask": {"eager": "da.exp2"}, "keras": {"eager": "keras_ops.exp2"}}},
    "ExpandDims": {"description": "The ExpandDims operation.", "operation": "ExpandDims", "variants": {"cupy": {"eager": "cp.expand_dims"}, "dask": {"eager": "da.expand_dims"}, "keras": {"eager": "keras_ops.expand_dims"}, "tensorflow": {"eager": "tf.expand_dims"}}},
    "Expm1": {"description": "The Expm1 operation.", "operation": "Expm1", "variants": {"cupy": {"eager": "cp.expm1"}, "dask": {"eager": "da.expm1"}, "keras": {"eager": "keras_ops.expm1"}, "tensorflow": {"eager": "tf.math.expm1"}}},
    "Extract": {"description": "The Extract operation.", "operation": "Extract", "variants": {"cupy": {"eager": "cp.extract"}, "dask": {"eager": "da.extract"}}},
    "ExtractVolumePatches": {"description": "The ExtractVolumePatches operation.", "operation": "ExtractVolumePatches", "variants": {"tensorflow": {"eager": "tf.extract_volume_patches"}}},
    "Fabs": {"description": "The Fabs operation.", "operation": "Fabs", "variants": {"cupy": {"eager": "cp.fabs"}, "dask": {"eager": "da.fabs"}}},
    "Fft": {"description": "The Fft operation.", "operation": "Fft", "variants": {"cupy": {"eager": "cp.fft"}, "dask": {"eager": "da.fft"}, "keras": {"eager": "keras_ops.fft"}, "numpy": {"generator": "np.fft.fft"}}},
    "Fft2": {"description": "The Fft2 operation.", "operation": "Fft2", "variants": {"cupy": {"eager": "cp.fft.fft2"}, "dask": {"eager": "da.fft.fft2"}, "keras": {"eager": "keras_ops.fft2"}}},
    "Fft2d": {"description": "The Fft2d operation.", "operation": "Fft2d", "variants": {"pytorch": {"generator": "torch.fft.fft2({0}, s={s}, dim={axes})"}}},
    "Fft3d": {"description": "The Fft3d operation.", "operation": "Fft3d", "variants": {"pytorch": {"generator": "torch.fft.fftn({0}, s={s}, dim={axes})"}}},
    "Fftfreq": {"description": "The Fftfreq operation.", "operation": "Fftfreq", "variants": {"cupy": {"eager": "cp.fft.fftfreq"}, "dask": {"eager": "da.fft.fftfreq"}}},
    "Fftn": {"description": "The Fftn operation.", "operation": "Fftn", "variants": {"cupy": {"eager": "cp.fft.fftn"}, "dask": {"eager": "da.fft.fftn"}, "numpy": {"generator": "np.fft.fftn"}}},
    "Fftnd": {"description": "The Fftnd operation.", "operation": "Fftnd", "variants": {"numpy": {"generator": "np.fft.fftn({0})"}, "tensorflow": {"eager": "tf.fftnd"}}},
    "Fftshift": {"description": "The Fftshift operation.", "operation": "Fftshift", "variants": {"cupy": {"eager": "cp.fft.fftshift"}, "dask": {"eager": "da.fft.fftshift"}, "numpy": {"generator": "np.fft.fftshift({0})"}}},
    "Fix": {"description": "The Fix operation.", "operation": "Fix", "variants": {"cupy": {"eager": "cp.fix"}, "dask": {"eager": "da.fix"}}},
    "Flatnonzero": {"description": "The Flatnonzero operation.", "operation": "Flatnonzero", "variants": {"cupy": {"eager": "cp.flatnonzero"}, "dask": {"eager": "da.flatnonzero"}}},
    "Flip": {"description": "The Flip operation.", "operation": "Flip", "variants": {"cupy": {"eager": "cp.flip"}, "dask": {"eager": "da.flip"}, "keras": {"eager": "keras_ops.flip"}}},
    "Fliplr": {"description": "The Fliplr operation.", "operation": "Fliplr", "variants": {"cupy": {"eager": "cp.fliplr"}, "dask": {"eager": "da.fliplr"}}},
    "Flipud": {"description": "The Flipud operation.", "operation": "Flipud", "variants": {"cupy": {"eager": "cp.flipud"}, "dask": {"eager": "da.flipud"}}},
    "FloatPower": {"description": "The FloatPower operation.", "operation": "FloatPower", "variants": {"cupy": {"eager": "cp.float_power"}, "dask": {"eager": "da.float_power"}}},
    "Floor": {
        "description": "The Floor operation.",
        "operation": "Floor",
        "variants": {"cupy": {"eager": "cp.floor"}, "dask": {"eager": "da.floor"}, "edge_onnx": {"generator": "Floor"}, "edge_stablehlo": {"generator": "stablehlo.floor"}, "keras": {"eager": "keras_ops.floor"}, "tensorflow": {"eager": "tf.floor"}},
    },
    "FloorDivide": {"description": "The FloorDivide operation.", "operation": "FloorDivide", "variants": {"cupy": {"eager": "cp.floor_divide"}, "dask": {"eager": "da.floor_divide"}, "keras": {"eager": "keras_ops.floor_divide"}}},
    "Fmax": {"description": "The Fmax operation.", "operation": "Fmax", "variants": {"cupy": {"eager": "cp.fmax"}, "dask": {"eager": "da.fmax"}}},
    "Fmin": {"description": "The Fmin operation.", "operation": "Fmin", "variants": {"cupy": {"eager": "cp.fmin"}, "dask": {"eager": "da.fmin"}}},
    "Fmod": {"description": "The Fmod operation.", "operation": "Fmod", "variants": {"cupy": {"eager": "cp.fmod"}, "dask": {"eager": "da.fmod"}}},
    "FractionalAvgPool": {"description": "The FractionalAvgPool operation.", "operation": "FractionalAvgPool", "variants": {"tensorflow": {"eager": "tf.nn.fractional_avg_pool"}}},
    "FractionalMaxPool": {"description": "The FractionalMaxPool operation.", "operation": "FractionalMaxPool", "variants": {"tensorflow": {"eager": "tf.nn.fractional_max_pool"}}},
    "Frexp": {"description": "The Frexp operation.", "operation": "Frexp", "variants": {"cupy": {"eager": "cp.frexp"}, "dask": {"eager": "da.frexp"}}},
    "Fromfile": {"description": "The Fromfile operation.", "operation": "Fromfile", "variants": {"numpy": {"generator": "np.fromfile"}}},
    "Fromfunction": {"description": "The Fromfunction operation.", "operation": "Fromfunction", "variants": {"cupy": {"eager": "cp.fromfunction"}, "dask": {"eager": "da.fromfunction"}, "numpy": {"generator": "np.fromfunction"}}},
    "Fromiter": {"description": "The Fromiter operation.", "operation": "Fromiter", "variants": {"numpy": {"generator": "np.fromiter"}}},
    "Frompyfunc": {"description": "The Frompyfunc operation.", "operation": "Frompyfunc", "variants": {"cupy": {"eager": "cp.frompyfunc"}, "dask": {"eager": "da.frompyfunc"}, "numpy": {"generator": "np.frompyfunc"}}},
    "Fromstring": {"description": "The Fromstring operation.", "operation": "Fromstring", "variants": {"numpy": {"generator": "np.fromstring"}}},
    "Full": {"description": "The Full operation.", "operation": "Full", "variants": {"numpy": {"generator": "np.full"}, "pytorch": {"generator": "torch.full({shape}, {fill_value})"}}},
    "Gamma": {"description": "The Gamma operation.", "operation": "Gamma", "variants": {"numpy": {"generator": "np.random.gamma({1}, size={shape})"}}},
    "Gather": {"description": "The Gather operation.", "operation": "Gather", "variants": {"edge_onnx": {"generator": "Gather"}, "edge_stablehlo": {"generator": "stablehlo.gather"}, "tensorflow": {"eager": "tf.gather"}}},
    "GatherNd": {"description": "The GatherNd operation.", "operation": "GatherNd", "variants": {"tensorflow": {"eager": "tf.gather_nd"}}},
    "Geomspace": {"description": "The Geomspace operation.", "operation": "Geomspace", "variants": {"numpy": {"generator": "np.geomspace"}}},
    "GetItem": {"description": "The GetItem operation.", "operation": "GetItem", "variants": {"keras": {"eager": "keras_ops.get_item"}}},
    "Gradient": {"description": "The Gradient operation.", "operation": "Gradient", "variants": {"numpy": {"generator": "np.gradient"}}},
    "Greater": {
        "description": "The Greater operation.",
        "operation": "Greater",
        "variants": {
            "cupy": {"eager": "cp.greater", "generator": "cp.greater"},
            "dask": {"eager": "da.greater", "generator": "da.greater"},
            "edge_onnx": {"generator": "Greater"},
            "edge_stablehlo": {"generator": "stablehlo.compare"},
            "keras": {"eager": "keras_ops.greater"},
            "numpy": {"generator": "np.greater"},
            "tensorflow": {"eager": "tf.greater"},
        },
    },
    "GreaterEqual": {"description": "The GreaterEqual operation.", "operation": "GreaterEqual", "variants": {"cupy": {"eager": "cp.greater_equal"}, "dask": {"eager": "da.greater_equal"}, "keras": {"eager": "keras_ops.greater_equal"}, "tensorflow": {"eager": "tf.greater_equal"}}},
    "GridSample": {"description": "The GridSample operation.", "operation": "GridSample", "variants": {"pytorch": {"generator": "torch.nn.functional.grid_sample({0}, {1}, mode={mode}, padding_mode={padding_mode}, align_corners={align_corners})"}}},
    "HammingWindow": {"description": "The HammingWindow operation.", "operation": "HammingWindow", "variants": {"pytorch": {"generator": "torch.hamming_window({window_length}, periodic={periodic}, alpha={alpha}, beta={beta})"}}},
    "HannWindow": {"description": "The HannWindow operation.", "operation": "HannWindow", "variants": {"pytorch": {"generator": "torch.hann_window({window_length}, periodic={periodic})"}}},
    "HardSilu": {"description": "The HardSilu operation.", "operation": "HardSilu", "variants": {"keras": {"eager": "keras_ops.hard_silu"}}},
    "HardSwish": {"description": "The HardSwish operation.", "operation": "HardSwish", "variants": {"keras": {"eager": "keras_ops.hard_swish"}}},
    "Hfft": {"description": "The Hfft operation.", "operation": "Hfft", "variants": {"cupy": {"eager": "cp.fft.hfft"}, "dask": {"eager": "da.fft.hfft"}, "numpy": {"generator": "np.fft.hfft"}}},
    "Histogram": {"description": "The Histogram operation.", "operation": "Histogram", "variants": {"numpy": {"generator": "np.histogram"}}},
    "Histogram2d": {"description": "The Histogram2d operation.", "operation": "Histogram2d", "variants": {"numpy": {"generator": "np.histogram2d"}}},
    "HistogramBinEdges": {"description": "The HistogramBinEdges operation.", "operation": "HistogramBinEdges", "variants": {"numpy": {"generator": "np.histogram_bin_edges"}}},
    "Histogramdd": {"description": "The Histogramdd operation.", "operation": "Histogramdd", "variants": {"numpy": {"generator": "np.histogramdd"}}},
    "Hstack": {"description": "The Hstack operation.", "operation": "Hstack", "variants": {"cupy": {"eager": "cp.hstack"}, "dask": {"eager": "da.hstack"}, "keras": {"eager": "keras_ops.hstack"}}},
    "Hypot": {"description": "The Hypot operation.", "operation": "Hypot", "variants": {"cupy": {"eager": "cp.hypot"}, "dask": {"eager": "da.hypot"}}},
    "I0": {"description": "The I0 operation.", "operation": "I0", "variants": {"numpy": {"generator": "np.i0"}}},
    "If": {"description": "The If operation.", "operation": "If", "variants": {"edge_onnx": {"generator": "If"}, "edge_stablehlo": {"generator": "stablehlo.if"}}},
    "Ifft": {"description": "The Ifft operation.", "operation": "Ifft", "variants": {"cupy": {"eager": "cp.fft.ifft"}, "dask": {"eager": "da.fft.ifft"}, "numpy": {"generator": "np.fft.ifft"}, "pytorch": {"generator": "torch.fft.ifft({0}, n={n}, dim={axis})"}}},
    "Ifft2": {"description": "The Ifft2 operation.", "operation": "Ifft2", "variants": {"cupy": {"eager": "cp.fft.ifft2"}, "dask": {"eager": "da.fft.ifft2"}, "keras": {"eager": "keras_ops.ifft2"}, "numpy": {"generator": "np.fft.ifft2"}}},
    "Ifft2d": {"description": "The Ifft2d operation.", "operation": "Ifft2d", "variants": {"pytorch": {"generator": "torch.fft.ifft2({0}, s={s}, dim={axes})"}}},
    "Ifft3d": {"description": "The Ifft3d operation.", "operation": "Ifft3d", "variants": {"pytorch": {"generator": "torch.fft.ifftn({0}, s={s}, dim={axes})"}}},
    "Ifftn": {"description": "The Ifftn operation.", "operation": "Ifftn", "variants": {"cupy": {"eager": "cp.fft.ifftn"}, "dask": {"eager": "da.fft.ifftn"}, "numpy": {"generator": "np.fft.ifftn"}}},
    "Ifftnd": {"description": "The Ifftnd operation.", "operation": "Ifftnd", "variants": {"numpy": {"generator": "np.fft.ifftn({0})"}, "tensorflow": {"eager": "tf.ifftnd"}}},
    "Ifftshift": {"description": "The Ifftshift operation.", "operation": "Ifftshift", "variants": {"cupy": {"eager": "cp.fft.ifftshift"}, "dask": {"eager": "da.fft.ifftshift"}, "numpy": {"generator": "np.fft.ifftshift({0})"}}},
    "Igamma": {"description": "The Igamma operation.", "operation": "Igamma", "variants": {"numpy": {"generator": "scipy.special.gammainc"}, "tensorflow": {"eager": "tf.math.igamma"}}},
    "IgammaGradA": {"description": "The IgammaGradA operation.", "operation": "IgammaGradA", "variants": {"numpy": {"generator": "lambda a, x: a"}}},
    "Igammac": {"description": "The Igammac operation.", "operation": "Igammac", "variants": {"numpy": {"generator": "scipy.special.gammaincc"}, "tensorflow": {"eager": "tf.math.igammac"}}},
    "Ihfft": {"description": "The Ihfft operation.", "operation": "Ihfft", "variants": {"cupy": {"eager": "cp.fft.ihfft"}, "dask": {"eager": "da.fft.ihfft"}}},
    "Imag": {"description": "The Imag operation.", "operation": "Imag", "variants": {"cupy": {"eager": "cp.imag"}, "dask": {"eager": "da.imag"}, "keras": {"eager": "keras_ops.imag"}, "tensorflow": {"eager": "tf.math.imag"}}},
    "InTopK": {"description": "The InTopK operation.", "operation": "InTopK", "variants": {"keras": {"eager": "keras_ops.in_top_k"}, "tensorflow": {"eager": "tf.math.in_top_k"}}},
    "IndexInDim": {"description": "The IndexInDim operation.", "operation": "IndexInDim", "variants": {"numpy": {"generator": "np.take({0}, {1}, axis={2})"}}},
    "Infeed": {"description": "The Infeed operation.", "operation": "Infeed", "variants": {"numpy": {"generator": "{0}"}}},
    "Inner": {"description": "The Inner operation.", "operation": "Inner", "variants": {"keras": {"eager": "keras_ops.inner"}}},
    "Insert": {"description": "The Insert operation.", "operation": "Insert", "variants": {"cupy": {"eager": "cp.insert"}, "dask": {"eager": "da.insert"}}},
    "Inv": {"description": "The Inv operation.", "operation": "Inv", "variants": {"cupy": {"eager": "cp.linalg.inv"}, "dask": {"eager": "da.linalg.inv"}, "keras": {"eager": "keras_ops.inv"}, "numpy": {"generator": "np.linalg.inv"}, "tensorflow": {"eager": "tf.linalg.inv"}}},
    "Invert": {"description": "The Invert operation.", "operation": "Invert", "variants": {"cupy": {"eager": "cp.invert"}, "dask": {"eager": "da.invert"}}},
    "InvertPermutation": {"description": "The InvertPermutation operation.", "operation": "InvertPermutation", "variants": {"tensorflow": {"eager": "tf.math.invert_permutation"}}},
    "Irfft": {"description": "The Irfft operation.", "operation": "Irfft", "variants": {"cupy": {"eager": "cp.fft.irfft"}, "dask": {"eager": "da.fft.irfft"}, "keras": {"eager": "keras_ops.irfft"}, "pytorch": {"generator": "torch.fft.irfft({0}, n={n}, dim={axis})"}}},
    "Irfft2": {"description": "The Irfft2 operation.", "operation": "Irfft2", "variants": {"cupy": {"eager": "cp.fft.irfft2"}, "dask": {"eager": "da.fft.irfft2"}, "numpy": {"generator": "np.fft.irfft2"}}},
    "Irfft2d": {"description": "The Irfft2d operation.", "operation": "Irfft2d", "variants": {"pytorch": {"generator": "torch.fft.irfft2({0}, s={s}, dim={axes})"}}},
    "Irfft3d": {"description": "The Irfft3d operation.", "operation": "Irfft3d", "variants": {"pytorch": {"generator": "torch.fft.irfftn({0}, s={s}, dim={axes})"}}},
    "Irfftn": {"description": "The Irfftn operation.", "operation": "Irfftn", "variants": {"cupy": {"eager": "cp.fft.irfftn"}, "dask": {"eager": "da.fft.irfftn"}, "numpy": {"generator": "np.fft.irfftn"}}},
    "Irfftnd": {"description": "The Irfftnd operation.", "operation": "Irfftnd", "variants": {"numpy": {"generator": "np.fft.irfftn({0})"}, "tensorflow": {"eager": "tf.irfftnd"}}},
    "IsNonDecreasing": {"description": "The IsNonDecreasing operation.", "operation": "IsNonDecreasing", "variants": {"tensorflow": {"eager": "tf.math.is_non_decreasing"}}},
    "IsStrictlyIncreasing": {"description": "The IsStrictlyIncreasing operation.", "operation": "IsStrictlyIncreasing", "variants": {"tensorflow": {"eager": "tf.math.is_strictly_increasing"}}},
    "Isclose": {"description": "The Isclose operation.", "operation": "Isclose", "variants": {"cupy": {"eager": "cp.isclose"}, "dask": {"eager": "da.isclose"}, "keras": {"eager": "keras_ops.isclose"}}},
    "Iscomplex": {"description": "The Iscomplex operation.", "operation": "Iscomplex", "variants": {"cupy": {"eager": "cp.iscomplex"}, "dask": {"eager": "da.iscomplex"}}},
    "Isfinite": {"description": "The Isfinite operation.", "operation": "Isfinite", "variants": {"cupy": {"eager": "cp.isfinite"}, "dask": {"eager": "da.isfinite"}, "keras": {"eager": "keras_ops.isfinite"}}},
    "Isin": {"description": "The Isin operation.", "operation": "Isin", "variants": {"cupy": {"eager": "cp.isin"}, "dask": {"eager": "da.isin"}}},
    "Isinf": {"description": "The Isinf operation.", "operation": "Isinf", "variants": {"cupy": {"eager": "cp.isinf"}, "dask": {"eager": "da.isinf"}, "keras": {"eager": "keras_ops.isinf"}}},
    "Isnan": {"description": "The Isnan operation.", "operation": "Isnan", "variants": {"cupy": {"eager": "cp.isnan"}, "dask": {"eager": "da.isnan"}, "keras": {"eager": "keras_ops.isnan"}}},
    "Isneginf": {"description": "The Isneginf operation.", "operation": "Isneginf", "variants": {"cupy": {"eager": "cp.isneginf"}, "dask": {"eager": "da.isneginf"}}},
    "Isposinf": {"description": "The Isposinf operation.", "operation": "Isposinf", "variants": {"cupy": {"eager": "cp.isposinf"}, "dask": {"eager": "da.isposinf"}}},
    "Isreal": {"description": "The Isreal operation.", "operation": "Isreal", "variants": {"cupy": {"eager": "cp.isreal"}, "dask": {"eager": "da.isreal"}}},
    "Istft": {
        "description": "The Istft operation.",
        "operation": "Istft",
        "variants": {
            "keras": {"eager": "keras_ops.istft"},
            "pytorch": {"generator": "torch.istft({0}, n_fft={n_fft}, hop_length={hop_length}, win_length={win_length}, window={window}, center={center}, normalized={normalized}, onesided={onesided}, length={length}, return_complex={return_complex})"},
        },
    },
    "KaiserWindow": {"description": "The KaiserWindow operation.", "operation": "KaiserWindow", "variants": {"pytorch": {"generator": "torch.kaiser_window({window_length}, periodic={periodic}, beta={beta})"}}},
    "L2Normalize": {"description": "The L2Normalize operation.", "operation": "L2Normalize", "variants": {"tensorflow": {"eager": "tf.linalg.l2_normalize"}}},
    "Lbeta": {"description": "The Lbeta operation.", "operation": "Lbeta", "variants": {"tensorflow": {"eager": "tf.math.lbeta"}}},
    "Ldexp": {"description": "The Ldexp operation.", "operation": "Ldexp", "variants": {"cupy": {"eager": "cp.ldexp"}, "dask": {"eager": "da.ldexp"}}},
    "LeftShift": {"description": "The LeftShift operation.", "operation": "LeftShift", "variants": {"cupy": {"eager": "cp.left_shift"}, "dask": {"eager": "da.left_shift"}, "keras": {"eager": "keras_ops.left_shift"}}},
    "Less": {
        "description": "The Less operation.",
        "operation": "Less",
        "variants": {
            "cupy": {"eager": "cp.less", "generator": "cp.less"},
            "dask": {"eager": "da.less", "generator": "da.less"},
            "edge_onnx": {"generator": "Less"},
            "edge_stablehlo": {"generator": "stablehlo.compare"},
            "keras": {"eager": "keras_ops.less"},
            "numpy": {"generator": "np.less"},
            "tensorflow": {"eager": "tf.less"},
        },
    },
    "LessEqual": {"description": "The LessEqual operation.", "operation": "LessEqual", "variants": {"cupy": {"eager": "cp.less_equal"}, "dask": {"eager": "da.less_equal"}, "keras": {"eager": "keras_ops.less_equal"}, "tensorflow": {"eager": "tf.less_equal"}}},
    "Lgamma": {"description": "The Lgamma operation.", "operation": "Lgamma", "variants": {"tensorflow": {"eager": "tf.math.lgamma"}}},
    "Log": {
        "description": "The Log operation.",
        "operation": "Log",
        "variants": {
            "cupy": {"eager": "cp.log", "generator": "cp.log"},
            "dask": {"eager": "da.log", "generator": "da.log"},
            "edge_onnx": {"generator": "Log"},
            "edge_stablehlo": {"generator": "stablehlo.log"},
            "keras": {"eager": "keras_ops.log"},
            "numpy": {"generator": "np.log"},
            "tensorflow": {"eager": "tf.math.log"},
        },
    },
    "Log10": {"description": "The Log10 operation.", "operation": "Log10", "variants": {"cupy": {"eager": "cp.log10"}, "dask": {"eager": "da.log10"}, "keras": {"eager": "keras_ops.log10"}}},
    "Log1p": {"description": "The Log1p operation.", "operation": "Log1p", "variants": {"edge_stablehlo": {"generator": "stablehlo.log1p"}}},
    "Log2": {"description": "The Log2 operation.", "operation": "Log2", "variants": {"cupy": {"eager": "cp.log2"}, "dask": {"eager": "da.log2"}, "keras": {"eager": "keras_ops.log2"}}},
    "LogSigmoid": {"description": "The LogSigmoid operation.", "operation": "LogSigmoid", "variants": {"keras": {"eager": "keras_ops.log_sigmoid"}, "tensorflow": {"eager": "tf.math.log_sigmoid"}}},
    "LogSoftmax": {"description": "The LogSoftmax operation.", "operation": "LogSoftmax", "variants": {"keras": {"eager": "keras_ops.log_softmax"}, "numpy": {"generator": "scipy.special.log_softmax({0}, axis={axis})"}, "tensorflow": {"eager": "tf.math.log_softmax"}}},
    "Logaddexp": {"description": "The Logaddexp operation.", "operation": "Logaddexp", "variants": {"cupy": {"eager": "cp.logaddexp"}, "dask": {"eager": "da.logaddexp"}, "keras": {"eager": "keras_ops.logaddexp"}}},
    "Logaddexp2": {"description": "The Logaddexp2 operation.", "operation": "Logaddexp2", "variants": {"cupy": {"eager": "cp.logaddexp2"}, "dask": {"eager": "da.logaddexp2"}}},
    "Logcumsumexp": {"description": "The Logcumsumexp operation.", "operation": "Logcumsumexp", "variants": {"numpy": {"generator": "scipy.special.logsumexp"}}},
    "LogicalAnd": {"description": "The LogicalAnd operation.", "operation": "LogicalAnd", "variants": {"cupy": {"eager": "cp.logical_and"}, "dask": {"eager": "da.logical_and"}, "keras": {"eager": "keras_ops.logical_and"}, "tensorflow": {"eager": "tf.logical_and"}}},
    "LogicalNot": {"description": "The LogicalNot operation.", "operation": "LogicalNot", "variants": {"cupy": {"eager": "cp.logical_not"}, "dask": {"eager": "da.logical_not"}, "keras": {"eager": "keras_ops.logical_not"}, "tensorflow": {"eager": "tf.logical_not"}}},
    "LogicalOr": {"description": "The LogicalOr operation.", "operation": "LogicalOr", "variants": {"cupy": {"eager": "cp.logical_or"}, "dask": {"eager": "da.logical_or"}, "keras": {"eager": "keras_ops.logical_or"}, "tensorflow": {"eager": "tf.logical_or"}}},
    "LogicalXor": {"description": "The LogicalXor operation.", "operation": "LogicalXor", "variants": {"cupy": {"eager": "cp.logical_xor"}, "dask": {"eager": "da.logical_xor"}, "keras": {"eager": "keras_ops.logical_xor"}, "tensorflow": {"eager": "tf.math.logical_xor"}}},
    "Logsumexp": {"description": "The Logsumexp operation.", "operation": "Logsumexp", "variants": {"keras": {"eager": "keras_ops.logsumexp"}}},
    "Lookup": {"description": "The Lookup operation.", "operation": "Lookup", "variants": {"tensorflow": {"eager": "tf.lookup"}}},
    "Loop": {"description": "The Loop operation.", "operation": "Loop", "variants": {"edge_onnx": {"generator": "Loop"}}},
    "Lstsq": {
        "description": "The Lstsq operation.",
        "operation": "Lstsq",
        "variants": {"cupy": {"eager": "cp.linalg.lstsq"}, "dask": {"eager": "da.linalg.lstsq"}, "keras": {"eager": "keras_ops.lstsq"}, "numpy": {"generator": "np.linalg.lstsq({0}, {1}, rcond={rcond})[0]"}, "tensorflow": {"eager": "tf.linalg.lstsq"}},
    },
    "Lu": {"description": "The Lu operation.", "operation": "Lu", "variants": {"cupy": {"eager": "cp.linalg.lu"}, "dask": {"eager": "da.linalg.lu"}, "numpy": {"generator": "scipy.linalg.lu"}, "tensorflow": {"eager": "tf.linalg.lu"}}},
    "LuFactor": {"description": "The LuFactor operation.", "operation": "LuFactor", "variants": {"keras": {"eager": "keras_ops.lu_factor"}, "numpy": {"generator": "scipy.linalg.lu_factor"}}},
    "LuMatrixInverse": {
        "description": "The LuMatrixInverse operation.",
        "operation": "LuMatrixInverse",
        "variants": {
            "numpy": {"generator": "np.linalg.inv(np.take_along_axis(np.matmul(np.tril({0}, -1) + np.eye({0}.shape[-1], dtype={0}.dtype), np.triu({0})), np.broadcast_to(np.expand_dims(np.argsort({1}, axis=-1), -1), {0}.shape), axis=-2))"},
            "tensorflow": {"eager": "tf.linalg.lu_matrix_inverse"},
        },
    },
    "LuReconstruct": {
        "description": "The LuReconstruct operation.",
        "operation": "LuReconstruct",
        "variants": {"numpy": {"generator": "np.take_along_axis(np.matmul(np.tril({0}, -1) + np.eye({0}.shape[-1], dtype={0}.dtype), np.triu({0})), np.broadcast_to(np.expand_dims(np.argsort({1}, axis=-1), -1), {0}.shape), axis=-2)"}, "tensorflow": {"eager": "tf.linalg.lu_reconstruct"}},
    },
    "LuSolve": {"description": "The LuSolve operation.", "operation": "LuSolve", "variants": {"numpy": {"generator": "scipy.linalg.lu_solve"}, "tensorflow": {"eager": "tf.linalg.lu_solve"}}},
    "MatMul": {"description": "The MatMul operation.", "operation": "MatMul", "variants": {"edge_onnx": {"generator": "MatMul"}, "edge_stablehlo": {"generator": "stablehlo.dot_general"}}},
    "MatrixExponential": {"description": "The MatrixExponential operation.", "operation": "MatrixExponential", "variants": {"numpy": {"generator": "scipy.linalg.expm"}}},
    "MatrixNorm": {"description": "The MatrixNorm operation.", "operation": "MatrixNorm", "variants": {"numpy": {"generator": "np.linalg.norm({0}, keepdims={keepdims})"}}},
    "MatrixPower": {"description": "The MatrixPower operation.", "operation": "MatrixPower", "variants": {"numpy": {"generator": "np.linalg.matrix_power"}}},
    "MatrixRank": {"description": "The MatrixRank operation.", "operation": "MatrixRank", "variants": {"numpy": {"generator": "np.linalg.matrix_rank({0}, tol={tol}, hermitian={hermitian})"}, "tensorflow": {"eager": "tf.linalg.matrix_rank"}}},
    "MatrixTranspose": {"description": "The MatrixTranspose operation.", "operation": "MatrixTranspose", "variants": {"numpy": {"generator": "np.swapaxes({0}, -1, -2)"}, "tensorflow": {"eager": "tf.linalg.matrix_transpose"}}},
    "Max": {
        "description": "The Max operation.",
        "operation": "Max",
        "variants": {"cupy": {"eager": "cp.max", "generator": "cp.max"}, "dask": {"eager": "da.max", "generator": "da.max"}, "keras": {"eager": "keras_ops.max"}, "numpy": {"generator": "np.max"}, "pytorch": {"generator": "torch.max({0}, dim={axis}, keepdim={keepdims})"}},
    },
    "MaxPool": {"description": "The MaxPool operation.", "operation": "MaxPool", "variants": {"edge_onnx": {"generator": "MaxPool"}}},
    "MaxPool2D": {"description": "The MaxPool2D operation.", "operation": "MaxPool2D", "variants": {"edge_onnx": {"generator": "MaxPool"}}},
    "Maximum": {"description": "The Maximum operation.", "operation": "Maximum", "variants": {"cupy": {"eager": "cp.maximum"}, "dask": {"eager": "da.maximum"}, "keras": {"eager": "keras_ops.maximum"}, "tensorflow": {"eager": "tf.maximum"}}},
    "Mean": {
        "description": "The Mean operation.",
        "operation": "Mean",
        "variants": {"cupy": {"eager": "cp.mean", "generator": "cp.mean"}, "dask": {"eager": "da.mean", "generator": "da.mean"}, "keras": {"eager": "keras_ops.mean"}, "numpy": {"generator": "np.mean"}, "pytorch": {"generator": "torch.mean({0}, dim={axis}, keepdim={keepdims})"}},
    },
    "Mgrid": {"description": "The Mgrid operation.", "operation": "Mgrid", "variants": {"numpy": {"generator": "np.mgrid"}}},
    "Min": {
        "description": "The Min operation.",
        "operation": "Min",
        "variants": {"cupy": {"eager": "cp.min", "generator": "cp.min"}, "dask": {"eager": "da.min", "generator": "da.min"}, "keras": {"eager": "keras_ops.min"}, "numpy": {"generator": "np.min"}, "pytorch": {"generator": "torch.min({0}, dim={axis}, keepdim={keepdims})"}},
    },
    "Minimum": {"description": "The Minimum operation.", "operation": "Minimum", "variants": {"cupy": {"eager": "cp.minimum"}, "dask": {"eager": "da.minimum"}, "keras": {"eager": "keras_ops.minimum"}, "tensorflow": {"eager": "tf.minimum"}}},
    "Mod": {"description": "The Mod operation.", "operation": "Mod", "variants": {"cupy": {"eager": "cp.mod"}, "dask": {"eager": "da.mod"}, "keras": {"eager": "keras_ops.mod"}, "tensorflow": {"eager": "tf.math.mod"}}},
    "Moveaxis": {"description": "The Moveaxis operation.", "operation": "Moveaxis", "variants": {"cupy": {"eager": "cp.moveaxis"}, "dask": {"eager": "da.moveaxis"}, "keras": {"eager": "keras_ops.moveaxis"}}},
    "MultiDot": {"description": "The MultiDot operation.", "operation": "MultiDot", "variants": {"numpy": {"generator": "np.linalg.multi_dot({0})"}}},
    "Multiply": {
        "description": "The Multiply operation.",
        "operation": "Multiply",
        "variants": {
            "cupy": {"eager": "cp.multiply", "generator": "cp.multiply"},
            "dask": {"eager": "da.multiply", "generator": "da.multiply"},
            "edge_onnx": {"generator": "Mul"},
            "edge_stablehlo": {"generator": "stablehlo.multiply"},
            "keras": {"eager": "keras_ops.multiply"},
            "numpy": {"generator": "np.multiply"},
            "tensorflow": {"eager": "tf.multiply"},
        },
    },
    "MultiplyNoNan": {"description": "The MultiplyNoNan operation.", "operation": "MultiplyNoNan", "variants": {"tensorflow": {"eager": "tf.math.multiply_no_nan"}}},
    "NanToNum": {
        "description": "The NanToNum operation.",
        "operation": "NanToNum",
        "variants": {"cupy": {"eager": "cp.nan_to_num"}, "dask": {"eager": "da.nan_to_num"}, "keras": {"eager": "keras_ops.nan_to_num"}, "numpy": {"generator": "np.nan_to_num"}, "pytorch": {"generator": "torch.nan_to_num({0}, nan={nan}, posinf={posinf}, neginf={neginf})"}},
    },
    "Nanargmax": {"description": "The Nanargmax operation.", "operation": "Nanargmax", "variants": {"cupy": {"eager": "cp.nanargmax"}, "dask": {"eager": "da.nanargmax"}}},
    "Nanargmin": {"description": "The Nanargmin operation.", "operation": "Nanargmin", "variants": {"cupy": {"eager": "cp.nanargmin"}, "dask": {"eager": "da.nanargmin"}}},
    "Nancumprod": {"description": "The Nancumprod operation.", "operation": "Nancumprod", "variants": {"cupy": {"eager": "cp.nancumprod"}, "dask": {"eager": "da.nancumprod"}}},
    "Nancumsum": {"description": "The Nancumsum operation.", "operation": "Nancumsum", "variants": {"cupy": {"eager": "cp.nancumsum"}, "dask": {"eager": "da.nancumsum"}}},
    "Nanmax": {"description": "The Nanmax operation.", "operation": "Nanmax", "variants": {"cupy": {"eager": "cp.nanmax"}, "dask": {"eager": "da.nanmax"}}},
    "Nanmean": {"description": "The Nanmean operation.", "operation": "Nanmean", "variants": {"cupy": {"eager": "cp.nanmean"}, "dask": {"eager": "da.nanmean"}}},
    "Nanmedian": {"description": "The Nanmedian operation.", "operation": "Nanmedian", "variants": {"cupy": {"eager": "cp.nanmedian"}, "dask": {"eager": "da.nanmedian"}}},
    "Nanmin": {"description": "The Nanmin operation.", "operation": "Nanmin", "variants": {"cupy": {"eager": "cp.nanmin"}, "dask": {"eager": "da.nanmin"}}},
    "Nanprod": {"description": "The Nanprod operation.", "operation": "Nanprod", "variants": {"cupy": {"eager": "cp.nanprod"}, "dask": {"eager": "da.nanprod"}}},
    "Nanstd": {"description": "The Nanstd operation.", "operation": "Nanstd", "variants": {"cupy": {"eager": "cp.nanstd"}, "dask": {"eager": "da.nanstd"}}},
    "Nansum": {"description": "The Nansum operation.", "operation": "Nansum", "variants": {"cupy": {"eager": "cp.nansum"}, "dask": {"eager": "da.nansum"}}},
    "Nanvar": {"description": "The Nanvar operation.", "operation": "Nanvar", "variants": {"cupy": {"eager": "cp.nanvar"}, "dask": {"eager": "da.nanvar"}}},
    "Ndtri": {"description": "The Ndtri operation.", "operation": "Ndtri", "variants": {"tensorflow": {"eager": "tf.math.ndtri"}}},
    "Neg": {"description": "The Neg operation.", "operation": "Neg", "variants": {"edge_onnx": {"generator": "Neg"}, "edge_stablehlo": {"generator": "stablehlo.negate"}}},
    "Negative": {
        "description": "The Negative operation.",
        "operation": "Negative",
        "variants": {
            "cupy": {"eager": "cp.negative", "generator": "cp.negative"},
            "dask": {"eager": "da.negative", "generator": "da.negative"},
            "edge_onnx": {"generator": "Neg"},
            "edge_stablehlo": {"generator": "stablehlo.negate"},
            "keras": {"eager": "keras_ops.negative"},
            "numpy": {"generator": "np.negative"},
            "tensorflow": {"eager": "tf.negative"},
        },
    },
    "Nextafter": {"description": "The Nextafter operation.", "operation": "Nextafter", "variants": {"cupy": {"eager": "cp.nextafter"}, "dask": {"eager": "da.nextafter"}, "tensorflow": {"eager": "tf.math.nextafter"}}},
    "Nonzero": {"description": "The Nonzero operation.", "operation": "Nonzero", "variants": {"cupy": {"eager": "cp.nonzero"}, "dask": {"eager": "da.nonzero"}, "keras": {"eager": "keras_ops.nonzero"}}},
    "Norm": {"description": "The Norm operation.", "operation": "Norm", "variants": {"cupy": {"eager": "cp.linalg.norm"}, "dask": {"eager": "da.linalg.norm"}, "keras": {"eager": "keras_ops.norm"}, "numpy": {"generator": "np.linalg.norm"}, "tensorflow": {"eager": "tf.norm"}}},
    "NotEqual": {
        "description": "The NotEqual operation.",
        "operation": "NotEqual",
        "variants": {"cupy": {"eager": "cp.not_equal", "generator": "cp.not_equal"}, "dask": {"eager": "da.not_equal", "generator": "da.not_equal"}, "keras": {"eager": "keras_ops.not_equal"}, "numpy": {"generator": "np.not_equal"}, "tensorflow": {"eager": "tf.not_equal"}},
    },
    "Ogrid": {"description": "The Ogrid operation.", "operation": "Ogrid", "variants": {"numpy": {"generator": "np.ogrid"}}},
    "OneHot": {"description": "The OneHot operation.", "operation": "OneHot", "variants": {"keras": {"eager": "keras_ops.one_hot"}, "numpy": {"generator": "np.eye({depth})[{0}]"}, "tensorflow": {"eager": "tf.one_hot"}}},
    "Ones": {"description": "The Ones operation.", "operation": "Ones", "variants": {"numpy": {"generator": "np.ones"}, "pytorch": {"generator": "torch.ones({shape})"}}},
    "Outer": {"description": "The Outer operation.", "operation": "Outer", "variants": {"cupy": {"eager": "cp.outer"}, "dask": {"eager": "da.outer"}, "keras": {"eager": "keras_ops.outer"}, "numpy": {"generator": "np.outer({0}, {1})"}}},
    "Outfeed": {"description": "The Outfeed operation.", "operation": "Outfeed", "variants": {"numpy": {"generator": "{0}"}}},
    "Pad": {"description": "The Pad operation.", "operation": "Pad", "variants": {"cupy": {"eager": "cp.pad"}, "dask": {"eager": "da.pad"}, "edge_onnx": {"generator": "Pad"}, "edge_stablehlo": {"generator": "stablehlo.pad"}, "keras": {"eager": "keras_ops.pad"}, "tensorflow": {"eager": "tf.pad"}}},
    "Percentile": {"description": "The Percentile operation.", "operation": "Percentile", "variants": {"cupy": {"eager": "cp.percentile"}, "dask": {"eager": "da.percentile"}}},
    "Pinv": {"description": "The Pinv operation.", "operation": "Pinv", "variants": {"numpy": {"generator": "np.linalg.pinv"}, "tensorflow": {"eager": "tf.linalg.pinv"}}},
    "Pmax": {"description": "The Pmax operation.", "operation": "Pmax", "variants": {"numpy": {"generator": "{0}"}}},
    "Pmin": {"description": "The Pmin operation.", "operation": "Pmin", "variants": {"numpy": {"generator": "{0}"}}},
    "Polar": {"description": "The Polar operation.", "operation": "Polar", "variants": {"keras": {"eager": "keras_ops.polar"}}},
    "Poly": {"description": "The Poly operation.", "operation": "Poly", "variants": {"numpy": {"generator": "np.poly"}}},
    "Polyadd": {"description": "The Polyadd operation.", "operation": "Polyadd", "variants": {"numpy": {"generator": "np.polyadd"}}},
    "Polyder": {"description": "The Polyder operation.", "operation": "Polyder", "variants": {"numpy": {"generator": "np.polyder"}}},
    "Polydiv": {"description": "The Polydiv operation.", "operation": "Polydiv", "variants": {"numpy": {"generator": "np.polydiv"}}},
    "Polyfit": {"description": "The Polyfit operation.", "operation": "Polyfit", "variants": {"numpy": {"generator": "np.polyfit"}}},
    "Polygamma": {"description": "The Polygamma operation.", "operation": "Polygamma", "variants": {"numpy": {"generator": "scipy.special.polygamma"}, "tensorflow": {"eager": "tf.math.polygamma"}}},
    "Polyint": {"description": "The Polyint operation.", "operation": "Polyint", "variants": {"numpy": {"generator": "np.polyint"}}},
    "Polymul": {"description": "The Polymul operation.", "operation": "Polymul", "variants": {"numpy": {"generator": "np.polymul"}}},
    "Polysub": {"description": "The Polysub operation.", "operation": "Polysub", "variants": {"numpy": {"generator": "np.polysub"}}},
    "Polyval": {"description": "The Polyval operation.", "operation": "Polyval", "variants": {"numpy": {"generator": "np.polyval"}, "tensorflow": {"eager": "tf.math.polyval"}}},
    "Positive": {"description": "The Positive operation.", "operation": "Positive", "variants": {"cupy": {"eager": "cp.positive"}, "dask": {"eager": "da.positive"}}},
    "Power": {"description": "The Power operation.", "operation": "Power", "variants": {"cupy": {"eager": "cp.power"}, "dask": {"eager": "da.power"}, "keras": {"eager": "keras_ops.power"}}},
    "Ppermute": {"description": "The Ppermute operation.", "operation": "Ppermute", "variants": {"numpy": {"generator": "{0}"}}},
    "Prod": {"description": "The Prod operation.", "operation": "Prod", "variants": {"cupy": {"eager": "cp.prod"}, "dask": {"eager": "da.prod"}, "keras": {"eager": "keras_ops.prod"}, "pytorch": {"generator": "torch.prod({0}, dim={axis}, keepdim={keepdims})"}}},
    "Pshuffle": {"description": "The Pshuffle operation.", "operation": "Pshuffle", "variants": {"numpy": {"generator": "{0}"}}},
    "PsumScatter": {"description": "The PsumScatter operation.", "operation": "PsumScatter", "variants": {"numpy": {"generator": "{0}"}}},
    "Pswapaxes": {"description": "The Pswapaxes operation.", "operation": "Pswapaxes", "variants": {"numpy": {"generator": "{0}"}}},
    "Qr": {"description": "The Qr operation.", "operation": "Qr", "variants": {"cupy": {"eager": "cp.linalg.qr"}, "dask": {"eager": "da.linalg.qr"}, "keras": {"eager": "keras_ops.qr"}, "numpy": {"generator": "np.linalg.qr"}, "tensorflow": {"eager": "tf.linalg.qr"}}},
    "Quantile": {"description": "The Quantile operation.", "operation": "Quantile", "variants": {"keras": {"eager": "keras_ops.quantile"}}},
    "RNNCellDeviceWrapper": {"description": "The RNNCellDeviceWrapper operation.", "operation": "RNNCellDeviceWrapper", "variants": {"numpy": {"generator": "tf.nn.rnn_cell.DeviceWrapper"}}},
    "RNNCellDropoutWrapper": {"description": "The RNNCellDropoutWrapper operation.", "operation": "RNNCellDropoutWrapper", "variants": {"numpy": {"generator": "tf.nn.rnn_cell.DropoutWrapper"}}},
    "RNNCellResidualWrapper": {"description": "The RNNCellResidualWrapper operation.", "operation": "RNNCellResidualWrapper", "variants": {"numpy": {"generator": "tf.nn.rnn_cell.ResidualWrapper"}}},
    "R_": {"description": "The R_ operation.", "operation": "R_", "variants": {"numpy": {"generator": "np.r_"}}},
    "Radians": {"description": "The Radians operation.", "operation": "Radians", "variants": {"cupy": {"eager": "cp.radians"}, "dask": {"eager": "da.radians"}}},
    "RaggedConstant": {"description": "The RaggedConstant operation.", "operation": "RaggedConstant", "variants": {"numpy": {"generator": "tf.ragged.constant"}}},
    "RaggedCrossHashed": {"description": "The RaggedCrossHashed operation.", "operation": "RaggedCrossHashed", "variants": {"numpy": {"generator": "tf.ragged.cross_hashed"}}},
    "RaggedRange": {"description": "The RaggedRange operation.", "operation": "RaggedRange", "variants": {"numpy": {"generator": "tf.ragged.range"}}},
    "RaggedRowSplitsToSegmentIds": {"description": "The RaggedRowSplitsToSegmentIds operation.", "operation": "RaggedRowSplitsToSegmentIds", "variants": {"numpy": {"generator": "tf.ragged.row_splits_to_segment_ids"}}},
    "RaggedSegmentIdsToRowSplits": {"description": "The RaggedSegmentIdsToRowSplits operation.", "operation": "RaggedSegmentIdsToRowSplits", "variants": {"numpy": {"generator": "tf.ragged.segment_ids_to_row_splits"}}},
    "RaggedStack": {"description": "The RaggedStack operation.", "operation": "RaggedStack", "variants": {"numpy": {"generator": "tf.ragged.stack"}}},
    "RaggedStackDynamicPartitions": {"description": "The RaggedStackDynamicPartitions operation.", "operation": "RaggedStackDynamicPartitions", "variants": {"numpy": {"generator": "tf.ragged.stack_dynamic_partitions"}}},
    "RandomCategorical": {"description": "The RandomCategorical operation.", "operation": "RandomCategorical", "variants": {"numpy": {"generator": "np.argmax({1} + np.random.gumbel(size={1}.shape), axis={axis})"}}},
    "RandomGammaGrad": {"description": "The RandomGammaGrad operation.", "operation": "RandomGammaGrad", "variants": {"numpy": {"generator": "lambda a, x: a"}}},
    "Rank": {"description": "The Rank operation.", "operation": "Rank", "variants": {"tensorflow": {"eager": "tf.rank"}}},
    "RavelMultiIndex": {"description": "The RavelMultiIndex operation.", "operation": "RavelMultiIndex", "variants": {"cupy": {"eager": "cp.ravel_multi_index"}, "dask": {"eager": "da.ravel_multi_index"}}},
    "ReadVariable": {"description": "The ReadVariable operation.", "operation": "ReadVariable", "variants": {"pytorch": {"generator": "{0}"}}},
    "Real": {"description": "The Real operation.", "operation": "Real", "variants": {"cupy": {"eager": "cp.real"}, "dask": {"eager": "da.real"}, "keras": {"eager": "keras_ops.real"}, "tensorflow": {"eager": "tf.math.real"}}},
    "Reciprocal": {"description": "The Reciprocal operation.", "operation": "Reciprocal", "variants": {"cupy": {"eager": "cp.reciprocal"}, "dask": {"eager": "da.reciprocal"}, "keras": {"eager": "keras_ops.reciprocal"}, "tensorflow": {"eager": "tf.math.reciprocal"}}},
    "ReciprocalNoNan": {"description": "The ReciprocalNoNan operation.", "operation": "ReciprocalNoNan", "variants": {"tensorflow": {"eager": "tf.math.reciprocal_no_nan"}}},
    "ReduceEuclideanNorm": {"description": "The ReduceEuclideanNorm operation.", "operation": "ReduceEuclideanNorm", "variants": {"tensorflow": {"eager": "tf.math.reduce_euclidean_norm"}}},
    "ReduceMax": {"description": "The ReduceMax operation.", "operation": "ReduceMax", "variants": {"edge_onnx": {"generator": "ReduceMax"}, "edge_stablehlo": {"generator": "stablehlo.reduce"}}},
    "ReduceMean": {"description": "The ReduceMean operation.", "operation": "ReduceMean", "variants": {"edge_onnx": {"generator": "ReduceMean"}, "edge_stablehlo": {"generator": "stablehlo.reduce"}}},
    "ReduceMin": {"description": "The ReduceMin operation.", "operation": "ReduceMin", "variants": {"edge_onnx": {"generator": "ReduceMin"}, "edge_stablehlo": {"generator": "stablehlo.reduce"}}},
    "ReduceSum": {"description": "The ReduceSum operation.", "operation": "ReduceSum", "variants": {"edge_onnx": {"generator": "ReduceSum"}, "edge_stablehlo": {"generator": "stablehlo.reduce"}}},
    "Relu": {"description": "The Relu operation.", "operation": "Relu", "variants": {"edge_onnx": {"generator": "Relu"}, "edge_stablehlo": {"generator": "stablehlo.maximum"}}},
    "Remainder": {"description": "The Remainder operation.", "operation": "Remainder", "variants": {"cupy": {"eager": "cp.remainder"}, "dask": {"eager": "da.remainder"}}},
    "Repeat": {"description": "The Repeat operation.", "operation": "Repeat", "variants": {"cupy": {"eager": "cp.repeat"}, "dask": {"eager": "da.repeat"}, "keras": {"eager": "keras_ops.repeat"}, "tensorflow": {"eager": "tf.repeat"}}},
    "Reshape": {
        "description": "The Reshape operation.",
        "operation": "Reshape",
        "variants": {
            "cupy": {"eager": "cp.reshape", "generator": "cp.reshape"},
            "dask": {"eager": "da.reshape", "generator": "da.reshape"},
            "edge_onnx": {"generator": "Reshape"},
            "edge_stablehlo": {"generator": "stablehlo.reshape"},
            "keras": {"eager": "keras_ops.reshape"},
            "numpy": {"generator": "np.reshape"},
            "pytorch": {"generator": "torch.reshape({0}, {shape})"},
            "tensorflow": {"eager": "tf.reshape"},
        },
    },
    "Resize": {"description": "The Resize operation.", "operation": "Resize", "variants": {"pytorch": {"generator": "torch.nn.functional.interpolate({0}, size={size}, mode={method}, antialias={antialias})"}}},
    "Reverse": {"description": "The Reverse operation.", "operation": "Reverse", "variants": {"numpy": {"generator": "np.flip"}}},
    "Rfft": {"description": "The Rfft operation.", "operation": "Rfft", "variants": {"cupy": {"eager": "cp.fft.rfft"}, "dask": {"eager": "da.fft.rfft"}, "keras": {"eager": "keras_ops.rfft"}, "numpy": {"generator": "np.fft.rfft"}}},
    "Rfft2": {"description": "The Rfft2 operation.", "operation": "Rfft2", "variants": {"cupy": {"eager": "cp.fft.rfft2"}, "dask": {"eager": "da.fft.rfft2"}, "numpy": {"generator": "np.fft.rfft2"}}},
    "Rfft2d": {"description": "The Rfft2d operation.", "operation": "Rfft2d", "variants": {"pytorch": {"generator": "torch.fft.rfft2({0}, s={s}, dim={axes})"}}},
    "Rfft3d": {"description": "The Rfft3d operation.", "operation": "Rfft3d", "variants": {"pytorch": {"generator": "torch.fft.rfftn({0}, s={s}, dim={axes})"}}},
    "Rfftfreq": {"description": "The Rfftfreq operation.", "operation": "Rfftfreq", "variants": {"cupy": {"eager": "cp.fft.rfftfreq"}, "dask": {"eager": "da.fft.rfftfreq"}, "numpy": {"generator": "np.fft.rfftfreq({0}, d={d})"}}},
    "Rfftn": {"description": "The Rfftn operation.", "operation": "Rfftn", "variants": {"cupy": {"eager": "cp.fft.rfftn"}, "dask": {"eager": "da.fft.rfftn"}, "numpy": {"generator": "np.fft.rfftn"}}},
    "Rfftnd": {"description": "The Rfftnd operation.", "operation": "Rfftnd", "variants": {"numpy": {"generator": "np.fft.rfftn({0})"}, "tensorflow": {"eager": "tf.rfftnd"}}},
    "RgbToYiq": {"description": "The RgbToYiq operation.", "operation": "RgbToYiq", "variants": {"pytorch": {"generator": "{0}"}}},
    "RgbToYuv": {"description": "The RgbToYuv operation.", "operation": "RgbToYuv", "variants": {"pytorch": {"generator": "{0}"}}},
    "RightShift": {"description": "The RightShift operation.", "operation": "RightShift", "variants": {"cupy": {"eager": "cp.right_shift"}, "dask": {"eager": "da.right_shift"}, "keras": {"eager": "keras_ops.right_shift"}}},
    "Rint": {"description": "The Rint operation.", "operation": "Rint", "variants": {"cupy": {"eager": "cp.rint"}, "dask": {"eager": "da.rint"}, "tensorflow": {"eager": "tf.math.rint"}}},
    "RngBitGenerator": {"description": "The RngBitGenerator operation.", "operation": "RngBitGenerator", "variants": {"numpy": {"generator": "np.random.randint(0, 255, size={shape})"}}},
    "RngUniform": {"description": "The RngUniform operation.", "operation": "RngUniform", "variants": {"numpy": {"generator": "np.random.uniform({0}, {1}, size={shape})"}}},
    "Roll": {"description": "The Roll operation.", "operation": "Roll", "variants": {"cupy": {"eager": "cp.roll"}, "dask": {"eager": "da.roll"}, "keras": {"eager": "keras_ops.roll"}, "tensorflow": {"eager": "tf.roll"}}},
    "Roots": {"description": "The Roots operation.", "operation": "Roots", "variants": {"numpy": {"generator": "np.roots"}}},
    "Round": {
        "description": "The Round operation.",
        "operation": "Round",
        "variants": {"cupy": {"eager": "cp.round"}, "dask": {"eager": "da.round"}, "edge_onnx": {"generator": "Round"}, "edge_stablehlo": {"generator": "stablehlo.round_nearest_afz"}, "keras": {"eager": "keras_ops.round"}, "tensorflow": {"eager": "tf.round"}},
    },
    "Rsqrt": {"description": "The Rsqrt operation.", "operation": "Rsqrt", "variants": {"keras": {"eager": "keras_ops.rsqrt"}, "tensorflow": {"eager": "tf.math.rsqrt"}}},
    "Scan": {"description": "The Scan operation.", "operation": "Scan", "variants": {"keras": {"eager": "keras_ops.scan"}, "tensorflow": {"eager": "tf.scan"}}},
    "Scatter": {"description": "The Scatter operation.", "operation": "Scatter", "variants": {"edge_stablehlo": {"generator": "stablehlo.scatter"}, "keras": {"eager": "keras_ops.scatter"}}},
    "ScatterND": {"description": "The ScatterND operation.", "operation": "ScatterND", "variants": {"edge_onnx": {"generator": "ScatterND"}}},
    "Searchsorted": {"description": "The Searchsorted operation.", "operation": "Searchsorted", "variants": {"cupy": {"eager": "cp.searchsorted"}, "dask": {"eager": "da.searchsorted"}, "keras": {"eager": "keras_ops.searchsorted"}, "tensorflow": {"eager": "tf.searchsorted"}}},
    "Select": {"description": "The Select operation.", "operation": "Select", "variants": {"cupy": {"eager": "cp.select"}, "dask": {"eager": "da.select"}, "keras": {"eager": "keras_ops.select"}}},
    "Sigmoid": {
        "description": "The Sigmoid operation.",
        "operation": "Sigmoid",
        "variants": {"edge_onnx": {"generator": "Sigmoid"}, "edge_stablehlo": {"generator": "stablehlo.logistic"}, "keras": {"eager": "keras_ops.sigmoid"}, "numpy": {"generator": "scipy.special.expit({0})"}, "tensorflow": {"eager": "tf.sigmoid"}},
    },
    "Sign": {"description": "The Sign operation.", "operation": "Sign", "variants": {"cupy": {"eager": "cp.sign"}, "dask": {"eager": "da.sign"}, "keras": {"eager": "keras_ops.sign"}, "tensorflow": {"eager": "tf.sign"}}},
    "Signbit": {"description": "The Signbit operation.", "operation": "Signbit", "variants": {"cupy": {"eager": "cp.signbit"}, "dask": {"eager": "da.signbit"}, "keras": {"eager": "keras_ops.signbit"}}},
    "Sin": {
        "description": "The Sin operation.",
        "operation": "Sin",
        "variants": {
            "cupy": {"eager": "cp.sin", "generator": "cp.sin"},
            "dask": {"eager": "da.sin", "generator": "da.sin"},
            "edge_onnx": {"generator": "Sin"},
            "edge_stablehlo": {"generator": "stablehlo.sine"},
            "keras": {"eager": "keras_ops.sin"},
            "numpy": {"generator": "np.sin"},
            "tensorflow": {"eager": "tf.sin"},
        },
    },
    "Sinc": {"description": "The Sinc operation.", "operation": "Sinc", "variants": {"cupy": {"eager": "cp.sinc"}, "dask": {"eager": "da.sinc"}}},
    "Sinh": {"description": "The Sinh operation.", "operation": "Sinh", "variants": {"cupy": {"eager": "cp.sinh"}, "dask": {"eager": "da.sinh"}, "keras": {"eager": "keras_ops.sinh"}, "tensorflow": {"eager": "tf.sinh"}}},
    "Size": {"description": "The Size operation.", "operation": "Size", "variants": {"keras": {"eager": "keras_ops.size"}, "tensorflow": {"eager": "tf.size"}}},
    "Slice": {"description": "The Slice operation.", "operation": "Slice", "variants": {"edge_onnx": {"generator": "Slice"}, "edge_stablehlo": {"generator": "stablehlo.slice"}, "keras": {"eager": "keras_ops.slice"}, "tensorflow": {"eager": "tf.slice"}}},
    "Slogdet": {"description": "The Slogdet operation.", "operation": "Slogdet", "variants": {"keras": {"eager": "keras_ops.slogdet"}, "numpy": {"generator": "np.linalg.slogdet"}, "tensorflow": {"eager": "tf.linalg.slogdet"}}},
    "SobolSample": {"description": "The SobolSample operation.", "operation": "SobolSample", "variants": {"tensorflow": {"eager": "tf.math.sobol_sample"}}},
    "Softmax": {"description": "The Softmax operation.", "operation": "Softmax", "variants": {"edge_onnx": {"generator": "Softmax"}, "keras": {"eager": "keras_ops.softmax"}, "numpy": {"generator": "scipy.special.softmax({0}, axis={axis})"}, "tensorflow": {"eager": "tf.math.softmax"}}},
    "Softsign": {"description": "The Softsign operation.", "operation": "Softsign", "variants": {"keras": {"eager": "keras_ops.softsign"}, "tensorflow": {"eager": "tf.math.softsign"}}},
    "Solve": {"description": "The Solve operation.", "operation": "Solve", "variants": {"cupy": {"eager": "cp.linalg.solve"}, "dask": {"eager": "da.linalg.solve"}, "keras": {"eager": "keras_ops.solve"}, "numpy": {"generator": "np.linalg.solve"}, "tensorflow": {"eager": "tf.linalg.solve"}}},
    "Sort": {"description": "The Sort operation.", "operation": "Sort", "variants": {"keras": {"eager": "keras_ops.sort"}, "numpy": {"generator": "np.sort"}, "pytorch": {"generator": "torch.sort({0}, dim={dimension})"}, "tensorflow": {"eager": "tf.sort"}}},
    "SpaceToBatch": {"description": "The SpaceToBatch operation.", "operation": "SpaceToBatch", "variants": {"tensorflow": {"eager": "tf.space_to_batch"}}},
    "SpaceToBatchND": {"description": "The SpaceToBatchND operation.", "operation": "SpaceToBatchND", "variants": {"tensorflow": {"eager": "tf.space_to_batch_nd"}}},
    "SparseBincount": {"description": "The SparseBincount operation.", "operation": "SparseBincount", "variants": {"numpy": {"generator": "tf.sparse.bincount"}}},
    "SparseCrossHashed": {"description": "The SparseCrossHashed operation.", "operation": "SparseCrossHashed", "variants": {"numpy": {"generator": "tf.sparse.cross_hashed"}}},
    "SparseExpandDims": {"description": "The SparseExpandDims operation.", "operation": "SparseExpandDims", "variants": {"numpy": {"generator": "tf.sparse.expand_dims"}}},
    "SparseEye": {"description": "The SparseEye operation.", "operation": "SparseEye", "variants": {"numpy": {"generator": "tf.sparse.eye"}}},
    "SparseFillEmptyRows": {"description": "The SparseFillEmptyRows operation.", "operation": "SparseFillEmptyRows", "variants": {"numpy": {"generator": "tf.sparse.fill_empty_rows"}}},
    "SparseMapValues": {"description": "The SparseMapValues operation.", "operation": "SparseMapValues", "variants": {"numpy": {"generator": "tf.sparse.map_values"}}},
    "SparseMask": {"description": "The SparseMask operation.", "operation": "SparseMask", "variants": {"numpy": {"generator": "tf.sparse.mask"}}},
    "SparseMaximum": {"description": "The SparseMaximum operation.", "operation": "SparseMaximum", "variants": {"numpy": {"generator": "tf.sparse.maximum"}}},
    "SparseMinimum": {"description": "The SparseMinimum operation.", "operation": "SparseMinimum", "variants": {"numpy": {"generator": "tf.sparse.minimum"}}},
    "SparsePlus": {"description": "The SparsePlus operation.", "operation": "SparsePlus", "variants": {"keras": {"eager": "keras_ops.sparse_plus"}}},
    "SparseReduceMax": {"description": "The SparseReduceMax operation.", "operation": "SparseReduceMax", "variants": {"numpy": {"generator": "tf.sparse.reduce_max"}}},
    "SparseReduceSum": {"description": "The SparseReduceSum operation.", "operation": "SparseReduceSum", "variants": {"numpy": {"generator": "tf.sparse.reduce_sum"}}},
    "SparseReorder": {"description": "The SparseReorder operation.", "operation": "SparseReorder", "variants": {"numpy": {"generator": "tf.sparse.reorder"}}},
    "SparseResetShape": {"description": "The SparseResetShape operation.", "operation": "SparseResetShape", "variants": {"numpy": {"generator": "tf.sparse.reset_shape"}}},
    "SparseReshape": {"description": "The SparseReshape operation.", "operation": "SparseReshape", "variants": {"numpy": {"generator": "tf.sparse.reshape"}}},
    "SparseRetain": {"description": "The SparseRetain operation.", "operation": "SparseRetain", "variants": {"numpy": {"generator": "tf.sparse.retain"}}},
    "SparseSegmentMean": {"description": "The SparseSegmentMean operation.", "operation": "SparseSegmentMean", "variants": {"numpy": {"generator": "tf.sparse.segment_mean"}}},
    "SparseSegmentSqrtN": {"description": "The SparseSegmentSqrtN operation.", "operation": "SparseSegmentSqrtN", "variants": {"numpy": {"generator": "tf.sparse.segment_sqrt_n"}}},
    "SparseSegmentSum": {"description": "The SparseSegmentSum operation.", "operation": "SparseSegmentSum", "variants": {"numpy": {"generator": "tf.sparse.segment_sum"}}},
    "SparseSigmoid": {"description": "The SparseSigmoid operation.", "operation": "SparseSigmoid", "variants": {"keras": {"eager": "keras_ops.sparse_sigmoid"}}},
    "SparseSlice": {"description": "The SparseSlice operation.", "operation": "SparseSlice", "variants": {"numpy": {"generator": "tf.sparse.slice"}}},
    "SparseSoftmax": {"description": "The SparseSoftmax operation.", "operation": "SparseSoftmax", "variants": {"numpy": {"generator": "tf.sparse.softmax"}}},
    "SparseToIndicator": {"description": "The SparseToIndicator operation.", "operation": "SparseToIndicator", "variants": {"numpy": {"generator": "tf.sparse.to_indicator"}}},
    "SparseTranspose": {"description": "The SparseTranspose operation.", "operation": "SparseTranspose", "variants": {"numpy": {"generator": "tf.sparse.transpose"}}},
    "Split": {"description": "The Split operation.", "operation": "Split", "variants": {"keras": {"eager": "keras_ops.split"}, "tensorflow": {"eager": "tf.split"}}},
    "Sqrt": {
        "description": "The Sqrt operation.",
        "operation": "Sqrt",
        "variants": {"cupy": {"eager": "cp.sqrt"}, "dask": {"eager": "da.sqrt"}, "edge_onnx": {"generator": "Sqrt"}, "edge_stablehlo": {"generator": "stablehlo.sqrt"}, "keras": {"eager": "keras_ops.sqrt"}, "tensorflow": {"eager": "tf.sqrt"}},
    },
    "Sqrtm": {"description": "The Sqrtm operation.", "operation": "Sqrtm", "variants": {"tensorflow": {"eager": "tf.linalg.sqrtm"}}},
    "Square": {"description": "The Square operation.", "operation": "Square", "variants": {"cupy": {"eager": "cp.square"}, "dask": {"eager": "da.square"}, "keras": {"eager": "keras_ops.square"}, "tensorflow": {"eager": "tf.square"}}},
    "SquaredDifference": {"description": "The SquaredDifference operation.", "operation": "SquaredDifference", "variants": {"tensorflow": {"eager": "tf.math.squared_difference"}}},
    "Squareplus": {"description": "The Squareplus operation.", "operation": "Squareplus", "variants": {"keras": {"eager": "keras_ops.squareplus"}}},
    "Squeeze": {"description": "The Squeeze operation.", "operation": "Squeeze", "variants": {"cupy": {"eager": "cp.squeeze"}, "dask": {"eager": "da.squeeze"}, "edge_onnx": {"generator": "Squeeze"}, "keras": {"eager": "keras_ops.squeeze"}, "tensorflow": {"eager": "tf.squeeze"}}},
    "Stack": {"description": "The Stack operation.", "operation": "Stack", "variants": {"cupy": {"eager": "cp.stack"}, "dask": {"eager": "da.stack"}, "keras": {"eager": "keras_ops.stack"}, "tensorflow": {"eager": "tf.stack"}}},
    "Std": {"description": "The Std operation.", "operation": "Std", "variants": {"cupy": {"eager": "cp.std"}, "dask": {"eager": "da.std"}, "keras": {"eager": "keras_ops.std"}}},
    "Stft": {
        "description": "The Stft operation.",
        "operation": "Stft",
        "variants": {"keras": {"eager": "keras_ops.stft"}, "pytorch": {"generator": "torch.stft({0}, n_fft={n_fft}, hop_length={hop_length}, win_length={win_length}, window={window}, center={center}, normalized={normalized}, onesided={onesided}, return_complex={return_complex})"}},
    },
    "StopGradient": {"description": "The StopGradient operation.", "operation": "StopGradient", "variants": {"pytorch": {"generator": "{0}.detach()"}}},
    "StridedSlice": {"description": "The StridedSlice operation.", "operation": "StridedSlice", "variants": {"tensorflow": {"eager": "tf.strided_slice"}}},
    "Subtract": {
        "description": "The Subtract operation.",
        "operation": "Subtract",
        "variants": {
            "cupy": {"eager": "cp.subtract", "generator": "cp.subtract"},
            "dask": {"eager": "da.subtract", "generator": "da.subtract"},
            "edge_onnx": {"generator": "Sub"},
            "edge_stablehlo": {"generator": "stablehlo.subtract"},
            "keras": {"eager": "keras_ops.subtract"},
            "numpy": {"generator": "np.subtract"},
            "tensorflow": {"eager": "tf.subtract"},
        },
    },
    "Sum": {
        "description": "The Sum operation.",
        "operation": "Sum",
        "variants": {"cupy": {"eager": "cp.sum", "generator": "cp.sum"}, "dask": {"eager": "da.sum", "generator": "da.sum"}, "keras": {"eager": "keras_ops.sum"}, "numpy": {"generator": "np.sum"}, "pytorch": {"generator": "torch.sum({0}, dim={axis}, keepdim={keepdims})"}},
    },
    "Svd": {"description": "The Svd operation.", "operation": "Svd", "variants": {"cupy": {"eager": "cp.linalg.svd"}, "dask": {"eager": "da.linalg.svd"}, "keras": {"eager": "keras_ops.svd"}, "numpy": {"generator": "np.linalg.svd"}, "tensorflow": {"eager": "tf.linalg.svd"}}},
    "Svdvals": {"description": "The Svdvals operation.", "operation": "Svdvals", "variants": {"numpy": {"generator": "np.linalg.svd({0}, compute_uv=False)"}}},
    "Swapaxes": {"description": "The Swapaxes operation.", "operation": "Swapaxes", "variants": {"cupy": {"eager": "cp.swapaxes"}, "dask": {"eager": "da.swapaxes"}, "keras": {"eager": "keras_ops.swapaxes"}}},
    "Switch": {"description": "The Switch operation.", "operation": "Switch", "variants": {"keras": {"eager": "keras_ops.switch"}}},
    "Take": {"description": "The Take operation.", "operation": "Take", "variants": {"cupy": {"eager": "cp.take"}, "dask": {"eager": "da.take"}, "keras": {"eager": "keras_ops.take"}}},
    "TakeAlongAxis": {"description": "The TakeAlongAxis operation.", "operation": "TakeAlongAxis", "variants": {"keras": {"eager": "keras_ops.take_along_axis"}}},
    "Tan": {"description": "The Tan operation.", "operation": "Tan", "variants": {"cupy": {"eager": "cp.tan"}, "dask": {"eager": "da.tan"}, "edge_onnx": {"generator": "Tan"}, "keras": {"eager": "keras_ops.tan"}, "tensorflow": {"eager": "tf.tan"}}},
    "Tanh": {
        "description": "The Tanh operation.",
        "operation": "Tanh",
        "variants": {"cupy": {"eager": "cp.tanh"}, "dask": {"eager": "da.tanh"}, "edge_onnx": {"generator": "Tanh"}, "edge_stablehlo": {"generator": "stablehlo.tanh"}, "keras": {"eager": "keras_ops.tanh"}, "tensorflow": {"eager": "tf.tanh"}},
    },
    "TensorScatterAdd": {"description": "The TensorScatterAdd operation.", "operation": "TensorScatterAdd", "variants": {"pytorch": {"generator": "{0}.clone().index_put_(tuple({1}.unbind(-1)), {2}, accumulate=True)"}}},
    "TensorScatterUpdate": {"description": "The TensorScatterUpdate operation.", "operation": "TensorScatterUpdate", "variants": {"pytorch": {"generator": "{0}.clone().index_put_(tuple({1}.unbind(-1)), {2})"}}},
    "Tensordot": {
        "description": "The Tensordot operation.",
        "operation": "Tensordot",
        "variants": {"cupy": {"eager": "cp.tensordot"}, "dask": {"eager": "da.tensordot"}, "keras": {"eager": "keras_ops.tensordot"}, "numpy": {"generator": "np.tensordot({0}, {1}, axes={axes})"}, "tensorflow": {"eager": "tf.tensordot"}},
    },
    "Tensorinv": {"description": "The Tensorinv operation.", "operation": "Tensorinv", "variants": {"numpy": {"generator": "np.linalg.tensorinv({0}, ind={ind})"}}},
    "Tensorsolve": {"description": "The Tensorsolve operation.", "operation": "Tensorsolve", "variants": {"numpy": {"generator": "np.linalg.tensorsolve({0}, {1}, axes={axes})"}}},
    "Tile": {"description": "The Tile operation.", "operation": "Tile", "variants": {"cupy": {"eager": "cp.tile"}, "dask": {"eager": "da.tile"}, "keras": {"eager": "keras_ops.tile"}, "tensorflow": {"eager": "tf.tile"}}},
    "TopK": {"description": "The TopK operation.", "operation": "TopK", "variants": {"keras": {"eager": "keras_ops.top_k"}, "tensorflow": {"eager": "tf.math.top_k"}}},
    "Trace": {
        "description": "The Trace operation.",
        "operation": "Trace",
        "variants": {"cupy": {"eager": "cp.trace"}, "dask": {"eager": "da.trace"}, "keras": {"eager": "keras_ops.trace"}, "numpy": {"generator": "np.trace({0}, offset={offset}, axis1={axis1}, axis2={axis2})"}, "tensorflow": {"eager": "tf.linalg.trace"}},
    },
    "Transpose": {
        "description": "The Transpose operation.",
        "operation": "Transpose",
        "variants": {
            "cupy": {"eager": "cp.transpose", "generator": "cp.transpose"},
            "dask": {"eager": "da.transpose", "generator": "da.transpose"},
            "edge_onnx": {"generator": "Transpose"},
            "edge_stablehlo": {"generator": "stablehlo.transpose"},
            "keras": {"eager": "keras_ops.transpose"},
            "numpy": {"generator": "np.transpose"},
            "pytorch": {"generator": "torch.permute({0}, {axes})"},
            "tensorflow": {"eager": "tf.transpose"},
        },
    },
    "TriangularSolve": {
        "description": "The TriangularSolve operation.",
        "operation": "TriangularSolve",
        "variants": {"numpy": {"generator": "scipy.linalg.solve_triangular({0}, {1}, lower={lower}, unit_diagonal={unit_diagonal}, trans=1 if {adjoint} else 0, check_finite=False)"}, "tensorflow": {"eager": "tf.linalg.triangular_solve"}},
    },
    "TridiagonalMatmul": {"description": "The TridiagonalMatmul operation.", "operation": "TridiagonalMatmul", "variants": {"tensorflow": {"eager": "tf.linalg.tridiagonal_matmul"}}},
    "TridiagonalSolve": {"description": "The TridiagonalSolve operation.", "operation": "TridiagonalSolve", "variants": {"numpy": {"generator": "scipy.linalg.solve_banded((1, 1), np.stack([{2}, {1}, {0}], axis=-2), {3})"}, "tensorflow": {"eager": "tf.linalg.tridiagonal_solve"}}},
    "TrueDivide": {
        "description": "The TrueDivide operation.",
        "operation": "TrueDivide",
        "variants": {
            "cupy": {"eager": "cp.true_divide", "generator": "cp.divide"},
            "dask": {"eager": "da.true_divide", "generator": "da.divide"},
            "edge_onnx": {"generator": "Div"},
            "edge_stablehlo": {"generator": "stablehlo.divide"},
            "keras": {"eager": "keras_ops.true_divide"},
            "numpy": {"generator": "np.divide"},
            "pytorch": {"generator": "torch.true_divide({0}, {1})"},
        },
    },
    "Trunc": {"description": "The Trunc operation.", "operation": "Trunc", "variants": {"cupy": {"eager": "cp.trunc"}, "dask": {"eager": "da.trunc"}, "keras": {"eager": "keras_ops.trunc"}}},
    "TruncateDiv": {"description": "The TruncateDiv operation.", "operation": "TruncateDiv", "variants": {"pytorch": {"generator": "torch.trunc({0} / {1})"}}},
    "TruncateMod": {"description": "The TruncateMod operation.", "operation": "TruncateMod", "variants": {"pytorch": {"generator": "torch.fmod({0}, {1})"}}},
    "Union1d": {"description": "The Union1d operation.", "operation": "Union1d", "variants": {"cupy": {"eager": "cp.union1d"}, "dask": {"eager": "da.union1d"}}},
    "Unique": {"description": "The Unique operation.", "operation": "Unique", "variants": {"cupy": {"eager": "cp.unique"}, "dask": {"eager": "da.unique"}, "tensorflow": {"eager": "tf.unique"}}},
    "UnravelIndex": {"description": "The UnravelIndex operation.", "operation": "UnravelIndex", "variants": {"cupy": {"eager": "cp.unravel_index"}, "dask": {"eager": "da.unravel_index"}, "keras": {"eager": "keras_ops.unravel_index"}, "tensorflow": {"eager": "tf.unravel_index"}}},
    "Unsqueeze": {"description": "The Unsqueeze operation.", "operation": "Unsqueeze", "variants": {"edge_onnx": {"generator": "Unsqueeze"}}},
    "Unstack": {"description": "The Unstack operation.", "operation": "Unstack", "variants": {"keras": {"eager": "keras_ops.unstack"}, "tensorflow": {"eager": "tf.unstack"}}},
    "Vdot": {"description": "The Vdot operation.", "operation": "Vdot", "variants": {"cupy": {"eager": "cp.vdot"}, "dask": {"eager": "da.vdot"}, "keras": {"eager": "keras_ops.vdot"}}},
    "Vecdot": {"description": "The Vecdot operation.", "operation": "Vecdot", "variants": {"numpy": {"generator": "np.sum({0} * {1}, axis={axis})"}}},
    "VectorNorm": {"description": "The VectorNorm operation.", "operation": "VectorNorm", "variants": {"numpy": {"generator": "np.linalg.norm({0}, axis={axis}, keepdims={keepdims}, ord={ord})"}}},
    "Vstack": {"description": "The Vstack operation.", "operation": "Vstack", "variants": {"cupy": {"eager": "cp.vstack"}, "dask": {"eager": "da.vstack"}, "keras": {"eager": "keras_ops.vstack"}}},
    "Where": {
        "description": "The Where operation.",
        "operation": "Where",
        "variants": {"cupy": {"eager": "cp.where"}, "dask": {"eager": "da.where"}, "edge_onnx": {"generator": "Where"}, "edge_stablehlo": {"generator": "stablehlo.select"}, "keras": {"eager": "keras_ops.where"}, "tensorflow": {"eager": "tf.where"}},
    },
    "WhileLoop": {"description": "The WhileLoop operation.", "operation": "WhileLoop", "variants": {"edge_onnx": {"generator": "Loop"}, "edge_stablehlo": {"generator": "stablehlo.while"}}},
    "WithShardingConstraint": {"description": "The WithShardingConstraint operation.", "operation": "WithShardingConstraint", "variants": {"numpy": {"generator": "{0}"}}},
    "Xdivy": {"description": "The Xdivy operation.", "operation": "Xdivy", "variants": {"tensorflow": {"eager": "tf.math.xdivy"}}},
    "Xlog1py": {"description": "The Xlog1py operation.", "operation": "Xlog1py", "variants": {"tensorflow": {"eager": "tf.math.xlog1py"}}},
    "Xlogy": {"description": "The Xlogy operation.", "operation": "Xlogy", "variants": {"tensorflow": {"eager": "tf.math.xlogy"}}},
    "YiqToRgb": {"description": "The YiqToRgb operation.", "operation": "YiqToRgb", "variants": {"pytorch": {"generator": "{0}"}}},
    "YuvToRgb": {"description": "The YuvToRgb operation.", "operation": "YuvToRgb", "variants": {"pytorch": {"generator": "{0}"}}},
    "ZeroFraction": {"description": "The ZeroFraction operation.", "operation": "ZeroFraction", "variants": {"tensorflow": {"eager": "tf.math.zero_fraction"}}},
    "Zeros": {"description": "The Zeros operation.", "operation": "Zeros", "variants": {"numpy": {"generator": "np.zeros"}, "pytorch": {"generator": "torch.zeros({shape})"}}},
    "Zeta": {"description": "The Zeta operation.", "operation": "Zeta", "variants": {"numpy": {"generator": "scipy.special.zeta"}, "tensorflow": {"eager": "tf.math.zeta"}}},
    "bfloat16": {"description": "The bfloat16 operation.", "operation": "bfloat16", "variants": {"edge_stablehlo": {"generator": "bf16"}}},
    "bool": {"description": "The bool operation.", "operation": "bool", "variants": {"edge_stablehlo": {"generator": "i1"}}},
    "float16": {"description": "The float16 operation.", "operation": "float16", "variants": {"edge_stablehlo": {"generator": "f16"}}},
    "float32": {"description": "The float32 operation.", "operation": "float32", "variants": {"edge_stablehlo": {"generator": "f32"}}},
    "float64": {"description": "The float64 operation.", "operation": "float64", "variants": {"edge_stablehlo": {"generator": "f64"}}},
    "int16": {"description": "The int16 operation.", "operation": "int16", "variants": {"edge_stablehlo": {"generator": "i16"}}},
    "int32": {"description": "The int32 operation.", "operation": "int32", "variants": {"edge_stablehlo": {"generator": "i32"}}},
    "int64": {"description": "The int64 operation.", "operation": "int64", "variants": {"edge_stablehlo": {"generator": "i64"}}},
    "int8": {"description": "The int8 operation.", "operation": "int8", "variants": {"edge_stablehlo": {"generator": "i8"}}},
    "uint16": {"description": "The uint16 operation.", "operation": "uint16", "variants": {"edge_stablehlo": {"generator": "ui16"}}},
    "uint32": {"description": "The uint32 operation.", "operation": "uint32", "variants": {"edge_stablehlo": {"generator": "ui32"}}},
    "uint64": {"description": "The uint64 operation.", "operation": "uint64", "variants": {"edge_stablehlo": {"generator": "ui64"}}},
    "uint8": {"description": "The uint8 operation.", "operation": "uint8", "variants": {"edge_stablehlo": {"generator": "ui8"}}},
}
