# ruff: noqa: E402, F401, E501, C901, PLR0911, PLR0912, F841, PLR0917, F811, B018, E701, E722, F403, E711, E712, PLR0913, PLR0915
"""Module image.py."""

from typing import Any

"""Image processing operations (alias for vision module)."""

from ml_switcheroo_compiler.ops.vision import (
    adjust_brightness,
    adjust_contrast,
    adjust_hue,
    adjust_saturation,
    augmix,
    auto_contrast,
    crop,
    crop_and_resize,
    crop_images,
    cutmix,
    degeneration,
    elastic_transform,
    equalization,
    extract_bounding_boxes,
    extract_patches,
    flip_left_right,
    flip_up_down,
    gaussian_blur,
    hsv_to_rgb,
    invert,
    iou,
    map_coordinates,
    median_filter,
    mixup,
    non_max_suppression,
    pad_images,
    pad_to_bounding_box,
    perspective_transform,
    posterize,
    rand_augment,
    random_color_jitter,
    random_erasing,
    random_flip,
    random_rotation,
    resize,
    resize_bicubic,
    resize_bilinear,
    resize_lanczos3,
    resize_nearest,
    rgb_to_grayscale,
    rgb_to_hsv,
    sharpen,
    solarize,
)

__all__ = [
    "adjust_brightness",
    "adjust_contrast",
    "adjust_hue",
    "adjust_saturation",
    "augmix",
    "auto_contrast",
    "crop",
    "crop_and_resize",
    "crop_images",
    "cutmix",
    "degeneration",
    "elastic_transform",
    "equalization",
    "extract_bounding_boxes",
    "extract_patches",
    "flip_left_right",
    "flip_up_down",
    "gaussian_blur",
    "hsv_to_rgb",
    "invert",
    "iou",
    "map_coordinates",
    "median_filter",
    "mixup",
    "non_max_suppression",
    "pad_images",
    "pad_to_bounding_box",
    "perspective_transform",
    "posterize",
    "rand_augment",
    "random_color_jitter",
    "random_erasing",
    "random_flip",
    "random_rotation",
    "resize",
    "resize_bicubic",
    "resize_bilinear",
    "resize_lanczos3",
    "resize_nearest",
    "rgb_to_grayscale",
    "rgb_to_hsv",
    "sharpen",
    "solarize",
]
