"""Image processing operations (alias for vision module)."""

from ml_switcheroo_compiler.ops.vision import (
    affine_generator,
    affine_transform,
    crop,
    crop_and_resize,
    elastic_transform,
    extract_bounding_boxes,
    flip_left_right,
    flip_up_down,
    pad_to_bounding_box,
    perspective_transform,
    resize_bicubic,
    resize_bilinear,
    resize_lanczos3,
    resize_nearest,
    adjust_brightness,
    adjust_contrast,
    adjust_hue,
    adjust_saturation,
    hsv_to_rgb,
    rgb_to_hsv,
    gaussian_blur,
    iou,
    median_filter,
    non_max_suppression,
)

# Keras ops.image compatibility aliases
resize = resize_bilinear

__all__ = [
    "affine_generator",
    "affine_transform",
    "crop",
    "crop_and_resize",
    "elastic_transform",
    "extract_bounding_boxes",
    "flip_left_right",
    "flip_up_down",
    "pad_to_bounding_box",
    "perspective_transform",
    "resize_bicubic",
    "resize_bilinear",
    "resize_lanczos3",
    "resize_nearest",
    "resize",
    "adjust_brightness",
    "adjust_contrast",
    "adjust_hue",
    "adjust_saturation",
    "hsv_to_rgb",
    "rgb_to_hsv",
    "gaussian_blur",
    "iou",
    "median_filter",
    "non_max_suppression",
]
