"""Base generator for emitting backend code from IR."""

from abc import ABC, abstractmethod

from ml_switcheroo_compiler.ir.core import IRGraph, IRNode


class BaseGenerator(ABC):
    """Abstract base class for backend code generation."""

    def __init__(self, graph: IRGraph) -> None:
        """Initializes the object.

        Args:
            graph (IRGraph): The graph to process.
        """
        self.graph = graph
        from ml_switcheroo_compiler.core.utils.graph_utils import topological_sort

        self.sorted_nodes = topological_sort(graph)
        self.var_names: dict[str, str] = {}
        self.code: list[str] = []
        self.indent_level = 0
        self.header = "# AUTOGENERATED VIA ML-SWITCHEROO - DO NOT EDIT MANUALLY\n\n"

    def get_indent(self) -> str:
        """Evaluate get indent.

        Returns:
            str: The computed result.
        """
        return "    " * self.indent_level

    def add_line(self, line: str) -> None:
        """Add line.

        Args:
            line (str): The line to process.
        """
        self.code.append(f"{self.get_indent()}{line}")

    def assign_var_name(self, node_id: str, prefix: str = "tensor") -> str:
        """Assign var name.

        Args:
            node_id (str): The node_id to process.
            prefix (str): The prefix to process.

        Returns:
            str: The resulting output.
        """
        if node_id not in self.var_names:
            self.var_names[node_id] = f"{prefix}_{len(self.var_names)}"
        return self.var_names[node_id]

    def emit_constant(self, node: IRNode) -> str:
        """Emit code for the constant backend.

        Args:
            node (IRNode): The node to process.

        Returns:
            str: The resulting output.
        """
        val = node.attributes.get("value")
        return repr(val)

    @abstractmethod
    def generate(self) -> str:
        """Define the function wrapper.

        Returns:
            str: The computed result.
        """
        ...

    def _generate_body(self, input_prefix: str = "args") -> None:
        """Visit nodes to generate code body.

        Args:
            input_prefix (str): The input_prefix.
        """
        self.input_idx = 0

        for node in self.sorted_nodes:
            self._generate_node(node, input_prefix)

        if not any(n.op_type == "Output" for n in self.sorted_nodes):
            self.add_line("return None")

    def _generate_node(self, node: IRNode, input_prefix: str) -> None:
        """Execute _generate_node.

        Args:
            node (Any): Argument node.
            input_prefix (Any): Argument input_prefix.
        """
        if node.op_type == "Constant":
            self._handle_constant_node(node)
        elif node.op_type == "Input":
            self._handle_input_node(node, input_prefix)
        elif node.op_type == "Output":
            self._handle_output_node(node)
        else:
            self._handle_compute_node(node)

    def _handle_constant_node(self, node: IRNode) -> None:
        """Execute _handle_constant_node.

        Args:
            node (Any): Argument node.
        """
        val_repr = self.emit_constant(node)
        var_name = self.assign_var_name(node.id, "const")
        self._emit_constant_assignment(var_name, val_repr)

    def _handle_input_node(self, node: IRNode, input_prefix: str) -> None:
        """Execute _handle_input_node.

        Args:
            node (Any): Argument node.
            input_prefix (Any): Argument input_prefix.
        """
        var_name = self.assign_var_name(node.id, "input")
        self._emit_input_assignment(var_name, node, input_prefix, self.input_idx)
        self.input_idx += 1

    def _handle_output_node(self, node: IRNode) -> None:
        """Execute _handle_output_node.

        Args:
            node (Any): Argument node.
        """
        input_vars = [self.var_names.get(in_id, in_id) for in_id in node.inputs]
        returns = ", ".join(input_vars)
        self._emit_output_assignment(node, input_vars, returns)

    def _handle_compute_node(self, node: IRNode) -> None:
        """Execute _handle_compute_node.

        Args:
            node (Any): Argument node.
        """
        var_name = self.assign_var_name(node.id)
        input_vars = [self.var_names.get(in_id, in_id) for in_id in node.inputs]

        kwargs = {**node.attributes}
        if "stream_id" in node.attributes:
            kwargs["stream_id"] = node.attributes["stream_id"]
        if "async_check" in node.attributes:
            kwargs["async_check"] = node.attributes["async_check"]

        if hasattr(node, "shape_metadata") and node.shape_metadata:
            kwargs["shape"] = str(node.shape_metadata)

        expr = self.visit(node, input_vars, **kwargs)
        self.add_line(f"{var_name} = {expr}")

    @abstractmethod
    def visit(
        self,
        node: IRNode,
        input_vars: list[str],
        **kwargs: object,
    ) -> str:
        """Visit a node and return the formatted code string for the operation.

        Args:
            node (IRNode): The node.
            input_vars (list[str]): The input_vars.
            **kwargs: Additional keyword arguments.

        Returns:
            str: The computed result.
        """
        ...

    def _emit_constant_assignment(self, var_name: str, val_repr: str) -> None:
        """Override in subclasses to emit framework-specific constant arrays.

        Args:
            var_name (str): The var_name.
            val_repr (str): The val_repr.
        """
        self.add_line(f"{var_name} = {val_repr}")

    def _emit_input_assignment(
        self,
        var_name: str,
        node: IRNode,
        input_prefix: str,
        input_idx: int,
    ) -> None:
        """Override in subclasses to handle custom input logic (e.g. keras.Input).

        Args:
            var_name (str): The var_name.
            node (IRNode): The node.
            input_prefix (str): The input_prefix.
            input_idx (int): The input_idx.
        """
        self.add_line(f"{var_name} = {input_prefix}[{input_idx}]")

    def _emit_output_assignment(
        self,
        node: IRNode,
        input_vars: list[str],
        returns: str,
    ) -> None:
        """Override in subclasses to handle custom output logic.

        Args:
            node (IRNode): The node.
            input_vars (list[str]): The input_vars.
            returns (str): The returns.
        """
        self.add_line(f"return {returns}")

    @classmethod
    def execute_op(cls: type, op_type: str, *args: object, **kwargs: object) -> object:
        """Eagerly execute an operation.

        Args:
            op_type (str): The operation type.
            *args (object): Positional arguments.
            **kwargs (object): Keyword arguments.

        Returns:
            object: The result.
        """
        msg = f"execute_op not implemented for {cls.__name__}"
        raise NotImplementedError(msg)

    @classmethod
    def zeros(cls: type, shape: tuple[int, ...]) -> object:
        """Create a zero tensor.

        Args:
            shape (tuple[int, ...]): The shape.

        Returns:
            object: The result.
        """
        msg = f"zeros not implemented for {cls.__name__}"
        raise NotImplementedError(msg)

    @classmethod
    def array(cls: type, data: object) -> object:
        """Create a tensor from data.

        Args:
            data (object): The data.

        Returns:
            object: The result.
        """
        msg = f"array not implemented for {cls.__name__}"
        raise NotImplementedError(msg)

    @classmethod
    def asarray(cls: type, data: object) -> object:
        """Convert data to tensor.

        Args:
            data (object): The data.

        Returns:
            object: The result.
        """
        msg = f"asarray not implemented for {cls.__name__}"
        raise NotImplementedError(msg)

    @classmethod
    def item(cls: type, data: object) -> float:
        """Extract a scalar float from the tensor.

        Args:
            data (object): The data.

        Returns:
            float: The result.
        """
        msg = f"item not implemented for {cls.__name__}"
        raise NotImplementedError(msg)

    def _format_generic_fallback(
        self,
        prefix: str,
        op_type: str,
        input_vars: list[str],
        kwargs: dict,
        axis_kwarg: str = "axis",
        keepdims_kwarg: str = "keepdims",
    ) -> str:
        """Execute _format_generic_fallback.

        Args:
            prefix (Any): Argument prefix.
            op_type (Any): Argument op_type.
            input_vars (Any): Argument input_vars.
            kwargs (Any): Argument kwargs.
            axis_kwarg (Any): Argument axis_kwarg.
            keepdims_kwarg (Any): Argument keepdims_kwarg.

        Returns:
        Any: The result.
        """
        args = list(input_vars)
        if "axis" in kwargs and kwargs["axis"] is not None:
            args.append(f"{axis_kwarg}={kwargs['axis']}")
        if kwargs.get("keepdims"):
            args.append(f"{keepdims_kwarg}={kwargs['keepdims']}")

        args_str = ", ".join(args)
        return f"{prefix}.{op_type.lower()}({args_str})"
