"""Formatting utilities for backend code generators."""

from dataclasses import dataclass


@dataclass
class FormatterContext:
    """A context object for the formatter."""

    prefix: str
    op_type: str
    input_vars: list[str]
    kwargs: dict
    axis_kwarg: str = "axis"
    keepdims_kwarg: str = "keepdims"


class OpFormatter:
    """Formatter for backend operation strings."""

    @staticmethod
    def format_backend_string(fmt: str, input_vars: list[str], kwargs: dict) -> str:
        """Replaces format placeholders with variables and kwargs.

        Args:
            fmt: The format string
            input_vars: List of input variable names
            kwargs: Dictionary of keyword arguments

        Returns:
            The formatted string
        """
        for k, v in kwargs.items():
            if f"{{{k}}}" in fmt:
                fmt = fmt.replace(f"{{{k}}}", str(v))
        for i, var in enumerate(input_vars):
            fmt = fmt.replace(f"{{{i}}}", var)
        return fmt

    @staticmethod
    def format_generic_fallback(context: FormatterContext) -> str:
        """Format a generic function call fallback.

        Args:
            context (FormatterContext): The formatting context configuration.

        Returns:
            str: The formatted code string.
        """
        args = list(context.input_vars)
        if "axis" in context.kwargs and context.kwargs["axis"] is not None:
            args.append(f"{context.axis_kwarg}={context.kwargs['axis']}")
        if context.kwargs.get("keepdims"):
            args.append(f"{context.keepdims_kwarg}={context.kwargs['keepdims']}")

        args_str = ", ".join(args)
        return f"{context.prefix}.{context.op_type.lower()}({args_str})"


class FallbackHandler:
    """Handler for code generation fallbacks."""

    @staticmethod
    def generate_fallback_code(
        node: object,
        input_vars: list[str],
        prefix: str,
        **kwargs: object,
    ) -> str:
        """Generate fallback code for an unsupported operation.

        Args:
            node (object): The IR node.
            input_vars (list[str]): List of input variables.
            prefix (str): Backend prefix.
            kwargs (dict): Node attributes.

        Returns:
            str: Generated python code.
        """
        ctx = FormatterContext(  # pragma: no cover
            prefix=prefix,
            op_type=getattr(node, "op_type", "Unknown"),
            input_vars=input_vars,
            kwargs=kwargs,
        )
        return OpFormatter.format_generic_fallback(ctx)  # pragma: no cover


class CodeFormatter:
    """Formatter for handling general code generation syntax and variables."""

    def __init__(self) -> None:
        """Initialize the formatter."""
        self.var_names: dict[str, str] = {}
        self.code: list[str] = []
        self.indent_level = 0
        self.header = "# AUTOGENERATED VIA ML-SWITCHEROO - DO NOT EDIT MANUALLY\n\n"

    def get_indent(self) -> str:
        """Evaluate get indent.

        Returns:
            str: The evaluated output resulting from this operation.
        """
        return "    " * self.indent_level

    def add_line(self, line: str) -> None:
        """Add line.

        Args:
            line (str): The line to process.
        """
        self.code.append(f"{self.get_indent()}{line}")

    def assign_var_name(self, node_id: str, prefix: str = "tensor") -> str:
        """Assign var name.

        Args:
            node_id (str): The node_id to process.
            prefix (str): The prefix to process.

        Returns:
            str: The evaluated output resulting from this operation.
        """
        if node_id not in self.var_names:
            self.var_names[node_id] = f"{prefix}_{len(self.var_names)}"
        return self.var_names[node_id]
