# ruff: noqa: E402, F401, E501, C901, PLR0911, PLR0912, F841, PLR0917, F811, B018, E701, E722, F403, E711, E712, PLR0913, PLR0915
"""Formatting utilities for backend code generators."""

from dataclasses import dataclass
from typing import Any


@dataclass
class FormatterContext:
    """Provide a context object for the formatter."""

    prefix: str
    op_type: str
    input_vars: list[str]
    kwargs: dict[str, Any]
    axis_kwarg: str = "axis"
    keepdims_kwarg: str = "keepdims"


class OpFormatter:
    """Formatter for backend operation strings."""

    @staticmethod
    def format_backend_string(fmt: str, input_vars: list[str], kwargs: dict[str, Any]) -> str:
        """Replace format placeholders with variables and kwargs.

        Args:
            fmt: The format string
            input_vars: List of input variable names
            kwargs: Dictionary of keyword arguments

        Returns:
            The formatted string
        """
        for k, v in kwargs.items():
            if f"{{{k}}}" in fmt:
                fmt = fmt.replace(f"{{{k}}}", str(v))
        for i, var in enumerate(input_vars):
            fmt = fmt.replace(f"{{{i}}}", var)
        if "{__inputs__}" in fmt:
            fmt = fmt.replace("{__inputs__}", ", ".join(input_vars))
        return fmt

    @staticmethod
    def format_generic_fallback(context: FormatterContext) -> str:
        """Format a generic function call fallback.

        Args:
            context (FormatterContext): The formatting context configuration.

        Returns:
            str: The formatted code string.
        """
        args = list(context.input_vars)
        for k, v in context.kwargs.items():
            if k == "axis":
                if v is not None:
                    args.append(f"{context.axis_kwarg}={v}")
            elif k == "keepdims":
                if v:
                    args.append(f"{context.keepdims_kwarg}={v}")
            elif k in ["shape_metadata", "metadata", "node_id"]:
                continue
            else:
                if isinstance(v, str) and not v.startswith("("):
                    args.append(f"{k}='{v}'")
                else:
                    args.append(f"{k}={v}")

        args_str = ", ".join(args)
        return f"{context.prefix}.{context.op_type.lower()}({args_str})"


class FallbackHandler:
    """Handler for code generation fallbacks."""

    @staticmethod
    def generate_fallback_code(
        node: Any,
        input_vars: list[str],
        prefix: str,
        **kwargs: Any,
    ) -> str:
        """Generate fallback code for an unsupported operation.

        Args:
            node (object): The IR node.
            input_vars (list[str]): List of input variables.
            prefix (str): Backend prefix.
            kwargs (dict): Node attributes.

        Returns:
            str: Generated python code.
        """
        ctx = FormatterContext(
            prefix=prefix,
            op_type=getattr(node, "op_type", "Unknown"),
            input_vars=input_vars,
            kwargs=kwargs,
        )
        return OpFormatter.format_generic_fallback(ctx)


class CodeFormatter:
    """Formatter for handling general code generation syntax and variables."""

    def __init__(self) -> None:
        """Initialize the formatter."""
        self.var_names: dict[str, str] = {}
        self.code: list[str] = []
        self.indent_level = 0
        self.header = "# AUTOGENERATED VIA ML-SWITCHEROO - DO NOT EDIT MANUALLY\n\n"

    def get_indent(self) -> str:
        """Get the current indentation string.

        Returns:
            str: The indentation string.
        """
        return "    " * self.indent_level

    def add_line(self, line: str) -> None:
        """Add a line of code.

        Args:
            line (str): The line to add.
        """
        self.code.append(f"{self.get_indent()}{line}")

    def assign_var_name(self, node_id: str, prefix: str = "tensor") -> str:
        """Assign a variable name to a node ID.

        Args:
            node_id (str): The node ID.
            prefix (str): The prefix. Defaults to "tensor".

        Returns:
            str: The variable name.
        """
        if node_id not in self.var_names:
            self.var_names[node_id] = f"{prefix}_{len(self.var_names)}"
        return self.var_names[node_id]
