"""Neural network operations."""

from .activations import (
    crelu as crelu,
    isotonic_regression as isotonic_regression,
)
from .activations import (
    elu,
    gelu,
    relu,
    selu,
    softplus,
    celu,
    glu,
    hard_shrink,
    hard_sigmoid,
    hard_silu,
    hard_swish,
    hard_tanh,
    leaky_relu,
    log_sigmoid,
    log_softmax,
    relu6,
    sigmoid,
    silu,
    soft_shrink,
    softmax,
    softsign,
    hardshrink,
    hardtanh,
    hardswish,
    logsigmoid,
    mish,
    prelu,
    softmin,
    softshrink,
    step,
    sparse_plus,
    sparse_sigmoid,
    sparsemax,
    squareplus,
    swish,
    tanh_shrink,
    threshold,
)
from .conv import (
    GenericConvConfig,
    conv,
    conv1d,
    conv1d_transpose,
    conv2d,
    conv2d_transpose,
    conv3d,
    conv3d_transpose,
    conv_transpose1d,
    conv_transpose2d,
    conv_transpose3d,
    conv_transpose,
    depthwise_conv,
    depthwise_conv1d,
    depthwise_conv2d,
    separable_conv,
    separable_conv1d,
    separable_conv2d,
)
from .dropout import dropout, activity_regularization
from .loss import (
    log_poisson_loss as log_poisson_loss,
    in_top_k as in_top_k,
    l2_loss as l2_loss,
    scale_regularization_loss as scale_regularization_loss,
)
from .normalization import (
    layer_norm,
    group_norm,
    instance_norm,
    batch_norm,
    rms_norm,
    l2_normalize as l2_normalize,
    moments as moments,
    normalize_moments as normalize_moments,
    sufficient_statistics as sufficient_statistics,
    weighted_moments as weighted_moments,
    zero_fraction as zero_fraction,
)
from .loss import (
    ctc_loss,
    dice_loss,
    categorical_generalized_cross_entropy,
    circle_loss,
    binary_crossentropy,
    categorical_crossentropy,
    sparse_categorical_crossentropy,
    ctc_decode,
)
from .normalization import (
    local_response_normalization,
    batch_normalization,
    rms_normalization,
    BatchNormConfig,
)
from .nlp import (
    all_candidate_sampler,
    compute_accidental_hits,
    fixed_unigram_candidate_sampler,
    learned_unigram_candidate_sampler,
    log_uniform_candidate_sampler,
    uniform_candidate_sampler,
    nce_loss,
    sampled_softmax_loss,
    embedding_lookup,
    embedding_lookup_sparse,
    safe_embedding_lookup_sparse,
)
from .conv_utils import (
    depthwise_conv2d_backprop_filter,
    depthwise_conv2d_backprop_input,
    dilation2d,
    erosion2d,
    convolution,
    bias_add,
    collapse_repeated,
    compute_average_loss,
)
from .pooling import (
    avg_pool1d,
    avg_pool2d,
    avg_pool3d,
    max_pool1d,
    max_pool2d,
    max_pool3d,
    max_pool_with_argmax,
    fractional_avg_pool,
    fractional_max_pool,
    pool,
)
from .normalization import (
    batch_norm_with_global_normalization,
    lrn,
)
from .nlp import (
    ctc_beam_search_decoder,
    ctc_greedy_decoder,
    ctc_unique_labels,
)
from .rnn_utils import (
    RNNCellDeviceWrapper,
    RNNCellDropoutWrapper,
    RNNCellResidualWrapper,
)
from .nlp import (
    AttentionConfig,
    DotProductAttentionConfig,
    AttentionInputs,
    attention,
    embedding,
    dot_product_attention,
)
from .time_distributed import time_distributed
from .pooling import average_pool, avg_pool, max_pool, pool1d, pool2d, pool3d
from .rnn import (
    RNNConfig,
    ScanConfig,
    BidirectionalConfig,
    BidirectionalInputs,
    ConvLSTMConfig,
    RNNWeights,
    gru_cell,
    lstm_cell,
    simple_rnn_cell,
    rnn,
    scan,
    conv_lstm_cell,
    conv1d_lstm_cell,
    conv2d_lstm_cell,
    conv3d_lstm_cell,
    bidirectional,
)

from ml_switcheroo_compiler.ops.reductions import adaptive_avg_pool2d, adaptive_max_pool2d

__all__ = [
    "AttentionConfig",
    "AttentionInputs",
    "BatchNormConfig",
    "BidirectionalConfig",
    "BidirectionalInputs",
    "ConvLSTMConfig",
    "DotProductAttentionConfig",
    "GenericConvConfig",
    "RNNCellDeviceWrapper",
    "RNNCellDropoutWrapper",
    "RNNCellResidualWrapper",
    "RNNConfig",
    "RNNWeights",
    "ScanConfig",
    "activity_regularization",
    "adaptive_avg_pool2d",
    "adaptive_max_pool2d",
    "all_candidate_sampler",
    "attention",
    "average_pool",
    "avg_pool",
    "avg_pool1d",
    "avg_pool2d",
    "avg_pool3d",
    "batch_norm",
    "batch_norm_with_global_normalization",
    "batch_normalization",
    "bias_add",
    "bidirectional",
    "binary_crossentropy",
    "categorical_crossentropy",
    "categorical_generalized_cross_entropy",
    "celu",
    "circle_loss",
    "collapse_repeated",
    "compute_accidental_hits",
    "compute_average_loss",
    "conv",
    "conv1d",
    "conv1d_lstm_cell",
    "conv1d_transpose",
    "conv2d",
    "conv2d_lstm_cell",
    "conv2d_transpose",
    "conv3d",
    "conv3d_lstm_cell",
    "conv3d_transpose",
    "conv_lstm_cell",
    "conv_transpose",
    "conv_transpose1d",
    "conv_transpose2d",
    "conv_transpose3d",
    "convolution",
    "crelu",
    "ctc_beam_search_decoder",
    "ctc_decode",
    "ctc_greedy_decoder",
    "ctc_loss",
    "ctc_unique_labels",
    "depthwise_conv",
    "depthwise_conv1d",
    "depthwise_conv2d",
    "depthwise_conv2d_backprop_filter",
    "depthwise_conv2d_backprop_input",
    "dice_loss",
    "dilation2d",
    "dot_product_attention",
    "dropout",
    "elu",
    "embedding",
    "embedding_lookup",
    "embedding_lookup_sparse",
    "erosion2d",
    "fixed_unigram_candidate_sampler",
    "fractional_avg_pool",
    "fractional_max_pool",
    "gelu",
    "glu",
    "group_norm",
    "gru_cell",
    "hard_shrink",
    "hard_sigmoid",
    "hard_silu",
    "hard_swish",
    "hard_tanh",
    "hardshrink",
    "hardswish",
    "hardtanh",
    "in_top_k",
    "instance_norm",
    "isotonic_regression",
    "l2_loss",
    "l2_normalize",
    "layer_norm",
    "leaky_relu",
    "learned_unigram_candidate_sampler",
    "local_response_normalization",
    "log_poisson_loss",
    "log_sigmoid",
    "log_softmax",
    "log_uniform_candidate_sampler",
    "logsigmoid",
    "lrn",
    "lstm_cell",
    "max_pool",
    "max_pool1d",
    "max_pool2d",
    "max_pool3d",
    "max_pool_with_argmax",
    "mish",
    "moments",
    "nce_loss",
    "normalize_moments",
    "pool",
    "pool1d",
    "pool2d",
    "pool3d",
    "prelu",
    "relu",
    "relu6",
    "rms_norm",
    "rms_normalization",
    "rnn",
    "safe_embedding_lookup_sparse",
    "sampled_softmax_loss",
    "scale_regularization_loss",
    "scan",
    "selu",
    "separable_conv",
    "separable_conv1d",
    "separable_conv2d",
    "sigmoid",
    "silu",
    "simple_rnn_cell",
    "soft_shrink",
    "softmax",
    "softmin",
    "softplus",
    "softshrink",
    "softsign",
    "sparse_categorical_crossentropy",
    "sparse_plus",
    "sparse_sigmoid",
    "sparsemax",
    "squareplus",
    "step",
    "sufficient_statistics",
    "swish",
    "tanh_shrink",
    "threshold",
    "time_distributed",
    "uniform_candidate_sampler",
    "weighted_moments",
    "zero_fraction",
]
