"""Activations and advanced NN operations."""

from ml_switcheroo_compiler.nn.activations import (
    elu,
    gelu,
    relu,
    selu,
    softplus,
    celu,
    glu,
    hard_shrink,
    hard_sigmoid,
    hard_silu,
    hard_swish,
    hard_tanh,
    leaky_relu,
    log_sigmoid,
    log_softmax,
    relu6,
    sigmoid,
    silu,
    soft_shrink,
    softmax,
    soft_sign as softsign,
    sparse_plus,
    sparse_sigmoid,
    sparsemax,
    squareplus,
    swish,
    tanh_shrink,
    threshold,
)

__all__ = [
    "relu",
    "selu",
    "elu",
    "gelu",
    "softplus",
    "celu",
    "glu",
    "hard_shrink",
    "hard_sigmoid",
    "hard_silu",
    "hard_swish",
    "hard_tanh",
    "leaky_relu",
    "log_sigmoid",
    "log_softmax",
    "relu6",
    "sigmoid",
    "silu",
    "soft_shrink",
    "softmax",
    "softsign",
    "sparse_plus",
    "sparse_sigmoid",
    "sparsemax",
    "squareplus",
    "swish",
    "tanh_shrink",
    "threshold",
]
