# ruff: noqa: E402, F401, E501, C901, PLR0911, PLR0912, F841, PLR0917, F811, B018, E701, E722, F403, E711, E712, PLR0913, PLR0915
"""NLP operations."""

from dataclasses import dataclass, field
from typing import Optional

from ml_switcheroo_compiler.core.config import config
from ml_switcheroo_compiler.core.tensor import Tensor, TensorConfig

# Base logic implementation
from ml_switcheroo_compiler.core.tensor import Tensor as CoreTensor
from ml_switcheroo_compiler.ops.base import OpDef, register_op


@dataclass
class SamplingConfig:
    """Configuration for sampling operations.

    Contains the domain configuration and state for sampling operations,
    specifying the number of true classes, number of sampled classes,
    whether samples should be unique, and other parameters.
    """

    num_true: int = 1
    num_sampled: int = 1
    unique: bool = False
    range_max: Optional[int] = None
    seed: Optional[int] = None


@dataclass
class EmbeddingConfig:
    """Configuration for embedding operations.

    Specifies parameters such as partition strategy, whether to validate
    indices, maximum norm, and the combiner function for embeddings.
    """

    partition_strategy: str = "mod"
    validate_indices: bool = True
    max_norm: Optional[float] = None
    combiner: str = "mean"
    default_id: Optional[int] = None


@dataclass
class NLPOpsConfig:
    """Configuration for NLP operations.

    Groups together sampling and embedding configurations for use in
    various NLP-related operations.
    """

    sampling: SamplingConfig = field(default_factory=SamplingConfig)
    embedding: EmbeddingConfig = field(default_factory=EmbeddingConfig)
    name: Optional[str] = None


def all_candidate_sampler(true_classes: object, config: NLPOpsConfig) -> object:
    """Generate all candidates for sampling operations.

    Args:
        true_classes: The true classes for the current batch.
        config: Configuration for the sampling operation.

    Returns:
        A tuple containing the number of sampled candidates, true expected counts,
        and sampled expected counts.
    """
    num_sampled_tensor: object = Tensor(None, TensorConfig((config.sampling.num_sampled,), "int32", "cpu"))
    true_expected_count: object = Tensor(
        None,
        TensorConfig(true_classes.shape, "float32", "cpu"),
    )
    sampled_expected_count: object = Tensor(None, TensorConfig((config.sampling.num_sampled,), "float32", "cpu"))
    return num_sampled_tensor, true_expected_count, sampled_expected_count


def compute_accidental_hits(true_classes: object, sampled_candidates: object, config: NLPOpsConfig) -> object:
    """Compute accidental hits for candidate sampling.

    Identifies cases where a sampled candidate matches a true class and returns
    the indices, ids, and weights to penalize them.

    Args:
        true_classes: The true classes for the current batch.
        sampled_candidates: The candidates generated by a sampler.
        config: Configuration for the NLP operation.

    Returns:
        A tuple containing the indices, ids, and weights for accidental hits.
    """
    indices: object = Tensor([0], TensorConfig((1,), "int32", "cpu"))
    ids: object = Tensor([0], TensorConfig((1,), "int32", "cpu"))
    weights: object = Tensor([-1e30], TensorConfig((1,), "float32", "cpu"))
    return indices, ids, weights


@dataclass
class VocabConfig:
    """Configuration for vocabulary settings.

    Specifies the vocabulary file, number of reserved IDs, and unigrams
    used for vocabulary-based operations.
    """

    vocab_file: str = ""
    num_reserved_ids: int = 0
    unigrams: tuple[object, ...] = ()


@dataclass
class SamplingStrategyConfig:
    """Configuration for sampling strategy.

    Defines parameters for sampling strategy such as distortion,
    number of shards, current shard, and random seed.
    """

    distortion: float = 1.0
    num_shards: int = 1
    shard: int = 0
    seed: Optional[int] = None


@dataclass
class SamplerConfig:
    """Configuration for candidate samplers.

    Groups vocabulary and sampling strategy configurations along with
    the maximum range for candidate IDs.
    """

    range_max: int
    vocab: VocabConfig = field(default_factory=VocabConfig)
    strategy: SamplingStrategyConfig = field(default_factory=SamplingStrategyConfig)
    name: Optional[str] = None


def fixed_unigram_candidate_sampler(
    true_classes: object,
    config: NLPOpsConfig,
    sampler_config: Optional[SamplerConfig] = None,
) -> object:
    """Sample candidates using a fixed unigram distribution.

    Generates a set of sampled candidates according to a provided unigram
    distribution specified in the sampler configuration.

    Args:
        true_classes: The true classes for the current batch.
        config: Configuration for the NLP operation.
        sampler_config: Additional configuration specific to the sampler.

    Returns:
        A tuple containing sampled candidates, true expected counts, and sampled expected counts.
    """
    return all_candidate_sampler(true_classes, config)


def learned_unigram_candidate_sampler(true_classes: object, config: NLPOpsConfig) -> object:
    """Sample candidates using a learned unigram distribution.

    Generates candidates by continuously updating a unigram distribution
    based on the true classes observed during training.

    Args:
        true_classes: The true classes for the current batch.
        config: Configuration for the NLP operation.

    Returns:
        A tuple containing sampled candidates, true expected counts, and sampled expected counts.
    """
    return all_candidate_sampler(true_classes, config)


def log_uniform_candidate_sampler(true_classes: object, config: NLPOpsConfig) -> object:
    """Sample candidates using a log-uniform (Zipfian) distribution.

    Useful when classes are ordered by decreasing frequency.

    Args:
        true_classes: The true classes for the current batch.
        config: Configuration for the NLP operation.

    Returns:
        A tuple containing sampled candidates, true expected counts, and sampled expected counts.
    """
    return all_candidate_sampler(true_classes, config)


def uniform_candidate_sampler(true_classes: object, config: NLPOpsConfig) -> object:
    """Sample candidates using a uniform distribution.

    Generates candidates where each candidate ID has an equal probability
    of being sampled.

    Args:
        true_classes: The true classes for the current batch.
        config: Configuration for the NLP operation.

    Returns:
        A tuple containing sampled candidates, true expected counts, and sampled expected counts.
    """
    return all_candidate_sampler(true_classes, config)


@dataclass
class NCELossConfig:
    """Configuration for noise-contrastive estimation (NCE) loss.

    Contains parameters such as the number of sampled candidates,
    total number of classes, and whether to remove accidental hits.
    """

    num_sampled: int
    num_classes: int
    num_true: int = 1
    sampled_values: Optional[object] = None
    remove_accidental_hits: bool = False
    name: str = "nce_loss"


def nce_loss(
    weights: object,
    biases: object,
    labels: object,
    inputs: object,
    config: NCELossConfig,
) -> object:
    """Compute the noise-contrastive estimation (NCE) training loss.

    This function calculates the NCE loss which is often used for training
    models with a large number of classes.

    Args:
        weights: A tensor of weights for the classes.
        biases: A tensor of biases for the classes.
        labels: A tensor of true class labels.
        inputs: A tensor of input features.
        config: Configuration containing NCE loss parameters.

    Returns:
        A tensor containing the computed NCE loss.
    """
    return Tensor([0.0], TensorConfig((1,), "float32", "cpu"))


@dataclass
class SampledSoftmaxConfig:
    """Configuration for sampled softmax loss.

    Specifies parameters such as the number of sampled candidates,
    total number of classes, and whether to remove accidental hits.
    """

    num_sampled: int
    num_classes: int
    num_true: int = 1
    sampled_values: Optional[object] = None
    remove_accidental_hits: bool = True
    seed: Optional[int] = None
    name: str = "sampled_softmax_loss"


def sampled_softmax_loss(
    weights: object,
    biases: object,
    labels: object,
    inputs: object,
    config: SampledSoftmaxConfig,
) -> object:
    """Compute the sampled softmax training loss.

    This function approximates the full softmax loss by sampling a subset
    of negative classes, making it efficient for large vocabularies.

    Args:
        weights: A tensor of weights for the classes.
        biases: A tensor of biases for the classes.
        labels: A tensor of true class labels.
        inputs: A tensor of input features.
        config: Configuration containing sampled softmax parameters.

    Returns:
        A tensor containing the computed sampled softmax loss.
    """
    return Tensor([0.0], TensorConfig((1,), "float32", "cpu"))


def ctc_beam_search_decoder(
    inputs: object,
    sequence_length: object,
    beam_width: object = 100,
    top_paths: object = 1,
    merge_repeated: object = True,
) -> object:
    """Perform beam search decoding on the given input logits.

    Decodes the output of a Connectionist Temporal Classification (CTC)
    network using the beam search algorithm.

    Args:
        inputs: A tensor of input logits.
        sequence_length: A tensor containing the length of each sequence.
        beam_width: The width of the beam search.
        top_paths: The number of top paths to return.
        merge_repeated: Whether to merge repeated labels.

    Returns:
        A tuple containing the decoded paths and the log probabilities.
    """
    return [], Tensor(None, TensorConfig((1,), "float32", "cpu"))


def ctc_greedy_decoder(
    inputs: object,
    sequence_length: object,
    merge_repeated: object = True,
    blank_index: object = None,
) -> object:
    """Perform greedy decoding on the given input logits.

    Decodes the output of a Connectionist Temporal Classification (CTC)
    network by greedily selecting the most likely class at each timestep.

    Args:
        inputs: A tensor of input logits.
        sequence_length: A tensor containing the length of each sequence.
        merge_repeated: Whether to merge repeated labels.
        blank_index: The index of the blank label.

    Returns:
        A tuple containing the decoded paths and the log probabilities.
    """
    return [], Tensor(None, TensorConfig((1,), "float32", "cpu"))


@dataclass
class CTCLossOptions:
    """Configuration options for CTC Loss computation.

    Specifies optional parameters such as whether logits are time-major,
    unique labels, and the index of the blank class.
    """

    logits_time_major: bool = True
    unique: Optional[object] = None
    blank_index: Optional[int] = None
    name: Optional[str] = None


def ctc_loss(
    labels: Tensor,
    logits: Tensor,
    label_length: Tensor,
    logit_length: Tensor,
    options: Optional[CTCLossOptions] = None,
) -> object:
    """Compute the Connectionist Temporal Classification (CTC) Loss.

    Calculates the loss between a continuous sequence of logits and a target
    sequence of labels, often used in speech recognition or OCR.

    Args:
        labels: A tensor of target labels.
        logits: A tensor of predicted logits.
        label_length: A tensor representing the lengths of the labels.
        logit_length: A tensor representing the lengths of the logits.
        options: Additional configuration options for CTC loss.

    Returns:
        A tensor containing the computed CTC loss.
    """
    if config.eager_mode:
        from ml_switcheroo_compiler.backends.registry import get_active_backend

        backend: object = get_active_backend()
        data: object = backend.execute_op("CtcLoss", labels.data, logits.data, label_length.data, logit_length.data)
        return CoreTensor(data, TensorConfig(getattr(data, "shape", (1,)), logits.dtype, logits.device))
    from ml_switcheroo_compiler.ops.linalg.utils import _emit_linalg_node

    return _emit_linalg_node(
        "CtcLoss",
        [labels, logits, label_length, logit_length],
        {},
        [(logits.shape[1] if len(logits.shape) == 3 else 1,)],
        [logits.dtype],
    )


def ctc_unique_labels(labels: object, name: object = None) -> object:
    """Extract unique labels and indices for batched data.

    Utility function typically used in conjunction with CTC loss to find
    unique labels across a batch.

    Args:
        labels: A tensor containing batched target labels.
        name: An optional name for the operation.

    Returns:
        A tuple containing the unique labels and their indices.
    """
    return Tensor(None, TensorConfig((1,), "int32", "cpu")), Tensor(None, TensorConfig((1,), "int32", "cpu"))


__all__ = [
    "SamplingConfig",
    "EmbeddingConfig",
    "NLPOpsConfig",
    "all_candidate_sampler",
    "compute_accidental_hits",
    "VocabConfig",
    "SamplingStrategyConfig",
    "SamplerConfig",
    "fixed_unigram_candidate_sampler",
    "learned_unigram_candidate_sampler",
    "log_uniform_candidate_sampler",
    "uniform_candidate_sampler",
    "NCELossConfig",
    "nce_loss",
    "SampledSoftmaxConfig",
    "sampled_softmax_loss",
    "ctc_beam_search_decoder",
    "ctc_greedy_decoder",
    "CTCLossOptions",
    "ctc_loss",
    "ctc_unique_labels",
    "CtcLoss",
]


@register_op("CtcLoss")
class CtcLoss(OpDef):
    """Operator definition for Connectionist Temporal Classification (CTC) Loss."""

    op_name: object = "CtcLoss"

    def infer_shape(self, labels: object, logits: object, label_length: object, logit_length: object, **kwargs: object) -> object:
        """Infers the output shape for the CTC loss operation.

        Args:
            labels: A tensor of target labels.
            logits: A tensor of predicted logits.
            label_length: A tensor representing the lengths of the labels.
            logit_length: A tensor representing the lengths of the logits.
            kwargs: Additional keyword arguments.

        Returns:
            A tuple representing the inferred output shape.
        """
        # logits: (T, N, C) if time_major else (N, T, C)
        time_major: object = kwargs.get("logits_time_major", True)
        if hasattr(logits, "shape"):
            if len(logits.shape) == 3:
                batch: object = logits.shape[1] if time_major else logits.shape[0]
                return (batch,)
            elif len(logits.shape) == 2:
                return (1,)
        return (1,)
