"""Base generator for emitting backend code from IR."""

from abc import ABC, abstractmethod
from ml_switcheroo.ir.core import IRGraph, IRNode
from ml_switcheroo.ops import get_op


class BaseGenerator(ABC):
    """Abstract base class for backend code generation."""

    def __init__(self, graph: IRGraph) -> None:
        """Docstring."""
        self.graph = graph
        self.sorted_nodes = self._topological_sort(graph)
        self.var_names: dict[str, str] = {}
        self.code: list[str] = []
        self.indent_level = 0
        self.header = "# AUTOGENERATED VIA ML-SWITCHEROO - DO NOT EDIT MANUALLY\n\n"

    def _topological_sort(self, graph: IRGraph) -> list[IRNode]:
        """Strictly sorted nodes for code emission."""
        visited: set[str] = set()
        temp_mark: set[str] = set()
        sorted_nodes: list[IRNode] = []

        def visit(node_id: str) -> None:
            """Docstring."""
            if node_id in temp_mark:
                raise ValueError("Cycle detected in graph.")
            if node_id not in visited:
                temp_mark.add(node_id)
                node = graph.nodes.get(node_id)
                if node is not None:
                    for in_id in node.inputs:
                        visit(in_id)
                temp_mark.remove(node_id)
                visited.add(node_id)
                if node is not None:
                    sorted_nodes.append(node)

        for node_id in graph.nodes.keys():
            if node_id not in visited:
                visit(node_id)

        return sorted_nodes

    def get_indent(self) -> str:
        """Docstring."""
        return "    " * self.indent_level

    def add_line(self, line: str) -> None:
        """Docstring."""
        self.code.append(f"{self.get_indent()}{line}")

    def assign_var_name(self, node_id: str, prefix: str = "tensor") -> str:
        """Docstring."""
        if node_id not in self.var_names:
            self.var_names[node_id] = f"{prefix}_{len(self.var_names)}"
        return self.var_names[node_id]

    def emit_constant(self, node: IRNode) -> str:
        """Docstring."""
        val = node.attributes.get("value")
        return repr(val)

    @abstractmethod
    def generate(self) -> str:
        """Subclasses must implement this to define the function wrapper."""
        ...

    def _generate_body(self, input_prefix: str = "args") -> None:
        """Main execution loop that queries the OpRegistry for string templates."""
        input_idx = 0

        for node in self.sorted_nodes:
            if node.op_type == "Constant":
                val_repr = self.emit_constant(node)
                var_name = self.assign_var_name(node.id, "const")
                self._emit_constant_assignment(var_name, val_repr)
            elif node.op_type == "Input":
                var_name = self.assign_var_name(node.id, "input")
                self._emit_input_assignment(var_name, node, input_prefix, input_idx)
                input_idx += 1
            elif node.op_type == "Output":
                input_vars = [self.var_names.get(in_id, in_id) for in_id in node.inputs]
                returns = ", ".join(input_vars)
                self._emit_output_assignment(node, input_vars, returns)
            else:
                var_name = self.assign_var_name(node.id)
                input_vars = [self.var_names.get(in_id, in_id) for in_id in node.inputs]

                # Query OpRegistry
                try:
                    op_cls = get_op(node.op_type)
                    op_instance = op_cls()

                    kwargs = {**node.attributes}
                    if hasattr(node, "shape_metadata") and node.shape_metadata:
                        kwargs["shape"] = str(node.shape_metadata)

                    # Dispatch to specific backend template
                    expr = self._dispatch_op_template(
                        op_instance, *input_vars, **kwargs
                    )
                    self.add_line(f"{var_name} = {expr}")
                except KeyError:
                    # Fallback for unknown ops during transition
                    args_str = ", ".join(input_vars)
                    self.add_line(
                        f"{var_name} = unknown_op_{node.op_type.lower()}({args_str})"
                    )

        if not any(n.op_type == "Output" for n in self.sorted_nodes):
            self.add_line("return None")

    @abstractmethod
    def _dispatch_op_template(
        self, op_instance: object, *args: object, **kwargs: object
    ) -> str:
        """Delegate to the correct backend emitter (e.g., emit_jax, emit_pytorch)."""
        ...

    def _emit_constant_assignment(self, var_name: str, val_repr: str) -> None:
        """Override in subclasses to emit framework-specific constant arrays."""
        self.add_line(f"{var_name} = {val_repr}")

    def _emit_input_assignment(
        self, var_name: str, node: IRNode, input_prefix: str, input_idx: int
    ) -> None:
        """Override in subclasses to handle custom input logic (e.g. keras.Input)."""
        self.add_line(f"{var_name} = {input_prefix}[{input_idx}]")

    def _emit_output_assignment(
        self, node: IRNode, input_vars: list[str], returns: str
    ) -> None:
        """Override in subclasses to handle custom output logic."""
        self.add_line(f"return {returns}")
