"""JAX/Flax Target Emission."""

from ml_switcheroo.backends.python_generator import PythonCodeGenerator


class JAXCodeGenerator(PythonCodeGenerator):
    """Emit JAX-compatible pure functions from IR."""

    def generate(self) -> str:
        """Generate JAX code from the IR graph.

        Returns:
            str: The generated JAX Python code.
        """
        self.code = [
            "# AUTOGENERATED VIA ML-SWITCHEROO - DO NOT EDIT MANUALLY",
            "import jax",
            "import jax.numpy as jnp\n",
        ]

        self.indent_level = 0
        self.add_line("def apply_model(params, *args, **kwargs):")
        self.indent_level += 1

        input_idx = 0

        for node in self.sorted_nodes:
            if node.op_type == "Constant":
                val_repr = self.emit_constant(node)
                var_name = self.assign_var_name(node.id, "const")
                self.add_line(f"{var_name} = jnp.array({val_repr})")
            elif node.op_type == "Input":
                var_name = self.assign_var_name(node.id, "input")
                self.add_line(f"{var_name} = args[{input_idx}]")
                input_idx += 1
            elif node.op_type == "Output":
                input_vars = [self.var_names.get(in_id, in_id) for in_id in node.inputs]
                returns = ", ".join(input_vars)
                self.add_line(f"return {returns}")
            else:
                var_name = self.assign_var_name(node.id)
                input_vars = [self.var_names.get(in_id, in_id) for in_id in node.inputs]
                args_str = ", ".join(input_vars)

                op_map = {
                    "Add": "jnp.add",
                    "Sub": "jnp.subtract",
                    "Mul": "jnp.multiply",
                    "Div": "jnp.divide",
                    "MatMul": "jnp.matmul",
                    "Relu": "jax.nn.relu",
                    "Transpose": "jnp.transpose",
                    "Greater": "jnp.greater",
                    "Where": "jnp.where",
                    "Expand": "jnp.broadcast_to",
                }
                jax_op = op_map.get(node.op_type, f"jnp.{node.op_type.lower()}")

                # Special handling for operators with kwargs
                if node.op_type == "Expand" and node.shape_metadata:
                    self.add_line(
                        f"{var_name} = {jax_op}({args_str}, shape={node.shape_metadata})"  # noqa: E501
                    )
                else:
                    self.add_line(f"{var_name} = {jax_op}({args_str})")

        if not any(n.op_type == "Output" for n in self.sorted_nodes):
            self.add_line("return None")

        return "\n".join(self.code)
