"""Keras Target Emission."""

from ml_switcheroo.backends.python_generator import PythonCodeGenerator


class KerasCodeGenerator(PythonCodeGenerator):
    """Emit Keras Functional API script from IR."""

    def generate(self) -> str:
        """Generate Keras model code from the IR graph.

        Returns:
            str: The generated Keras Python code.
        """
        self.code = [
            "# AUTOGENERATED VIA ML-SWITCHEROO - DO NOT EDIT MANUALLY",
            "import keras\n",
        ]

        self.indent_level = 0
        self.add_line("def get_model():")
        self.indent_level += 1

        input_vars = []
        output_vars = []

        for node in self.sorted_nodes:
            if node.op_type == "Constant":
                val_repr = self.emit_constant(node)
                var_name = self.assign_var_name(node.id, "const")
                # Using keras.ops.convert_to_tensor for constants if possible,
                # or just treating as a python variable that layers can use.
                self.add_line(f"{var_name} = {val_repr}")
            elif node.op_type == "Input":
                var_name = self.assign_var_name(node.id, "input")
                shape_str = (
                    str(node.shape_metadata) if node.shape_metadata else "(None,)"
                )
                self.add_line(
                    f"{var_name} = keras.Input(shape={shape_str}, name='{node.id}')"
                )
                input_vars.append(var_name)
            elif node.op_type == "Output":
                in_vars = [self.var_names.get(in_id, in_id) for in_id in node.inputs]
                output_vars.extend(in_vars)
            else:
                var_name = self.assign_var_name(node.id)
                in_vars = [self.var_names.get(in_id, in_id) for in_id in node.inputs]

                layer_map = {
                    "Add": f"keras.layers.Add()([{', '.join(in_vars)}])",
                    "Sub": f"keras.layers.Subtract()([{', '.join(in_vars)}])",
                    "Mul": f"keras.layers.Multiply()([{', '.join(in_vars)}])",
                    "Relu": f"keras.layers.ReLU()({in_vars[0] if in_vars else ''})",
                }

                if node.op_type in layer_map:
                    expr = layer_map[node.op_type]
                else:
                    args_str = ", ".join(in_vars)
                    expr = f"keras.layers.{node.op_type}()({args_str})"

                self.add_line(f"{var_name} = {expr}")

        inputs_str = ", ".join(input_vars)
        outputs_str = ", ".join(output_vars)
        self.add_line(
            f"return keras.Model(inputs=[{inputs_str}], outputs=[{outputs_str}])"
        )

        return "\n".join(self.code)
