"""Keras Target Emission."""

from ml_switcheroo.backends.python_generator import PythonCodeGenerator


class KerasCodeGenerator(PythonCodeGenerator):
    """Emit Keras Functional API script from IR."""

    def generate(self) -> str:
        self.code = [
            "# AUTOGENERATED VIA ML-SWITCHEROO - DO NOT EDIT MANUALLY",
            "import keras\n",
        ]

        self.add_line("def get_model():")
        self.indent_level += 1

        for node in self.sorted_nodes:
            # Map IR nodes directly to keras.layers.*
            pass

        self.add_line("return keras.Model(inputs=[], outputs=[])")

        return "\n".join(self.code)
