"""MLX Target Emission."""

from ml_switcheroo.backends.python_generator import PythonCodeGenerator


class MLXCodeGenerator(PythonCodeGenerator):
    """Emit MLX-compatible code from IR."""

    def generate(self) -> str:
        """Generate MLX model code from the IR graph.

        Returns:
            str: The generated MLX Python code.
        """
        self.code = [
            "# AUTOGENERATED VIA ML-SWITCHEROO - DO NOT EDIT MANUALLY",
            "import mlx.core as mx",
            "import mlx.nn as nn\n",
            "class CompiledModel(nn.Module):",
        ]
        self.indent_level = 1
        self.add_line("def __init__(self):")
        self.indent_level += 1
        self.add_line("super().__init__()")
        self.add_line("pass\n")
        self.indent_level -= 1

        self.add_line("def __call__(self, *args, **kwargs):")
        self.indent_level += 1

        input_idx = 0

        for node in self.sorted_nodes:
            if node.op_type == "Constant":
                val_repr = self.emit_constant(node)
                var_name = self.assign_var_name(node.id, "const")
                self.add_line(f"{var_name} = mx.array({val_repr})")
            elif node.op_type == "Input":
                var_name = self.assign_var_name(node.id, "input")
                self.add_line(f"{var_name} = args[{input_idx}]")
                input_idx += 1
            elif node.op_type == "Output":
                input_vars = [self.var_names.get(in_id, in_id) for in_id in node.inputs]
                returns = ", ".join(input_vars)
                self.add_line(f"return {returns}")
            else:
                var_name = self.assign_var_name(node.id)
                input_vars = [self.var_names.get(in_id, in_id) for in_id in node.inputs]
                args_str = ", ".join(input_vars)

                op_map = {
                    "Add": "mx.add",
                    "Sub": "mx.subtract",
                    "Mul": "mx.multiply",
                    "Div": "mx.divide",
                    "MatMul": "mx.matmul",
                    "Relu": "nn.relu",
                    "Transpose": "mx.transpose",
                    "Greater": "mx.greater",
                    "Where": "mx.where",
                    "Expand": "mx.broadcast_to",
                }

                mlx_op = op_map.get(node.op_type, f"mx.{node.op_type.lower()}")

                if node.op_type == "Expand" and node.shape_metadata:
                    self.add_line(
                        f"{var_name} = {mlx_op}({args_str}, {node.shape_metadata})"
                    )
                else:
                    self.add_line(f"{var_name} = {mlx_op}({args_str})")

        if not any(n.op_type == "Output" for n in self.sorted_nodes):
            self.add_line("return None")

        return "\n".join(self.code)
