"""Graph-to-Code Emission Engine (from IR)."""

from ml_switcheroo.ir.core import IRGraph, IRNode
from ml_switcheroo.transforms.pass_manager import DAGTopologicalSorter


class PythonCodeGenerator:
    """Walks the IR graph and emits flat, functional-style Python natively."""

    def __init__(self, graph: IRGraph) -> None:
        """Initialize the PythonCodeGenerator.

        Args:
            graph (IRGraph): The intermediate representation graph to compile.
        """
        self.graph = graph
        self.sorted_nodes = DAGTopologicalSorter.sort(graph)
        self.var_names: dict[str, str] = {}
        self.code: list[str] = []
        self.indent_level = 0
        self.header = "# AUTOGENERATED VIA ML-SWITCHEROO - DO NOT EDIT MANUALLY\n\n"

    def get_indent(self) -> str:
        """Get the current indentation string.

        Returns:
            str: Whitespace string for current indentation.
        """
        return "    " * self.indent_level

    def add_line(self, line: str) -> None:
        """Add a line of code with the current indentation.

        Args:
            line (str): The code line to add.
        """
        self.code.append(f"{self.get_indent()}{line}")

    def assign_var_name(self, node_id: str, prefix: str = "tensor") -> str:
        """Deterministic, topologically sorted variable naming.

        Args:
            node_id (str): The node identifier.
            prefix (str): Prefix for the variable name.

        Returns:
            str: The assigned variable name.
        """
        if node_id not in self.var_names:
            self.var_names[node_id] = f"{prefix}_{len(self.var_names)}"
        return self.var_names[node_id]

    def emit_constant(self, node: IRNode) -> str:
        """Implement Constant Inlining.

        Args:
            node (IRNode): The constant node.

        Returns:
            str: String representation of the constant value.
        """
        val = node.attributes.get("value")
        return repr(val)

    def generate(self) -> str:
        """Generate the Python code.

        Returns:
            str: The generated Python code.
        """
        self.code = [
            self.header,
            "import ml_switcheroo.ops as ops",
            "import ml_switcheroo.nn as nn",
            "\n",
        ]
        self.add_line("def apply_model(*args, **kwargs):")
        self.indent_level += 1

        input_idx = 0

        for node in self.sorted_nodes:
            if node.op_type == "Constant":
                val_repr = self.emit_constant(node)
                var_name = self.assign_var_name(node.id, "const")
                self.add_line(f"{var_name} = {val_repr}")
            elif node.op_type == "Input":
                var_name = self.assign_var_name(node.id, "input")
                self.add_line(f"{var_name} = args[{input_idx}]")
                input_idx += 1
            elif node.op_type == "Output":
                input_vars = [self.var_names.get(in_id, in_id) for in_id in node.inputs]
                returns = ", ".join(input_vars)
                self.add_line(f"return {returns}")
            else:
                var_name = self.assign_var_name(node.id)
                input_vars = [self.var_names.get(in_id, in_id) for in_id in node.inputs]
                args_str = ", ".join(input_vars)

                if node.op_type == "Expand" and node.shape_metadata:
                    self.add_line(
                        f"{var_name} = ops.expand({args_str}, shape={node.shape_metadata})"  # noqa: E501
                    )
                else:
                    self.add_line(
                        f"{var_name} = ops.{node.op_type.lower()}({args_str})"
                    )

        if not any(n.op_type == "Output" for n in self.sorted_nodes):
            self.add_line("return None")

        return "\n".join(self.code)
