"""Graph-to-Code Emission Engine (from IR)."""

from typing import Dict, List
from ml_switcheroo.ir.core import IRGraph, IRNode
from ml_switcheroo.transforms.pass_manager import DAGTopologicalSorter


class PythonCodeGenerator:
    """Walks the IR graph and emits flat, functional-style Python natively."""

    def __init__(self, graph: IRGraph) -> None:
        """Initialize the PythonCodeGenerator."""
        self.graph = graph
        self.sorted_nodes = DAGTopologicalSorter.sort(graph)
        self.var_names: Dict[str, str] = {}
        self.code: List[str] = []
        self.indent_level = 0
        self.header = "# AUTOGENERATED VIA ML-SWITCHEROO - DO NOT EDIT MANUALLY\n\n"

    def get_indent(self) -> str:
        """Get the current indentation string."""
        return "    " * self.indent_level

    def add_line(self, line: str) -> None:
        """Add a line of code with the current indentation."""
        self.code.append(f"{self.get_indent()}{line}")

    def assign_var_name(self, node_id: str, prefix: str = "tensor") -> str:
        """Deterministic, topologically sorted variable naming."""
        if node_id not in self.var_names:
            self.var_names[node_id] = f"{prefix}_{len(self.var_names)}"
        return self.var_names[node_id]

    def emit_constant(self, node: IRNode) -> str:
        """Implement Constant Inlining."""
        val = node.attributes.get("value")
        return repr(val)

    def generate(self) -> str:
        """Generate the Python code."""
        self.code = [
            self.header,
            "import ml_switcheroo.ops as ops",
            "import ml_switcheroo.nn as nn",
            "\n",
        ]
        self.add_line("def apply_model(*args, **kwargs):")
        self.indent_level += 1

        for node in self.sorted_nodes:
            if node.op_type == "Constant":
                val_repr = self.emit_constant(node)
                var_name = self.assign_var_name(node.id, "const")
                self.add_line(f"{var_name} = {val_repr}")
            elif node.op_type == "Input":
                var_name = self.assign_var_name(node.id, "input")
                # Handle inputs through args
                pass
            elif node.op_type == "Output":
                input_vars = [self.var_names.get(in_id, in_id) for in_id in node.inputs]
                returns = ", ".join(input_vars)
                self.add_line(f"return {returns}")
            else:
                var_name = self.assign_var_name(node.id)
                input_vars = [self.var_names.get(in_id, in_id) for in_id in node.inputs]
                # Dummy code folding/op mapping
                args_str = ", ".join(input_vars)
                self.add_line(f"{var_name} = ops.{node.op_type.lower()}({args_str})")

        return "\n".join(self.code)
