"""PyTorch Target Emission."""

from ml_switcheroo.backends.python_generator import PythonCodeGenerator


class PyTorchCodeGenerator(PythonCodeGenerator):
    """Emit PyTorch-compatible code from IR."""

    def generate(self) -> str:
        self.code = [
            "# AUTOGENERATED VIA ML-SWITCHEROO - DO NOT EDIT MANUALLY",
            "import torch",
            "import torch.nn as nn\n",
            "class CompiledModel(nn.Module):",
        ]
        self.indent_level = 1
        self.add_line("def __init__(self):")
        self.indent_level += 1
        self.add_line("super().__init__()")
        # Emit mappings to self.register_parameter
        self.add_line("pass\n")
        self.indent_level -= 1

        self.add_line("def forward(self, *args, **kwargs):")
        self.indent_level += 1

        for node in self.sorted_nodes:
            # Emit topologically sorted torch.* ops
            pass

        self.add_line("return None")

        return "\n".join(self.code)
