"""PyTorch Target Emission."""

from ml_switcheroo.backends.python_generator import PythonCodeGenerator


class PyTorchCodeGenerator(PythonCodeGenerator):
    """Emit PyTorch-compatible code from IR."""

    def generate(self) -> str:
        """Generate PyTorch model code from the IR graph.

        Returns:
            str: The generated PyTorch Python code.
        """
        self.code = [
            "# AUTOGENERATED VIA ML-SWITCHEROO - DO NOT EDIT MANUALLY",
            "import torch",
            "import torch.nn as nn\n",
            "class CompiledModel(nn.Module):",
        ]

        # __init__
        self.indent_level = 1
        self.add_line("def __init__(self):")
        self.indent_level += 1
        self.add_line("super().__init__()")

        has_params = False
        for node in self.sorted_nodes:
            if node.op_type == "Constant":
                val_repr = self.emit_constant(node)
                var_name = self.assign_var_name(node.id, "const")
                self.add_line(
                    f"self.register_parameter('{var_name}', nn.Parameter(torch.tensor({val_repr})))"  # noqa: E501
                )
                has_params = True

        if not has_params:
            self.add_line("pass")

        self.add_line("")
        self.indent_level -= 1

        # forward
        self.add_line("def forward(self, *args, **kwargs):")
        self.indent_level += 1

        input_idx = 0

        for node in self.sorted_nodes:
            if node.op_type == "Constant":
                var_name = self.var_names[node.id]
                self.add_line(f"{var_name} = self.{var_name}")
            elif node.op_type == "Input":
                var_name = self.assign_var_name(node.id, "input")
                self.add_line(f"{var_name} = args[{input_idx}]")
                input_idx += 1
            elif node.op_type == "Output":
                input_vars = [self.var_names.get(in_id, in_id) for in_id in node.inputs]
                returns = ", ".join(input_vars)
                self.add_line(f"return {returns}")
            else:
                var_name = self.assign_var_name(node.id)
                input_vars = [self.var_names.get(in_id, in_id) for in_id in node.inputs]
                args_str = ", ".join(input_vars)

                op_map = {
                    "Add": "torch.add",
                    "Sub": "torch.sub",
                    "Mul": "torch.mul",
                    "Div": "torch.div",
                    "MatMul": "torch.matmul",
                    "Relu": "torch.relu",
                    "Transpose": "torch.transpose",
                    "Greater": "torch.greater",
                    "Where": "torch.where",
                    "Expand": "torch.broadcast_to",
                }

                pt_op = op_map.get(node.op_type, f"torch.{node.op_type.lower()}")

                if node.op_type == "Expand" and node.shape_metadata:
                    self.add_line(
                        f"{var_name} = {pt_op}({args_str}, size={node.shape_metadata})"
                    )
                else:
                    self.add_line(f"{var_name} = {pt_op}({args_str})")

        if not any(n.op_type == "Output" for n in self.sorted_nodes):
            self.add_line("return None")

        return "\n".join(self.code)
