"""TensorFlow Target Emission."""

from ml_switcheroo.backends.python_generator import PythonCodeGenerator


class TensorFlowCodeGenerator(PythonCodeGenerator):
    """Emit TensorFlow-compatible code from IR."""

    def generate(self) -> str:
        """Generate TensorFlow model code from the IR graph.

        Returns:
            str: The generated TensorFlow Python code.
        """
        self.code = [
            "# AUTOGENERATED VIA ML-SWITCHEROO - DO NOT EDIT MANUALLY",
            "import tensorflow as tf\n",
        ]

        self.indent_level = 0
        self.add_line("@tf.function")
        self.add_line("def apply_model(*args, **kwargs):")
        self.indent_level += 1

        input_idx = 0

        for node in self.sorted_nodes:
            if node.op_type == "Constant":
                val_repr = self.emit_constant(node)
                var_name = self.assign_var_name(node.id, "const")
                self.add_line(f"{var_name} = tf.constant({val_repr})")
            elif node.op_type == "Input":
                var_name = self.assign_var_name(node.id, "input")
                self.add_line(f"{var_name} = args[{input_idx}]")
                input_idx += 1
            elif node.op_type == "Output":
                input_vars = [self.var_names.get(in_id, in_id) for in_id in node.inputs]
                returns = ", ".join(input_vars)
                self.add_line(f"return {returns}")
            else:
                var_name = self.assign_var_name(node.id)
                input_vars = [self.var_names.get(in_id, in_id) for in_id in node.inputs]
                args_str = ", ".join(input_vars)

                op_map = {
                    "Add": "tf.add",
                    "Sub": "tf.subtract",
                    "Mul": "tf.multiply",
                    "Div": "tf.divide",
                    "MatMul": "tf.matmul",
                    "Relu": "tf.nn.relu",
                    "Transpose": "tf.transpose",
                    "Greater": "tf.greater",
                    "Where": "tf.where",
                    "Expand": "tf.broadcast_to",
                }

                tf_op = op_map.get(node.op_type, f"tf.raw_ops.{node.op_type}")

                if node.op_type == "Expand" and node.shape_metadata:
                    self.add_line(
                        f"{var_name} = {tf_op}({args_str}, shape={node.shape_metadata})"
                    )
                else:
                    self.add_line(f"{var_name} = {tf_op}({args_str})")

        if not any(n.op_type == "Output" for n in self.sorted_nodes):
            self.add_line("return None")

        return "\n".join(self.code)
