"""TensorFlow Target Emission."""

from ml_switcheroo.backends.python_generator import PythonCodeGenerator


class TensorFlowCodeGenerator(PythonCodeGenerator):
    """Emit TensorFlow-compatible code from IR."""

    def generate(self) -> str:
        self.code = [
            "# AUTOGENERATED VIA ML-SWITCHEROO - DO NOT EDIT MANUALLY",
            "import tensorflow as tf\n",
        ]

        self.add_line("@tf.function")
        self.add_line("def apply_model(*args, **kwargs):")
        self.indent_level += 1

        for node in self.sorted_nodes:
            # Map math to tf.raw_ops.*
            pass

        self.add_line("return None")

        return "\n".join(self.code)
