# ruff: noqa: E402, F401, E501, C901, PLR0911, PLR0912, F841, PLR0917, F811, B018, E701, E722, F403, E711, E712, PLR0913, PLR0915
"""Module __init__.py."""

"""Generate random API."""

from ml_switcheroo_compiler.random.continuous import (
    ball,
    beta,
    cauchy,
    chisquare,
    dirichlet,
    double_sided_maxwell,
    exponential,
    f,
    gamma,
    generalized_normal,
    gumbel,
    laplace,
    loggamma,
    logistic,
    lognormal,
    maxwell,
    multivariate_normal,
    normal,
    orthogonal,
    pareto,
    random_gamma_p,
    rayleigh,
    t,
    triangular,
    truncated_normal,
    uniform,
    wald,
    weibull_min,
)
from ml_switcheroo_compiler.random.distributions_discrete import (
    bernoulli,
    binomial,
    categorical,
    choice,
    geometric,
    multinomial,
    permutation,
    poisson,
    rademacher,
    randint,
)
from ml_switcheroo_compiler.random.state import (
    rng_uniform,
)
from ml_switcheroo_compiler.random.transformations import shuffle

__all__ = [
    "ball",
    "bernoulli",
    "beta",
    "binomial",
    "categorical",
    "cauchy",
    "chisquare",
    "choice",
    "dirichlet",
    "double_sided_maxwell",
    "exponential",
    "f",
    "gamma",
    "generalized_normal",
    "geometric",
    "gumbel",
    "laplace",
    "loggamma",
    "logistic",
    "lognormal",
    "maxwell",
    "multinomial",
    "multivariate_normal",
    "normal",
    "orthogonal",
    "pareto",
    "permutation",
    "poisson",
    "rademacher",
    "randint",
    "random_gamma_p",
    "rayleigh",
    "rng_uniform",
    "shuffle",
    "t",
    "triangular",
    "truncated_normal",
    "uniform",
    "wald",
    "weibull_min",
]
