"""Auto-generated high-fidelity type stubs for edge_onnx from ml-framework-snapshots."""
# ruff: noqa: E501

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    def __init__(self, *args: object, **kwargs: object) -> None: ...

def Abs(X: Tensor) -> Tensor: ...
def Acos(input: Tensor) -> Tensor: ...
def Acosh(input: Tensor) -> Tensor: ...
def Add(A: Tensor, B: Tensor) -> Tensor: ...
def AffineGrid(theta: Tensor, size: Tensor, *, align_corners: int = ...) -> Tensor: ...
def And(A: Tensor, B: Tensor) -> Tensor: ...
def ArgMax(data: Tensor, *, select_last_index: int = ..., keepdims: int = ..., axis: int = ...) -> Tensor: ...
def ArgMin(data: Tensor, *, select_last_index: int = ..., keepdims: int = ..., axis: int = ...) -> Tensor: ...
def ArrayFeatureExtractor(X: Tensor, Y: Tensor) -> Tensor: ...
def Asin(input: Tensor) -> Tensor: ...
def Asinh(input: Tensor) -> Tensor: ...
def Atan(input: Tensor) -> Tensor: ...
def Atanh(input: Tensor) -> Tensor: ...
def Attention(
    Q: Tensor, K: Tensor, V: Tensor, attn_mask: Tensor, past_key: Tensor, past_value: Tensor, nonpad_kv_seqlen: Tensor, *, qk_matmul_output_mode: int = ..., softmax_precision: int = ..., is_causal: int = ..., kv_num_heads: int = ..., q_num_heads: int = ..., softcap: float = ..., scale: float = ...
) -> Tensor: ...
def AveragePool(X: Tensor, *, count_include_pad: int = ..., ceil_mode: int = ..., pads: Tensor = ..., kernel_shape: Tensor = ..., strides: Tensor = ..., dilations: Tensor = ..., auto_pad: Tensor = ...) -> Tensor: ...
def BatchNormalization(X: Tensor, scale: Tensor, B: Tensor, input_mean: Tensor, input_var: Tensor, *, training_mode: int = ..., momentum: float = ..., epsilon: float = ...) -> Tensor: ...
def Bernoulli(input: Tensor, *, dtype: int = ..., seed: float = ...) -> Tensor: ...
def Binarizer(X: Tensor, *, threshold: float = ...) -> Tensor: ...
def BitShift(X: Tensor, Y: Tensor, *, direction: Tensor = ...) -> Tensor: ...
def BitwiseAnd(A: Tensor, B: Tensor) -> Tensor: ...
def BitwiseNot(X: Tensor) -> Tensor: ...
def BitwiseOr(A: Tensor, B: Tensor) -> Tensor: ...
def BitwiseXor(A: Tensor, B: Tensor) -> Tensor: ...
def BlackmanWindow(size: Tensor, *, periodic: int = ..., output_datatype: int = ...) -> Tensor: ...
def Cast(input: Tensor, *, round_mode: Tensor = ..., saturate: int = ..., to: int = ...) -> Tensor: ...
def CastLike(input: Tensor, target_type: Tensor, *, round_mode: Tensor = ..., saturate: int = ...) -> Tensor: ...
def CastMap(X: Tensor, *, max_map: int = ..., map_form: Tensor = ..., cast_to: Tensor = ...) -> Tensor: ...
def CategoryMapper(X: Tensor, *, default_int64: int = ..., cats_int64s: Tensor = ..., default_string: Tensor = ..., cats_strings: Tensor = ...) -> Tensor: ...
def Ceil(X: Tensor) -> Tensor: ...
def Celu(X: Tensor, *, alpha: float = ...) -> Tensor: ...
def CenterCropPad(input_data: Tensor, shape: Tensor, *, axes: Tensor = ...) -> Tensor: ...
def Clip(input: Tensor, min: Tensor, max: Tensor) -> Tensor: ...
def Col2Im(input: Tensor, image_shape: Tensor, block_shape: Tensor, *, strides: Tensor = ..., pads: Tensor = ..., dilations: Tensor = ...) -> Tensor: ...
def Compress(input: Tensor, condition: Tensor, *, axis: int = ...) -> Tensor: ...
def Concat(inputs: Tensor, *, axis: int = ...) -> Tensor: ...
def ConcatFromSequence(input_sequence: Tensor, *, new_axis: int = ..., axis: int = ...) -> Tensor: ...
def Constant(*, value_string: Tensor = ..., value_float: float = ..., sparse_value: Tensor = ..., value_floats: Tensor = ..., value_ints: Tensor = ..., value_strings: Tensor = ..., value_int: int = ..., value: Tensor = ...) -> Tensor: ...
def ConstantOfShape(input: Tensor, *, value: Tensor = ...) -> Tensor: ...
def Conv(X: Tensor, W: Tensor, B: Tensor, *, group: int = ..., pads: Tensor = ..., kernel_shape: Tensor = ..., strides: Tensor = ..., auto_pad: Tensor = ..., dilations: Tensor = ...) -> Tensor: ...
def ConvInteger(x: Tensor, w: Tensor, x_zero_point: Tensor, w_zero_point: Tensor, *, group: int = ..., pads: Tensor = ..., kernel_shape: Tensor = ..., strides: Tensor = ..., dilations: Tensor = ..., auto_pad: Tensor = ...) -> Tensor: ...
def ConvTranspose(X: Tensor, W: Tensor, B: Tensor, *, group: int = ..., pads: Tensor = ..., kernel_shape: Tensor = ..., strides: Tensor = ..., output_shape: Tensor = ..., auto_pad: Tensor = ..., dilations: Tensor = ..., output_padding: Tensor = ...) -> Tensor: ...
def Cos(input: Tensor) -> Tensor: ...
def Cosh(input: Tensor) -> Tensor: ...
def CumSum(x: Tensor, axis: Tensor, *, reverse: int = ..., exclusive: int = ...) -> Tensor: ...
def DFT(input: Tensor, dft_length: Tensor, axis: Tensor, *, inverse: int = ..., onesided: int = ...) -> Tensor: ...
def DeformConv(X: Tensor, W: Tensor, offset: Tensor, B: Tensor, mask: Tensor, *, pads: Tensor = ..., group: int = ..., offset_group: int = ..., strides: Tensor = ..., kernel_shape: Tensor = ..., dilations: Tensor = ...) -> Tensor: ...
def DepthToSpace(input: Tensor, *, mode: Tensor = ..., blocksize: int = ...) -> Tensor: ...
def DequantizeLinear(x: Tensor, x_scale: Tensor, x_zero_point: Tensor, *, output_dtype: int = ..., block_size: int = ..., axis: int = ...) -> Tensor: ...
def Det(X: Tensor) -> Tensor: ...
def DictVectorizer(X: Tensor, *, int64_vocabulary: Tensor = ..., string_vocabulary: Tensor = ...) -> Tensor: ...
def Div(A: Tensor, B: Tensor) -> Tensor: ...
def Dropout(data: Tensor, ratio: Tensor, training_mode: Tensor, *, seed: int = ...) -> Tensor: ...
def DynamicQuantizeLinear(x: Tensor) -> Tensor: ...
def Einsum(Inputs: Tensor, *, equation: Tensor = ...) -> Tensor: ...
def Elu(X: Tensor, *, alpha: float = ...) -> Tensor: ...
def Equal(A: Tensor, B: Tensor) -> Tensor: ...
def Erf(input: Tensor) -> Tensor: ...
def Exp(input: Tensor) -> Tensor: ...
def Expand(input: Tensor, shape: Tensor) -> Tensor: ...
def EyeLike(input: Tensor, *, dtype: int = ..., k: int = ...) -> Tensor: ...
def FeatureVectorizer(X: Tensor, *, inputdimensions: Tensor = ...) -> Tensor: ...
def Flatten(input: Tensor, *, axis: int = ...) -> Tensor: ...
def Floor(X: Tensor) -> Tensor: ...
def GRU(
    X: Tensor, W: Tensor, R: Tensor, B: Tensor, sequence_lens: Tensor, initial_h: Tensor, *, activation_beta: Tensor = ..., activation_alpha: Tensor = ..., clip: float = ..., hidden_size: int = ..., layout: int = ..., direction: Tensor = ..., linear_before_reset: int = ..., activations: Tensor = ...
) -> Tensor: ...
def Gather(data: Tensor, indices: Tensor, *, axis: int = ...) -> Tensor: ...
def GatherElements(data: Tensor, indices: Tensor, *, axis: int = ...) -> Tensor: ...
def GatherND(data: Tensor, indices: Tensor, *, batch_dims: int = ...) -> Tensor: ...
def Gelu(X: Tensor, *, approximate: Tensor = ...) -> Tensor: ...
def Gemm(A: Tensor, B: Tensor, C: Tensor, *, beta: float = ..., transB: int = ..., alpha: float = ..., transA: int = ...) -> Tensor: ...
def GlobalAveragePool(X: Tensor) -> Tensor: ...
def GlobalLpPool(X: Tensor, *, p: int = ...) -> Tensor: ...
def GlobalMaxPool(X: Tensor) -> Tensor: ...
def Greater(A: Tensor, B: Tensor) -> Tensor: ...
def GreaterOrEqual(A: Tensor, B: Tensor) -> Tensor: ...
def GridSample(X: Tensor, grid: Tensor, *, align_corners: int = ..., padding_mode: Tensor = ..., mode: Tensor = ...) -> Tensor: ...
def GroupNormalization(X: Tensor, scale: Tensor, bias: Tensor, *, num_groups: int = ..., stash_type: int = ..., epsilon: float = ...) -> Tensor: ...
def HammingWindow(size: Tensor, *, periodic: int = ..., output_datatype: int = ...) -> Tensor: ...
def HannWindow(size: Tensor, *, periodic: int = ..., output_datatype: int = ...) -> Tensor: ...
def HardSigmoid(X: Tensor, *, beta: float = ..., alpha: float = ...) -> Tensor: ...
def HardSwish(X: Tensor) -> Tensor: ...
def Hardmax(input: Tensor, *, axis: int = ...) -> Tensor: ...
def Identity(input: Tensor) -> Tensor: ...
def If(cond: Tensor, *, else_branch: Tensor = ..., then_branch: Tensor = ...) -> Tensor: ...
def ImageDecoder(encoded_stream: Tensor, *, pixel_format: Tensor = ...) -> Tensor: ...
def Imputer(X: Tensor, *, replaced_value_int64: int = ..., imputed_value_int64s: Tensor = ..., replaced_value_float: float = ..., imputed_value_floats: Tensor = ...) -> Tensor: ...
def InstanceNormalization(input: Tensor, scale: Tensor, B: Tensor, *, epsilon: float = ...) -> Tensor: ...
def IsInf(X: Tensor, *, detect_negative: int = ..., detect_positive: int = ...) -> Tensor: ...
def IsNaN(X: Tensor) -> Tensor: ...
def LRN(X: Tensor, *, beta: float = ..., alpha: float = ..., bias: float = ..., size: int = ...) -> Tensor: ...
def LSTM(
    X: Tensor,
    W: Tensor,
    R: Tensor,
    B: Tensor,
    sequence_lens: Tensor,
    initial_h: Tensor,
    initial_c: Tensor,
    P: Tensor,
    *,
    activation_alpha: Tensor = ...,
    clip: float = ...,
    hidden_size: int = ...,
    layout: int = ...,
    direction: Tensor = ...,
    activation_beta: Tensor = ...,
    input_forget: int = ...,
    activations: Tensor = ...,
) -> Tensor: ...
def LabelEncoder(
    X: Tensor,
    *,
    default_tensor: Tensor = ...,
    keys_int64s: Tensor = ...,
    default_string: Tensor = ...,
    keys_strings: Tensor = ...,
    values_floats: Tensor = ...,
    values_tensor: Tensor = ...,
    keys_floats: Tensor = ...,
    default_int64: int = ...,
    values_int64s: Tensor = ...,
    values_strings: Tensor = ...,
    default_float: float = ...,
    keys_tensor: Tensor = ...,
) -> Tensor: ...
def LayerNormalization(X: Tensor, Scale: Tensor, B: Tensor, *, stash_type: int = ..., epsilon: float = ..., axis: int = ...) -> Tensor: ...
def LeakyRelu(X: Tensor, *, alpha: float = ...) -> Tensor: ...
def Less(A: Tensor, B: Tensor) -> Tensor: ...
def LessOrEqual(A: Tensor, B: Tensor) -> Tensor: ...
def LinearClassifier(X: Tensor, *, post_transform: Tensor = ..., classlabels_strings: Tensor = ..., classlabels_ints: Tensor = ..., coefficients: Tensor = ..., multi_class: int = ..., intercepts: Tensor = ...) -> Tensor: ...
def LinearRegressor(X: Tensor, *, targets: int = ..., intercepts: Tensor = ..., coefficients: Tensor = ..., post_transform: Tensor = ...) -> Tensor: ...
def Log(input: Tensor) -> Tensor: ...
def LogSoftmax(input: Tensor, *, axis: int = ...) -> Tensor: ...
def Loop(M: Tensor, cond: Tensor, v_initial: Tensor, *, body: Tensor = ...) -> Tensor: ...
def LpNormalization(input: Tensor, *, p: int = ..., axis: int = ...) -> Tensor: ...
def LpPool(X: Tensor, *, ceil_mode: int = ..., pads: Tensor = ..., kernel_shape: Tensor = ..., strides: Tensor = ..., p: int = ..., auto_pad: Tensor = ..., dilations: Tensor = ...) -> Tensor: ...
def MatMul(A: Tensor, B: Tensor) -> Tensor: ...
def MatMulInteger(A: Tensor, B: Tensor, a_zero_point: Tensor, b_zero_point: Tensor) -> Tensor: ...
def Max(data_0: Tensor) -> Tensor: ...
def MaxPool(X: Tensor, *, storage_order: int = ..., ceil_mode: int = ..., pads: Tensor = ..., kernel_shape: Tensor = ..., strides: Tensor = ..., dilations: Tensor = ..., auto_pad: Tensor = ...) -> Tensor: ...
def MaxRoiPool(X: Tensor, rois: Tensor, *, spatial_scale: float = ..., pooled_shape: Tensor = ...) -> Tensor: ...
def MaxUnpool(X: Tensor, I: Tensor, output_shape: Tensor, *, pads: Tensor = ..., strides: Tensor = ..., kernel_shape: Tensor = ...) -> Tensor: ...
def Mean(data_0: Tensor) -> Tensor: ...
def MeanVarianceNormalization(X: Tensor, *, axes: Tensor = ...) -> Tensor: ...
def MelWeightMatrix(num_mel_bins: Tensor, dft_length: Tensor, sample_rate: Tensor, lower_edge_hertz: Tensor, upper_edge_hertz: Tensor, *, output_datatype: int = ...) -> Tensor: ...
def Min(data_0: Tensor) -> Tensor: ...
def Mish(X: Tensor) -> Tensor: ...
def Mod(A: Tensor, B: Tensor, *, fmod: int = ...) -> Tensor: ...
def Mul(A: Tensor, B: Tensor) -> Tensor: ...
def Multinomial(input: Tensor, *, dtype: int = ..., seed: float = ..., sample_size: int = ...) -> Tensor: ...
def Neg(X: Tensor) -> Tensor: ...
def NegativeLogLikelihoodLoss(input: Tensor, target: Tensor, weight: Tensor, *, ignore_index: int = ..., reduction: Tensor = ...) -> Tensor: ...
def NonMaxSuppression(boxes: Tensor, scores: Tensor, max_output_boxes_per_class: Tensor, iou_threshold: Tensor, score_threshold: Tensor, *, center_point_box: int = ...) -> Tensor: ...
def NonZero(X: Tensor) -> Tensor: ...
def Normalizer(X: Tensor, *, norm: Tensor = ...) -> Tensor: ...
def Not(X: Tensor) -> Tensor: ...
def OneHot(indices: Tensor, depth: Tensor, values: Tensor, *, axis: int = ...) -> Tensor: ...
def OneHotEncoder(X: Tensor, *, zeros: int = ..., cats_strings: Tensor = ..., cats_int64s: Tensor = ...) -> Tensor: ...
def OptionalGetElement(input: Tensor) -> Tensor: ...
def OptionalHasElement(input: Tensor) -> Tensor: ...
def Or(A: Tensor, B: Tensor) -> Tensor: ...
def PRelu(X: Tensor, slope: Tensor) -> Tensor: ...
def Pad(data: Tensor, pads: Tensor, constant_value: Tensor, axes: Tensor, *, mode: Tensor = ...) -> Tensor: ...
def Pow(X: Tensor, Y: Tensor) -> Tensor: ...
def QLinearConv(
    x: Tensor, x_scale: Tensor, x_zero_point: Tensor, w: Tensor, w_scale: Tensor, w_zero_point: Tensor, y_scale: Tensor, y_zero_point: Tensor, B: Tensor, *, group: int = ..., pads: Tensor = ..., kernel_shape: Tensor = ..., strides: Tensor = ..., dilations: Tensor = ..., auto_pad: Tensor = ...
) -> Tensor: ...
def QLinearMatMul(a: Tensor, a_scale: Tensor, a_zero_point: Tensor, b: Tensor, b_scale: Tensor, b_zero_point: Tensor, y_scale: Tensor, y_zero_point: Tensor) -> Tensor: ...
def QuantizeLinear(x: Tensor, y_scale: Tensor, y_zero_point: Tensor, *, output_dtype: int = ..., block_size: int = ..., precision: int = ..., saturate: int = ..., axis: int = ...) -> Tensor: ...
def RMSNormalization(X: Tensor, scale: Tensor, *, stash_type: int = ..., epsilon: float = ..., axis: int = ...) -> Tensor: ...
def RNN(X: Tensor, W: Tensor, R: Tensor, B: Tensor, sequence_lens: Tensor, initial_h: Tensor, *, activation_beta: Tensor = ..., activation_alpha: Tensor = ..., clip: float = ..., hidden_size: int = ..., layout: int = ..., direction: Tensor = ..., activations: Tensor = ...) -> Tensor: ...
def RandomNormal(*, shape: Tensor = ..., scale: float = ..., dtype: int = ..., seed: float = ..., mean: float = ...) -> Tensor: ...
def RandomNormalLike(input: Tensor, *, scale: float = ..., dtype: int = ..., seed: float = ..., mean: float = ...) -> Tensor: ...
def RandomUniform(*, shape: Tensor = ..., dtype: int = ..., seed: float = ..., high: float = ..., low: float = ...) -> Tensor: ...
def RandomUniformLike(input: Tensor, *, dtype: int = ..., seed: float = ..., high: float = ..., low: float = ...) -> Tensor: ...
def Range(start: Tensor, limit: Tensor, delta: Tensor) -> Tensor: ...
def Reciprocal(X: Tensor) -> Tensor: ...
def ReduceL1(data: Tensor, axes: Tensor, *, noop_with_empty_axes: int = ..., keepdims: int = ...) -> Tensor: ...
def ReduceL2(data: Tensor, axes: Tensor, *, noop_with_empty_axes: int = ..., keepdims: int = ...) -> Tensor: ...
def ReduceLogSum(data: Tensor, axes: Tensor, *, noop_with_empty_axes: int = ..., keepdims: int = ...) -> Tensor: ...
def ReduceLogSumExp(data: Tensor, axes: Tensor, *, noop_with_empty_axes: int = ..., keepdims: int = ...) -> Tensor: ...
def ReduceMax(data: Tensor, axes: Tensor, *, noop_with_empty_axes: int = ..., keepdims: int = ...) -> Tensor: ...
def ReduceMean(data: Tensor, axes: Tensor, *, noop_with_empty_axes: int = ..., keepdims: int = ...) -> Tensor: ...
def ReduceMin(data: Tensor, axes: Tensor, *, noop_with_empty_axes: int = ..., keepdims: int = ...) -> Tensor: ...
def ReduceProd(data: Tensor, axes: Tensor, *, noop_with_empty_axes: int = ..., keepdims: int = ...) -> Tensor: ...
def ReduceSum(data: Tensor, axes: Tensor, *, noop_with_empty_axes: int = ..., keepdims: int = ...) -> Tensor: ...
def ReduceSumSquare(data: Tensor, axes: Tensor, *, noop_with_empty_axes: int = ..., keepdims: int = ...) -> Tensor: ...
def RegexFullMatch(X: Tensor, *, pattern: Tensor = ...) -> Tensor: ...
def Relu(X: Tensor) -> Tensor: ...
def Reshape(data: Tensor, shape: Tensor, *, allowzero: int = ...) -> Tensor: ...
def Resize(
    X: Tensor,
    roi: Tensor,
    scales: Tensor,
    sizes: Tensor,
    *,
    extrapolation_value: float = ...,
    keep_aspect_ratio_policy: Tensor = ...,
    antialias: int = ...,
    nearest_mode: Tensor = ...,
    exclude_outside: int = ...,
    cubic_coeff_a: float = ...,
    coordinate_transformation_mode: Tensor = ...,
    axes: Tensor = ...,
    mode: Tensor = ...,
) -> Tensor: ...
def ReverseSequence(input: Tensor, sequence_lens: Tensor, *, batch_axis: int = ..., time_axis: int = ...) -> Tensor: ...
def RoiAlign(X: Tensor, rois: Tensor, batch_indices: Tensor, *, coordinate_transformation_mode: Tensor = ..., sampling_ratio: int = ..., mode: Tensor = ..., output_width: int = ..., output_height: int = ..., spatial_scale: float = ...) -> Tensor: ...
def RotaryEmbedding(X: Tensor, cos_cache: Tensor, sin_cache: Tensor, position_ids: Tensor, *, num_heads: int = ..., rotary_embedding_dim: int = ..., interleaved: int = ...) -> Tensor: ...
def Round(X: Tensor) -> Tensor: ...
def STFT(signal: Tensor, frame_step: Tensor, window: Tensor, frame_length: Tensor, *, onesided: int = ...) -> Tensor: ...
def SVMClassifier(
    X: Tensor,
    *,
    post_transform: Tensor = ...,
    prob_b: Tensor = ...,
    rho: Tensor = ...,
    prob_a: Tensor = ...,
    vectors_per_class: Tensor = ...,
    coefficients: Tensor = ...,
    support_vectors: Tensor = ...,
    kernel_params: Tensor = ...,
    classlabels_ints: Tensor = ...,
    classlabels_strings: Tensor = ...,
    kernel_type: Tensor = ...,
) -> Tensor: ...
def SVMRegressor(X: Tensor, *, rho: Tensor = ..., post_transform: Tensor = ..., n_supports: int = ..., coefficients: Tensor = ..., support_vectors: Tensor = ..., kernel_type: Tensor = ..., one_class: int = ..., kernel_params: Tensor = ...) -> Tensor: ...
def Scaler(X: Tensor, *, scale: Tensor = ..., offset: Tensor = ...) -> Tensor: ...
def Scan(initial_state_and_scan_inputs: Tensor, *, scan_output_axes: Tensor = ..., scan_input_axes: Tensor = ..., scan_output_directions: Tensor = ..., scan_input_directions: Tensor = ..., num_scan_inputs: int = ..., body: Tensor = ...) -> Tensor: ...
def Scatter(data: Tensor, indices: Tensor, updates: Tensor, *, axis: int = ...) -> Tensor: ...
def ScatterElements(data: Tensor, indices: Tensor, updates: Tensor, *, reduction: Tensor = ..., axis: int = ...) -> Tensor: ...
def ScatterND(data: Tensor, indices: Tensor, updates: Tensor, *, reduction: Tensor = ...) -> Tensor: ...
def Selu(X: Tensor, *, gamma: float = ..., alpha: float = ...) -> Tensor: ...
def SequenceAt(input_sequence: Tensor, position: Tensor) -> Tensor: ...
def SequenceConstruct(inputs: Tensor) -> Tensor: ...
def SequenceEmpty(*, dtype: int = ...) -> Tensor: ...
def SequenceErase(input_sequence: Tensor, position: Tensor) -> Tensor: ...
def SequenceInsert(input_sequence: Tensor, tensor: Tensor, position: Tensor) -> Tensor: ...
def SequenceLength(input_sequence: Tensor) -> Tensor: ...
def SequenceMap(input_sequence: Tensor, additional_inputs: Tensor, *, body: Tensor = ...) -> Tensor: ...
def Shape(data: Tensor, *, end: int = ..., start: int = ...) -> Tensor: ...
def Shrink(input: Tensor, *, bias: float = ..., lambd: float = ...) -> Tensor: ...
def Sigmoid(X: Tensor) -> Tensor: ...
def Sign(input: Tensor) -> Tensor: ...
def Sin(input: Tensor) -> Tensor: ...
def Sinh(input: Tensor) -> Tensor: ...
def Size(data: Tensor) -> Tensor: ...
def Slice(data: Tensor, starts: Tensor, ends: Tensor, axes: Tensor, steps: Tensor) -> Tensor: ...
def Softmax(input: Tensor, *, axis: int = ...) -> Tensor: ...
def SoftmaxCrossEntropyLoss(scores: Tensor, labels: Tensor, weights: Tensor, *, ignore_index: int = ..., reduction: Tensor = ...) -> Tensor: ...
def Softplus(X: Tensor) -> Tensor: ...
def Softsign(input: Tensor) -> Tensor: ...
def SpaceToDepth(input: Tensor, *, blocksize: int = ...) -> Tensor: ...
def Split(input: Tensor, split: Tensor, *, num_outputs: int = ..., axis: int = ...) -> Tensor: ...
def SplitToSequence(input: Tensor, split: Tensor, *, keepdims: int = ..., axis: int = ...) -> Tensor: ...
def Sqrt(X: Tensor) -> Tensor: ...
def Squeeze(data: Tensor, axes: Tensor) -> Tensor: ...
def StringConcat(X: Tensor, Y: Tensor) -> Tensor: ...
def StringNormalizer(X: Tensor, *, locale: Tensor = ..., stopwords: Tensor = ..., is_case_sensitive: int = ..., case_change_action: Tensor = ...) -> Tensor: ...
def StringSplit(X: Tensor, *, maxsplit: int = ..., delimiter: Tensor = ...) -> Tensor: ...
def Sub(A: Tensor, B: Tensor) -> Tensor: ...
def Sum(data_0: Tensor) -> Tensor: ...
def Swish(X: Tensor, *, alpha: float = ...) -> Tensor: ...
def Tan(input: Tensor) -> Tensor: ...
def Tanh(input: Tensor) -> Tensor: ...
def TensorScatter(past_cache: Tensor, update: Tensor, write_indices: Tensor, *, mode: Tensor = ..., axis: int = ...) -> Tensor: ...
def TfIdfVectorizer(X: Tensor, *, weights: Tensor = ..., ngram_indexes: Tensor = ..., ngram_counts: Tensor = ..., max_skip_count: int = ..., pool_int64s: Tensor = ..., min_gram_length: int = ..., pool_strings: Tensor = ..., mode: Tensor = ..., max_gram_length: int = ...) -> Tensor: ...
def ThresholdedRelu(X: Tensor, *, alpha: float = ...) -> Tensor: ...
def Tile(input: Tensor, repeats: Tensor) -> Tensor: ...
def TopK(X: Tensor, K: Tensor, *, sorted: int = ..., largest: int = ..., axis: int = ...) -> Tensor: ...
def Transpose(data: Tensor, *, perm: Tensor = ...) -> Tensor: ...
def TreeEnsemble(
    X: Tensor,
    *,
    aggregate_function: int = ...,
    n_targets: int = ...,
    leaf_weights: Tensor = ...,
    leaf_targetids: Tensor = ...,
    nodes_missing_value_tracks_true: Tensor = ...,
    nodes_falseleafs: Tensor = ...,
    nodes_falsenodeids: Tensor = ...,
    membership_values: Tensor = ...,
    nodes_trueleafs: Tensor = ...,
    tree_roots: Tensor = ...,
    post_transform: int = ...,
    nodes_splits: Tensor = ...,
    nodes_truenodeids: Tensor = ...,
    nodes_modes: Tensor = ...,
    nodes_hitrates: Tensor = ...,
    nodes_featureids: Tensor = ...,
) -> Tensor: ...
def TreeEnsembleClassifier(
    X: Tensor,
    *,
    base_values_as_tensor: Tensor = ...,
    classlabels_int64s: Tensor = ...,
    class_weights_as_tensor: Tensor = ...,
    class_weights: Tensor = ...,
    post_transform: Tensor = ...,
    class_ids: Tensor = ...,
    class_nodeids: Tensor = ...,
    nodes_missing_value_tracks_true: Tensor = ...,
    classlabels_strings: Tensor = ...,
    nodes_truenodeids: Tensor = ...,
    nodes_modes: Tensor = ...,
    class_treeids: Tensor = ...,
    nodes_hitrates_as_tensor: Tensor = ...,
    nodes_falsenodeids: Tensor = ...,
    nodes_values_as_tensor: Tensor = ...,
    nodes_hitrates: Tensor = ...,
    nodes_treeids: Tensor = ...,
    nodes_nodeids: Tensor = ...,
    base_values: Tensor = ...,
    nodes_values: Tensor = ...,
    nodes_featureids: Tensor = ...,
) -> Tensor: ...
def TreeEnsembleRegressor(
    X: Tensor,
    *,
    base_values_as_tensor: Tensor = ...,
    aggregate_function: Tensor = ...,
    post_transform: Tensor = ...,
    n_targets: int = ...,
    target_weights: Tensor = ...,
    target_ids: Tensor = ...,
    target_treeids: Tensor = ...,
    nodes_missing_value_tracks_true: Tensor = ...,
    nodes_truenodeids: Tensor = ...,
    nodes_modes: Tensor = ...,
    nodes_hitrates_as_tensor: Tensor = ...,
    nodes_falsenodeids: Tensor = ...,
    nodes_values_as_tensor: Tensor = ...,
    nodes_hitrates: Tensor = ...,
    target_weights_as_tensor: Tensor = ...,
    nodes_treeids: Tensor = ...,
    target_nodeids: Tensor = ...,
    nodes_nodeids: Tensor = ...,
    base_values: Tensor = ...,
    nodes_values: Tensor = ...,
    nodes_featureids: Tensor = ...,
) -> Tensor: ...
def Trilu(input: Tensor, k: Tensor, *, upper: int = ...) -> Tensor: ...
def Unique(X: Tensor, *, axis: int = ..., sorted: int = ...) -> Tensor: ...
def Unsqueeze(data: Tensor, axes: Tensor) -> Tensor: ...
def Upsample(X: Tensor, scales: Tensor, *, mode: Tensor = ...) -> Tensor: ...
def Where(condition: Tensor, X: Tensor, Y: Tensor) -> Tensor: ...
def Xor(A: Tensor, B: Tensor) -> Tensor: ...
def ZipMap(X: Tensor, *, classlabels_int64s: Tensor = ..., classlabels_strings: Tensor = ...) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
