"""Auto-generated high-fidelity type stubs for edge_onnx from live module introspection."""
# ruff: noqa: E501, UP007, UP045, D100, D101, D102, D103

from collections.abc import Sequence

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    device: str
    ndim: int
    size: int
    def __init__(self, data: object = ..., shape: Sequence[int] | None = ..., dtype: str | None = ...) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: object) -> Tensor: ...
    def __add__(self, other: Tensor | float | int) -> Tensor: ...
    def __sub__(self, other: Tensor | float | int) -> Tensor: ...
    def __mul__(self, other: Tensor | float | int) -> Tensor: ...
    def __truediv__(self, other: Tensor | float | int) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def numpy(self) -> object: ...
    def to(self, device: str) -> Tensor: ...
    def reshape(self, shape: Sequence[int]) -> Tensor: ...
    def transpose(self, axes: Sequence[int] | None = ...) -> Tensor: ...

def AttributeProto(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def DeviceConfigurationProto(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def FunctionProto(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def GraphProto(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def IO() -> Tensor: ...
def IntIntListEntryProto(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def Literal(*args: Tensor, **kwds: Tensor) -> Tensor: ...
def MapProto(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ModelProto(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def NodeDeviceConfigurationProto(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def NodeProto(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def OperatorProto(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def OperatorSetIdProto(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def OperatorSetProto(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def OptionalProto(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def SequenceProto(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ShardedDimProto(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ShardingSpecProto(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def SimpleShardedDimProto(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def SparseTensorProto(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def StringStringEntryProto(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def TensorAnnotation(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def TensorProto(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def TensorShapeProto(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def TrainingInfoProto(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def TypeProto(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def Union(*args: Tensor, **kwds: Tensor) -> Tensor: ...
def ValueInfoProto(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def convert_model_to_external_data(model: Tensor, all_tensors_to_one_file: Tensor = ..., location: Tensor = ..., size_threshold: Tensor = ..., convert_attribute: Tensor = ...) -> Tensor: ...
def load(f: Tensor, format: Tensor = ..., load_external_data: Tensor = ...) -> Tensor: ...
def load_external_data_for_model(model: Tensor, base_dir: Tensor) -> Tensor: ...
def load_from_string(s: Tensor, format: Tensor = ...) -> Tensor: ...
def load_model(f: Tensor, format: Tensor = ..., load_external_data: Tensor = ...) -> Tensor: ...
def load_model_from_string(s: Tensor, format: Tensor = ...) -> Tensor: ...
def load_tensor(f: Tensor, format: Tensor = ...) -> Tensor: ...
def load_tensor_from_string(s: Tensor, format: Tensor = ...) -> Tensor: ...
def save(proto: Tensor, f: Tensor, format: Tensor = ..., *, save_as_external_data: Tensor = ..., all_tensors_to_one_file: Tensor = ..., location: Tensor = ..., size_threshold: Tensor = ..., convert_attribute: Tensor = ...) -> Tensor: ...
def save_model(proto: Tensor, f: Tensor, format: Tensor = ..., *, save_as_external_data: Tensor = ..., all_tensors_to_one_file: Tensor = ..., location: Tensor = ..., size_threshold: Tensor = ..., convert_attribute: Tensor = ...) -> Tensor: ...
def save_tensor(proto: Tensor, f: Tensor, format: Tensor = ...) -> Tensor: ...
def write_external_data_tensors(model: Tensor, filepath: Tensor) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
