"""Auto-generated high-fidelity type stubs for awkward from ml-framework-snapshots."""
# ruff: noqa: E501

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    def __init__(self, *args: object, **kwargs: object) -> None: ...

def broadcast_arrays(*arrays: Tensor, depth_limit: Tensor = ..., broadcast_parameters_rule: Tensor = ..., left_broadcast: bool = ..., right_broadcast: bool = ..., highlevel: Tensor = ..., behavior: Tensor = ..., attrs: Tensor = ...) -> Tensor: ...
def cartesian(arrays: Tensor, axis: int = ..., *, nested: str = ..., parameters: Tensor = ..., with_name: Tensor = ..., highlevel: bool = ..., behavior: Tensor = ..., attrs: Tensor = ...) -> Tensor: ...
def combinations(array: Tensor, n: int, *, replacement: bool = ..., axis: int = ..., fields: int = ..., parameters: Tensor = ..., with_name: Tensor = ..., highlevel: bool = ..., behavior: Tensor = ..., attrs: Tensor = ...) -> Tensor: ...
def concatenate(arrays: Tensor, axis: int = ..., *, mergebool: bool = ..., highlevel: bool = ..., behavior: Tensor = ..., attrs: Tensor = ...) -> Tensor: ...
def fill_none(array: Tensor, value: Tensor, axis: Tensor = ..., *, highlevel: bool = ..., behavior: Tensor = ..., attrs: Tensor = ...) -> Tensor: ...
def flatten(array: Tensor, axis: Tensor = ..., *, highlevel: bool = ..., behavior: Tensor = ..., attrs: Tensor = ...) -> Tensor: ...
def from_arrow(array: Tensor, *, generate_bitmasks: bool = ..., highlevel: bool = ..., behavior: None or dict = ..., attrs: None or dict = ...) -> Tensor: ...
def from_numpy(array: Tensor, *, regulararray: bool = ..., recordarray: bool = ..., highlevel: bool = ..., behavior: Tensor = ..., attrs: Tensor = ..., primitive_policy: str = ...) -> Tensor: ...
def is_none(array: Tensor, axis: int = ..., *, highlevel: bool = ..., behavior: Tensor = ..., attrs: Tensor = ...) -> Tensor: ...
def mean(x: Tensor, weight: Tensor = ..., axis: Tensor = ..., *, keepdims: int = ..., mask_identity: bool = ..., highlevel: bool = ..., behavior: Tensor = ..., attrs: Tensor = ...) -> Tensor: ...
def pad_none(array: Tensor, target: int, axis: int = ..., *, clip: bool = ..., highlevel: bool = ..., behavior: Tensor = ..., attrs: Tensor = ...) -> Tensor: ...
def std(x: Tensor, weight: Tensor = ..., ddof: int = ..., axis: Tensor = ..., *, keepdims: int = ..., mask_identity: bool = ..., highlevel: bool = ..., behavior: Tensor = ..., attrs: Tensor = ...) -> Tensor: ...
def sum(array: Tensor, axis: Tensor = ..., *, keepdims: int = ..., mask_identity: bool = ..., highlevel: bool = ..., behavior: Tensor = ..., attrs: Tensor = ...) -> Tensor: ...
def to_arrow(array: Tensor, *, list_to32: bool = ..., string_to32: bool = ..., bytestring_to32: bool = ..., emptyarray_to: Tensor = ..., categorical_as_dictionary: bool = ..., extensionarray: bool = ..., count_nulls: int = ...) -> Tensor: ...
def to_numpy(array: Tensor, *, allow_missing: bool = ...) -> Tensor: ...
def unflatten(array: Tensor, counts: int, axis: int = ..., *, highlevel: bool = ..., behavior: Tensor = ..., attrs: Tensor = ...) -> Tensor: ...
def unzip(array: Tensor, *, how: Tensor = ..., highlevel: bool = ..., behavior: Tensor = ..., attrs: Tensor = ...) -> Tensor: ...
def where(condition: Tensor, x: Tensor, y: Tensor, *args: Tensor, mergebool: bool = ..., highlevel: Tensor = ..., behavior: Tensor = ..., attrs: Tensor = ...) -> Tensor: ...
def zip(arrays: Tensor, depth_limit: Tensor = ..., *, parameters: Tensor = ..., with_name: Tensor = ..., right_broadcast: bool = ..., optiontype_outside_record: bool = ..., highlevel: bool = ..., behavior: Tensor = ..., attrs: Tensor = ...) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
