"""Distributed collective operations re-exported for edge distributed compatibility."""

from ml_switcheroo_compiler.backends.edge.distributed_webrtc.collectives import (
    _BACKEND_COLLECTIVE_REGISTRY,
    DEFAULT_CHUNK_SIZE,
    HIGH_WATERMARK_BYTES,
    LOW_WATERMARK_BYTES,
    DistributedBarrier,
    WebRTCDataChannelStream,
    _recv_data,
    _send_data,
    all_gather,
    all_reduce,
    all_to_all,
    broadcast,
    dispatch_collective,
    get_collective_backend,
    recursive_halving_doubling_all_gather,
    reduce_scatter,
    register_collective_backend,
    ring_all_reduce,
    ring_reduce_scatter,
)

__all__ = [
    "DEFAULT_CHUNK_SIZE",
    "HIGH_WATERMARK_BYTES",
    "LOW_WATERMARK_BYTES",
    "DistributedBarrier",
    "WebRTCDataChannelStream",
    "_BACKEND_COLLECTIVE_REGISTRY",
    "_recv_data",
    "_send_data",
    "all_gather",
    "all_reduce",
    "all_to_all",
    "broadcast",
    "dispatch_collective",
    "get_collective_backend",
    "recursive_halving_doubling_all_gather",
    "reduce_scatter",
    "register_collective_backend",
    "ring_all_reduce",
    "ring_reduce_scatter",
]
