"""Auto-generated high-fidelity type stubs for dask from live module introspection."""
# ruff: noqa: E501

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    def __init__(self, *args: object, **kwargs: object) -> None: ...

def Array(dask: Tensor, name: Tensor, chunks: Tensor, dtype: Tensor = ..., meta: Tensor = ..., shape: Tensor = ...) -> Tensor: ...
def PerformanceWarning(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def abs(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def absolute(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def add(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def all(a: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def allclose(arr1: Tensor, arr2: Tensor, rtol: Tensor = ..., atol: Tensor = ..., equal_nan: Tensor = ...) -> Tensor: ...
def angle(x: Tensor, deg: Tensor = ...) -> Tensor: ...
def any(a: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def append(arr: Tensor, values: Tensor, axis: Tensor = ...) -> Tensor: ...
def apply_along_axis(func1d: Tensor, axis: Tensor, arr: Tensor, *args: Tensor, dtype: Tensor = ..., shape: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def apply_gufunc(func: Tensor, signature: Tensor, *args: Tensor, axes: Tensor = ..., axis: Tensor = ..., keepdims: Tensor = ..., output_dtypes: Tensor = ..., output_sizes: Tensor = ..., vectorize: Tensor = ..., allow_rechunk: Tensor = ..., meta: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def apply_over_axes(func: Tensor, a: Tensor, axes: Tensor) -> Tensor: ...
def arange(*args: Tensor, chunks: Tensor = ..., like: Tensor = ..., dtype: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def arccos(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def arccosh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def arcsin(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def arcsinh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def arctan(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def arctan2(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def arctanh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def argmax(a: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def argmin(a: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def argtopk(a: Tensor, k: Tensor, axis: Tensor = ..., split_every: Tensor = ...) -> Tensor: ...
def argwhere(a: Tensor) -> Tensor: ...
def around(x: Tensor, decimals: Tensor = ...) -> Tensor: ...
def array(x: Tensor, dtype: Tensor = ..., ndmin: Tensor = ..., *, like: Tensor = ...) -> Tensor: ...
def as_gufunc(signature: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def asanyarray(a: Tensor, dtype: Tensor = ..., order: Tensor = ..., *, like: Tensor = ..., inline_array: Tensor = ...) -> Tensor: ...
def asarray(a: Tensor, allow_unknown_chunksizes: Tensor = ..., dtype: Tensor = ..., order: Tensor = ..., *, like: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def assert_eq(
    a: Tensor, b: Tensor, check_shape: Tensor = ..., check_graph: Tensor = ..., check_meta: Tensor = ..., check_chunks: Tensor = ..., check_ndim: Tensor = ..., check_type: Tensor = ..., check_dtype: Tensor = ..., equal_nan: Tensor = ..., scheduler: Tensor = ..., **kwargs: Tensor
) -> Tensor: ...
def atleast_1d(*arys: Tensor) -> Tensor: ...
def atleast_2d(*arys: Tensor) -> Tensor: ...
def atleast_3d(*arys: Tensor) -> Tensor: ...
def atop(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def average(a: Tensor, axis: Tensor = ..., weights: Tensor = ..., returned: Tensor = ..., keepdims: Tensor = ...) -> Tensor: ...
def bincount(x: Tensor, weights: Tensor = ..., minlength: Tensor = ..., split_every: Tensor = ...) -> Tensor: ...
def bitwise_and(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bitwise_not(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bitwise_or(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def bitwise_xor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def block(arrays: Tensor, allow_unknown_chunksizes: Tensor = ...) -> Tensor: ...
def blockwise(func: Tensor, out_ind: Tensor, *args: Tensor, name: Tensor = ..., token: Tensor = ..., dtype: Tensor = ..., adjust_chunks: Tensor = ..., new_axes: Tensor = ..., align_arrays: Tensor = ..., concatenate: Tensor = ..., meta: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def broadcast_arrays(*args: Tensor, subok: Tensor = ...) -> Tensor: ...
def broadcast_to(x: Tensor, shape: Tensor, chunks: Tensor = ..., meta: Tensor = ...) -> Tensor: ...
def cbrt(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ceil(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def choose(a: Tensor, choices: Tensor) -> Tensor: ...
def clip(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def coarsen(reduction: Tensor, x: Tensor, axes: Tensor, trim_excess: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def compress(condition: Tensor, a: Tensor, axis: Tensor = ...) -> Tensor: ...
def compute(*args: Tensor, traverse: Tensor = ..., optimize_graph: Tensor = ..., scheduler: Tensor = ..., get: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def concatenate(seq: Tensor, axis: Tensor = ..., allow_unknown_chunksizes: Tensor = ...) -> Tensor: ...
def conj(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def copysign(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def corrcoef(x: Tensor, y: Tensor = ..., rowvar: Tensor = ...) -> Tensor: ...
def cos(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def cosh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def count_nonzero(a: Tensor, axis: Tensor = ...) -> Tensor: ...
def cov(m: Tensor, y: Tensor = ..., rowvar: Tensor = ..., bias: Tensor = ..., ddof: Tensor = ...) -> Tensor: ...
def cumprod(x: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., method: Tensor = ...) -> Tensor: ...
def cumsum(x: Tensor, axis: Tensor = ..., dtype: Tensor = ..., out: Tensor = ..., method: Tensor = ...) -> Tensor: ...
def deg2rad(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def degrees(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def delete(arr: Tensor, obj: Tensor, axis: Tensor) -> Tensor: ...
def diag(v: Tensor, k: Tensor = ...) -> Tensor: ...
def diagonal(a: Tensor, offset: Tensor = ..., axis1: Tensor = ..., axis2: Tensor = ...) -> Tensor: ...
def diff(a: Tensor, n: Tensor = ..., axis: Tensor = ..., prepend: Tensor = ..., append: Tensor = ...) -> Tensor: ...
def digitize(a: Tensor, bins: Tensor, right: Tensor = ...) -> Tensor: ...
def divide(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def divmod(x: Tensor, y: Tensor) -> Tensor: ...
def dot(a: Tensor, b: Tensor) -> Tensor: ...
def dstack(tup: Tensor, allow_unknown_chunksizes: Tensor = ...) -> Tensor: ...
def ediff1d(ary: Tensor, to_end: Tensor = ..., to_begin: Tensor = ...) -> Tensor: ...
def einsum(*operands: Tensor, dtype: Tensor = ..., optimize: Tensor = ..., split_every: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def empty(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def empty_like(a: Tensor, dtype: Tensor = ..., order: Tensor = ..., chunks: Tensor = ..., name: Tensor = ..., shape: Tensor = ...) -> Tensor: ...
def equal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def exp(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def exp2(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def expand_dims(a: Tensor, axis: Tensor) -> Tensor: ...
def expm1(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def extract(condition: Tensor, arr: Tensor) -> Tensor: ...
def eye(N: Tensor, chunks: Tensor = ..., M: Tensor = ..., k: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def fabs(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fix(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def flatnonzero(a: Tensor) -> Tensor: ...
def flip(m: Tensor, axis: Tensor = ...) -> Tensor: ...
def fliplr(m: Tensor) -> Tensor: ...
def flipud(m: Tensor) -> Tensor: ...
def float_power(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def floor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def floor_divide(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fmax(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fmin(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def fmod(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def frexp(x: Tensor) -> Tensor: ...
def from_array(x: Tensor, chunks: Tensor = ..., name: Tensor = ..., lock: Tensor = ..., asarray: Tensor = ..., fancy: Tensor = ..., getitem: Tensor = ..., meta: Tensor = ..., inline_array: Tensor = ...) -> Tensor: ...
def from_delayed(value: Tensor, shape: Tensor, dtype: Tensor = ..., meta: Tensor = ..., name: Tensor = ...) -> Tensor: ...
def from_npy_stack(dirname: Tensor, mmap_mode: Tensor = ...) -> Tensor: ...
def from_tiledb(uri: Tensor, attribute: Tensor = ..., chunks: Tensor = ..., storage_options: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def from_zarr(url: Tensor, component: Tensor = ..., storage_options: Tensor = ..., chunks: Tensor = ..., name: Tensor = ..., inline_array: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def fromfunction(func: Tensor, chunks: Tensor = ..., shape: Tensor = ..., dtype: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def frompyfunc(func: Tensor, nin: Tensor, nout: Tensor) -> Tensor: ...
def full(shape: Tensor, fill_value: Tensor, *args: Tensor, **kwargs: Tensor) -> Tensor: ...
def full_like(a: Tensor, fill_value: Tensor, order: Tensor = ..., dtype: Tensor = ..., chunks: Tensor = ..., name: Tensor = ..., shape: Tensor = ...) -> Tensor: ...
def gradient(f: Tensor, *varargs: Tensor, axis: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def greater(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def greater_equal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def gufunc(pyfunc: Tensor, *, signature: Tensor = ..., vectorize: Tensor = ..., axes: Tensor = ..., axis: Tensor = ..., keepdims: Tensor = ..., output_sizes: Tensor = ..., output_dtypes: Tensor = ..., allow_rechunk: Tensor = ..., meta: Tensor = ...) -> Tensor: ...
def histogram(a: Tensor, bins: Tensor = ..., range: Tensor = ..., normed: Tensor = ..., weights: Tensor = ..., density: Tensor = ...) -> Tensor: ...
def histogram2d(x: Tensor, y: Tensor, bins: Tensor = ..., range: Tensor = ..., normed: Tensor = ..., weights: Tensor = ..., density: Tensor = ...) -> Tensor: ...
def histogramdd(sample: Tensor, bins: Tensor, range: Tensor = ..., normed: Tensor = ..., weights: Tensor = ..., density: Tensor = ...) -> Tensor: ...
def hstack(tup: Tensor, allow_unknown_chunksizes: Tensor = ...) -> Tensor: ...
def hypot(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def i0(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def imag(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def indices(dimensions: Tensor, dtype: Tensor = ..., chunks: Tensor = ...) -> Tensor: ...
def insert(arr: Tensor, obj: Tensor, values: Tensor, axis: Tensor) -> Tensor: ...
def invert(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def isclose(arr1: Tensor, arr2: Tensor, rtol: Tensor = ..., atol: Tensor = ..., equal_nan: Tensor = ...) -> Tensor: ...
def iscomplex(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def isfinite(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def isin(element: Tensor, test_elements: Tensor, assume_unique: Tensor = ..., invert: Tensor = ..., *, kind: Tensor = ...) -> Tensor: ...
def isinf(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def isnan(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def isneginf(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def isnull(values: Tensor) -> Tensor: ...
def isposinf(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def isreal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ldexp(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def left_shift(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def less(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def less_equal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def linspace(start: Tensor, stop: Tensor, num: Tensor = ..., endpoint: Tensor = ..., retstep: Tensor = ..., chunks: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def log(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def log10(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def log1p(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def log2(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logaddexp(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logaddexp2(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logical_and(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logical_not(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logical_or(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def logical_xor(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def map_blocks(func: Tensor, *args: Tensor, name: Tensor = ..., token: Tensor = ..., dtype: Tensor = ..., chunks: Tensor = ..., drop_axis: Tensor = ..., new_axis: Tensor = ..., enforce_ndim: Tensor = ..., meta: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def map_overlap(func: Tensor, *args: Tensor, depth: Tensor = ..., boundary: Tensor = ..., trim: Tensor = ..., align_arrays: Tensor = ..., allow_rechunk: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def matmul(a: Tensor, b: Tensor) -> Tensor: ...
def max(a: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def maximum(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def mean(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., keepdims: Tensor = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def median(a: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def meshgrid(*xi: Tensor, sparse: Tensor = ..., indexing: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def min(a: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def minimum(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def mod(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def modf(x: Tensor) -> Tensor: ...
def moment(a: Tensor, order: Tensor, axis: Tensor = ..., dtype: Tensor = ..., keepdims: Tensor = ..., ddof: Tensor = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def moveaxis(a: Tensor, source: Tensor, destination: Tensor) -> Tensor: ...
def multiply(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def nan_to_num(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def nanargmax(a: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nanargmin(a: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nancumprod(x: Tensor, axis: Tensor, dtype: Tensor = ..., out: Tensor = ..., *, method: Tensor = ...) -> Tensor: ...
def nancumsum(x: Tensor, axis: Tensor, dtype: Tensor = ..., out: Tensor = ..., *, method: Tensor = ...) -> Tensor: ...
def nanmax(a: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nanmean(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., keepdims: Tensor = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nanmedian(a: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nanmin(a: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nanprod(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., keepdims: Tensor = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nanstd(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., keepdims: Tensor = ..., ddof: Tensor = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nansum(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., keepdims: Tensor = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nanvar(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., keepdims: Tensor = ..., ddof: Tensor = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def ndim(a: Tensor) -> Tensor: ...
def negative(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def nextafter(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def nonzero(a: Tensor) -> Tensor: ...
def not_equal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def notnull(values: Tensor) -> Tensor: ...
def ones(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ones_like(a: Tensor, dtype: Tensor = ..., order: Tensor = ..., chunks: Tensor = ..., name: Tensor = ..., shape: Tensor = ...) -> Tensor: ...
def optimize(dsk: Tensor, keys: Tensor, fuse_keys: Tensor = ..., fast_functions: Tensor = ..., inline_functions_fast_functions: Tensor = ..., rename_fused_keys: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def outer(a: Tensor, b: Tensor) -> Tensor: ...
def pad(array: Tensor, pad_width: Tensor, mode: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def percentile(a: Tensor, q: Tensor, method: Tensor = ..., internal_method: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def piecewise(x: Tensor, condlist: Tensor, funclist: Tensor, *args: Tensor, **kw: Tensor) -> Tensor: ...
def positive(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def power(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def prod(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., keepdims: Tensor = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def ptp(a: Tensor, axis: Tensor = ...) -> Tensor: ...
def rad2deg(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def radians(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def ravel(array_like: Tensor) -> Tensor: ...
def ravel_multi_index(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def real(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def rechunk(x: Tensor, chunks: Tensor = ..., threshold: Tensor = ..., block_size_limit: Tensor = ..., balance: Tensor = ..., method: Tensor = ...) -> Tensor: ...
def reciprocal(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def reduction(
    x: Tensor, chunk: Tensor, aggregate: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., dtype: Tensor = ..., split_every: Tensor = ..., combine: Tensor = ..., name: Tensor = ..., out: Tensor = ..., concatenate: Tensor = ..., output_size: Tensor = ..., meta: Tensor = ..., weights: Tensor = ...
) -> Tensor: ...
def register_chunk_type(type: Tensor) -> Tensor: ...
def remainder(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def repeat(a: Tensor, repeats: Tensor, axis: Tensor = ...) -> Tensor: ...
def reshape(x: Tensor, shape: Tensor, merge_chunks: Tensor = ..., limit: Tensor = ...) -> Tensor: ...
def result_type(*args: Tensor) -> Tensor: ...
def right_shift(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def rint(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def roll(array: Tensor, shift: Tensor, axis: Tensor = ...) -> Tensor: ...
def rollaxis(a: Tensor, axis: Tensor, start: Tensor = ...) -> Tensor: ...
def rot90(m: Tensor, k: Tensor = ..., axes: Tensor = ...) -> Tensor: ...
def round(a: Tensor, decimals: Tensor = ...) -> Tensor: ...
def searchsorted(a: Tensor, v: Tensor, side: Tensor = ..., sorter: Tensor = ...) -> Tensor: ...
def select(condlist: Tensor, choicelist: Tensor, default: Tensor = ...) -> Tensor: ...
def shape(array: Tensor) -> Tensor: ...
def shuffle(x: Tensor, indexer: Tensor, axis: Tensor) -> Tensor: ...
def sign(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def signbit(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sin(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sinc(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sinh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def spacing(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sqrt(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def square(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def squeeze(a: Tensor, axis: Tensor = ...) -> Tensor: ...
def stack(seq: Tensor, axis: Tensor = ..., allow_unknown_chunksizes: Tensor = ...) -> Tensor: ...
def std(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., keepdims: Tensor = ..., ddof: Tensor = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def store(sources: Tensor, targets: Tensor, lock: Tensor = ..., regions: Tensor = ..., compute: Tensor = ..., return_stored: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def subtract(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sum(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., keepdims: Tensor = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def swapaxes(a: Tensor, axis1: Tensor, axis2: Tensor) -> Tensor: ...
def take(a: Tensor, indices: Tensor, axis: Tensor = ...) -> Tensor: ...
def tan(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def tanh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def tensordot(lhs: Tensor, rhs: Tensor, axes: Tensor = ...) -> Tensor: ...
def tile(A: Tensor, reps: Tensor) -> Tensor: ...
def to_hdf5(filename: Tensor, *args: Tensor, chunks: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def to_npy_stack(dirname: Tensor, x: Tensor, axis: Tensor = ...) -> Tensor: ...
def to_tiledb(darray: Tensor, uri: Tensor, compute: Tensor = ..., return_stored: Tensor = ..., storage_options: Tensor = ..., key: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def to_zarr(arr: Tensor, url: Tensor, component: Tensor = ..., storage_options: Tensor = ..., overwrite: Tensor = ..., region: Tensor = ..., compute: Tensor = ..., return_stored: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def topk(a: Tensor, k: Tensor, axis: Tensor = ..., split_every: Tensor = ...) -> Tensor: ...
def trace(a: Tensor, offset: Tensor = ..., axis1: Tensor = ..., axis2: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def transpose(a: Tensor, axes: Tensor = ...) -> Tensor: ...
def tri(N: Tensor, M: Tensor = ..., k: Tensor = ..., dtype: Tensor = ..., chunks: Tensor = ..., *, like: Tensor = ...) -> Tensor: ...
def tril(m: Tensor, k: Tensor = ...) -> Tensor: ...
def tril_indices(n: Tensor, k: Tensor = ..., m: Tensor = ..., chunks: Tensor = ...) -> Tensor: ...
def tril_indices_from(arr: Tensor, k: Tensor = ...) -> Tensor: ...
def triu(m: Tensor, k: Tensor = ...) -> Tensor: ...
def triu_indices(n: Tensor, k: Tensor = ..., m: Tensor = ..., chunks: Tensor = ...) -> Tensor: ...
def triu_indices_from(arr: Tensor, k: Tensor = ...) -> Tensor: ...
def true_divide(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def trunc(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def unify_chunks(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def union1d(ar1: Tensor, ar2: Tensor) -> Tensor: ...
def unique(ar: Tensor, return_index: Tensor = ..., return_inverse: Tensor = ..., return_counts: Tensor = ...) -> Tensor: ...
def unravel_index(indices: Tensor, shape: Tensor, order: Tensor = ...) -> Tensor: ...
def var(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., keepdims: Tensor = ..., ddof: Tensor = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def vdot(a: Tensor, b: Tensor) -> Tensor: ...
def vstack(tup: Tensor, allow_unknown_chunksizes: Tensor = ...) -> Tensor: ...
def where(condition: Tensor, x: Tensor = ..., y: Tensor = ...) -> Tensor: ...
def zeros(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def zeros_like(a: Tensor, dtype: Tensor = ..., order: Tensor = ..., chunks: Tensor = ..., name: Tensor = ..., shape: Tensor = ...) -> Tensor: ...
