"""Auto-generated high-fidelity type stubs for dask from ml-framework-snapshots."""
# ruff: noqa: E501, UP007, UP045, D100, D101, D102, D103

from collections.abc import Sequence

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    device: str
    ndim: int
    size: int
    def __init__(self, data: object = ..., shape: Sequence[int] | None = ..., dtype: str | None = ...) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: object) -> Tensor: ...
    def __add__(self, other: Tensor | float | int) -> Tensor: ...
    def __sub__(self, other: Tensor | float | int) -> Tensor: ...
    def __mul__(self, other: Tensor | float | int) -> Tensor: ...
    def __truediv__(self, other: Tensor | float | int) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def numpy(self) -> object: ...
    def to(self, device: str) -> Tensor: ...
    def reshape(self, shape: Sequence[int]) -> Tensor: ...
    def transpose(self, axes: Sequence[int] | None = ...) -> Tensor: ...

def absolute(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def add(*args: Tensor, out: Tensor, where: Tensor, x1: Tensor, x2: Tensor, **kwargs: Tensor) -> Tensor: ...
def all(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., split_every: Tensor = ..., out: float = ...) -> Tensor: ...
def allclose(arr1: Tensor, arr2: Tensor, rtol: float = ..., atol: float = ..., equal_nan: bool = ...) -> Tensor: ...
def angle(x: Tensor, deg: int = ...) -> Tensor: ...
def any(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., split_every: Tensor = ..., out: float = ...) -> Tensor: ...
def append(arr: Tensor, values: Tensor, axis: Tensor = ...) -> Tensor: ...
def apply(func: Tensor, args: Tensor, kwargs: Tensor = ...) -> Tensor: ...
def apply_along_axis(func1d: Tensor, axis: Tensor, arr: Tensor, *args: Tensor, dtype: Tensor = ..., shape: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def apply_gufunc(func: Tensor, signature: Tensor, *args: Tensor, axes: Tensor = ..., axis: Tensor = ..., keepdims: bool = ..., output_dtypes: Tensor = ..., output_sizes: Tensor = ..., vectorize: Tensor = ..., allow_rechunk: bool = ..., meta: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def apply_over_axes(func: Tensor, a: Tensor, axes: Tensor) -> Tensor: ...
def arange(*args: Tensor, chunks: str = ..., like: Tensor = ..., dtype: Tensor = ..., start: int, stop: int, step: int, **kwargs: Tensor) -> Tensor: ...
def arccos(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def arccosh(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def arcsin(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def arcsinh(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def arctan(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def arctan2(*args: Tensor, x1: Tensor, x2: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def arctanh(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def argmax(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def argmin(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def argtopk(a: Tensor, k: Tensor, axis: int = ..., split_every: Tensor = ...) -> Tensor: ...
def argwhere(a: Tensor) -> Tensor: ...
def around(x: Tensor, decimals: int = ...) -> Tensor: ...
def array(x: Tensor, dtype: Tensor = ..., ndmin: Tensor = ..., *, like: Tensor = ...) -> Tensor: ...
def array_safe(a: Tensor, like: Tensor, **kwargs: Tensor) -> Tensor: ...
def as_gufunc(signature: Tensor = ..., *, axes: Tensor, axis: Tensor, keepdims: Tensor, output_dtypes: Tensor, output_sizes: Tensor, vectorize: Tensor, allow_rechunk: Tensor, meta: Tensor, **kwargs: Tensor) -> Tensor: ...
def asanyarray(a: Tensor, dtype: Tensor = ..., order: Tensor = ..., *, like: Tensor = ..., inline_array: bool = ...) -> Tensor: ...
def asarray(a: Tensor, allow_unknown_chunksizes: bool = ..., dtype: Tensor = ..., order: Tensor = ..., *, like: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def assert_eq(a: Tensor, b: Tensor, check_shape: bool = ..., check_graph: bool = ..., check_meta: bool = ..., check_chunks: bool = ..., check_ndim: bool = ..., check_type: bool = ..., check_dtype: bool = ..., equal_nan: bool = ..., scheduler: str = ..., **kwargs: Tensor) -> Tensor: ...
def atleast_1d(*arys: Tensor) -> Tensor: ...
def atleast_2d(*arys: Tensor) -> Tensor: ...
def atleast_3d(*arys: Tensor) -> Tensor: ...
def atop(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def average(a: Tensor, axis: Tensor = ..., weights: Tensor = ..., returned: bool = ..., keepdims: bool = ...) -> Tensor: ...
def bincount(x: Tensor, weights: Tensor = ..., minlength: int = ..., split_every: Tensor = ...) -> Tensor: ...
def bitwise_and(*args: Tensor, out: Tensor, where: Tensor, x1: Tensor, x2: Tensor, **kwargs: Tensor) -> Tensor: ...
def bitwise_or(*args: Tensor, out: Tensor, where: Tensor, x1: Tensor, x2: Tensor, **kwargs: Tensor) -> Tensor: ...
def bitwise_xor(*args: Tensor, out: Tensor, where: Tensor, x1: Tensor, x2: Tensor, **kwargs: Tensor) -> Tensor: ...
def block(arrays: Tensor, allow_unknown_chunksizes: bool = ...) -> Tensor: ...
def blocked_empty_like(*args: Tensor, prototype: Tensor, dtype: Tensor, order: Tensor, subok: Tensor, shape: Tensor, **kwargs: Tensor) -> Tensor: ...
def blocked_ones_like(*args: Tensor, a: Tensor, dtype: Tensor, order: Tensor, subok: Tensor, shape: Tensor, **kwargs: Tensor) -> Tensor: ...
def blocked_zeros_like(*args: Tensor, a: Tensor, dtype: Tensor, order: Tensor, subok: Tensor, shape: Tensor, **kwargs: Tensor) -> Tensor: ...
def blockwise(func: Tensor, out_ind: Tensor, *args: Tensor, name: Tensor = ..., token: Tensor = ..., dtype: Tensor = ..., adjust_chunks: Tensor = ..., new_axes: Tensor = ..., align_arrays: bool = ..., concatenate: bool = ..., meta: Tensor = ..., Examples: Tensor, **kwargs: Tensor) -> Tensor: ...
def broadcast_arrays(*args: Tensor, subok: bool = ...) -> Tensor: ...
def broadcast_to(x: Tensor, shape: Tensor, chunks: Tensor = ..., meta: Tensor = ...) -> Tensor: ...
def cbrt(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def ceil(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def cholesky(a: Tensor, lower: bool = ...) -> Tensor: ...
def choose(a: int, choices: Tensor) -> Tensor: ...
def clip(*args: Tensor, a: Tensor, out: Tensor, a_min: Tensor, a_max: Tensor, **kwargs: Tensor) -> Tensor: ...
def coarsen(reduction: Tensor, x: Tensor, axes: Tensor, trim_excess: bool = ..., *, Examples: Tensor, **kwargs: Tensor) -> Tensor: ...
def compress(condition: Tensor, a: Tensor, axis: Tensor = ...) -> Tensor: ...
def compression_level(n: int, q: int, n_oversamples: int = ..., min_subspace_size: int = ...) -> Tensor: ...
def compression_matrix(data: Tensor, q: int, iterator: str = ..., n_power_iter: int = ..., n_oversamples: int = ..., seed: Tensor = ..., compute: bool = ...) -> Tensor: ...
def compute(*args: Tensor, traverse: bool = ..., optimize_graph: bool = ..., scheduler: Tensor = ..., get: Tensor = ..., Examples: Tensor, **kwargs: Tensor) -> Tensor: ...
def concatenate(seq: Tensor, axis: int = ..., allow_unknown_chunksizes: bool = ...) -> Tensor: ...
def conjugate(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def copysign(*args: Tensor, x1: Tensor, x2: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def corrcoef(x: Tensor, y: Tensor = ..., rowvar: int = ...) -> Tensor: ...
def cos(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def cosh(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def count_nonzero(a: Tensor, axis: Tensor = ...) -> Tensor: ...
def cov(m: Tensor, y: Tensor = ..., rowvar: int = ..., bias: int = ..., ddof: Tensor = ...) -> Tensor: ...
def cumprod(x: Tensor, axis: Tensor = ..., dtype: int = ..., out: Tensor = ..., method: str = ...) -> Tensor: ...
def cumsum(x: Tensor, axis: Tensor = ..., dtype: int = ..., out: Tensor = ..., method: str = ...) -> Tensor: ...
def default_rng(seed: Tensor = ...) -> Tensor: ...
def deg2rad(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def degrees(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def delayed(obj: Tensor, name: Tensor = ..., pure: bool = ..., nout: Tensor = ..., traverse: Tensor = ...) -> Tensor: ...
def delete(arr: Tensor, obj: Tensor, axis: Tensor) -> Tensor: ...
def derived_from(original_klass: Tensor, version: str = ..., ua_args: Tensor = ..., skipblocks: int = ..., inconsistencies: Tensor = ...) -> Tensor: ...
def diag(v: Tensor, k: int = ...) -> Tensor: ...
def diagonal(a: Tensor, offset: int = ..., axis1: int = ..., axis2: int = ...) -> Tensor: ...
def diff(a: Tensor, n: int = ..., axis: int = ..., prepend: Tensor = ..., append: Tensor = ...) -> Tensor: ...
def digitize(a: Tensor, bins: Tensor, right: bool = ...) -> Tensor: ...
def divide(*args: Tensor, x1: Tensor, x2: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def divmod(x: Tensor, y: Tensor) -> Tensor: ...
def dot(a: Tensor, b: Tensor) -> Tensor: ...
def dotmany(A: Tensor, B: Tensor, leftfunc: Tensor = ..., rightfunc: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def dstack(tup: Tensor, allow_unknown_chunksizes: bool = ...) -> Tensor: ...
def ediff1d(ary: Tensor, to_end: Tensor = ..., to_begin: Tensor = ...) -> Tensor: ...
def einsum(*operands: Tensor, dtype: Tensor = ..., optimize: bool = ..., split_every: Tensor = ..., subscripts: Tensor, out: Tensor, order: Tensor, casting: Tensor, **kwargs: Tensor) -> Tensor: ...
def empty_like(a: Tensor, dtype: Tensor = ..., order: str = ..., chunks: Tensor = ..., name: str = ..., shape: Tensor = ...) -> Tensor: ...
def equal(*args: Tensor, out: Tensor, where: Tensor, x1: Tensor, x2: Tensor, **kwargs: Tensor) -> Tensor: ...
def exp(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def exp2(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def expand_dims(a: Tensor, axis: Tensor) -> Tensor: ...
def expm1(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def extract(condition: Tensor, arr: Tensor) -> Tensor: ...
def eye(N: int, chunks: str = ..., M: Tensor = ..., k: int = ..., dtype: Tensor = ...) -> Tensor: ...
def fabs(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def fft(a: Tensor, n: Tensor = ..., axis: Tensor = ...) -> Tensor: ...
def fft2(a: Tensor, s: Tensor = ..., axes: Tensor = ...) -> Tensor: ...
def fft_wrap(fft_func: Tensor, kind: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def fftfreq(n: int, d: float = ..., chunks: str = ...) -> Tensor: ...
def fftn(a: Tensor, s: Tensor = ..., axes: Tensor = ...) -> Tensor: ...
def fftshift(x: Tensor, axes: Tensor = ...) -> Tensor: ...
def fix(*args: Tensor, x: Tensor, out: Tensor, **kwargs: Tensor) -> Tensor: ...
def flatnonzero(a: Tensor) -> Tensor: ...
def flip(m: Tensor, axis: Tensor = ...) -> Tensor: ...
def fliplr(m: Tensor) -> Tensor: ...
def flipud(m: Tensor) -> Tensor: ...
def float_power(*args: Tensor, x1: Tensor, x2: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def floor(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def floor_divide(*args: Tensor, x1: Tensor, x2: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def fmax(*args: Tensor, out: Tensor, where: Tensor, x1: Tensor, x2: Tensor, **kwargs: Tensor) -> Tensor: ...
def fmin(*args: Tensor, out: Tensor, where: Tensor, x1: Tensor, x2: Tensor, **kwargs: Tensor) -> Tensor: ...
def fmod(*args: Tensor, x1: Tensor, x2: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def frexp(x: Tensor) -> Tensor: ...
def from_array(x: Tensor, chunks: str = ..., name: Tensor = ..., lock: bool = ..., asarray: bool = ..., fancy: bool = ..., getitem: Tensor = ..., meta: Tensor = ..., inline_array: bool = ...) -> Tensor: ...
def from_delayed(value: Tensor, shape: Tensor, dtype: Tensor = ..., meta: Tensor = ..., name: Tensor = ...) -> Tensor: ...
def from_npy_stack(dirname: Tensor, mmap_mode: str = ...) -> Tensor: ...
def from_tiledb(uri: Tensor, attribute: Tensor = ..., chunks: Tensor = ..., storage_options: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def from_zarr(url: Tensor, component: Tensor = ..., storage_options: Tensor = ..., chunks: Tensor = ..., name: Tensor = ..., inline_array: bool = ..., **kwargs: Tensor) -> Tensor: ...
def fromfunction(func: Tensor, chunks: str = ..., shape: Tensor = ..., dtype: Tensor = ..., *, function: Tensor, like: Tensor, **kwargs: Tensor) -> Tensor: ...
def frompyfunc(func: Tensor, nin: int, nout: int) -> Tensor: ...
def full(shape: Tensor, fill_value: Tensor, *args: Tensor, a: Tensor, dtype: Tensor, order: Tensor, subok: Tensor, **kwargs: Tensor) -> Tensor: ...
def full_like(a: Tensor, fill_value: Tensor, order: str = ..., dtype: Tensor = ..., chunks: Tensor = ..., name: str = ..., shape: Tensor = ...) -> Tensor: ...
def gradient(f: Tensor, *varargs: Tensor, axis: Tensor = ..., edge_order: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def greater(*args: Tensor, out: Tensor, where: Tensor, x1: Tensor, x2: Tensor, **kwargs: Tensor) -> Tensor: ...
def greater_equal(*args: Tensor, out: Tensor, where: Tensor, x1: Tensor, x2: Tensor, **kwargs: Tensor) -> Tensor: ...
def hfft(a: Tensor, n: Tensor = ..., axis: Tensor = ...) -> Tensor: ...
def histogram(a: Tensor, bins: int = ..., range: Tensor = ..., normed: bool = ..., weights: Tensor = ..., density: bool = ...) -> Tensor: ...
def histogram2d(x: Tensor, y: Tensor, bins: int = ..., range: Tensor = ..., normed: Tensor = ..., weights: Tensor = ..., density: int = ...) -> Tensor: ...
def histogramdd(sample: Tensor, bins: Tensor, range: Tensor = ..., normed: Tensor = ..., weights: Tensor = ..., density: bool = ...) -> Tensor: ...
def hstack(tup: Tensor, allow_unknown_chunksizes: bool = ...) -> Tensor: ...
def hypot(*args: Tensor, out: Tensor, where: Tensor, x1: Tensor, x2: Tensor, **kwargs: Tensor) -> Tensor: ...
def i0(*args: Tensor, x: Tensor, **kwargs: Tensor) -> Tensor: ...
def ifft(a: Tensor, n: Tensor = ..., axis: Tensor = ...) -> Tensor: ...
def ifft2(a: Tensor, s: Tensor = ..., axes: Tensor = ...) -> Tensor: ...
def ifftn(a: Tensor, s: Tensor = ..., axes: Tensor = ...) -> Tensor: ...
def ifftshift(x: Tensor, axes: Tensor = ...) -> Tensor: ...
def ihfft(a: Tensor, n: int = ..., axis: Tensor = ...) -> Tensor: ...
def imag(*args: Tensor, val: Tensor, **kwargs: Tensor) -> Tensor: ...
def indices(dimensions: Tensor, dtype: Tensor = ..., chunks: str = ...) -> Tensor: ...
def insert(arr: Tensor, obj: Tensor, values: Tensor, axis: Tensor) -> Tensor: ...
def inv(a: Tensor) -> Tensor: ...
def invert(*args: Tensor, x: int, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def irfft(a: Tensor, n: Tensor = ..., axis: Tensor = ...) -> Tensor: ...
def irfft2(a: Tensor, s: Tensor = ..., axes: Tensor = ...) -> Tensor: ...
def irfftn(a: Tensor, s: int = ..., axes: Tensor = ...) -> Tensor: ...
def isclose(arr1: Tensor, arr2: Tensor, rtol: float = ..., atol: float = ..., equal_nan: bool = ...) -> Tensor: ...
def iscomplex(*args: Tensor, x: Tensor, **kwargs: Tensor) -> Tensor: ...
def isfinite(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def isin(element: Tensor, test_elements: Tensor, assume_unique: bool = ..., invert: bool = ..., *, kind: Tensor = ...) -> Tensor: ...
def isinf(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def isnan(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def isneginf(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def isnull(values: Tensor) -> Tensor: ...
def isposinf(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def isreal(*args: Tensor, x: Tensor, **kwargs: Tensor) -> Tensor: ...
def ldexp(*args: Tensor, x1: Tensor, x2: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def left_shift(*args: Tensor, x1: Tensor, x2: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def less(*args: Tensor, out: Tensor, where: Tensor, x1: Tensor, x2: Tensor, **kwargs: Tensor) -> Tensor: ...
def less_equal(*args: Tensor, out: Tensor, where: Tensor, x1: Tensor, x2: Tensor, **kwargs: Tensor) -> Tensor: ...
def linspace(start: Tensor, stop: Tensor, num: int = ..., endpoint: bool = ..., retstep: bool = ..., chunks: str = ..., dtype: Tensor = ...) -> Tensor: ...
def log(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def log10(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def log1p(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def log2(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def logaddexp(*args: Tensor, out: Tensor, where: Tensor, x1: Tensor, x2: Tensor, **kwargs: Tensor) -> Tensor: ...
def logaddexp2(*args: Tensor, out: Tensor, where: Tensor, x1: Tensor, x2: Tensor, **kwargs: Tensor) -> Tensor: ...
def logical_and(*args: Tensor, out: Tensor, where: Tensor, x1: Tensor, x2: Tensor, **kwargs: Tensor) -> Tensor: ...
def logical_not(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def logical_or(*args: Tensor, out: Tensor, where: Tensor, x1: Tensor, x2: Tensor, **kwargs: Tensor) -> Tensor: ...
def logical_xor(*args: Tensor, out: Tensor, where: Tensor, x1: Tensor, x2: Tensor, **kwargs: Tensor) -> Tensor: ...
def lstsq(a: Tensor, b: Tensor) -> Tensor: ...
def lu(a: Tensor) -> Tensor: ...
def map_blocks(func: Tensor, *args: Tensor, name: Tensor = ..., token: Tensor = ..., dtype: Tensor = ..., chunks: Tensor = ..., drop_axis: Tensor = ..., new_axis: Tensor = ..., enforce_ndim: bool = ..., meta: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def map_overlap(func: Tensor, *args: Tensor, depth: Tensor = ..., boundary: Tensor = ..., trim: bool = ..., align_arrays: bool = ..., allow_rechunk: bool = ..., **kwargs: Tensor) -> Tensor: ...
def matmul(a: Tensor, b: Tensor) -> Tensor: ...
def max(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def maximum(*args: Tensor, out: Tensor, where: Tensor, x1: Tensor, x2: Tensor, **kwargs: Tensor) -> Tensor: ...
def mean(a: Tensor, axis: Tensor = ..., dtype: int = ..., keepdims: bool = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def median(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., out: Tensor = ...) -> Tensor: ...
def meshgrid(*xi: Tensor, sparse: bool = ..., indexing: str = ..., copy: Tensor, x1: Tensor, x2: Tensor, **kwargs: Tensor) -> Tensor: ...
def meta_from_array(x: Tensor, ndim: Tensor = ..., dtype: Tensor = ...) -> Tensor: ...
def min(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def minimum(*args: Tensor, out: Tensor, where: Tensor, x1: Tensor, x2: Tensor, **kwargs: Tensor) -> Tensor: ...
def modf(x: Tensor) -> Tensor: ...
def moment(a: Tensor, order: int, axis: int = ..., dtype: Tensor = ..., keepdims: bool = ..., ddof: int = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def moveaxis(a: Tensor, source: Tensor, destination: Tensor) -> Tensor: ...
def multiply(*args: Tensor, out: Tensor, where: Tensor, x1: Tensor, x2: Tensor, **kwargs: Tensor) -> Tensor: ...
def nan_to_num(*args: Tensor, x: Tensor, copy: Tensor, nan: Tensor, posinf: int, neginf: int, **kwargs: Tensor) -> Tensor: ...
def nanargmax(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nanargmin(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nancumprod(x: Tensor, axis: Tensor, dtype: int = ..., out: Tensor = ..., *, method: str = ...) -> Tensor: ...
def nancumsum(x: Tensor, axis: Tensor, dtype: int = ..., out: Tensor = ..., *, method: str = ...) -> Tensor: ...
def nanmax(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nanmean(a: Tensor, axis: Tensor = ..., dtype: int = ..., keepdims: bool = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nanmedian(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., out: Tensor = ...) -> Tensor: ...
def nanmin(a: Tensor, axis: Tensor = ..., keepdims: bool = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nanprod(a: Tensor, axis: Tensor = ..., dtype: int = ..., keepdims: bool = ..., split_every: Tensor = ..., out: int = ...) -> Tensor: ...
def nanstd(a: Tensor, axis: Tensor = ..., dtype: int = ..., keepdims: bool = ..., ddof: int = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def nansum(a: Tensor, axis: Tensor = ..., dtype: int = ..., keepdims: bool = ..., split_every: Tensor = ..., out: int = ...) -> Tensor: ...
def nanvar(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., keepdims: bool = ..., ddof: int = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def ndim(a: Tensor) -> Tensor: ...
def negative(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def nextafter(*args: Tensor, x1: Tensor, x2: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def nonzero(a: Tensor) -> Tensor: ...
def norm(x: Tensor, ord: Tensor = ..., axis: int = ..., keepdims: bool = ...) -> Tensor: ...
def not_equal(*args: Tensor, out: Tensor, where: Tensor, x1: Tensor, x2: Tensor, **kwargs: Tensor) -> Tensor: ...
def notnull(values: Tensor) -> Tensor: ...
def ones_like(a: Tensor, dtype: Tensor = ..., order: str = ..., chunks: Tensor = ..., name: str = ..., shape: Tensor = ...) -> Tensor: ...
def optimize(dsk: Tensor, keys: Tensor, fuse_keys: Tensor = ..., fast_functions: Tensor = ..., inline_functions_fast_functions: Tensor = ..., rename_fused_keys: bool = ..., **kwargs: Tensor) -> Tensor: ...
def outer(a: Tensor, b: Tensor) -> Tensor: ...
def pad(array: Tensor, pad_width: Tensor, mode: str = ..., *, stat_length: Tensor, constant_values: Tensor, end_values: Tensor, reflect_type: Tensor, **kwargs: Tensor) -> Tensor: ...
def percentile(a: Tensor, q: Tensor, method: str = ..., internal_method: str = ..., *, interpolation: Tensor, **kwargs: Tensor) -> Tensor: ...
def piecewise(x: Tensor, condlist: bool, funclist: Tensor, *args: Tensor, **kw: Tensor) -> Tensor: ...
def positive(*args: Tensor, x: Tensor, **kwargs: Tensor) -> Tensor: ...
def power(*args: Tensor, x1: Tensor, x2: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def prod(a: Tensor, axis: Tensor = ..., dtype: int = ..., keepdims: bool = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def ptp(a: Tensor, axis: Tensor = ...) -> Tensor: ...
def qr(a: Tensor) -> Tensor: ...
def rad2deg(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def radians(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def ravel(array_like: Tensor) -> Tensor: ...
def ravel_multi_index(multi_index: Tensor, dims: Tensor, mode: Tensor = ..., order: bool = ...) -> Tensor: ...
def real(*args: Tensor, val: Tensor, **kwargs: Tensor) -> Tensor: ...
def rechunk(x: Tensor, chunks: str = ..., threshold: Tensor = ..., block_size_limit: Tensor = ..., balance: bool = ..., method: Tensor = ...) -> Tensor: ...
def reciprocal(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def reduction(
    x: Tensor, chunk: Tensor, aggregate: Tensor, axis: Tensor = ..., keepdims: bool = ..., dtype: Tensor = ..., split_every: Tensor = ..., combine: Tensor = ..., name: Tensor = ..., out: Tensor = ..., concatenate: bool = ..., output_size: int = ..., meta: Tensor = ..., weights: Tensor = ...
) -> Tensor: ...
def register_chunk_type(type: Tensor) -> Tensor: ...
def remainder(*args: Tensor, x1: Tensor, x2: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def repeat(a: Tensor, repeats: int, axis: Tensor = ...) -> Tensor: ...
def reshape(x: Tensor, shape: Tensor, merge_chunks: bool = ..., limit: Tensor = ...) -> Tensor: ...
def result_type(*args: Tensor) -> Tensor: ...
def rfft(a: Tensor, n: Tensor = ..., axis: Tensor = ...) -> Tensor: ...
def rfft2(a: Tensor, s: Tensor = ..., axes: Tensor = ...) -> Tensor: ...
def rfftfreq(n: int, d: float = ..., chunks: str = ...) -> Tensor: ...
def rfftn(a: Tensor, s: Tensor = ..., axes: Tensor = ...) -> Tensor: ...
def right_shift(*args: Tensor, x1: Tensor, x2: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def rint(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def roll(array: Tensor, shift: Tensor, axis: Tensor = ...) -> Tensor: ...
def rollaxis(a: Tensor, axis: Tensor, start: int = ...) -> Tensor: ...
def rot90(m: Tensor, k: int = ..., axes: Tensor = ...) -> Tensor: ...
def round(a: Tensor, decimals: int = ...) -> Tensor: ...
def searchsorted(a: Tensor, v: Tensor, side: str = ..., sorter: Tensor = ...) -> Tensor: ...
def select(condlist: Tensor, choicelist: Tensor, default: int = ...) -> Tensor: ...
def sfqr(data: Tensor, name: Tensor = ...) -> Tensor: ...
def shape(array: Tensor) -> Tensor: ...
def shuffle(x: Tensor, indexer: Tensor, axis: int) -> Tensor: ...
def sign(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def signbit(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def sin(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def sinc(*args: Tensor, x: Tensor, **kwargs: Tensor) -> Tensor: ...
def sinh(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def skip_doctest(doc: Tensor) -> Tensor: ...
def solve(a: Tensor, b: Tensor, sym_pos: Tensor = ..., assume_a: str = ...) -> Tensor: ...
def solve_triangular(a: Tensor, b: Tensor, lower: bool = ...) -> Tensor: ...
def solve_triangular_safe(a: Tensor, b: Tensor, lower: bool = ...) -> Tensor: ...
def spacing(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def sqrt(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def square(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def squeeze(a: Tensor, axis: Tensor = ...) -> Tensor: ...
def stack(seq: Tensor, axis: int = ..., allow_unknown_chunksizes: bool = ...) -> Tensor: ...
def std(a: Tensor, axis: Tensor = ..., dtype: int = ..., keepdims: bool = ..., ddof: int = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def store(sources: Tensor, targets: Tensor, lock: Tensor = ..., regions: Tensor = ..., compute: bool = ..., return_stored: bool = ..., **kwargs: Tensor) -> Tensor: ...
def subtract(*args: Tensor, out: Tensor, where: Tensor, x1: Tensor, x2: Tensor, **kwargs: Tensor) -> Tensor: ...
def sum(a: Tensor, axis: Tensor = ..., dtype: int = ..., keepdims: bool = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def svd(a: Tensor, coerce_signs: bool = ...) -> Tensor: ...
def svd_compressed(a: Tensor, k: Tensor, iterator: str = ..., n_power_iter: int = ..., n_oversamples: int = ..., seed: Tensor = ..., compute: bool = ..., coerce_signs: bool = ...) -> Tensor: ...
def svd_flip(u: Tensor, v: Tensor, u_based_decision: bool = ...) -> Tensor: ...
def swapaxes(a: Tensor, axis1: int, axis2: int) -> Tensor: ...
def take(a: Tensor, indices: Tensor, axis: int = ...) -> Tensor: ...
def tan(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def tanh(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def tensordot(lhs: Tensor, rhs: Tensor, axes: int = ...) -> Tensor: ...
def tile(A: Tensor, reps: Tensor) -> Tensor: ...
def to_hdf5(filename: Tensor, *args: Tensor, chunks: bool = ..., **kwargs: Tensor) -> Tensor: ...
def to_npy_stack(dirname: Tensor, x: Tensor, axis: int = ...) -> Tensor: ...
def to_tiledb(darray: Tensor, uri: Tensor, compute: bool = ..., return_stored: bool = ..., storage_options: Tensor = ..., key: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def to_zarr(arr: Tensor, url: Tensor, component: Tensor = ..., storage_options: Tensor = ..., overwrite: bool = ..., region: Tensor = ..., compute: bool = ..., return_stored: bool = ..., **kwargs: Tensor) -> Tensor: ...
def tokenize(*args: Tensor, ensure_deterministic: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def topk(a: Tensor, k: Tensor, axis: int = ..., split_every: Tensor = ...) -> Tensor: ...
def trace(a: Tensor, offset: int = ..., axis1: int = ..., axis2: int = ..., dtype: Tensor = ...) -> Tensor: ...
def transpose(a: Tensor, axes: Tensor = ...) -> Tensor: ...
def tri(N: int, M: Tensor = ..., k: int = ..., dtype: Tensor = ..., chunks: str = ..., *, like: Tensor = ...) -> Tensor: ...
def tril(m: Tensor, k: int = ...) -> Tensor: ...
def tril_indices(n: int, k: int = ..., m: Tensor = ..., chunks: str = ...) -> Tensor: ...
def tril_indices_from(arr: Tensor, k: int = ...) -> Tensor: ...
def triu(m: Tensor, k: int = ...) -> Tensor: ...
def triu_indices(n: int, k: int = ..., m: Tensor = ..., chunks: str = ...) -> Tensor: ...
def triu_indices_from(arr: Tensor, k: int = ...) -> Tensor: ...
def trunc(*args: Tensor, x: Tensor, out: Tensor, where: Tensor, **kwargs: Tensor) -> Tensor: ...
def tsqr(data: Tensor, compute_svd: bool = ..., _max_vchunk_size: Tensor = ...) -> Tensor: ...
def unify_chunks(*args: Tensor, Examples: Tensor, **kwargs: Tensor) -> Tensor: ...
def union1d(ar1: Tensor, ar2: Tensor) -> Tensor: ...
def unique(ar: Tensor, return_index: bool = ..., return_inverse: bool = ..., return_counts: bool = ...) -> Tensor: ...
def unravel_index(indices: Tensor, shape: Tensor, order: str = ...) -> Tensor: ...
def var(a: Tensor, axis: Tensor = ..., dtype: Tensor = ..., keepdims: bool = ..., ddof: int = ..., split_every: Tensor = ..., out: Tensor = ...) -> Tensor: ...
def vdot(a: Tensor, b: Tensor) -> Tensor: ...
def vstack(tup: Tensor, allow_unknown_chunksizes: bool = ...) -> Tensor: ...
def wait(x: Tensor, timeout: Tensor = ..., return_when: str = ...) -> Tensor: ...
def where(condition: Tensor, x: Tensor = ..., y: Tensor = ...) -> Tensor: ...
def zeros_like(a: Tensor, dtype: Tensor = ..., order: str = ..., chunks: Tensor = ..., name: str = ..., shape: Tensor = ...) -> Tensor: ...
def annotate(*, Examples: Tensor, **annotations: Tensor) -> Tensor: ...
def get_annotations(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def get_sync(dsk: Tensor, keys: Tensor, **kwargs: Tensor) -> Tensor: ...
def is_dask_collection(x: Tensor) -> Tensor: ...
def istask(x: Tensor) -> Tensor: ...
def persist(*args: Tensor, traverse: bool = ..., optimize_graph: bool = ..., scheduler: Tensor = ..., **kwargs: Tensor) -> Tensor: ...
def visualize(*args: Tensor, filename: str = ..., traverse: bool = ..., optimize_graph: bool = ..., maxval: int = ..., engine: Tensor = ..., format: Tensor, color: Tensor, collapse_outputs: Tensor, verbose: Tensor, Examples: Tensor, **kwargs: Tensor) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
