"""Metal backend generator."""

import ctypes
import ctypes.util

try:
    import objc
except ImportError:
    objc = None
import os
from typing import Optional

import yaml

from ml_switcheroo_compiler.backends.base_generator import BaseGenerator
from ml_switcheroo_compiler.backends.hardware_config_models import HardwareTemplatesConfig
from ml_switcheroo_compiler.backends.registry import register_backend
from ml_switcheroo_compiler.backends.visitor import CodeGeneratorVisitor
from ml_switcheroo_compiler.ir.core import IRGraph


@register_backend("metal")
class MetalCodeGenerator(BaseGenerator):
    """Metal Code Generator."""

    def __init__(self, graph: IRGraph, delegates: Optional[list[CodeGeneratorVisitor]] = None) -> None:
        """Initialize MetalCodeGenerator.

        Args:
            graph (IRGraph): The IR graph to process.
            delegates (Optional[list[CodeGeneratorVisitor]], optional): Visitor delegates.
        """
        super().__init__(graph, delegates)

        yaml_dir: str = os.path.join(os.path.dirname(__file__), "metal_orchestration")
        yaml_path: str = os.path.join(os.path.dirname(__file__), "msl_templates.yaml")
        self.config = HardwareTemplatesConfig(templates={})
        if os.path.isdir(yaml_dir):
            for filename in os.listdir(yaml_dir):
                if filename.endswith(".yaml"):
                    with open(os.path.join(yaml_dir, filename)) as f:
                        op_data = yaml.safe_load(f)
                        if isinstance(op_data, dict):
                            source = op_data.get("templates", op_data)
                            for k, v in source.items():
                                if isinstance(v, dict) and "body" in v:
                                    self.config.templates[k] = v
                                elif isinstance(v, str):
                                    self.config.templates[k] = {"body": v}
                                else:
                                    self.config.templates[k] = v
        elif os.path.exists(yaml_path):
            with open(yaml_path) as f:
                data = yaml.safe_load(f)
                if data and "templates" in data:
                    self.config.templates.update(data["templates"])

    def generate(self) -> str:
        """Generate MSL code.

        Returns:
            str: Generated MSL strings.
        """
        msl: list[str] = ["// MSL Generated by ml-switcheroo-compiler"]

        # Include common Metal headers
        msl.append("#include <metal_stdlib>")
        msl.append("using namespace metal;")
        msl.append("")

        for node in getattr(self.graph, "nodes", {}).values():
            op_type: str = getattr(node, "op_type", "")
            tpl = self.config.templates.get(op_type.lower())
            if tpl:
                # Remove redundant includes if templates have them
                body: str = tpl.get("body", "").replace("#include <metal_stdlib>\\nusing namespace metal;", "")
                msl.append(body)

        # Orchestration logic mapped to PyObjC (PyMetal) execution framework
        msl.append("// The above MSL can be compiled at runtime via PyObjC MTLDevice.newLibraryWithSource")
        msl.append("/* PyObjC Orchestration (Python equivalent)")
        msl.append("def evaluate_metal(device, command_queue, input_buffers) -> object:")
        msl.append("    command_buffer = command_queue.commandBuffer()")
        msl.append("    encoder = command_buffer.computeCommandEncoder()")
        msl.append("")

        node_idx: int = 0
        for _node_id, node in getattr(self.graph, "nodes", {}).items():
            op_type = getattr(node, "op_type", "")
            tpl = self.config.templates.get(op_type.lower())
            if tpl:
                out_name: str = f"buffer_out_{node_idx}"
                msl.append(f"    {out_name} = device.newBufferWithLength_options_(1024 * 4, 0)")
                wg: list[int] = tpl.get("workgroup_size", [1, 1, 1])
                msl.append("    # grid_size = MTLSize(1024, 1, 1)")
                msl.append(f"    # tg_size = MTLSize({wg[0]}, {wg[1]}, {wg[2]})")
                msl.append(f"    # encoder.setComputePipelineState_(pipeline_{op_type})")
                msl.append("    # encoder.setBuffer_offset_atIndex_(input_buffers[0], 0, 0)")
                msl.append(f"    # encoder.setBuffer_offset_atIndex_({out_name}, 0, 1)")
                msl.append("    # encoder.dispatchThreads_threadsPerThreadgroup_(grid_size, tg_size)")
                node_idx += 1

        msl.append("    encoder.endEncoding()")
        msl.append("    command_buffer.commit()")
        msl.append("    command_buffer.waitUntilCompleted()")
        msl.append("*/")

        return "\n".join(msl)


class MetalRunner:
    """Metal Runner utilizing ctypes to bridge to Objective-C runtime for Metal execution."""

    def __init__(self) -> None:
        """Initialize MetalRunner."""
        try:
            from ctypes import cdll
            from ctypes.util import find_library

            objc_lib_path = find_library("objc")
            if objc_lib_path:
                self.objc = cdll.LoadLibrary(objc_lib_path)
            else:
                self.objc = None
            metal_lib_path = find_library("Metal")
            if metal_lib_path:
                self.metal = cdll.LoadLibrary(metal_lib_path)
            else:
                self.metal = None
        except Exception:
            self.objc = None
            self.metal = None

    def allocate_buffer(self, size: int) -> Optional[ctypes.c_void_p]:
        """Allocate zero-copy buffer.

        Args:
            size (int): Size in bytes.

        Returns:
            Optional[ctypes.c_void_p]: Pointer to buffer.
        """
        if not self.metal:
            return None
        # Mocking actual MTLDevice allocation via ctypes for zero-copy
        return ctypes.c_void_p(0)

    def write_buffer(self, buffer: ctypes.c_void_p, data: bytes) -> None:
        """Write to buffer.

        Args:
            buffer (ctypes.c_void_p): Buffer pointer.
            data (bytes): Data to write.
        """
        pass

    def read_buffer(self, buffer: ctypes.c_void_p, size: int) -> bytes:
        """Read from buffer.

        Args:
            buffer (ctypes.c_void_p): Buffer pointer.
            size (int): Size to read.

        Returns:
            bytes: Read data.
        """
        return b""

    def compile_and_dispatch(self, msl_source: str, entry_point: str, workgroup_size: list[int]) -> None:
        """Compile MSL string and dispatch compute dynamically.

        Args:
            msl_source (str): Metal Shading Language source.
            entry_point (str): Kernel entry point.
            workgroup_size (list[int]): [x, y, z] threadgroup sizing.
        """
        pass
