"""Metal backend generator."""

import os
from typing import Any, Optional

import yaml

from ml_switcheroo_compiler.backends.base_generator import BaseGenerator
from ml_switcheroo_compiler.backends.hardware_config_models import HardwareTemplatesConfig
from ml_switcheroo_compiler.backends.registry import register_backend
from ml_switcheroo_compiler.ir.core import IRGraph


@register_backend("metal")
class MetalCodeGenerator(BaseGenerator):
    """Metal Code Generator."""

    def __init__(self, graph: IRGraph, delegates: Optional[list[Any]] = None) -> None:
        """Initialize MetalCodeGenerator.

        Args:
            graph (IRGraph): The IR graph to process.
            delegates (list, optional): Visitor delegates.
        """
        super().__init__(graph, delegates)

        yaml_path = os.path.join(os.path.dirname(__file__), "msl_templates.yaml")
        if os.path.exists(yaml_path):
            with open(yaml_path) as f:
                self.config = HardwareTemplatesConfig(**yaml.safe_load(f))
        else:
            self.config = HardwareTemplatesConfig(templates={})

    def generate(self) -> str:
        """Generate MSL code.

        Returns:
            str: Generated MSL strings.
        """
        msl = ["// MSL Generated by ml-switcheroo-compiler"]

        # Include common Metal headers
        msl.append("#include <metal_stdlib>")
        msl.append("using namespace metal;")
        msl.append("")

        for node in getattr(self.graph, "nodes", {}).values():
            op_type = getattr(node, "op_type", "")
            tpl = self.config.templates.get(op_type.lower())
            if tpl:
                # Remove redundant includes if templates have them
                body = tpl.body.replace("#include <metal_stdlib>\\nusing namespace metal;", "")
                msl.append(body)

        # Orchestration logic in Objective-C wrapper (Mock layout)
        msl.append("// Objective-C orchestration for Metal compute dispatch")
        msl.append("void evaluate_metal(id<MTLDevice> device, id<MTLCommandQueue> commandQueue) {")
        msl.append("    id<MTLCommandBuffer> commandBuffer = [commandQueue commandBuffer];")
        msl.append("    id<MTLComputeCommandEncoder> computeEncoder = [commandBuffer computeCommandEncoder];")

        node_idx = 0
        for _node_id, node in getattr(self.graph, "nodes", {}).items():
            op_type = getattr(node, "op_type", "")
            tpl = self.config.templates.get(op_type.lower())
            if tpl:
                out_name = f"buffer_out_{node_idx}"
                msl.append(f"    id<MTLBuffer> {out_name} = [device newBufferWithLength:1024 * sizeof(float) options:MTLResourceStorageModeShared];")
                wg = tpl.workgroup_size
                msl.append(f"    MTLSize gridSize_{node_idx} = MTLSizeMake(1024, 1, 1);")
                msl.append(f"    MTLSize threadGroupSize_{node_idx} = MTLSizeMake({wg[0]}, {wg[1]}, {wg[2]});")
                msl.append(f"    // [computeEncoder setComputePipelineState:pipelineState_{op_type}];")
                msl.append("    // [computeEncoder setBuffer:inputs[0] offset:0 atIndex:0];")
                msl.append("    // [computeEncoder setBuffer:inputs[1] offset:0 atIndex:1];")
                msl.append(f"    // [computeEncoder setBuffer:{out_name} offset:0 atIndex:2];")
                msl.append(f"    // [computeEncoder dispatchThreads:gridSize_{node_idx} threadsPerThreadgroup:threadGroupSize_{node_idx}];")
                node_idx += 1

        msl.append("    [computeEncoder endEncoding];")
        msl.append("    [commandBuffer commit];")
        msl.append("    [commandBuffer waitUntilCompleted];")
        msl.append("}")

        return "\n".join(msl)
