"""Metal backend generator."""

import os
from typing import Optional

import yaml

from ml_switcheroo_compiler.backends.base_generator import BaseGenerator
from ml_switcheroo_compiler.backends.hardware_config_models import HardwareTemplatesConfig
from ml_switcheroo_compiler.backends.registry import register_backend
from ml_switcheroo_compiler.ir.core import IRGraph


@register_backend("metal")
class MetalCodeGenerator(BaseGenerator):
    """Metal Code Generator."""

    def __init__(self, graph: IRGraph, delegates: Optional[list[object]] = None) -> None:
        """Initialize MetalCodeGenerator.

        Args:
            graph (IRGraph): The IR graph to process.
            delegates (list, optional): Visitor delegates.
        """
        super().__init__(graph, delegates)

        yaml_path: object = os.path.join(os.path.dirname(__file__), "msl_templates.yaml")
        if os.path.exists(yaml_path):
            with open(yaml_path) as f:
                self.config = HardwareTemplatesConfig(**yaml.safe_load(f))
        else:
            self.config = HardwareTemplatesConfig(templates={})

    def generate(self) -> str:
        """Generate MSL code.

        Returns:
            str: Generated MSL strings.
        """
        msl: object = ["// MSL Generated by ml-switcheroo-compiler"]

        # Include common Metal headers
        msl.append("#include <metal_stdlib>")
        msl.append("using namespace metal;")
        msl.append("")

        for node in getattr(self.graph, "nodes", {}).values():
            op_type: object = getattr(node, "op_type", "")
            tpl: object = self.config.templates.get(op_type.lower())
            if tpl:
                # Remove redundant includes if templates have them
                body: object = tpl.body.replace("#include <metal_stdlib>\\nusing namespace metal;", "")
                msl.append(body)

        # Orchestration logic mapped to PyObjC (PyMetal) execution framework
        msl.append("// The above MSL can be compiled at runtime via PyObjC MTLDevice.newLibraryWithSource")
        msl.append("/* PyObjC Orchestration (Python equivalent)")
        msl.append("def evaluate_metal(device, command_queue, input_buffers) -> object:")
        msl.append("    command_buffer = command_queue.commandBuffer()")
        msl.append("    encoder = command_buffer.computeCommandEncoder()")
        msl.append("")

        node_idx: object = 0
        for _node_id, node in getattr(self.graph, "nodes", {}).items():
            op_type: object = getattr(node, "op_type", "")
            tpl: object = self.config.templates.get(op_type.lower())
            if tpl:
                out_name: object = f"buffer_out_{node_idx}"
                msl.append(f"    {out_name} = device.newBufferWithLength_options_(1024 * 4, 0)")
                wg: object = tpl.workgroup_size
                msl.append("    # grid_size = MTLSize(1024, 1, 1)")
                msl.append(f"    # tg_size = MTLSize({wg[0]}, {wg[1]}, {wg[2]})")
                msl.append(f"    # encoder.setComputePipelineState_(pipeline_{op_type})")
                msl.append("    # encoder.setBuffer_offset_atIndex_(input_buffers[0], 0, 0)")
                msl.append(f"    # encoder.setBuffer_offset_atIndex_({out_name}, 0, 1)")
                msl.append("    # encoder.dispatchThreads_threadsPerThreadgroup_(grid_size, tg_size)")
                node_idx += 1

        msl.append("    encoder.endEncoding()")
        msl.append("    command_buffer.commit()")
        msl.append("    command_buffer.waitUntilCompleted()")
        msl.append("*/")

        return "\n".join(msl)
