"""Auto-generated high-fidelity type stubs for metal from ml-framework-snapshots."""
# ruff: noqa: E501

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    def __init__(self, *args: object, **kwargs: object) -> None: ...

def atomic_fetch_add_explicit(object: Tensor, operand: Tensor, memory_order: Tensor, *, order: str = ...) -> Tensor: ...
def atomic_fetch_max_explicit(object: Tensor, operand: Tensor, memory_order: Tensor, *, order: str = ...) -> Tensor: ...
def dot(x: Tensor, y: Tensor) -> Tensor: ...
def fma(a: Tensor, b: Tensor, c: Tensor) -> Tensor: ...
def rsqrt(x: Tensor, *, fast_math: bool = ...) -> Tensor: ...
def simd_shuffle(data: Tensor, lane: Tensor) -> Tensor: ...
def simd_sum(data: Tensor) -> Tensor: ...
def simdgroup_barrier(mem_flags: Tensor, *, scope: str = ...) -> Tensor: ...
def simdgroup_load(dest: Tensor, ptr: Tensor, stride: Tensor, *, transpose: bool = ...) -> Tensor: ...
def simdgroup_multiply_accumulate(dest: Tensor, a: Tensor, b: Tensor, c: Tensor, *, m: int = ..., n: int = ..., k: int = ...) -> Tensor: ...
def simdgroup_store(src: Tensor, ptr: Tensor, stride: Tensor, *, transpose: bool = ...) -> Tensor: ...
def threadgroup_barrier(mem_flags: Tensor, *, scope: str = ...) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
