"""Auto-generated high-fidelity type stubs for metal from ml-framework-snapshots."""
# ruff: noqa: E501, UP007, UP045, D100, D101, D102, D103

from collections.abc import Sequence

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    device: str
    ndim: int
    size: int
    def __init__(self, data: object = ..., shape: Sequence[int] | None = ..., dtype: str | None = ...) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: object) -> Tensor: ...
    def __add__(self, other: Tensor | float | int) -> Tensor: ...
    def __sub__(self, other: Tensor | float | int) -> Tensor: ...
    def __mul__(self, other: Tensor | float | int) -> Tensor: ...
    def __truediv__(self, other: Tensor | float | int) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def numpy(self) -> object: ...
    def to(self, device: str) -> Tensor: ...
    def reshape(self, shape: Sequence[int]) -> Tensor: ...
    def transpose(self, axes: Sequence[int] | None = ...) -> Tensor: ...

def atomic_fetch_add_explicit(object: Tensor, operand: Tensor, memory_order: Tensor, *, order: str = ...) -> Tensor: ...
def atomic_fetch_max_explicit(object: Tensor, operand: Tensor, memory_order: Tensor, *, order: str = ...) -> Tensor: ...
def dot(x: Tensor, y: Tensor) -> Tensor: ...
def fma(a: Tensor, b: Tensor, c: Tensor) -> Tensor: ...
def rsqrt(x: Tensor, *, fast_math: bool = ...) -> Tensor: ...
def simd_shuffle(data: Tensor, lane: Tensor) -> Tensor: ...
def simd_sum(data: Tensor) -> Tensor: ...
def simdgroup_barrier(mem_flags: Tensor, *, scope: str = ...) -> Tensor: ...
def simdgroup_load(dest: Tensor, ptr: Tensor, stride: Tensor, *, transpose: bool = ...) -> Tensor: ...
def simdgroup_multiply_accumulate(dest: Tensor, a: Tensor, b: Tensor, c: Tensor, *, m: int = ..., n: int = ..., k: int = ...) -> Tensor: ...
def simdgroup_store(src: Tensor, ptr: Tensor, stride: Tensor, *, transpose: bool = ...) -> Tensor: ...
def threadgroup_barrier(mem_flags: Tensor, *, scope: str = ...) -> Tensor: ...
def __getattr__(name: str) -> Tensor: ...
