"""Auto-generated high-fidelity type stubs for tensorflow from live module introspection."""
# ruff: noqa: E501

class Tensor:
    shape: tuple[int, ...]
    dtype: str
    def __init__(self, *args: object, **kwargs: object) -> None: ...

def abs(x: Tensor, name: Tensor = ...) -> Tensor: ...
def accumulate_n(inputs: Tensor, shape: Tensor = ..., tensor_dtype: Tensor = ..., name: Tensor = ...) -> Tensor: ...
def acos(x: Tensor, name: Tensor = ...) -> Tensor: ...
def acosh(x: Tensor, name: Tensor = ...) -> Tensor: ...
def add(x: Tensor, y: Tensor, name: Tensor = ...) -> Tensor: ...
def add_n(inputs: Tensor, name: Tensor = ...) -> Tensor: ...
def angle(input: Tensor, name: Tensor = ...) -> Tensor: ...
def approx_max_k(operand: Tensor, k: Tensor, reduction_dimension: Tensor = ..., recall_target: Tensor = ..., reduction_input_size_override: Tensor = ..., aggregate_to_topk: Tensor = ..., name: Tensor = ...) -> Tensor: ...
def approx_min_k(operand: Tensor, k: Tensor, reduction_dimension: Tensor = ..., recall_target: Tensor = ..., reduction_input_size_override: Tensor = ..., aggregate_to_topk: Tensor = ..., name: Tensor = ...) -> Tensor: ...
def argmax(input: Tensor, axis: Tensor = ..., output_type: Tensor = ..., name: Tensor = ...) -> Tensor: ...
def argmin(input: Tensor, axis: Tensor = ..., output_type: Tensor = ..., name: Tensor = ...) -> Tensor: ...
def asin(x: Tensor, name: Tensor = ...) -> Tensor: ...
def asinh(x: Tensor, name: Tensor = ...) -> Tensor: ...
def atan(x: Tensor, name: Tensor = ...) -> Tensor: ...
def atan2(y: Tensor, x: Tensor, name: Tensor = ...) -> Tensor: ...
def atanh(x: Tensor, name: Tensor = ...) -> Tensor: ...
def bessel_i0(x: Tensor, name: Tensor = ...) -> Tensor: ...
def bessel_i0e(x: Tensor, name: Tensor = ...) -> Tensor: ...
def bessel_i1(x: Tensor, name: Tensor = ...) -> Tensor: ...
def bessel_i1e(x: Tensor, name: Tensor = ...) -> Tensor: ...
def betainc(a: Tensor, b: Tensor, x: Tensor, name: Tensor = ...) -> Tensor: ...
def bincount(arr: Tensor, weights: Tensor = ..., minlength: Tensor = ..., maxlength: Tensor = ..., dtype: Tensor = ..., name: Tensor = ..., axis: Tensor = ..., binary_output: Tensor = ...) -> Tensor: ...
def ceil(x: Tensor, name: Tensor = ...) -> Tensor: ...
def confusion_matrix(labels: Tensor, predictions: Tensor, num_classes: Tensor = ..., weights: Tensor = ..., dtype: Tensor = ..., name: Tensor = ...) -> Tensor: ...
def conj(x: Tensor, name: Tensor = ...) -> Tensor: ...
def cos(x: Tensor, name: Tensor = ...) -> Tensor: ...
def cosh(x: Tensor, name: Tensor = ...) -> Tensor: ...
def count_nonzero(input: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., dtype: Tensor = ..., name: Tensor = ...) -> Tensor: ...
def cumprod(x: Tensor, axis: Tensor = ..., exclusive: Tensor = ..., reverse: Tensor = ..., name: Tensor = ...) -> Tensor: ...
def cumsum(x: Tensor, axis: Tensor = ..., exclusive: Tensor = ..., reverse: Tensor = ..., name: Tensor = ...) -> Tensor: ...
def cumulative_logsumexp(x: Tensor, axis: Tensor = ..., exclusive: Tensor = ..., reverse: Tensor = ..., name: Tensor = ...) -> Tensor: ...
def digamma(x: Tensor, name: Tensor = ...) -> Tensor: ...
def divide(x: Tensor, y: Tensor, name: Tensor = ...) -> Tensor: ...
def divide_no_nan(x: Tensor, y: Tensor, name: Tensor = ...) -> Tensor: ...
def equal(x: Tensor, y: Tensor, name: Tensor = ...) -> Tensor: ...
def erf(x: Tensor, name: Tensor = ...) -> Tensor: ...
def erfc(x: Tensor, name: Tensor = ...) -> Tensor: ...
def erfcinv(x: Tensor, name: Tensor = ...) -> Tensor: ...
def erfinv(x: Tensor, name: Tensor = ...) -> Tensor: ...
def exp(x: Tensor, name: Tensor = ...) -> Tensor: ...
def expm1(x: Tensor, name: Tensor = ...) -> Tensor: ...
def floor(x: Tensor, name: Tensor = ...) -> Tensor: ...
def floordiv(x: Tensor, y: Tensor, name: Tensor = ...) -> Tensor: ...
def floormod(x: Tensor, y: Tensor, name: Tensor = ...) -> Tensor: ...
def greater(x: Tensor, y: Tensor, name: Tensor = ...) -> Tensor: ...
def greater_equal(x: Tensor, y: Tensor, name: Tensor = ...) -> Tensor: ...
def igamma(a: Tensor, x: Tensor, name: Tensor = ...) -> Tensor: ...
def igammac(a: Tensor, x: Tensor, name: Tensor = ...) -> Tensor: ...
def imag(input: Tensor, name: Tensor = ...) -> Tensor: ...
def in_top_k(targets: Tensor, predictions: Tensor, k: Tensor, name: Tensor = ...) -> Tensor: ...
def invert_permutation(x: Tensor, name: Tensor = ...) -> Tensor: ...
def is_finite(x: Tensor, name: Tensor = ...) -> Tensor: ...
def is_inf(x: Tensor, name: Tensor = ...) -> Tensor: ...
def is_nan(x: Tensor, name: Tensor = ...) -> Tensor: ...
def is_non_decreasing(x: Tensor, name: Tensor = ...) -> Tensor: ...
def is_strictly_increasing(x: Tensor, name: Tensor = ...) -> Tensor: ...
def l2_normalize(x: Tensor, axis: Tensor = ..., epsilon: Tensor = ..., name: Tensor = ..., dim: Tensor = ...) -> Tensor: ...
def lbeta(x: Tensor, name: Tensor = ...) -> Tensor: ...
def less(x: Tensor, y: Tensor, name: Tensor = ...) -> Tensor: ...
def less_equal(x: Tensor, y: Tensor, name: Tensor = ...) -> Tensor: ...
def lgamma(x: Tensor, name: Tensor = ...) -> Tensor: ...
def log(x: Tensor, name: Tensor = ...) -> Tensor: ...
def log1p(x: Tensor, name: Tensor = ...) -> Tensor: ...
def log_sigmoid(x: Tensor, name: Tensor = ...) -> Tensor: ...
def log_softmax(logits: Tensor, axis: Tensor = ..., name: Tensor = ...) -> Tensor: ...
def logical_and(x: Tensor, y: Tensor, name: Tensor = ...) -> Tensor: ...
def logical_not(x: Tensor, name: Tensor = ...) -> Tensor: ...
def logical_or(x: Tensor, y: Tensor, name: Tensor = ...) -> Tensor: ...
def logical_xor(x: Tensor, y: Tensor, name: Tensor = ...) -> Tensor: ...
def maximum(x: Tensor, y: Tensor, name: Tensor = ...) -> Tensor: ...
def minimum(x: Tensor, y: Tensor, name: Tensor = ...) -> Tensor: ...
def mod(x: Tensor, y: Tensor, name: Tensor = ...) -> Tensor: ...
def multiply(x: Tensor, y: Tensor, name: Tensor = ...) -> Tensor: ...
def multiply_no_nan(x: Tensor, y: Tensor, name: Tensor = ...) -> Tensor: ...
def ndtri(x: Tensor, name: Tensor = ...) -> Tensor: ...
def negative(x: Tensor, name: Tensor = ...) -> Tensor: ...
def nextafter(x1: Tensor, x2: Tensor, name: Tensor = ...) -> Tensor: ...
def not_equal(x: Tensor, y: Tensor, name: Tensor = ...) -> Tensor: ...
def polygamma(a: Tensor, x: Tensor, name: Tensor = ...) -> Tensor: ...
def polyval(coeffs: Tensor, x: Tensor, name: Tensor = ...) -> Tensor: ...
def pow(x: Tensor, y: Tensor, name: Tensor = ...) -> Tensor: ...
def real(input: Tensor, name: Tensor = ...) -> Tensor: ...
def reciprocal(x: Tensor, name: Tensor = ...) -> Tensor: ...
def reciprocal_no_nan(x: Tensor, name: Tensor = ...) -> Tensor: ...
def reduce_all(input_tensor: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., name: Tensor = ...) -> Tensor: ...
def reduce_any(input_tensor: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., name: Tensor = ...) -> Tensor: ...
def reduce_euclidean_norm(input_tensor: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., name: Tensor = ...) -> Tensor: ...
def reduce_logsumexp(input_tensor: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., name: Tensor = ...) -> Tensor: ...
def reduce_max(input_tensor: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., name: Tensor = ...) -> Tensor: ...
def reduce_mean(input_tensor: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., name: Tensor = ...) -> Tensor: ...
def reduce_min(input_tensor: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., name: Tensor = ...) -> Tensor: ...
def reduce_prod(input_tensor: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., name: Tensor = ...) -> Tensor: ...
def reduce_std(input_tensor: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., name: Tensor = ...) -> Tensor: ...
def reduce_sum(input_tensor: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., name: Tensor = ...) -> Tensor: ...
def reduce_variance(input_tensor: Tensor, axis: Tensor = ..., keepdims: Tensor = ..., name: Tensor = ...) -> Tensor: ...
def rint(x: Tensor, name: Tensor = ...) -> Tensor: ...
def round(x: Tensor, name: Tensor = ...) -> Tensor: ...
def rsqrt(x: Tensor, name: Tensor = ...) -> Tensor: ...
def scalar_mul(scalar: Tensor, x: Tensor, name: Tensor = ...) -> Tensor: ...
def segment_max(data: Tensor, segment_ids: Tensor, name: Tensor = ...) -> Tensor: ...
def segment_mean(data: Tensor, segment_ids: Tensor, name: Tensor = ...) -> Tensor: ...
def segment_min(data: Tensor, segment_ids: Tensor, name: Tensor = ...) -> Tensor: ...
def segment_prod(data: Tensor, segment_ids: Tensor, name: Tensor = ...) -> Tensor: ...
def segment_sum(data: Tensor, segment_ids: Tensor, name: Tensor = ...) -> Tensor: ...
def sigmoid(x: Tensor, name: Tensor = ...) -> Tensor: ...
def sign(x: Tensor, name: Tensor = ...) -> Tensor: ...
def sin(x: Tensor, name: Tensor = ...) -> Tensor: ...
def sinh(x: Tensor, name: Tensor = ...) -> Tensor: ...
def sobol_sample(dim: Tensor, num_results: Tensor, skip: Tensor = ..., dtype: Tensor = ..., name: Tensor = ...) -> Tensor: ...
def softmax(logits: Tensor, axis: Tensor = ..., name: Tensor = ...) -> Tensor: ...
def softplus(features: Tensor, name: Tensor = ...) -> Tensor: ...
def softsign(features: Tensor, name: Tensor = ...) -> Tensor: ...
def sqrt(x: Tensor, name: Tensor = ...) -> Tensor: ...
def square(x: Tensor, name: Tensor = ...) -> Tensor: ...
def squared_difference(x: Tensor, y: Tensor, name: Tensor = ...) -> Tensor: ...
def subtract(x: Tensor, y: Tensor, name: Tensor = ...) -> Tensor: ...
def tan(x: Tensor, name: Tensor = ...) -> Tensor: ...
def tanh(x: Tensor, name: Tensor = ...) -> Tensor: ...
def top_k(input: Tensor, k: Tensor = ..., sorted: Tensor = ..., index_type: Tensor = ..., name: Tensor = ...) -> Tensor: ...
def truediv(x: Tensor, y: Tensor, name: Tensor = ...) -> Tensor: ...
def unsorted_segment_max(data: Tensor, segment_ids: Tensor, num_segments: Tensor, name: Tensor = ...) -> Tensor: ...
def unsorted_segment_mean(data: Tensor, segment_ids: Tensor, num_segments: Tensor, name: Tensor = ...) -> Tensor: ...
def unsorted_segment_min(data: Tensor, segment_ids: Tensor, num_segments: Tensor, name: Tensor = ...) -> Tensor: ...
def unsorted_segment_prod(data: Tensor, segment_ids: Tensor, num_segments: Tensor, name: Tensor = ...) -> Tensor: ...
def unsorted_segment_sqrt_n(data: Tensor, segment_ids: Tensor, num_segments: Tensor, name: Tensor = ...) -> Tensor: ...
def unsorted_segment_sum(data: Tensor, segment_ids: Tensor, num_segments: Tensor, name: Tensor = ...) -> Tensor: ...
def xdivy(x: Tensor, y: Tensor, name: Tensor = ...) -> Tensor: ...
def xlog1py(x: Tensor, y: Tensor, name: Tensor = ...) -> Tensor: ...
def xlogy(x: Tensor, y: Tensor, name: Tensor = ...) -> Tensor: ...
def zero_fraction(value: Tensor, name: Tensor = ...) -> Tensor: ...
def zeta(x: Tensor, q: Tensor, name: Tensor = ...) -> Tensor: ...
def silu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def gelu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def depthwise_conv2d(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def max_pool2d(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def avg_pool2d(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def resize(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def conv_transpose(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def dropout(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def lookup(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
