"""Auto-generated type stubs from snapshot."""

class Tensor: ...

def elu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def leaky_relu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def relu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def selu(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def sigmoid(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def softmax_v2(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
def tanh(*args: Tensor, **kwargs: Tensor) -> Tensor: ...
